### PR TITLE
Special characters menu item is not correctly marked when enabled

### LINKED ISSUE #16858: Special characters menu item is not correctly marked when enabled
## 📝 Provide detailed reproduction steps (if any)

The checkbox is missing.

image

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal (special-characters): Toolbar and menu bar button should be marked as toggleable. Closes #16858.

---

### Additional information

I added `isToggleable` for both menu bar and toolbar buttons. I see it is done the same way for AI Assistant and Comments archive so I assume this is the pattern we follow.

### CODE REVIEW

File: packages/ckeditor5-special-characters/src/specialcharacters.ts [hunk 1]
```diff
@@ -247,7 +247,7 @@ export default class SpecialCharacters extends Plugin {
 	}
 
 	/**
-	 * Creates a button for for menu bar that will show special characetrs dialog.
+	 * Creates a button for toolbar anda menu bar that will show special characters dialog.
```
Comment (DawidKossowski) [inline packages/ckeditor5-special-characters/src/specialcharacters.ts:250]:
```suggestion
	 * Creates a button for toolbar and menu bar that will show special characters dialog.
```

**Review by DawidKossowski — APPROVED** [review]
