### PR TITLE
Fix `todoListChecked` data lost in to-do list

### LINKED ISSUE #15602: Todolist lost checked property when reload or set to Source Editing
## 📝 Provide detailed reproduction steps (if any)

When I add todolist to a table cell, I checked the checkbox, and saved the data to server, when I reload the data, the checkbox's checked status is lost.

**Before**:
image
**Reload**:
image
**Below is my source code, you can copy the code to source editing, the checked="checked" status will be lost**
```html
<html><head></head><body>
<figure class="table">
    <table>
        <tbody>
            <tr>
                <td style="background-color:hsl(60, 75%, 60%);text-align:center;">
                    <p style="color:#7F6000;font-family:Calibri;font-size:12.0pt;margin:0in;">
                        <span style="color:hsl(0,0%,0%);"><strong>FOUNDATION</strong></span>
                    </p>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">
                    <ul class="todo-list">
                        <li>
                            <label class="todo-list__label todo-list__label_without-description"><input type="checkbox" checked="checked" disabled="disabled"></label>
                            <p style="font-family:Calibri;font-size:12.0pt;margin:0in;">
                                <strong>Net Worth:&nbsp;</strong>
                            </p>
                        </li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</figure>
</body></html>
```

### ✔️ Expected result

Checked status can reload correctly

### ❌ Actual result

Checked status is lost.

## 📃 Other details

* Browser: Latest Chrome
* OS: MacOS / Windows
* First affected CKEditor version: Latest ckeditor version
* Installed CKEditor plugins: 
    "@ckeditor/ckeditor5-alignment": "^40.0.0",
    "@ckeditor/ckeditor5-autoformat": "^40.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^40.0.0",
    "@ckeditor/ckeditor5-block-quote": "^40.0.0",
    "@ckeditor/ckeditor5-cloud-services": "^40.0.0",
    "@ckeditor/ckeditor5-dev-translations": "^32.1.2",
    "@ckeditor/ckeditor5-dev-utils": "^32.1.2",
    "@ckeditor/ckeditor5-editor-classic": "^40.0.0",
    "@ckeditor/ckeditor5-editor-inline": "^40.0.0",
    "@ckeditor/ckeditor5-essentials": "^40.0.0",
    "@ckeditor/ckeditor5-font": "^40.0.0",
    "@ckeditor/ckeditor5-heading": "^40.0.0",
    "@ckeditor/ckeditor5-horizontal-line": "^40.0.0",
    "@ckeditor/ckeditor5-html-support": "^40.0.0",
    "@ckeditor/ckeditor5-image": "^40.0.0",
    "@ckeditor/ckeditor5-indent": "^40.0.0",
    "@ckeditor/ckeditor5-link": "^40.0.0",
    "@ckeditor/ckeditor5-list": "^40.0.0",
    "@ckeditor/ckeditor5-media-embed": "^40.0.0",
    "@ckeditor/ckeditor5-mention": "^40.0.0",
    "@ckeditor/ckeditor5-page-break": "^40.0.0",
    "@ckeditor/ckeditor5-paragraph": "^40.0.0",
    "@ckeditor/ckeditor5-paste-from-office": "^40.0.0",
    "@ckeditor/ckeditor5-source-editing": "^40.0.0",
    "@ckeditor/ckeditor5-special-characters": "^40.0.0",
    "@ckeditor/ckeditor5-table": "^40.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^40.0.0",
    "@ckeditor/ckeditor5-typing": "^40.0.0",
    "@ckeditor/ckeditor5-word-count": "^40.0.0",
    "@ckeditor/ckeditor5-ui": "^40.0.0",
    "@ckeditor/ckeditor5-undo": "^40.0.0",

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (List): Should not lost data of `todoListChecked` attribute in to-do lists. Closes #15602.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by illia-stv** [comment]
More details: https://github.com/ckeditor/ckeditor5/issues/15602#issuecomment-2245521131

File: packages/ckeditor5-list/src/list/converters.ts [hunk 1]
```diff
@@ -81,6 +81,7 @@ export function listItemUpcastConverter(): GetCallback<UpcastElementEvent> {
 
 		const listItemId = ListItemUid.next();
 		const listIndent = getIndent( data.viewItem );
+		const todoListChecked = isTodoListChecked( items );
```
Comment (niegowski) [inline packages/ckeditor5-list/src/list/converters.ts:84]: I'd suggest fixing the to-do list converter instead of modifying the generic list converter.

https://github.com/ckeditor/ckeditor5/blob/897019cfb90f76bc4716332dfaf41a6f883d92f0/packages/ckeditor5-list/src/todolist/todolistediting.ts#L398-L424

**Review by niegowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-list/src/list/converters.ts (hunk 1 above)
Comment (Mati365) [reply packages/ckeditor5-list/src/list/converters.ts]: @niegowski I moved fix to to-do list converter in this [commit](https://github.com/ckeditor/ckeditor5/pull/16785/commits/3d2aed708ede0c5880b430f05d70861c09055cd6). Can you take a look?

File: packages/ckeditor5-list/src/todolist/todolistediting.ts [hunk 2]
```diff
@@ -111,6 +111,12 @@ export default class TodoListEditing extends Plugin {
 			dispatcher.on( 'element:span', elementUpcastConsumingConverter(
 				{ name: 'span', classes: 'todo-list__label__description' }
 			) );
+
+			// Priority is set to low to allow generic list item converter to run first.
+			dispatcher.on( 'element:li', todoListItemUpcastConverter(), {
+				priority: 'low'
+			} );
+
```
Comment (niegowski) [inline packages/ckeditor5-list/src/todolist/todolistediting.ts:119]: Please move this converter above the "consuming" converters so it is not lost in the crowd of just consuming converters.

File: packages/ckeditor5-list/src/todolist/todolistediting.ts [hunk 3]
```diff
@@ -392,6 +398,29 @@ export default class TodoListEditing extends Plugin {
...
 }
 
+/**
+ * Returns an upcast converter for to-do list items.
+ */
+function todoListItemUpcastConverter(): GetCallback<UpcastElementEvent> {
+	return ( evt, data, conversionApi ) => {
+		const { writer } = conversionApi;
+
+		if ( data.modelRange ) {
```
Comment (niegowski) [inline packages/ckeditor5-list/src/todolist/todolistediting.ts:408]: Please return from the converter early so we do not keep the whole body in a single `if` statement.

File: packages/ckeditor5-list/src/todolist/todolistediting.ts [hunk 4]
```diff
@@ -392,6 +398,29 @@ export default class TodoListEditing extends Plugin {
...
+			const items = Array
+				.from( data.modelRange.getItems( { shallow: true } ) )
+				.filter( ( item ): item is Element => item.getAttribute( 'listType' ) === 'todo' );
```
Comment (niegowski) [inline packages/ckeditor5-list/src/todolist/todolistediting.ts:411]: This won't work correctly if there is a nested to-do list. It would be handled the same as it would be the same list item. Please remember that lists are stored in the model as a flat structure.

File: packages/ckeditor5-list/src/todolist/todolistediting.ts [hunk 5]
```diff
@@ -392,6 +398,29 @@ export default class TodoListEditing extends Plugin {
...
+
+			// In some cases we need to set value of `todoListChecked` attribute in to-do lists.
+			// See: https://github.com/ckeditor/ckeditor5/issues/15602#top.
```
Comment (niegowski) [inline packages/ckeditor5-list/src/todolist/todolistediting.ts:414]:
```suggestion
			// See: https://github.com/ckeditor/ckeditor5/issues/15602.
```

File: packages/ckeditor5-list/src/todolist/todolistediting.ts [hunk 6]
```diff
@@ -392,6 +398,29 @@ export default class TodoListEditing extends Plugin {
...
+function todoListItemUpcastConverter(): GetCallback<UpcastElementEvent> {
+	return ( evt, data, conversionApi ) => {
+		const { writer } = conversionApi;
+
+		if ( data.modelRange ) {
+			const items = Array
+				.from( data.modelRange.getItems( { shallow: true } ) )
+				.filter( ( item ): item is Element => item.getAttribute( 'listType' ) === 'todo' );
+
+			// In some cases we need to set value of `todoListChecked` attribute in to-do lists.
```
Comment (niegowski) [inline packages/ckeditor5-list/src/todolist/todolistediting.ts:413]: Please explain what those cases are.

**Review by niegowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-list/src/todolist/todolistediting.ts (hunk 4 above)
Comment (Mati365) [reply packages/ckeditor5-list/src/todolist/todolistediting.ts]: @niegowski I added fix to group items before checks. From what I can see it solves the issue.  Can you take a look?

File: packages/ckeditor5-list/src/todolist/todolistediting.ts [hunk 7]
```diff
@@ -392,6 +398,47 @@ export default class TodoListEditing extends Plugin {
...
+			)
+			.reduce( ( acc, item ) => {
+				const listItemId = item.getAttribute( 'listItemId' ) as string;
+				const items = acc.get( listItemId ) || [];
+
+				items.push( item );
+				acc.set( listItemId, items );
+
+				return acc;
+			}, new Map<string, Array<Element>>() );
```
Comment (niegowski) [inline packages/ckeditor5-list/src/todolist/todolistediting.ts:426]: Can we use the util helper from here: https://ckeditor.com/docs/ckeditor5/latest/api/module_list_list_utils_model.html#function-getAllListItemBlocks ?

Comment (Mati365) [reply packages/ckeditor5-list/src/todolist/todolistediting.ts]: @niegowski Added in this commit https://github.com/ckeditor/ckeditor5/pull/16785/commits/ae81fc1f120e8c152d106c7629ab356302f83c6f

**Review by niegowski — APPROVED** [review]
