### PR TITLE
LinkImage should not crash if initialized before Image

### LINKED ISSUE #15617: LinkImage loaded before Image crashes the editor
## 📝 Provide detailed reproduction steps (if any)

Create an editor containing the `LinkImage` plugin (and Image, loaded later).

I prepared two demos:

* LinkImage, Image: https://jsfiddle.net/7q4ygwtu/ (error)
* Image, LinkImage: https://jsfiddle.net/7q4ygwtu/1/ (works)

### ✔️ Expected result

No error.

### ❌ Actual result

```
ckeditor5-dll.js:5 Uncaught (in promise) CKEditorError: schema-cannot-extend-missing-item {"itemName":"imageBlock"}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-schema-cannot-extend-missing-item
    at li.extend (ckeditor5-dll.js:5:312284)
    at je.init (link.js:5:40837)
    at async Editor.tsx:26:19
    at async Editor.tsx:124:4
```

### ❓ Possible solution

The `LinkImageEditing` plugin requires the `imageBlock` element (schema), registered by the `ImageEditing` plugin in the past. At some point, it has changed, and now, it does not work. Replacing the soft requirement from `ImageEditing` to `ImageBlockEditing ` fixes the issue.

* https://github.com/ckeditor/ckeditor5/blob/a217db61f47e60c61a44ea1814d1fd08e08a4d0c/packages/ckeditor5-link/src/linkimage.ts#L27
	* https://github.com/ckeditor/ckeditor5/blob/a217db61f47e60c61a44ea1814d1fd08e08a4d0c/packages/ckeditor5-link/src/linkimageediting.ts#L43
* https://github.com/ckeditor/ckeditor5/blob/a217db61f47e60c61a44ea1814d1fd08e08a4d0c/packages/ckeditor5-image/src/image/imageblockediting.ts#L41

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (link): Fixed the editor crash using the `LinkImage` plugin loaded before `Image`, which ends with extending the schema definitions before they are registered. Closes #15617.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-html-support/tests/integrations/image.js [hunk 1]
```diff
@@ -2474,10 +2474,10 @@ describe( 'ImageElementSupport', () => {
 						'alt',
 						'src',
 						'srcset',
-						'linkHref',
 						'width',
 						'height',
 						'placeholder',
+						'linkHref',
```
Comment (pomek) [inline packages/ckeditor5-html-support/tests/integrations/image.js:2480]: I am unsure about this test. If the order of items in the array does not matter, the assertion should be replaced with `to.contain` (x7). The current implementation it looks like the order should not be changed.

**Review by niegowski — APPROVED** [review]

**Review by psmyrek — APPROVED** [review]
LGTM 🎉
