### PR TITLE
[GHS] Media Embed feature integration

### LINKED ISSUE #9918: [GHS] Applying attributes to existing features - media embed
## 📝 Provide detailed reproduction steps (if any)

Due to the complex model structure of the [Media Embed](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by maxbarnas**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (html-support): Added General HTML Support integration for Media Embed feature. Closes #9918.

---

### Additional information

This feature does not cover a situation where `mediaEmbed.previewsInData` is `true`.

### CODE REVIEW

File: packages/ckeditor5-html-support/tests/manual/mediaembed.js [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+		image: { toolbar: [ 'toggleImageCaption', 'imageTextAlternative' ] },
+		toolbar: [ 'mediaEmbed', '|', 'sourceEditing' ],
+		mediaEmbed: {
+			toolbar: [ 'mediaEmbed' ]
+		},
+		htmlSupport: {
+			allow: [
+				{
+					name: /^(figure|oembed)$/,
+					attributes: [ 'data-validation-allow', 'data-validation-disallow' ],
```
Comment (psmyrek) [inline packages/ckeditor5-html-support/tests/manual/mediaembed.js:36]: Why `data-validation-disallow` attribute is in the `allow` section?

Comment (maxbarnas) [reply packages/ckeditor5-html-support/tests/manual/mediaembed.js:36]: Duh! My bad!

**Review by psmyrek — APPROVED** [review]
LGTM 🎉
