### PR TITLE
model.History#getOperations was returning incorrect values if history had operations with negative version numbers or version numbers differing by more than one

### LINKED ISSUE #8143: History#getOperations is incorrectly implemented
## 📝 Provide detailed reproduction steps (if any)

At the moment, `History#getOperations` is implemented in a way that it expects that:

*   Operations versions start from `0`,
*   Operations versions have incremental values.

However, in real-time editing, if operations get compressed, you may not get some initial operations. This causes crashes, for example in undo.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix: \`model.History#getOperations\` was returning incorrect values if history had operations with negative version numbers or version numbers differing by more than one. Closes #8143.

### CODE REVIEW

File: packages/ckeditor5-engine/tests/model/history.js [hunk 1]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
 	} );
 
 	describe( 'getOperations', () => {
-		let ops;
+		it( 'should return only operations from given base version', () => {
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 1 ) ) );
+			history.addOperation( ( new Operation( 2 ) ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:88]:
```suggestion
			history.addOperation( new Operation( 0 ) );
			history.addOperation( new Operation( 1 ) );
			history.addOperation( new Operation( 2 ) );
```

File: packages/ckeditor5-engine/tests/model/history.js [hunk 2]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
...
+			expect( ops[ 0 ].baseVersion ).to.equal( 1 );
+			expect( ops[ 1 ].baseVersion ).to.equal( 2 );
 		} );
 
-		it( 'should return only operations from given base version', () => {
-			const historyOperations = Array.from( history.getOperations( 1 ) );
+		it( 'should return only operations up to given base version', () => {
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 1 ) ) );
+			history.addOperation( ( new Operation( 2 ) ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:100]:
```suggestion
			history.addOperation( new Operation( 0 ) );
			history.addOperation( new Operation( 1 ) );
			history.addOperation( new Operation( 2 ) );
```

File: packages/ckeditor5-engine/tests/model/history.js [hunk 3]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
...
+			const ops = history.getOperations( 1, 2 );
+
+			expect( ops.length ).to.equal( 1 );
+			expect( ops[ 0 ].baseVersion ).to.equal( 1 );
+		} );
 
-			expect( historyOperations ).to.deep.equal( ops.slice( 1 ) );
+		it( 'should return empty array if no operations match', () => {
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 1 ) ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:110]:
```suggestion
			history.addOperation( new Operation( 0 ) );
			history.addOperation( new Operation( 1 ) );
```

File: packages/ckeditor5-engine/tests/model/history.js [hunk 4]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
...
 		} );
 
-		it( 'should return only operations up to given base version', () => {
-			const historyOperations = Array.from( history.getOperations( 1, 2 ) );
+		it( 'should return correct values if history holds operations with negative base version', () => {
+			history.addOperation( ( new Operation( -2 ) ) );
+			history.addOperation( ( new Operation( -1 ) ) );
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 1 ) ) );
+			history.addOperation( ( new Operation( 2 ) ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:121]:
```suggestion
			history.addOperation( new Operation( -2 ) );
			history.addOperation( new Operation( -1 ) );
			history.addOperation( new Operation( 0 ) );
			history.addOperation( new Operation( 1 ) );
			history.addOperation( new Operation( 2 ) );
```

File: packages/ckeditor5-engine/tests/model/history.js [hunk 5]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
...
 
-		it( 'should return empty array if no operations match', () => {
-			expect( Array.from( history.getOperations( 20 ) ).length ).to.equal( 0 );
-			expect( Array.from( history.getOperations( -1 ) ).length ).to.equal( 0 );
+		it( 'should return correct values if history holds operations with base versions that differ by more than one', () => {
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 4 ) ) );
+			history.addOperation( ( new Operation( 6 ) ) );
+			history.addOperation( ( new Operation( 9 ) ) );
+			history.addOperation( ( new Operation( 13 ) ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:131]:
```suggestion
			history.addOperation( new Operation( 0 ) );
			history.addOperation( new Operation( 4 ) );
			history.addOperation( new Operation( 6 ) );
			history.addOperation( new Operation( 9 ) );
			history.addOperation( new Operation( 13 ) );
```

File: packages/ckeditor5-engine/tests/model/history.js [hunk 6]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
...
-			const historyOperations = Array.from( history.getOperations( 1, 2 ) );
+		it( 'should return correct values if history holds operations with negative base version', () => {
+			history.addOperation( ( new Operation( -2 ) ) );
+			history.addOperation( ( new Operation( -1 ) ) );
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 1 ) ) );
+			history.addOperation( ( new Operation( 2 ) ) );
 
-			expect( historyOperations ).to.deep.equal( ops.slice( 1, 2 ) );
+			expect( history.getOperations( -1, 2 ).length ).to.equal( 3 ); // -1, 0, 1.
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:123]: Maybe we could check returned operations whether they are correct instead of code comment?

File: packages/ckeditor5-engine/tests/model/history.js [hunk 7]
```diff
@@ -78,31 +82,55 @@ describe( 'History', () => {
...
-			expect( Array.from( history.getOperations( 20 ) ).length ).to.equal( 0 );
-			expect( Array.from( history.getOperations( -1 ) ).length ).to.equal( 0 );
+		it( 'should return correct values if history holds operations with base versions that differ by more than one', () => {
+			history.addOperation( ( new Operation( 0 ) ) );
+			history.addOperation( ( new Operation( 4 ) ) );
+			history.addOperation( ( new Operation( 6 ) ) );
+			history.addOperation( ( new Operation( 9 ) ) );
+			history.addOperation( ( new Operation( 13 ) ) );
+
+			expect( history.getOperations( 2, 11 ).length ).to.equal( 3 ); // 4, 6, 9.
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/history.js:133]: Maybe we could check returned operations whether they are correct instead of code comment?

**Review by niegowski — APPROVED** [review]
