### PR TITLE
Fix (engine): detecting restricted objects in firefox

### LINKED ISSUE #9635: [Firefox] Error when clicking on label elements inside editor
## 📝 Provide detailed reproduction steps (if any)

There are multiple ways to reproduce this ( see screencasts below ), example steps:
1. Open Firefox and go to https://ckeditor.com/ckeditor-5/demo/
2. Open image alternative balloon
3. Click several times on label `Text alternative` 

### ✔️ Expected result

Nothing Happens

### ❌ Actual result

```js
Uncaught CKEditorError: Permission denied to access property Symbol.toStringTag
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Permission denied to access property Symbol.toStringTag
    tr istext.js:17
    domSelectionToView domconverter.js:515
    _handleSelectionChange selectionobserver.js:145
    observe selectionobserver.js:104
    fire emittermixin.js:199
    i emittermixin.js:247
    attach emittermixin.js:202
    listenTo emittermixin.js:61
    observe selectionobserver.js:103
    attachDomRoot view.js:288
    init classiceditorui.js:104
    create classiceditor.js:193
    promise callback*create/< classiceditor.js:193
    create classiceditor.js:188
    A app-bb5ed7289d.js:33
    P app-bb5ed7289d.js:33
    q app-bb5ed7289d.js:33
    init app-bb5ed7289d.js:33
    default app-bb5ed7289d.js:44
    init app-bb5ed7289d.js:16
    EventListener.handleEvent* app-bb5ed7289d.js:16
    n app-bb5ed7289d.js:1
    <anonymous> app-bb5ed7289d.js:1
    <anonymous> app-bb5ed7289d.js:1
ckeditorerror.js:64:2
```
## Screencasts

https://user-images.githubusercontent.com/34380544/117288882-4149f900-ae6c-11eb-95f9-ed722c1b6d7b.mp4

https://user-images.githubusercontent.com/34380544/117288891-45761680-ae6c-11eb-8a19-76268d3ca743.mp4

https://user-images.githubusercontent.com/34380544/117288896-460ead00-ae6c-11eb-960a-e9e6ecce0972.mp4

## 📃 Other details

* Browser: Firefox
* Happens since version `24.0.0`
* It happens when I click inside forms, specifically on label elements, but only those that are inside editor - for example I cannot reproduce this when opening media embed toolbar dropdown and clicking on the label.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (engine): Don't throw an error when clicking on baloon with input on Firefox. Closes #9635.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-engine/src/view/observer/selectionobserver.ts [hunk 1]
```diff
@@ -232,6 +232,10 @@ export default class SelectionObserver extends Observer {
 
 		const domSelection = domDocument.defaultView!.getSelection()!;
 
+		if ( env.isGecko && this._isObjectRestricted( domSelection.getRangeAt( 0 ).startContainer ) ) {
```
Comment (oleq) [inline packages/ckeditor5-engine/src/view/observer/selectionobserver.ts:235]: How about we `s/_isObjectRestricted/isGeckoRestrictedObject` and we move the `env.isGecko` check as the first line of the helper? IMO this would improve the readability of `_handleSelectionChange()` because the code would be as much natural language as possible.

File: packages/ckeditor5-engine/tests/view/observer/selectionobserver.js [hunk 2]
```diff
@@ -162,6 +162,46 @@ describe( 'SelectionObserver', () => {
 		changeDomSelection();
 	} );
 
+	it( 'should not pass non-valid object on Firefox', done => {
```
Comment (oleq) [inline packages/ckeditor5-engine/tests/view/observer/selectionobserver.js:165]: I suggested simplification of the try/catch code but this makes this test fail. Do you think this test case is valid? If so, then how?

File: packages/ckeditor5-engine/tests/view/observer/selectionobserver.js [hunk 3]
```diff
@@ -162,6 +162,46 @@ describe( 'SelectionObserver', () => {
...
+		testUtils.sinon.stub( env, 'isGecko' ).value( true );
+
+		const spy = sinon.spy( selectionObserver.mutationObserver, 'flush' );
+
+		changeDomSelection();
+		setTimeout( () => {
+			sinon.assert.calledOnce( spy );
+			done();
+		}, 100 );
+	} );
```
Comment (oleq) [inline packages/ckeditor5-engine/tests/view/observer/selectionobserver.js:203]: Let's wrap these into a `describe( 'Restricted objects handling in Gecko', () => {} )` group because... they are a group of tests for a very specific use-case 🙂

**Review by oleq — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-engine/src/view/observer/selectionobserver.ts [hunk 4]
```diff
@@ -302,6 +306,24 @@ export default class SelectionObserver extends Observer {
...
+			if ( Object.prototype.toString.call( obj ) ) {
+				isRestricted = false;
+			} else {
+				isRestricted = true;
+			}
+		} catch ( error ) {
+			isRestricted = true;
+		}
+
+		return isRestricted;
```
[the remark this answers is not in the document]
Comment (illia-stv) [reply packages/ckeditor5-engine/src/view/observer/selectionobserver.ts:324]: Yeah sure, nice idea

**Review by oleq — APPROVED** [review]
LGTM

I took the liberty of making the test a little bit more specific.

File: packages/ckeditor5-engine/src/view/observer/selectionobserver.ts [hunk 5]
```diff
@@ -232,6 +232,10 @@ export default class SelectionObserver extends Observer {
 
 		const domSelection = domDocument.defaultView!.getSelection()!;
 
+		if ( isGeckoRestrictedDomSelection( domSelection ) ) {
+			return;
+		}
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/observer/selectionobserver.ts:237]: I'm not sure if this code should be checked right here. I'm wondering if it should not be verified in `DomConverter#domSelectionToView()` and selection without ranges should be returned.

Comment (oleq) [reply packages/ckeditor5-engine/src/view/observer/selectionobserver.ts:237]: That would be after `this.mutationObserver.flush()`. Do you think this would be OK?

Comment (niegowski) [reply packages/ckeditor5-engine/src/view/observer/selectionobserver.ts:237]: I think so. What we miss in this PR is changing the hasDomSelection flag. The selection is no longer in editable so we should handle it as it would have no ranges.

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 6]
```diff
@@ -1787,6 +1792,24 @@ function _logUnsafeElement( elementName: string ): void {
 	}
 }
 
+// In certain cases, Firefox mysteriously assigns so called "restricted objects" to native DOM Range properties.
+// Any attempt at accessing restricted object's properties causes errors.
+// https://github.com/ckeditor/ckeditor5/issues/9635
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:1797]:
```suggestion
/**
 * In certain cases, Firefox mysteriously assigns so called "restricted objects" to native DOM Range properties.
 * Any attempt at accessing restricted object's properties causes errors.
 * https://github.com/ckeditor/ckeditor5/issues/9635
 */
```

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 7]
```diff
@@ -732,6 +733,10 @@ export default class DomConverter {
 	 * @returns View selection.
 	 */
 	public domSelectionToView( domSelection: DomSelection ): ViewSelection {
+		if ( isGeckoRestrictedDomSelection( domSelection ) ) {
+			return new ViewSelection( [] );
+		}
+
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:739]: Please add tests for this case (tests that are already for the selection observer should also stay there).

Comment (niegowski) [reply packages/ckeditor5-engine/src/view/domconverter.ts:739]: I'd add a link to the GH issue in code comment.

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 8]
```diff
@@ -1787,6 +1792,24 @@ function _logUnsafeElement( elementName: string ): void {
...
+// In certain cases, Firefox mysteriously assigns so called "restricted objects" to native DOM Range properties.
+// Any attempt at accessing restricted object's properties causes errors.
+// https://github.com/ckeditor/ckeditor5/issues/9635
+function isGeckoRestrictedDomSelection( domSelection: DomSelection ): boolean {
+	if ( !env.isGecko ) {
+		return false;
+	}
+
+	try {
+		const container = domSelection.getRangeAt( 0 ).startContainer;
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:1804]: There is a valid case when the DOM selection has no ranges and this should not affect this function. Now it will return true for selection without ranges and it would not be true.

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 9]
```diff
@@ -1787,6 +1792,24 @@ function _logUnsafeElement( elementName: string ): void {
...
+		Object.prototype.toString.call( container );
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:1805]:
```suggestion

		Object.prototype.toString.call( container );
```

**Review by niegowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 10]
```diff
@@ -1792,17 +1793,22 @@ function _logUnsafeElement( elementName: string ): void {
...
+ */
 function isGeckoRestrictedDomSelection( domSelection: DomSelection ): boolean {
 	if ( !env.isGecko ) {
 		return false;
 	}
 
 	try {
-		const container = domSelection.getRangeAt( 0 ).startContainer;
-		Object.prototype.toString.call( container );
+		if ( domSelection.rangeCount ) {
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:1807]: I'd extract this condition to the above one.

**Review by niegowski — COMMENTED** [review]
Live review, some fixes pushed. Please fix the SelectionObserver tests.

File: packages/ckeditor5-engine/tests/view/observer/selectionobserver.js [hunk 11]
```diff
@@ -30,6 +32,7 @@ describe( 'SelectionObserver', () => {
 		domRoot.innerHTML = '<div contenteditable="true"></div><div contenteditable="true" id="additional"></div>';
 		domMain = domRoot.childNodes[ 0 ];
 		domDocument.body.appendChild( domRoot );
+		converter = new DomConverter( viewDocument );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/view/observer/selectionobserver.js:35]: You should use DomConverter which is already available in `view.domConverter`.

File: packages/ckeditor5-engine/tests/view/observer/selectionobserver.js [hunk 12]
```diff
@@ -167,26 +170,73 @@ describe( 'SelectionObserver', () => {
 			testUtils.sinon.stub( env, 'isGecko' ).value( true );
 		} );
 
-		it( 'should detect "restricted objects" in Firefox DOM ranges and prevent an error being thrown', done => {
-			const domRangeStubWithRestrictedObject = domDocument.createRange();
+		it( 'should detect "restricted objects" in Firefox DOM ranges and prevent an error being thrown', () => {
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/view/observer/selectionobserver.js:173]: Those tests are not testing SelectionObserver at all. You should test the mocked selection change, not the DomConverter directly.

**Review by niegowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-engine/tests/view/observer/selectionobserver.js [hunk 13]
```diff
@@ -547,7 +488,6 @@ describe( 'SelectionObserver', () => {
 			selectionObserver.listenTo( domMain, 'selectstart', selectStartChangedSpy, { priority: 'highest' } );
 
 			// The event was fired somewhere else in DOM.
-			domDocument.dispatchEvent( new Event( 'selectstart' ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/view/observer/selectionobserver.js:473]: This looks like it was accidentally removed.
