### PR TITLE
Fixed ugly crashes when playing with List style feature

### LINKED ISSUE #7922: List loses the style of the base level after changing style in indented items
## 📝 Provide detailed reproduction steps (if any)

1. On latest `stable` branch go to docs `/features/lists.html#demo-2`
2. Choose some numbered styling
3. Add list item
4. Add indented list item and change its styling to bulleted
5. Press `enter` twice to get back to the base list level

### ✔️ Expected result

Styling gets back to the one chosen in step 2 ( in this case upper latin )

### ❌ Actual result

0_list1
  
The same happens the other way round - if you first choose _bulleted_ styles and then _numbered_ for indented items.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #7930: Wrong list style in undo stack after merging two different list styles
## 📝 Provide detailed reproduction steps (if any)

1.  Open [lists feature demo](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html) for the upcoming v21 release (not not published yet, so production link won't work).
2.  Focus the editor under the "List styles" section.
3.  Select entire first list.
4.  Change style to upper-roman.
5.  Remove the entire "How to prepare the coffee" paragraph, so that the list get combined.
6.  Undo.

Full screencast:

### ✔️ Expected result

Both lists preserve their initial styles (the first keeps upper Roman, the second keeps numeric with leading 0)

### ❌ Actual result

You're unable to restore initial list type of the second list.

## 📃 Other details

*   Browser: Chrome
*   OS: Windows 10
*   CKEditor version: v21

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #8072: Crash after indenting list item when list is the first element in the editor
### Steps:
1. On latest `master` open **list styles** manual test
2. Remove all content from the editor ( or put the cursor at the very beginning of editor content )
3. Add a list item
4. Press `enter` to add another one
5. Press `tab` to indent list item
```js
Uncaught TypeError: Cannot read property 'is' of null
    at liststyleediting.js:460
    at Document._callPostFixers (document.js:404)
    at Document._handleChangeBlock (document.js:303)
    at Model._runPendingChanges (model.js:833)
    at Model.change (model.js:175)
    at IndentCommand.execute (indentcommand.js:57)
    at IndentCommand.<anonymous> (observablemixin.js:255)
    at IndentCommand.fire (emittermixin.js:209)
    at IndentCommand.<computed> [as execute] (observablemixin.js:259)
    at CommandCollection.execute (commandcollection.js:69)
```
0_list2

### Other: 
- doesn't happen on normal list test
- looks like a recent regression, bisection shows this commit https://github.com/ckeditor/ckeditor5/commit/76014e5a3570e0f3ab87bad0e5e961f0671f0980

### LINKED ISSUE #8073: Crash when merging two list items
### Steps:
1. On latest master open **list styles** manual test
2. Add three list items ( each with +1 level of indentation )
3. Create selection spanning from middle of first to middle of second list item
4. Press `backspace`

### ✔️ Expected result

List items are merged with no error

### ❌ Actual result

Editor crashes:
```js
position.js:935 Uncaught TypeError: Cannot read property 'is' of null
    at Function._createAt (position.js:935)
    at Model.createPositionAt (model.js:635)
    at Writer.createPositionAt (writer.js:609)
    at liststyleediting.js:174
    at Model.change (model.js:178)
    at Model.listenTo.priority (liststyleediting.js:158)
    at Model.fire (emittermixin.js:209)
    at Model.<computed> [as deleteContent] (observablemixin.js:259)
    at Object.callback (deletecommand.js:113)
    at Model._runPendingChanges (model.js:830)
  
liststyleediting.js:196 Uncaught TypeError: Cannot read property 'getStyle' of null
    at UpcastDispatcher.dispatcher.on.priority (liststyleediting.js:196)
    at UpcastDispatcher.fire (emittermixin.js:209)
    at UpcastDispatcher._convertItem (upcastdispatcher.js:249)
    at UpcastDispatcher.convert (upcastdispatcher.js:207)
    at datacontroller.js:414
    at Model.change (model.js:178)
    at DataController.toModel (datacontroller.js:413)
    at MutationHandler._handleContainerChildrenMutations (injecttypingmutationshandling.js:109)
    at MutationHandler.handle (injecttypingmutationshandling.js:64)
    at Document.<anonymous> (injecttypingmutationshandling.js:22)
```
0_list3

## 📃 Other details
- cannot reproduce on normal list manual test
- recent regression, bisection shows this commit: https://github.com/ckeditor/ckeditor5/commit/f7dc25ea6fcdadb6d1a46a7a0aea8ac196c87a41

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #8081: For 2nd and deeper indent level, cannot use list style that was used before
## 📝 Provide detailed reproduction steps (if any)

1. Create list with the following structure:
```js
- level 0
    - level 1
        - level 2
    - level 1
        - level 2
```
2. Apply some style for level 1 list items
3. Try to apply style for both level 2 list items ( same style )

### ✔️ Expected result

You can add any list style to all 2nd and deeper level indents.

### ❌ Actual result

You cannot use style that has already been used in the list above ( in this case lower latin ) :
0_list1

## 📃 Other details

* Browser: any
* CKEditor version: happens since the introduction of the feature

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (list): The editor will not crash when indenting a list item that is the last element in the editor. Closes #8072.

Fix (list): Undo will restore the proper value of the `list-style-type` attribute in the [`View`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_containerelement-ContainerElement.html) element after undoing merging different lists. Closes #7930. 

Fix (list): Fixed a bug that blocked using the same value of the [List style](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html#list-styles) feature for nested lists. Closes #8081.

Internal (list): The mechanism that merges two lists and inherits their list styles will not crash while deleting content (lists with different values of the `listIndent` attribute) in a nested list. Closes #8073.

Internal (list): The `listStyle` attribute will be inherited while deleting nested lists. The previous implementation added in #7879 handled lists with the `listIndent=0`. See #8073.

☝️ Marking as internal since the bug appeared in the implementation #7879 that was added in the current iteration.

### CODE REVIEW

**Comment by mlewand** [comment]
@ckeditor/qa-team can you aid us with your testing super powers to see if it works fine? 🙂

**Comment by FilipTokarski** [comment]
Bugs fixed, I didn't find anything new in this PR 👍

**Comment by mlewand** [comment]
@ckeditor/qa-team since there was just added a fix to #[7930](https://github.com/ckeditor/ckeditor5/issues/7930) into this PR can I ask you to retest it again with this change in mind?

File: packages/ckeditor5-list/tests/liststyleediting.js [hunk 1]
```diff
@@ -923,6 +973,97 @@ describe( 'ListStyleEditing', () => {
...
+						view = editor.editing.view;
+					} );
+			} );
+
+			afterEach( () => {
+				return editor.destroy();
+			} );
+
+			// See: #7930.
+			it( 'should restore proper list style attribute after undo merging lists', () => {
```
Comment (mlewand) [inline packages/ckeditor5-list/tests/liststyleediting.js:996]: This test doesn't fail for implementation that is on `master` so it doesn't protect us from a regression.

**Review by mlewand — COMMENTED** [review]
Pushed one micro commit. The code looks fine, except one of unit tests doesn't verify #7930.

So once we have the test fixed and green light from @ckeditor/qa-team we're good to go :ok\_hand:

**Comment by FilipTokarski** [comment]
Looks good, I didn't find anything new 👍

File: packages/ckeditor5-list/tests/liststyleediting.js (hunk 1 above)
Comment (pomek) [reply packages/ckeditor5-list/tests/liststyleediting.js:996]: That's weird. I figured out that the bug (#7930) was fixed (accidentally) while I was working on the merging lists ticket (#7879).

Bisect showed me this commit – https://github.com/ckeditor/ckeditor5/commit/7aa952823a8b182dc41075fa8cf4cc3a452eb78b – as a point where the bug is no longer reproducible.

But on the parent commit – https://github.com/ckeditor/ckeditor5/commit/7aa952823a8b182dc41075fa8cf4cc3a452eb78b – I was able to reproduce the error (#7930).

I also checked the unit test – it behaves as expected. Passes for the first commit and fails for the second one.

Comment (mlewand) [reply packages/ckeditor5-list/tests/liststyleediting.js:996]: In case it was fixed in another PR it make sense that it passes now. I have verified that it indeed passes since 7aa9528.
