### PR TITLE
Validating image url input and disabling media insert button when inp…

### LINKED ISSUE #7917: Inserting images via URL does not validate input
## 📝 Provide detailed reproduction steps (if any)

1. On latest `release` branch go to docs `/features/image.html#inserting-images-via-source-url`
2. Try using `insert image via URL` with following data:
    - pressing `space`
    - random letters
    - random digits

### ✔️ Expected result

Input gets validated ( at least rubbish input like the one mentioned above )

### ❌ Actual result

You can type anything, plugin will insert broken image placeholder or empty widget:  
  
0_img1

## 📃 Other details

* Browser: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pkwasnik**
…ut is empty

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (image, media-embed): Validating image url input and disabling media insert button when input is empty. Closes #7917.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-image/tests/imageinsert/ui/imageinsertpanelview.js [hunk 1]
```diff
@@ -294,5 +294,32 @@ describe( 'ImageUploadPanelView', () => {
...
+			form.fieldView.fire( 'input' );
+
+			expect( view.imageURLInputValue ).to.equal( 'test' );
+		} );
+
+		it( 'binds saveButtonView#isEnabled to URL input value', () => {
+			const form = view.getIntegration( 'insertImageViaUrl' );
+			const saveButtonView = view.template.children[ 1 ].children.first;
+
+			expect( !!saveButtonView.isEnabled ).to.be.false;
```
Comment (jodator) [inline packages/ckeditor5-image/tests/imageinsert/ui/imageinsertpanelview.js:316]:
```suggestion
			expect( saveButtonView.isEnabled ).to.be.false;
```

I'm adding suggestions to this - as I think that we should have consistent values for `isFooBar` properties. We document this as `Boolean` so I think that this should be done on the bounding level.

File: packages/ckeditor5-media-embed/tests/mediaembedui.js [hunk 2]
```diff
@@ -209,13 +209,27 @@ describe( 'MediaEmbedUI', () => {
...
+			form.urlInputView.fieldView.element.value = '   test   ';
+			form.urlInputView.fieldView.fire( 'input' );
+
+			expect( form.mediaURLInputValue ).to.equal( 'test' );
+		} );
+
+		it( 'binds saveButtonView#isEnabled to trimmed URL input value', () => {
+			form.urlInputView.fieldView.fire( 'input' );
+
+			expect( !!form.saveButtonView.isEnabled ).to.be.false;
```
Comment (jodator) [inline packages/ckeditor5-media-embed/tests/mediaembedui.js:227]:
```suggestion
			expect( form.saveButtonView.isEnabled ).to.be.false;
```

File: packages/ckeditor5-media-embed/tests/mediaembedui.js [hunk 3]
```diff
@@ -209,13 +209,27 @@ describe( 'MediaEmbedUI', () => {
...
+
+			form.urlInputView.fieldView.element.value = 'test';
+			form.urlInputView.fieldView.fire( 'input' );
+
+			expect( !!form.saveButtonView.isEnabled ).to.be.true;
```
Comment (jodator) [inline packages/ckeditor5-media-embed/tests/mediaembedui.js:232]:
```suggestion
			expect( form.saveButtonView.isEnabled ).to.be.true;
```

File: packages/ckeditor5-media-embed/src/ui/mediaformview.js [hunk 4]
```diff
@@ -71,6 +79,7 @@ export default class MediaFormView extends View {
 		 */
 		this.saveButtonView = this._createButton( t( 'Save' ), checkIcon, 'ck-button-save' );
 		this.saveButtonView.type = 'submit';
+		this.saveButtonView.bind( 'isEnabled' ).to( this, 'mediaURLInputValue' );
```
Comment (jodator) [inline packages/ckeditor5-media-embed/src/ui/mediaformview.js:82]:
```suggestion
		this.saveButtonView.bind( 'isEnabled' ).to( this, 'mediaURLInputValue', value => !!value );
```

I'd go with this here to make `Button.isEnabled` a boolean.

**Review by jodator — APPROVED** [review]
Great!

I've changed one thing from the original code. I think that we should expose `isEnabled` as `Boolean` and we can to it easily with binding and custom callback (not directly stated in the docs).
