### PR TITLE
Fix image resize handle displaying NaN.

### LINKED ISSUE #10776: Image Resize handles not working properly
Hello there!! Thank you for this awesome editor.

I'm trying to enable Image Resize Handles on a custom inline editor build in Angular 12. But when i try to drag the square handlers it just show %NaN instead of the percentage. 

image

My configuration is: 

```javascript

import InlineEditorBase from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Subscript from '@ckeditor/ckeditor5-basic-styles/src/subscript';
import Superscript from '@ckeditor/ckeditor5-basic-styles/src/superscript';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import Link from '@ckeditor/ckeditor5-link/src/link';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';
import CloudServices from '@ckeditor/ckeditor5-cloud-services/src/cloudservices';

import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import Clipboard from '@ckeditor/ckeditor5-clipboard/src/clipboard';
import MathType from '@wiris/mathtype-ckeditor5/src/plugin';
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';
import ImageInsert from '@ckeditor/ckeditor5-image/src/imageinsert';
import Font from '@ckeditor/ckeditor5-font/src/font';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import ListStyle from '@ckeditor/ckeditor5-list/src/liststyle';
import HtmlEmbed from '@ckeditor/ckeditor5-html-embed/src/htmlembed';

InlineEditor.builtinPlugins = [
	Essentials,
	Autoformat,
	Bold,
	Italic,
	Underline,
	Strikethrough,
	Subscript,
	Superscript,
	BlockQuote,
	CloudServices,
	Heading,
	Image,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	IndentBlock,
	Link,
	ListStyle,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TableProperties,
	TableCellProperties,
	TextTransformation,
	Alignment,
	ImageResize,
	Clipboard,
	SimpleUploadAdapter,
	ImageInsert,
	MathType,
	Font,
	HtmlEmbed
]
```

---

Add 👍 if you would like this issue to be resolved.

### PR DESCRIPTION
**Pull request by mremiszewski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (image): Fix the image resize handle displaying NaN in some scenarios. Closes #10776.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-widget/src/widgetresize/resizerstate.ts [hunk 1]
```diff
@@ -189,13 +189,24 @@ export default class ResizeState extends ObservableMixin() {
...
- * Calculates a relative width of a `domResizeHost` compared to it's parent in percents.
+ * Calculates a relative width of a `domResizeHost` compared to its ancestor in percents.
  */
 function calculateHostPercentageWidth( domResizeHost: HTMLElement, resizeHostRect: Rect ) {
 	const domResizeHostParent = domResizeHost.parentElement;
 	// Need to use computed style as it properly excludes parent's paddings from the returned value.
-	const parentWidth = parseFloat( domResizeHostParent!.ownerDocument.defaultView!.getComputedStyle( domResizeHostParent! ).width );
-
+	let parentWidth = parseFloat( domResizeHostParent!.ownerDocument.defaultView!.getComputedStyle( domResizeHostParent! ).width );
+	try {
```
Comment (arkflpc) [inline packages/ckeditor5-widget/src/widgetresize/resizerstate.ts:198]: Add empty lines before and after code blocks.

File: packages/ckeditor5-widget/src/widgetresize/resizerstate.ts [hunk 2]
```diff
@@ -189,13 +189,24 @@ export default class ResizeState extends ObservableMixin() {
...
+		while ( isNaN( parentWidth ) ) {
+			checkedElement = checkedElement.parentElement!;
+			parentWidth = parseFloat(
+				domResizeHostParent!.ownerDocument.defaultView!.getComputedStyle( checkedElement ).width
+			);
+		}
+	}
+	catch {
+		return 0;
+	}
```
Comment (arkflpc) [inline packages/ckeditor5-widget/src/widgetresize/resizerstate.ts:209]: Add empty lines before and after code blocks.

**Review by arkflpc — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-widget/src/widgetresize/resizerstate.ts [hunk 3]
```diff
@@ -189,13 +189,24 @@ export default class ResizeState extends ObservableMixin() {
...
  */
 function calculateHostPercentageWidth( domResizeHost: HTMLElement, resizeHostRect: Rect ) {
 	const domResizeHostParent = domResizeHost.parentElement;
 	// Need to use computed style as it properly excludes parent's paddings from the returned value.
-	const parentWidth = parseFloat( domResizeHostParent!.ownerDocument.defaultView!.getComputedStyle( domResizeHostParent! ).width );
-
+	let parentWidth = parseFloat( domResizeHostParent!.ownerDocument.defaultView!.getComputedStyle( domResizeHostParent! ).width );
+	try {
+		let checkedElement = domResizeHostParent!;
+		while ( isNaN( parentWidth ) ) {
```
[the remark this answers is not in the document]
Comment (mremiszewski) [reply packages/ckeditor5-widget/src/widgetresize/resizerstate.ts:200]: Ad 1
IMO, current version has better readability
```
let parentWidth = sth(); // everything goes as usual

// error handling
try {
    ...code...
}
```

even if the line with `parentWidth` calculation is duplicated. If you insist I can change that.

Ad 2 
Eventually we'll go up to some root element, and return `0` with `catch` block, but I'll add some limit to not go too high

**Review by arkflpc — APPROVED** [review]
