### PR TITLE
Fixed rendering editor placeholder inside page break widget.

### LINKED ISSUE #8880: Editor placeholder renders inside page break widget
## 📝 Provide detailed reproduction steps (if any)

1.  http://fake.ckeditor.com:8125/ckeditor5/tests/manual/all-features.html
2.  remove all content
3.  insert page break

### ✔️ Expected result

Placeholder is not visible

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: current master branch
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pkwasnik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (page-break): Fixed rendering editor placeholder inside page break widget. Closes #8880.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-page-break/tests/pagebreakediting.js [hunk 1]
```diff
@@ -57,7 +57,7 @@ describe( 'PageBreakEditing', () => {
 		setModelData( model, '[<pageBreak></pageBreak>]' );
```
Comment (mlewand) [inline packages/ckeditor5-page-break/tests/pagebreakediting.js:57]: The TC name is still `should have label as a UIElement` now it is a raw element.

File: packages/ckeditor5-page-break/tests/pagebreakediting.js [hunk 2]
```diff
@@ -57,7 +57,7 @@ describe( 'PageBreakEditing', () => {
...
 		const textNode = viewDocument.getRoot().getChild( 0 ).getChild( 0 );
```
Comment (mlewand) [inline packages/ckeditor5-page-break/tests/pagebreakediting.js:58]: I don't know why this variable is called `textNode`? From what I see it holds an elemnt.

**Review by mlewand — CHANGES_REQUESTED** [review]
Just a minor details in the unit tests.

**Review by mlewand — APPROVED** [review]
Ok, all fine 👍 Marking the changelog entry as internal, since this regression has just been introduced on the master branch (was never published).
