### PR TITLE
Inserting emoji over a non-collapsed selection

### LINKED ISSUE #17819: Inserting a marker over non-collapses selection makes them collapsed
## 📝 Provide detailed reproduction steps (if any)

Use **Firefox** if cannot reproduce the issue on Chrome.

1. Open the Emoji manual test: http://localhost:8125/ckeditor5-emoji/tests/manual/emoji.html.
2. Double-click on any word.
3. Open the emoji picker.
4. Insert an emoji.

### ✔️ Expected result

Image

### ❌ Actual result

* The selection after double-click:
    Image
* After opening the emoji picker:
    Image

## 📃 Other details

* Browser: Firefox, `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0`.
* It's related to this part of the code: https://github.com/ckeditor/ckeditor5/blob/242a821aa8f898966152556dd63a54418dcb0cef/packages/ckeditor5-emoji/src/emojipicker.ts#L316-L320

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Inserting an emoji over a non-collapsed selection removes the selected text. Closes #17819.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by psmyrek — DISMISSED** [review]
LGTM 🎉

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

File: packages/ckeditor5-emoji/src/emojipicker.ts [hunk 1]
```diff
@@ -296,23 +332,27 @@ export default class EmojiPicker extends Plugin {
...
-					( { item } ) => !model.schema.isContent( item ),
-					{ boundaries: range }
-				);
-
-				writer.addMarker( VISUAL_SELECTION_MARKER_NAME, {
-					usingOperation: false,
-					affectsData: false,
-					range: writer.createRange( startPosition, range.end )
-				} );
+			if ( model.markers.has( VISUAL_SELECTION_MARKER_NAME ) ) {
```
Comment (przemyslaw-zan) [inline packages/ckeditor5-emoji/src/emojipicker.ts:329]: This could be a guard clause instead of nested `if`'s:

```
		model.change( writer => {
			const range = model.document.selection.getFirstRange()!;

			if ( model.markers.has( VISUAL_SELECTION_MARKER_NAME ) ) {
				writer.updateMarker( VISUAL_SELECTION_MARKER_NAME, { range } );

				return;
			}

			if ( range.start.isAtEnd ) {
				const startPosition = range.start.getLastMatchingPosition(
					( { item } ) => !model.schema.isContent( item ),
					{ boundaries: range }
				);

				writer.addMarker( VISUAL_SELECTION_MARKER_NAME, {
					usingOperation: false,
					affectsData: false,
					range: writer.createRange( startPosition, range.end )
				} );

				return;
			}

			writer.addMarker( VISUAL_SELECTION_MARKER_NAME, {
				usingOperation: false,
				affectsData: false,
				range
			} );
		} );
```

**Review by przemyslaw-zan — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-emoji/src/emojipicker.ts (hunk 1 above)
Comment (pomek) [reply packages/ckeditor5-emoji/src/emojipicker.ts:329]: I used the code we shared across the entire codebase. I would not change it.

**Comment by Witoso** [comment]
Curious, is this workaround related to the usage of markers and selection? how come it's workinkg in `link`?

**Comment by pomek** [comment]
Yeah, together with @psmyrek and @niegowski we found a proper solution and now it works as expected.

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Review by przemyslaw-zan — APPROVED** [review]
