### PR TITLE
hgroup and summary should work with source editing

### LINKED ISSUE #16947: hgroup and summary do not accept heading elements
## 📝 Provide detailed reproduction steps (if any)

1. Enter source editing mode
2. Create an hgroup element and add a heading element
3. Create a details element with a child summary element and add a heading element
4. Toggle back to design mode
5. Toggle back to source mode

### ✔️ Expected result

Code is preserved as written.

### ❌ Actual result

hgroup and summary elements are removed

### ❓ Possible solution

submitting PR to fix this in schema definitions

## 📃 Other details

* Browser: Chrome, Firefox
* OS: Windows 11, Ubuntu
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (html-support): `hgroup` and `summary` elements should work with source editing. Closes #16947 .

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-html-support/src/schemadefinitions.ts [hunk 1]
```diff
@@ -279,8 +279,17 @@ export default {
...
+					'htmlH1',
+					'htmlH2',
+					'htmlH3',
+					'htmlH4',
+					'htmlH5',
+					'htmlH6',
+					'$text'
+				],
 				allowIn: 'htmlDetails',
+				isLimit: true,
```
Comment (niegowski) [inline packages/ckeditor5-html-support/src/schemadefinitions.ts:292]: Why is this added?

Comment (jwylarsen) [reply packages/ckeditor5-html-support/src/schemadefinitions.ts]: I added it because I found that, without it, CK would remove the summary element if it contained a heading. If it works without it, great.

File: packages/ckeditor5-html-support/src/schemadefinitions.ts [hunk 2]
```diff
@@ -341,7 +349,10 @@ export default {
 			model: 'htmlHgroup',
 			view: 'hgroup',
 			modelSchema: {
+				allowIn: '$root',
```
Comment (jwylarsen) [inline packages/ckeditor5-html-support/src/schemadefinitions.ts:352]: Why $root and not $container? hgroup can go anywhere

Comment (niegowski) [reply packages/ckeditor5-html-support/src/schemadefinitions.ts:352]: I think it would be safe to use `$container` here.

**Review by jwylarsen — APPROVED** [review]

**Review by niegowski — APPROVED** [review]
