### PR TITLE
Review fixes for data-cke-ignore-events attribute handling

### LINKED ISSUE #8294: Review fixes for data-cke-ignore-events attribute handling
## Provide a description of the task

Based on https://github.com/ckeditor/ckeditor5/pull/8243#issuecomment-712665465:

> We'll merge the changes now and fix the review notes in a followup task as Raw HTML embedding is depending on this feature.

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (engine): Added support for excluding `imageLoaded` event from `ImageLoadObserver` for ignored element. Closes #8294.
Internal (engine): Added unit tests for `ImageLoadObserver` to check if `imageLoaded` event is not fired for ignored element.
Internal (engine): Added minor fixes after code review.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-engine/tests/manual/tickets/4600/1.js [hunk 1]
```diff
@@ -19,6 +20,11 @@ import InputObserver from '../../../../src/view/observer/inputobserver';
 import KeyObserver from '../../../../src/view/observer/keyobserver';
 import MouseObserver from '../../../../src/view/observer/mouseobserver';
 import MouseEventsObserver from '@ckeditor/ckeditor5-table/src/tablemouse/mouseeventsobserver';
+import DeleteObserver from '@ckeditor/ckeditor5-typing/src/deleteobserver';
+import ClipboardObserver from '@ckeditor/ckeditor5-clipboard/src/clipboardobserver';
+import EnterObserver from '@ckeditor/ckeditor5-enter/src/enterobserver';
+import ImageLoadObserver from '@ckeditor/ckeditor5-image/src/image/imageloadobserver';
+import MutationObserver from '@ckeditor/ckeditor5-engine/src/view/observer/mutationobserver';
```
Comment (mlewand) [inline packages/ckeditor5-engine/tests/manual/tickets/4600/1.js]: Let's remove MutationObserver - it adds much noise and we're not really handling it for the time being.

Comment (psmyrek) [reply packages/ckeditor5-engine/tests/manual/tickets/4600/1.js]: Done.

**Review by mlewand — APPROVED** [review]
LGTM, I made some changes in the manual test description.
