### PR TITLE
Set tabindex to -1 to prevent focusing the checkbox element with Tab key

### LINKED ISSUE #6535: To-do list is a focus trap
## 📝 Provide detailed reproduction steps (if any)

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/todo-lists.html
2.  Focus the editor by placing the selection anywhere in its content
3.  Press the `tab` key

### ✔️ Expected result

The focus should go outside of the editor

### ❌ Actual result

Focus for a brief moment goes to the first input checkbox (you can see it because _focus ring_ blinks for a moment) and goes back to your selection position.

## 📃 Other details

This is a rather major accessibility issue.

*   Browser: Any
*   OS: Any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pszczesniak**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (list): To-do list items should not interrupt the Tab key navigation across the editor content. Closes #6535 .

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-list/tests/todolist/todolistediting.js [hunk 1]
```diff
@@ -1265,6 +1265,8 @@ describe( 'TodoListEditing - checkbox rendering', () => {
 
 		expect( checkboxElement.tagName ).to.equal( 'INPUT' );
 		expect( checkboxElement.checked ).to.equal( false );
+		expect( checkboxElement.hasAttribute( 'tabindex' ) ).to.be.true;
```
Comment (oleq) [inline packages/ckeditor5-list/tests/todolist/todolistediting.js:1268]: This assertion is obsolete. `Element#getAttribute()` always returns `null` for a non-existing name. The next assertion will handle this.

**Review by oleq — CHANGES_REQUESTED** [review]
Please keep in mind that the commit merge message you propose will go directly to `CHANGELOG.md` file and https://ckeditor.com/docs/ckeditor5/latest/updating/changelog.html read by integrators. Try focusing on whys (user story) instead of whats (technical details) because this will allow developers understand the scope of the release. They may not understand the internals that we change but they can certainly relate to the problems of the user/business requirements.

For instance, something along the lines of "To-do list items should not interrupt the Tab key navigation across the editor content." should do the trick.

Bonus tip: Almost every "Fix (...)" change can be described using "should/should not".
