### PR TITLE
Fix list ordering when block quote was inserted

### LINKED ISSUE #11082: Ordering problem when block quote is being inserted into the middle of the list
## 📝 Provide detailed reproduction steps (if any)

1. Prepare six lines of text
2. Create numbered list (one number for each text line)
3. Select lines 3 and 4 and add a "Block quote"
4. Change the order of the list in the block quote.

### ✔️ Expected result

Order changes only in the block quoted list.

### ❌ Actual result

Order changes are also in the list below.
block quote order issue
Changing the order of the list above or below the block quote impacts only desired list. 

## 📃 Other details

Browser: Chrome, Firefox, Safari
OS: Mac Os Monterey
First affected CKEditor version: 31.1.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by DawidKossowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (list): Ordering problem when block quote was being inserted into the middle of the list. Closes #11082.

---

### Additional information

This issue was caused by by incorrectly ignoring closing tags when searching for list items.

### CODE REVIEW

File: packages/ckeditor5-list/tests/list/utils.js [hunk 1]
```diff
@@ -307,8 +308,8 @@ describe( 'utils', () => {
 				'<listItem listType="bulleted" listIndent="0">3.</listItem>' +
 				'<listItem listType="bulleted" listIndent="0">4.</listItem>'
 			);
-
```
Comment (scofalik) [inline packages/ckeditor5-list/tests/list/utils.js:310]: Looks like you accidentally removed a line break here.

File: packages/ckeditor5-list/tests/list/utils.js [hunk 2]
```diff
@@ -444,10 +449,31 @@ describe( 'utils', () => {
 			);
 
 			expect( getSiblingNodes( document.selection.getFirstPosition(), 'forward' ) ).to.deep.equal( [
+				document.getRoot().getChild( 2 ),
 				document.getRoot().getChild( 3 ),
 				document.getRoot().getChild( 4 )
 			] );
 		} );
+
+		it( 'should return only list items from block quoted list when selection is inside (direction="forward")', () => {
```
Comment (scofalik) [inline packages/ckeditor5-list/tests/list/utils.js:458]: Is there a similar test but for direction = "backward"? I know we didn't fix that case but it would be good to have symmetry in test, in case if someone changes something in the future.

File: packages/ckeditor5-list/src/list/utils.js [hunk 3]
```diff
@@ -395,7 +395,6 @@ export function getSelectedListItems( model ) {
 		.filter( element => element.is( 'element', 'listItem' ) )
 		.map( element => {
 			const position = model.change( writer => writer.createPositionAt( element, 0 ) );
-
```
Comment (scofalik) [inline packages/ckeditor5-list/src/list/utils.js:398]: Accidentally removed line break. Maybe something is wrong with your IDE settings?

File: packages/ckeditor5-list/tests/list/utils.js (hunk 2 above)
Comment (scofalik) [inline packages/ckeditor5-list/tests/list/utils.js:458]: I'd like you change the name for this test. This test is not about block quote only, it is about returning items that are contained in a different element. My proposal: "should return only list items that are inside the same parent element". Or "...the same container".

**Review by scofalik — CHANGES_REQUESTED** [review]
Good job, although some changes are needed.

Apart from what I commented, please change `getSiblingsNodes` description so that it mentions that if the `position` is inside a list item, that list item is returned as well.

**Comment by DawidKossowski** [comment]
@scofalik I added all the changes you raised.

**Review by scofalik — APPROVED** [review]
LGTM. Waiting for CLA.
