### PR TITLE
Mention plugin should not generate random model attribute values

### LINKED ISSUE #20010: Mention feature generates random IDs on upcast, leading to model mismatch problems
## 📝 Provide detailed reproduction steps (if any)

Currently, on upcast and on creation, mentions generate a random ID and set it into model as `modelAttribute.uid`. This is necessary, to make sure that two mentions next to each other won't get merged into one.

The problem is that these IDs are not passed to data. So, upcasting same HTML will result in different models (as the attribute is randomly generated).

This violates one of our main rules and directly leads to crashes when using CKEditor AI.

### ❓ Possible solution

The easiest solution is to store these UIDs in data, and read them on upcast, to maintain stability between multiple data loads.

It is a bit of a breaking change. We even have guides showing how to customize that converter. Well, if people won't update, they won't have a regression, but they will still encounter crashes when using AI.

Additionally, we will need to have clipboard handling -- to prevent duplication on copy-paste we need to remove these IDs when clipboard is used.

---

A different approach would be to remove UIDs entirely, but then, of course, the view attribute elements will get merged. To prevent that, we could create a new view element custom property, e.g. `preventMerging`:

```
writer.setCustomProperty( 'preventMerging', true, mentionElement );
```

Then, in the writer, in few places where we check `ViewAttribute#isSimilar` we would need to check also check this property.

This change may seem a bit broader, but will lead to a cleaner model and cleaner HTML output.

This would be a more impactful breaking change for integrators that overwrite the converter, as `modelAttribute.uid` will no longer be available, so their mentions will merge or the editor will crash.

### PR DESCRIPTION
**Pull request by scofalik**
### 🚀 Summary

Instead of generating random values for mentions attributes in model on upcast, store UIDs in data and read them from data on upcast.

---

### 📌 Related issues

* Closes #20010

---

### 💡 Additional information

*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*

---

### 🧾 Checklists

Use the following checklists to ensure important areas were not overlooked.
This does not apply to feature-branch merges.
If an item is **not relevant** to this type of change, simply leave it unchecked.

#### Author checklist

- [ ] Is the changelog entry intentionally omitted?
- [ ] Is the change backward-compatible?
- [ ] Have you considered the impact on different editor setups and core interactions? _(e.g., classic/inline/multi-root/many editors, typing, selection, paste, tables, lists, images, collaboration, pagination)_
- [ ] Has the change been manually verified in the relevant setups?
- [ ] Does this change affect any of the above?
- [ ] Is performance impacted?
- [ ] Is accessibility affected?
- [ ] Have tests been added that fail without this change (against regression)?
- [ ] Have the API documentation, guides, feature digest, and related feature sections been updated where needed?
- [ ] Have metadata files (ckeditor5-metadata.json) been updated if needed?
- [ ] Are there any changes the team should be informed about (e.g. architectural, difficult to revert in future versions or having impact on other features)?
- [ ] Were these changes documented (in Logbook)?

#### Reviewer checklist

- [ ] PR description explains the changes and the chosen approach (especially when  performance, API, or UX is affected).
- [ ] The changelog entry is clear, user‑ or integrator-facing, and it describes any breaking changes.
- [ ] All new external dependencies have been approved and mentioned in LICENSE.md (if any).
- [ ] All human-readable, translateable strings in this PR been introduced using `t()` (if any).
- [ ] I manually verified the change (e.g., in manual tests or documentation).
- [ ] The target branch is correct.

### CODE REVIEW

File: packages/ckeditor5-mention/src/mentionediting.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export function _addMentionAttributes(
 	baseMentionData: { id: string; _text: string },
 	data?: Record<string, unknown>
 ): MentionAttribute {
-	return Object.assign( { uid: uid() }, baseMentionData, data || {} );
+	return Object.assign( { uid: uid().slice( 0, 8 ) }, baseMentionData, data || {} );
```
Comment (oleq) [inline packages/ckeditor5-mention/src/mentionediting.ts:97]: Why just 8 characters? This significantly reduces the entropy of the UID and increases a chance of collision.

File: packages/ckeditor5-mention/docs/_snippets/examples/chat-with-mentions.js [hunk 2]
```diff
@@ -171,11 +171,11 @@ function MentionLinks( editor ) {
 			return writer.createAttributeElement( 'a', {
 				class: 'mention',
 				'data-mention': modelAttributeValue.id,
-				href
+				href,
+				// Omit `data-uid` in clipboard (copy/cut) to prevent UIDs duplication.
+				...( !options.isClipboardPipeline && { 'data-uid': modelAttributeValue.uid } )
 			}, {
-				// Make mention attribute to be wrapped by other attribute elements.
 				priority: 20,
```
Comment (oleq) [inline packages/ckeditor5-mention/docs/_snippets/examples/chat-with-mentions.js:179]: Why removing those comments? They may be useful to anyone working on it.

File: packages/ckeditor5-mention/docs/_snippets/features/mention-customization.js [hunk 3]
```diff
@@ -101,11 +101,11 @@ function MentionCustomization( editor ) {
 				class: 'mention',
 				'data-mention': modelAttributeValue.id,
 				'data-user-id': modelAttributeValue.userId,
-				'href': modelAttributeValue.link
+				'href': modelAttributeValue.link,
+				// Omit `data-uid` in clipboard (copy/cut) to prevent UIDs duplication.
+				...( !options.isClipboardPipeline && { 'data-uid': modelAttributeValue.uid } )
 			}, {
-				// Make mention attribute to be wrapped by other attribute elements.
 				priority: 20,
```
Comment (oleq) [inline packages/ckeditor5-mention/docs/_snippets/features/mention-customization.js:109]: Same: why remove these comments?

File: packages/ckeditor5-mention/docs/examples/chat-with-mentions.md [hunk 4]
```diff
@@ -200,11 +200,11 @@ function MentionLinks( editor ) {
 			return writer.createAttributeElement( 'a', {
 				class: 'mention',
 				'data-mention': modelAttributeValue.id,
-				href
+				href,
+				// Omit `data-uid` in clipboard (copy/cut) to prevent UIDs duplication.
+				...( !options.isClipboardPipeline && { 'data-uid': modelAttributeValue.uid } )
 			}, {
-				// Make mention attribute to be wrapped by other attribute elements.
 				priority: 20,
```
Comment (oleq) [inline packages/ckeditor5-mention/docs/examples/chat-with-mentions.md:208]: Why remove comments that may be useful for integrators?

File: packages/ckeditor5-mention/src/mentionediting.ts [hunk 5]
```diff
@@ -118,12 +118,14 @@ export function _toMentionAttribute(
 		return;
 	}
 
+	const dataUid = viewElementOrMention.getAttribute( 'data-uid' ) as string;
```
Comment (oleq) [inline packages/ckeditor5-mention/src/mentionediting.ts]: I'm a little bit apprehensive about using a generic `data-uid` name which may easily collide with integrator's code.

**Review by oleq — CHANGES_REQUESTED** [review]
Out of curiosity, why did you ditch the second approach described in the issue:

> A different approach would be to remove UIDs entirely, but then, of course, the view attribute elements will get merged. To prevent that, we could create a new view element custom property, e.g. preventMerging:

It seems more elegant, at least at first glance.

File: packages/ckeditor5-mention/src/mentionediting.ts (hunk 5 above)
Comment (scofalik) [reply packages/ckeditor5-mention/src/mentionediting.ts]: Good catch. This should be `data-mention-uid`.

File: packages/ckeditor5-mention/src/mentionediting.ts (hunk 1 above)
Comment (scofalik) [reply packages/ckeditor5-mention/src/mentionediting.ts:97]: I think this is actually a lot and I was even thinking to make it smaller. Reasoning:

1) Mentions aren't very common element in one document. I'd not expect more than a few dozens mentions. UIDs should be unique in a scope of a one document, of course.
2) Aparat from UID, mentions are differentiated by other attributes too.
3) This mechanism is used only when two mentions are next to each other.

Although UIDs should be, well, unique, I believe 8 characters is more enough for our needs. And the bug (merging two mentions) would be reproducible only if you are unlucky enough to have two same mentions with the same UID generated, and next to each other.

I wanted to keep the UID small so it doesn't make too much mess in output data, and is easier to preserve (and not use too many tokens ;)) for AI service.

**Comment by scofalik** [comment]
I made fixes and added changelog files. Ready for re-review, @oleq.

File: packages/ckeditor5-mention/src/mentionediting.ts [hunk 6]
```diff
@@ -118,12 +118,14 @@ export function _toMentionAttribute(
...
 
+	const dataUid = viewElementOrMention.getAttribute( 'data-mention-uid' ) as string;
+
 	const baseMentionData = {
 		id: dataMention,
 		_text: textNode.data
 	};
 
-	return _addMentionAttributes( baseMentionData, data );
+	return _addMentionAttributes( baseMentionData, dataUid ? { uid: dataUid, ...data } : data );
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-mention/src/mentionediting.ts:128]: Low severity.
