### PR TITLE
Missing labels for nested editables

### LINKED ISSUE #11837: Missing labels for nested editables
## 📝 Provide detailed reproduction steps (if any)

1.  Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html
2.  Launch VoiceOver or other screen reader
3.  Focus the caption of the image.

### ✔️ Expected result

The editable should be announced as an image caption.

### ❌ Actual result

There is no label.

### ❓ Possible solution

The caption can be announced as, e.g. "Caption for \<image's alt> image".

## 📃 Other details

*   Browser: all
*   OS: all
*   First affected CKEditor version: …
*   Installed CKEditor plugins: image, table

The same issue exists for other nested editables, e.g. table cells.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mmotyczynska**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (image, table): Adds missing labels for nested editables. Closes #11837.

---

### Additional information

In this PR, the `label` is added for figcaption element and the `role` is added to all editables. Labels for other elements will be added in #11867.

### CODE REVIEW

**Review by mlewand — CHANGES_REQUESTED** [review]
We already have an interesting problem that we need to solve 🙂

It works well for the first render. However, the image's `alt` value can change at a runtime (the author can change alternative text at any time or people collaborating might change it). We should have this information bound so that it doesn't get out of sync.

**Comment by mmotyczynska** [comment]
Good point @mlewand :+1: I updated the code to cover also changing image `alt` attribute at runtime.

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js [hunk 1]
```diff
@@ -132,7 +133,10 @@ export default class ImageCaptionEditing extends Plugin {
 					keepOnFocus: true
 				} );
 
-				return toWidgetEditable( figcaptionElement, writer );
+				const imageAlt = modelElement.parent.getAttribute( 'alt' );
+				const label = ( imageAlt ) ? t( 'Caption for %0 image', [ imageAlt ] ) : t( 'Caption for the image' );
```
Comment (oleq) [inline packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:137]: Do you think replacing `%0` with `"%0"` would make sense? I ran this in a screen reader both ways and I was able to better understand the description of an image and the caption label with the quotes (the boundary). But maybe it's just me. 

cc @Comandeer

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js [hunk 2]
```diff
@@ -132,7 +133,10 @@ export default class ImageCaptionEditing extends Plugin {
...
+
```
Comment (oleq) [inline packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:138]: Missing entries in `contexts.json`.

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js (hunk 1 above)
Comment (oleq) [reply packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:137]: Also, obsolete parentheses around the first operand of the ternary operator.

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js [hunk 3]
```diff
@@ -242,4 +246,36 @@ export default class ImageCaptionEditing extends Plugin {
...
+	/**
+	 * Reconverts image caption when image alt attribute changes.
+	 * The change of alt attribute is reflected in caption's aria-label attribute.
+	 *
+	 * @private
+	 */
+	_registerCaptionReconversion() {
+		const model = this.editor.model;
+
+		model.document.on( 'change:data', () => {
```
Comment (oleq) [inline packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:259]: @niegowski Could you take a look at this bit please? For instance, I'm worried about about accessing `image.name` without checking whether it exists but I'm not an expert in reconversion.

**Review by oleq — CHANGES_REQUESTED** [review]
The whole idea looks good. I checked with JAWS and VoiceOver. I left some comments.

Looks like there are tests failing in ckbox after merging master (see the CI) and decreased code coverate.

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js (hunk 3 above)
Comment (niegowski) [reply packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:259]: Accessing `change.range.start.nodeAfter` is safe there because the range of a Differ attribute change diff item always starts before the changed node. For an element attribute change it's: `[<el>]</el>` but for the text, the range is flat: `<$text>foo</$text>[<$text alt="x">bar</$text>]<$text>baz</$text>`. This makes `const caption = change.range.end.nodeAfter;` unsafe for cases where `alt` model attribute would be enabled (for whatever reason may be some 3rd party feature) on text nodes. So I would suggest to use a dedicated util to find the caption element: https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaptionutils_utils-ImageCaptionUtils.html#function-getCaptionFromImageModelElement.

**Comment by mmotyczynska** [comment]
Requested changes are addressed. Unit tests fixed. Code coverage improved.

File: packages/ckeditor5-image/lang/contexts.json [hunk 4]
```diff
@@ -22,5 +22,6 @@
 	"Insert": "The label of the form submit button if the image source URL input has no value.",
 	"Update": "The label of the form submit button if the image source URL input has a value.",
 	"Insert image via URL": "The input label for the Insert image via URL form.",
-	"Update image URL": "The input label for the Insert image via URL form for a pre-existing image."
+	"Update image URL": "The input label for the Insert image via URL form for a pre-existing image.",
+	"Caption for image: %0": "Text used by screen readers do describe an image, e.g. 'Caption for image: this is a description of the image.'"
```
Comment (oleq) [inline packages/ckeditor5-image/lang/contexts.json:26]:
```suggestion
	"Caption for the image": "Text used by screen readers do describe an image when the image has no text alternative.",
	"Caption for image: %0": "Text used by screen readers do describe an image when there is a text alternative available, e.g. 'Caption for image: this is a description of the image.'"
```

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js [hunk 5]
```diff
@@ -242,4 +246,38 @@ export default class ImageCaptionEditing extends Plugin {
...
+			const changes = model.document.differ.getChanges();
+
+			for ( const change of changes ) {
+				if ( change.attributeKey !== 'alt' ) {
+					continue;
+				}
+
+				const image = change.range.start.nodeAfter;
+
+				if ( image.name === 'imageBlock' ) {
```
Comment (oleq) [inline packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:271]:
```suggestion
				if ( imageUtils.isBlockImage( image ) ) {
```

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js [hunk 6]
```diff
@@ -242,4 +246,38 @@ export default class ImageCaptionEditing extends Plugin {
...
+	/**
+	 * Reconverts image caption when image alt attribute changes.
+	 * The change of alt attribute is reflected in caption's aria-label attribute.
+	 *
+	 * @private
+	 */
+	_registerCaptionReconversion() {
+		const editor = this.editor;
+		const model = editor.model;
+		const imageCaptionUtils = editor.plugins.get( 'ImageCaptionUtils' );
```
Comment (oleq) [inline packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js:259]:
```suggestion
		const imageUtils = editor.plugins.get( 'ImageUtils' );
		const imageCaptionUtils = editor.plugins.get( 'ImageCaptionUtils' );
```

**Review by oleq — CHANGES_REQUESTED** [review]
Do you think the nested editable label would make sense for the table captions as well?

https://github.com/ckeditor/ckeditor5/blob/6040c00a53dd84a977f1c8da0f0f72bbbd1c1647/packages/ckeditor5-table/src/tablecaption/tablecaptionediting.js#L107

**Comment by mmotyczynska** [comment]
> Do you think the nested editable label would make sense for the table captions as well?
> 
> https://github.com/ckeditor/ckeditor5/blob/6040c00a53dd84a977f1c8da0f0f72bbbd1c1647/packages/ckeditor5-table/src/tablecaption/tablecaptionediting.js#L107

Yes, and I guess we already have an issue for that #11867.
