### PR TITLE
Remove the `<style>` tag that comes with the table pasted from Google Sheets

### LINKED ISSUE #14131: GHS + PFO: pasting table from Google Sheets displays HTML comment
## 📝 Provide detailed reproduction steps (if any)

1. Add `PasteFromOffice` to `ghs-all-features` manual test.
2. Change config for GHS:
```
htmlSupport: {
	allow: [
		{
			name: /^(table|thead|tbody|td|th|tr|col|colgroup)$/,
			styles: true,
		},
	],
},
```
3. Paste a table from Google Sheets. 

### ✔️ Expected result

The table is displayed in the editor.

### ❌ Actual result

Besides the table, there is also an HTML comment displayed above.
image

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (paste-from-office): Remove the `<style>` tag that comes with the table pasted from Google Sheets. Closes #14131.

### CODE REVIEW

File: packages/ckeditor5-paste-from-office/src/filters/removestyleblock.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+/**
+ * Removes `<style>` block added by Google Sheets to a copied content.
+ *
+ * @param documentFragment element `data.content` obtained from clipboard
+ */
+export default function removeStyleBlock( documentFragment: ViewDocumentFragment, writer: UpcastWriter ): void {
+	for ( const child of documentFragment.getChildren() ) {
+		if ( child.is( 'element', 'style' ) ) {
+			writer.remove( child );
```
Comment (arkflpc) [inline packages/ckeditor5-paste-from-office/src/filters/removestyleblock.ts:20]: This changes the list while iterating over it? Does the iterator point to valid position?

Please add tests for more than one style elements (consecutive and not).

Probably you should iterate over `Array.from( documentFragment.getChildren() )`.

File: packages/ckeditor5-paste-from-office/src/filters/removestyleblock.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+import type { UpcastWriter, ViewDocumentFragment } from 'ckeditor5/src/engine';
+
+/**
+ * Removes `<style>` block added by Google Sheets to a copied content.
+ *
+ * @param documentFragment element `data.content` obtained from clipboard
+ */
+export default function removeStyleBlock( documentFragment: ViewDocumentFragment, writer: UpcastWriter ): void {
+	for ( const child of documentFragment.getChildren() ) {
```
Comment (arkflpc) [inline packages/ckeditor5-paste-from-office/src/filters/removestyleblock.ts:18]:
```suggestion
	for ( const child of Array.from( documentFragment.getChildren() ) ) {
```

**Review by arkflpc — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-paste-from-office/src/filters/removestyleblock.ts (hunk 1 above)
Comment (filipsobol) [reply packages/ckeditor5-paste-from-office/src/filters/removestyleblock.ts:20]: Done :heavy_check_mark:

**Review by arkflpc — APPROVED** [review]
