### PR TITLE
Resizing will not trigger other viewDocument#mousedown events

### LINKED ISSUE #6755: Table selection is active during image resize
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a table with an image.
2.  Start the image resize and move the selection to the next cell.

### ✔️ Expected result

Cells are not selected.

### ❌ Actual result

Cells are selected, resizing fails.

## 📃 Other details

*   Browser: All browsers

**GIF**

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (widget): The resizing mechanism will not trigger other `view.Document#mousedown` events. Thanks to that while resizing an image inside a cell, the mouse will not trigger the table's actions. Closes #6755.

### CODE REVIEW

**Comment by jodator** [comment]
Unfortunatelly, there is some kind of weird issue (maybe due to changed priorities or maybe browsers just suck...)

On Chrome it sometimes doesn't work correctly - below are 3 tries - all have different result:

1.  Failed to start (image dragged) resizing "works", no size feedback. Size saved.
2.  Drag started, no size feedback. Size not saved.
3.  Drag started (ignore the selection on other stuff), size feedback visible. Size saved.



On Firefox the most common scenario is "2".

If I set priority to 'normal' it backs to working normally AFAICS but the bug with table select gets back.

**Comment by pomek** [comment]
WHAT about switching priorities? I mean: `low` for events in `TableMouse` and `normal` (as it is on master) for resizing?

**Comment by jodator** [comment]
I feel like there's some bigger dpendency tree of those events which might behave differently in FF and Chrome and I don't have a clue why is that.

OTOH, I'd check this: #4600 if it could solve this problem (assuming revert to old Resizer events handling :( )

**Comment by pomek** [comment]
@jodator, could you check the PR once again?

File: packages/ckeditor5-widget/src/widgetresize/resizer.js [hunk 1]
```diff
@@ -107,7 +107,8 @@ export default class Resizer {
 
 		editingView.change( writer => {
 			const viewResizerWrapper = writer.createUIElement( 'div', {
-				class: 'ck ck-reset_all ck-widget__resizer'
+				class: 'ck ck-reset_all ck-widget__resizer',
+				'data-cke-ignore-events': true
```
Comment (jodator) [inline packages/ckeditor5-widget/src/widgetresize/resizer.js:111]:
```suggestion
				class: 'ck ck-reset_all ck-widget__resizer'
```
