### PR TITLE
Remove underscore from _updateEditorData method name and make it public.

### LINKED ISSUE #11008: Source editing doesn't save unless going back to WYSIWYG
Maybe this is rather a question than a bug but I couldn't find a bettter place to submit it. 

We're using CKeditor to edit the (mardown) contents of a textarea. Unfortuantely, the textarea isn't part of a submittable form and its contents (among others) are sent to a server after manually saving (and thereby closing the editing area). That's why I use a simple

```js
editor.model.document.on("change:data", (e) => {
    editor.updateSourceElement();
});
```

to ensure that the textarea always contains the user input of the WYSIWYG editor which works fine, except for input made from within the source editor.  There, the `change:data` event never fires and subsequently, nothing is changed.

For CKEditor 4 I found [this](https://stackoverflow.com/questions/36079798/ckeditor-checkdirty-on-source-editing-area). Is there something similar for CKEditor 5?  What am I missing?

## 📝 Provide detailed reproduction steps (if any)

1. Use a manual saving setup as above
2. Enter source mode and change something
3. Save (or observe the `change:data` event) and see that nothing happens

### ✔️ Expected result

Changing something while in source editing should also trigger the 

### ❌ Actual result

Only after going back to the WYSIWYG mode, the changes are applied (i.e., the `change:data` event is fired).

## 📃 Other details

* Browser: Firefox 95.0, Chromium 96.0.4664.110
* OS: Arch Linux
* First affected CKEditor version: 31.0.0
* Installed CKEditor plugins: Markdown, SourceEditing

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mremiszewski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature (source-editing): Remove the underscore from `_updateEditorData` method name and make it public. Closes #11008.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-source-editing/src/sourceediting.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@
 
 /* global console */
 
-import { type Editor, Plugin, PendingActions } from 'ckeditor5/src/core';
+import { type ContextPluginDependencies, type Editor, Plugin, PendingActions } from 'ckeditor5/src/core';
```
Comment (arkflpc) [inline packages/ckeditor5-source-editing/src/sourceediting.ts:12]:
```suggestion
import { type Editor, Plugin, PendingActions } from 'ckeditor5/src/core';
```

File: packages/ckeditor5-source-editing/src/sourceediting.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export default class SourceEditing extends Plugin {
 	/**
 	 * @inheritDoc
 	 */
-	public static get requires() {
+	public static get requires(): ContextPluginDependencies {
```
Comment (arkflpc) [inline packages/ckeditor5-source-editing/src/sourceediting.ts:41]:
```suggestion
	public static get requires() {
```

**Review by arkflpc — CHANGES_REQUESTED** [review]

**Review by arkflpc — APPROVED** [review]
