### PR TITLE
(Un)Link command state when an image is selected

### LINKED ISSUE #7429: LinkCommand#value does not work with `<image>`
After introducing the editing part for linking images, the `link` command should read the `linkHref` attribute set on the `<image>` element.

image

image

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal: `#value` and `#isEnabled` properties for `LinkCommand` and `UnlinkCommand` work properly with images. Closes #7429.

### CODE REVIEW

File: packages/ckeditor5-link/src/linkcommand.js [hunk 1]
```diff
@@ -57,13 +58,21 @@ export default class LinkCommand extends Command {
 		const model = this.editor.model;
 		const doc = model.document;
 
-		this.value = doc.selection.getAttribute( 'linkHref' );
+		const selectedElement = first( doc.selection.getSelectedBlocks() );
+
+		// A check for the `LinkImage` plugin. If the selection contains an element, get values from the element.
+		// Currently the selection reads attributes from text nodes only. See #7429.
+		if ( selectedElement && selectedElement.name === 'image' ) {
```
Comment (jodator) [inline packages/ckeditor5-link/src/linkcommand.js:65]:
```suggestion
		if ( selectedElement && selectedElement.is( 'image' ) ) {
```
