### PR TITLE
Table properties color picker label updated

### LINKED ISSUE #11895: JAWS: The color picker in Table properties is labelled as "Unlabeled 0"
## 📝 Provide detailed reproduction steps (if any)

1.  Insert table.
2.  Click Table properties.
3.  Start JAWS, use CTRL+Insert+C to get the available list of controls

### ✔️ Expected result

The color picker is labelled properly.

### ❌ Actual result

The color picker is labelled as "Unlabeled 0"

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mateuszzagorski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Added label for the Table properties color grid dropdown. Closes #11895.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-table/src/ui/colorinputview.js [hunk 1]
```diff
@@ -208,6 +208,7 @@ export default class ColorInputView extends View {
 
 		dropdown.buttonView.children.add( colorPreview );
 		dropdown.buttonView.tooltip = t( 'Color picker' );
+		dropdown.buttonView.label = t( 'Color picker' );
```
Comment (mlewand) [inline packages/ckeditor5-table/src/ui/colorinputview.js:211]: Now the label and tooltip are duplicated. These should remain synchronized.

I believe that setting `tooltip` to `true` will cause it to use the label, at least [that's what the docs are saying](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_button_button-Button.html#member-tooltip).

> If defined as a `Boolean` (e.g. `true`), then combination of `label` and `keystroke` will be set as a tooltip.

**Comment by Mgsy** [comment]
LGTM :+1:
