### PR TITLE
Border properties will be merged into the single group if possible

### LINKED ISSUE #9490: Border styles produced in inline styles could be more optimal
## 📝 Provide a description of the improvement

Consider the following examples.

<table>
    <tr>
        <td>Model</td>
        <td>Invalid (current) view</td>
        <td>Expected view</td>
        <td>The "Why?"</td>
    </tr>
    <tr>
        <td><code>&lt;table borderStyle="solid"&gt;</code></td>
        <td><code>&lt;table style="border-bottom:solid;border-left:solid;border-right:solid;border-top:solid;"&gt;</code></td>
        <td><code>&lt;table style="border-style:solid;"&gt;</code></td>
        <td><code>border-*</code> requires all values (width, style, color) to proper display the element. If any is missing, the "initial" data will be applied which is wrong because it overrides the default styles (from the website).</td>
    </tr>
    <tr>
        <td><code>&lt;table borderStyle="solid" borderWidth="2px"&gt;</code></td>
        <td><code>&lt;table style="border-bottom:2px solid;border-left:2px solid;border-right:2px solid;border-top:2px solid;"&gt;</code></td>
        <td><code>&lt;table style="border-style:solid;border-width:2px;"&gt;</code></td>
        <td>Same as above.</td>
    </tr>
    <tr>
        <td><code>&lt;table borderColor="#f00" borderStyle="solid" borderWidth="2px"&gt;</code></td>
        <td><code>&lt;table style="border-bottom:2px solid #f00;border-left:2px solid #f00;border-right:2px solid #f00;border-top:2px solid #f00;"&gt;</code></td>
        <td><code>&lt;table style="border:2px solid #f00;"&gt;</code></td>
        <td>If all border definitions are the same, why couldn't we merge them into single property?</td>
    </tr>
</table>

It is also possible to load different values than the editor accepts. E.g. when loading the table will the following styles:

```css
/* Assuming that border-color defines the website. */
border-top-style: solid;
border-top-width: 2px;
border-right-style: solid;
border-right-width: 4px;
border-bottom-style: solid;
border-right-width: 6px;
border-left-style: solid;
border-left-width: 8px;
```

The editor should return:

```css
/* border-style is merged into the single property. */
border-style: solid;
border-top-width: 2px;
border-right-width: 4px;
border-right-width: 6px;
border-left-width: 8px;
```

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (table): Border definitions produced by the `TableProperties` and `TableCellProperties` features will be merged into a group if possible. Instead of producing `border-(top|right|bottom|left):*` selectors, the `border:*` definition will be returned. See #9490.

Fix (engine): The `view.Element#getNormalizedStyle()` will return the merged `border` definition produced if all its properties (width, style, and color) are specified. Otherwise, `border-(width|style|color)` definition should be returned. Closes #9490.

MINOR BREAKING CHANGE (table): Values for the `borderColor`, `borderStyle`, and `borderWidth` attributes are unified (to values produced by the editor itself) while upcasting the table or table cells if all borders (top, right, bottom, and left) have the same values. Previously, the `<table style="border: 1px solid #ff0">` element was upcasted to `<table borderStyle="{"top":"solid","right":"solid","bottom":"solid","left":"solid"}" borderColor="{...}" borderWidth="{...}">`. Now the object will be replaced with the string value: `<table borderStyle="solid" borderColor="#ff0" borderWidth="1px">`. The same structure is created when using the editor's toolbar. If border values are not identical, the object notation will be inserted into the model (as it is now).

MINOR BREAKING CHANGE (table): Conversion helpers: `upcastStyleToAttribute()`, `downcastAttributeToStyle()`, `downcastTableAttribute()` accept two arguments now (the conversion instance and the options object). The previous usage: `conversionHelper( conversion, /* ... */ )` should be replaced with `conversionHelper( conversion, { /* ... */ } )`.

---

### Additional information

Do not forget about merging a PR in CF.

### CODE REVIEW

File: packages/ckeditor5-engine/src/view/styles/border.js [hunk 1]
```diff
@@ -238,39 +263,128 @@ function normalizeBorderShorthand( string ) {
...
-	const reduced = [];
+// The border reducer factory.
+//
+// It tries to produce the most optimal output for the specified styles.
+//
+// For border style:
+//
+//      style: {top: "solid", bottom: "solid", right: "solid", left: "solid"}
+//
+// It will produce: `border-style: top` output.
```
Comment (pomek) [inline packages/ckeditor5-engine/src/view/styles/border.js:274]:
```suggestion
// It will produce: `border-style: solid` output.
```

**Review by niegowski — APPROVED** [review]

File: packages/ckeditor5-table/src/converters/tableproperties.js [hunk 2]
```diff
@@ -14,8 +14,9 @@
  * @param {String} modelElement
  * @param {String} modelAttribute
  * @param {String} styleName
+ * @param {Boolean} [reduceBoxSides=false]
  */
-export function upcastStyleToAttribute( conversion, modelElement, modelAttribute, styleName ) {
+export function upcastStyleToAttribute( conversion, modelElement, modelAttribute, styleName, reduceBoxSides = false ) {
```
Comment (pomek) [inline packages/ckeditor5-table/src/converters/tableproperties.js:19]: 4 arguments for the function seem to be too many. Let's improve the API a little bit:

```js
upcastStyleToAttribute( conversion, { 
	modelElement: 'modelElement',
	modelAttribute: 'modelAttribute',
	styleName: 'styleName',
	reduceBoxSides: true // false by default (if not specified)
} );
```

The same should we do with the internal helper: `enableProperty()`.

Comment (niegowski) [reply packages/ckeditor5-table/src/converters/tableproperties.js]: :+1:
