### PR TITLE
#7679: The config.image.resizeOptions should have the default value.

### LINKED ISSUE #7679: Image resizeOptions config needs defaults
## 📝 Provide detailed reproduction steps (if any)

ATM when you just add the resize buttons or a dropdown to the image toolbar nothing happens because these components don't register unless `config.image.resizeOptions` is defined. All you get is the component factory error which does not tell the full story.

Besides, all our features come with the default configuration and so should `ImageResize`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
## Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (image): The `config.image.resizeOptions` should have the default value. Closes #7679.

### CODE REVIEW

File: packages/ckeditor5-image/src/imageresize/imageresizeediting.js [hunk 1]
```diff
@@ -26,6 +26,37 @@ export default class ImageResizeEditing extends Plugin {
 		return 'ImageResizeEditing';
 	}
 
+	/**
+	 * @inheritDoc
+	 */
+	constructor( editor ) {
+		super( editor );
+
+		editor.config.define( 'image', {
```
Comment (jodator) [inline packages/ckeditor5-image/src/imageresize/imageresizeediting.js:35]: WDYT about moving this to `ImageResizeButtons` - the configuration options are defined there (the docs) and is only used by this plugin.

Comment (oleq) [reply packages/ckeditor5-image/src/imageresize/imageresizeediting.js:35]: So default unit stays in editing and `resizeOptions` go to `ImageResizeButtons`? Sounds like a plan.

Comment (jodator) [reply packages/ckeditor5-image/src/imageresize/imageresizeediting.js:35]: Hmm... well :man\_shrugging: for me TBH. Different sub-features defines different configuration options. But since it's already messy we can leave that as is.
