### PR TITLE
Fix ability to change found text while the dialog is open

### LINKED ISSUE #15680: Ability to change found text while the dialog is open
## 📝 Provide detailed reproduction steps (if any)

1.  Open `Find and Replace` feature guide (http://127.0.0.1:8080/ckeditor5/latest/features/find-and-replace.html)
2.  Open `Find and Replace` dialog, type a word that exist in content and click button `Find`.
3.  Type something in `replace with...` input (to better see the final "effect").
4.  Now, for exaple, place selection in the middle of the marked word in content and start typing (or like on the video, select part of the word and move it somewhere else).
5.  Hit `Replace All` button.

### ✔️ Expected result

If searched words !== word in text, should marked text dissapeared and `Replace` should not affect this place.

### ❌ Actual result

https://github.com/ckeditor/ckeditor5/assets/9881379/6731fb8a-2c58-4667-8811-0d11da077c4c

### ❓ Possible solution

🤔 Maybe it should not be possible to change the marked text or it can be changed but searching should be refreshed?

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix(find-and-replace): Highlighted search result is no longer highlighted if the user has modified part of the found phrase in the text editor. 

---

### Additional information

Closes #15680

### CODE REVIEW

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 1]
```diff
@@ -192,27 +192,28 @@ export default class FindAndReplaceEditing extends Plugin {
 
 		const { findCallback, results } = editor.execute( 'find', callbackOrText );
 
-		this._activeResults = results;
+		this._inFilteringMode = true;
 
-		// @todo: handle this listener, another copy is in findcommand.js file.
-		this.listenTo( model.document, 'change:data', () => onDocumentChange( this._activeResults!, editor, findCallback ) );
+		this.listenTo( model.document, 'change:data', () => {
+			if ( this.state?.results ) {
```
[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: Fixed

**Review by Dumluregn — COMMENTED** [review]
There's a bug in the scenario when we're adding searched phrase to the content:

1.  Clear document content.
2.  Find anything, there should be 0 occurrences.
3.  Add the searched phrase to the document.

The find counter shows `0 of 1`. The "Find next" and "Find previous" buttons are disabled (because there's only one result). The "Replace" and "Replace all" buttons are enabled, but the former doesn't do anything when it's clicked. 

I think we should either select the new result (so apply the "selected" highlight and make the counter display `1 of 1`), or enable "Find next/previous" buttons in such case (but it's less intuitive IMO and requires to disable them again once used). CC @DawidKossowski

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 2]
```diff
@@ -80,7 +80,11 @@ function onDocumentChange(
 				results.remove( markerName );
 			}
 
-			writer.removeMarker( markerName );
+			// This condition is checked in several tests anyway and seems to be ignored by instabul.
```
[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:83]: It's not falsy in this scenario. It crashes when `results` object contain marker that no longer exists in document (because it was removed by the user in editor).

File: packages/ckeditor5-find-and-replace/src/findandreplace.ts [hunk 3]
```diff
@@ -76,20 +76,21 @@ export default class FindAndReplace extends Plugin {
...
 			if ( state.searchText !== data.searchText ) {
-				this.editor.execute( 'find', data.searchText );
+				findAndReplaceEditing.find( data.searchText );
 			}
 
 			const highlightedResult = state.highlightedResult;
 
 			if ( highlightedResult ) {
 				this.editor.execute( 'replace', data.replaceText, highlightedResult );
+				findAndReplaceEditing.find( data.searchText );
```
[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplace.ts]: You are right. After fixes it is no longer needed.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 4]
```diff
@@ -110,12 +114,12 @@ export default class FindAndReplaceEditing extends Plugin {
...
 	/**
-	 * The collection of currently highlighted search results.
+	 * Flag that indicates that user started using search
 	 *
 	 * @private
-	 * @member {module:utils/collection~Collection} #_activeResults
+	 * @member {module:utils/collection~Collection} #_inFilteringMode
 	 */
-	private _activeResults?: Collection<ResultType> | null;
+	private _inFilteringMode?: boolean = false;
```
[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: I removed this boolean completely and adjusted assertions. Works completely fine.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 5]
```diff
@@ -110,12 +114,12 @@ export default class FindAndReplaceEditing extends Plugin {
 	}
 
 	/**
-	 * The collection of currently highlighted search results.
+	 * Flag that indicates that user started using search
```
[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: Flag has been removed, not more relevant.

**Comment by Mati365** [comment]
@Dumluregn Can you take a look again? I fixed mentioned issues.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:83]: I agree with @Dumluregn, we should remove `istanbul ignore`.

Currently, the tests do not fall within this `if` statement, and adding the `istanbul ignore` comment should not be the solution. Perhaps you will need to prepare mocks or additional API calls to simulate this scenario in unit tests. If you can replicate this scenario in manual tests, it should also be feasible in unit tests.
Please take some time to determine how you can prepare unit tests to cover this case.

[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:83]: @DawidKossowski The problem is that tests[1] actually fall into this condition and if we remove it then they will simply fail. I added to the `Writer` class specified method[2] that actually does the same as current line and coverage is back equal 100% in this file. I suspect that instabul incorrectly handles the exception raised by `writer.removeMarker` and does not include this line into coverage at all. 

[1] `hitting "Find" with no result should watch document modifications and update highlighted item if not present`

[2] 
```ts 
public removeMarkerIfPresent( markerOrName: string | Marker ): void {
		this._assertWriterUsedCorrectly();

		const name = typeof markerOrName == 'string' ? markerOrName : markerOrName.name;

		if ( !this.model.markers.has( name ) ) {
			return;
		}

		const marker = this.model.markers.get( name )!;

		if ( !marker.managedUsingOperations ) {
			this.model.markers._remove( name );

			return;
		}

		const oldRange = marker.getRange();

		applyMarkerOperation( this, name, oldRange, null, marker.affectsData );
	}
```

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 6]
```diff
@@ -80,15 +80,33 @@ function onDocumentChange(
...
-		findAndReplaceUtils.updateFindResultFromRange( model.createRangeOn( nodeToCheck ), model, searchCallback, results );
+		const changedNodeSearchResults = findAndReplaceUtils.updateFindResultFromRange(
+			model.createRangeOn( nodeToCheck ), model, searchCallback, results
+		);
+
+		// Sometimes `changedNodeSearchResults` contains elements that are already present on `changedSearchResults`
+		// list so do not return them duplicated.
+		changedNodeSearchResults.forEach( changedNodeResult => {
+			changedSearchResults.add( changedNodeResult );
+		} );
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:104]: Could you give an example?

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 7]
```diff
@@ -80,15 +80,33 @@ function onDocumentChange(
 				results.remove( markerName );
 			}
 
-			writer.removeMarker( markerName );
+			// This condition is checked in several tests anyway and seems to be ignored by instabul.
+			// istanbul ignore next -- @preserve
+			if ( model.markers.has( markerName ) ) {
+				writer.removeMarker( markerName );
+			}
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:87]: After the research I can say this code is unnecessary. I pushed a branch with some added logs to better show what is going on here: `ck/15680-with-logs`.

Just a few lines above https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts#L82-L84 we update the find and replace state by removing the deleted results. This triggers the collection listener in [https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplacestate.ts#L78.](https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplacestate.ts#L78.) There the collection has its own logic removing the markers: [https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplacestate.ts#L90-L93.](https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplacestate.ts#L90-L93.) Remembering that this code is executed before the control is returned to `onDocumentChange()` callback in [https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts#L88-L91,](https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts#L88-L91,) the markers are already gone and there's nothing to remove.

Hence, AFAICS this whole block [https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts#L78-L93](https://github.com/ckeditor/ckeditor5/blob/00fdb2ccfb9912a5d1379650f1c458a25e6048e1/packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts#L78-L93) doesn't have to be inside a `model.change()` call - we can only remove the results.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 8]
```diff
@@ -190,29 +198,25 @@ export default class FindAndReplaceEditing extends Plugin {
...
 
-		this._activeResults = results;
+		this.listenTo( model.document, 'change:data', () => {
+			const { changedSearchResults } = onDocumentChange( this.state!.results, editor, findCallback );
 
-		// @todo: handle this listener, another copy is in findcommand.js file.
-		this.listenTo( model.document, 'change:data', () => onDocumentChange( this._activeResults!, editor, findCallback ) );
+			if ( changedSearchResults.length && !this.state!.highlightedResult ) {
+				this.state!.highlightedResult = changedSearchResults[ 0 ];
+			}
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:208]: I think it would be suitable to move these lines to the `onDocumentChange()` since it's a continuation of that logic.

**Review by Dumluregn — CHANGES_REQUESTED** [review]
Besides the inline comments, there's another bug to handle: the `Match case` and `Whole words only` options are not respected:

**Review by Dumluregn — COMMENTED** [review]
One more thing I noticed: every time `findAndReplaceEditing.find()` is executed, it applies a new `onDocumentChange()` callback. So if you use find 10 times, you get 10 callbacks. We obviously don't want that. The previous idea with having a flag indicating that we're tracking the document content was good, but the flag was checked in the cleanup instead of when the listener is added. Let's revisit this in the improved form, and with unit test for sure (execute `findAndReplaceEditing.find()` a number of times, then change something in the document and check how many times `onDocumentChange()` was called).

**Comment by Dumluregn** [comment]
Sorry for throwing small bits at you, but I also discussed with @DawidKossowski the architecture a bit and we'd like to get rid of `findAndReplaceEditing.find()` calls and instead be coherent and use editor commands (`editor.execute( ... )`) everywhere in the `findandreplace.ts` file listeners. That means that we'll apply the change listener next to these command execute calls instead of inside the `findAndReplaceEditing.find()` method. The good place for the flag I mentioned in the comment before seems to be a `FindAndReplaceState` class, both semantically and it will be handy to use it here.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts (hunk 7 above)
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: Removed. Thx!

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts (hunk 8 above)
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: Moved to that function

**Comment by Mati365** [comment]
@Dumluregn / @DawidKossowski I have refactored the use of `findCallback` and how callbacks listening for change are assembled. Can you take a look at it?

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 9]
```diff
@@ -269,4 +206,89 @@ export default class FindAndReplaceEditing extends Plugin {
...
+			);
+
+			// Sometimes `changedNodeSearchResults` contains elements that are already present on `changedSearchResults`
+			// list so do not return them duplicated.
+			changedNodeSearchResults.forEach( changedNodeResult => {
+				changedSearchResults.push( changedNodeResult );
+			} );
+		} );
+
+		// If there is no selection on found phrase then select first
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:271]:
```suggestion
		// If there are found phrases but none is selected, select the first one.
```

Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: changed

**Comment by Mati365** [comment]
@DawidKossowski / @Dumluregn I added some changes that add support for "find" event overloading in some plugins (e.g. track-changes).

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 10]
```diff
@@ -269,4 +197,106 @@ export default class FindAndReplaceEditing extends Plugin {
...
+				const changedNodeSearchResults = findAndReplaceUtils.updateFindResultFromRange(
+					markerToCheck.data.newRange, model, this.state!.lastSearchCallback!, results
+				);
+
+				console.info( 'new', [ ...markerToCheck.data.newRange ] );
+
+				changedSearchResults.push( ...changedNodeSearchResults );
+
+				console.info( 'new found', changedNodeSearchResults );
+			} else if ( markerToCheck.data.oldRange &&
```
Comment (scofalik) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:282]: I think this functionality will be difficult to implement and it might not be possible to do it here (in `change` event callback). We do know about `oldRange` but it was the range before any change happened. The model might have changed greatly, and the `oldRange` might be quite outdated and point to incorrect paths.

Which you already observed, but as we've seen, it crashed in another scenario and it still doesn't work other scenarios.

I'd drop this requirement for now. That is, do not react to deletion suggestion marker changes (or do not react to deletion suggestion markers being removed, as it seems it is easy to react to such markers being added). Let's move this to a separate ticket.

Other than that it seems to me that this whole callback would use some refactor but let's close what we have since the QA tests went fine.

**Review by scofalik — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts (hunk 10 above)
Comment (scofalik) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:282]: We can add followup for refactor as well, although I don't assume that we will find time for it.

File: packages/ckeditor5-find-and-replace/src/findandreplaceutils.ts [hunk 11]
```diff
@@ -52,6 +52,21 @@ export default class FindAndReplaceUtils extends Plugin {
 	): Collection<ResultType> {
 		const results = startResults || new Collection();
 
+		const checkIfResultAlreadyOnList = ( marker: Marker ) => results.find(
```
[the remark this answers is not in the document]
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceutils.ts:55]: > I guess there may be a situation where we removed something that already had a search marker and we re-add both the search marker and the new search result?
 
Yes, there can be such case. It happens quite often in T&C mode when you remove multiple paragraphs at once and then undo it. You are absolutely right about performance, it will affect it, but at this moment it's still better than having the feature broken at all. I suspect that this function and huge part of implementation of `_onDocumentChange` will be changed anyway, and it'll be no longer needed after fixing changes detection.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts (hunk 10 above)
Comment (Mati365) [reply packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts]: I added your comment to newly created issue about this problem.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 12]
```diff
@@ -110,27 +50,27 @@ export default class FindAndReplaceEditing extends Plugin {
...
+	 * @member {module:find-and-replace/findandreplacestate~FindAndReplaceState} #state
 	 */
-	private _activeResults?: Collection<ResultType> | null;
+	public state?: FindAndReplaceState;
 
 	/**
-	 * An object storing the find and replace state within a given editor instance.
+	 * A flag that indicates that the user has started a search and the editor is listening for changes
+	 * to the text on which it will perform an automatic search. Among other things, the mode is activated
+	 * when the user first clicks 'search' and then later deactivated when the modal or search dropdown is closed.
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:62]:
```suggestion
	 * when the user first clicks 'Find' button and then later deactivated when the modal or search dropdown is closed.
```

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 13]
```diff
@@ -110,27 +50,27 @@ export default class FindAndReplaceEditing extends Plugin {
 	}
 
 	/**
-	 * The collection of currently highlighted search results.
+	 * An object storing the find and replace state within a given editor instance.
 	 *
-	 * @private
-	 * @member {module:utils/collection~Collection} #_activeResults
+	 * @member {module:find-and-replace/findandreplacestate~FindAndReplaceState} #state
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:55]: Let's remove this deprecated \`@member\` tag.

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 14]
```diff
@@ -269,4 +201,90 @@ export default class FindAndReplaceEditing extends Plugin {
...
+				[ ...model.markers.getMarkersAtPosition( change.position ) ].forEach( markerAtChange => {
+					removedMarkers.add( markerAtChange.name );
+				} );
+			} else if ( change.type === 'insert' && change.position.nodeAfter ) {
+				changedNodes.add( change.position.nodeAfter );
+			}
+		} );
+
+		// Get markers from removed nodes also.
+		model.document.differ.getChangedMarkers().forEach( ( { name, data: { newRange } } ) => {
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:235]:
```suggestion
		changedMarkers.forEach( ( { name, data: { newRange } } ) => {
```

File: packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts [hunk 15]
```diff
@@ -269,4 +201,90 @@ export default class FindAndReplaceEditing extends Plugin {
...
+
+		changedNodes.forEach( nodeToCheck => {
+			const changedNodeSearchResults = findAndReplaceUtils.updateFindResultFromRange(
+				model.createRangeOn( nodeToCheck ), model, this.state!.lastSearchCallback!, results
+			);
+
+			changedSearchResults.push( ...changedNodeSearchResults );
+		} );
+
+		changedMarkers.forEach( markerToCheck => {
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplaceediting.ts:273]: Looks like this loop could be merged with the previous one (from the line 235).

File: packages/ckeditor5-find-and-replace/src/findandreplacestate.ts [hunk 16]
```diff
@@ -124,3 +134,7 @@ export default class FindAndReplaceState extends ObservableMixin() {
 	}
 }
 
+/**
+ * The callback function used to find matches in the document.
+ */
+export type FindCallback = ( ( { item, text }: { item: Item; text: string } ) => Array<ResultType> );
```
Comment (Dumluregn) [inline packages/ckeditor5-find-and-replace/src/findandreplacestate.ts:140]: I think I'd keep this type in `findcommand.ts`, but I won't persist on it.

**Review by Dumluregn — COMMENTED** [review]
I noticed one incorrect behavior with replace and undo:

https://github.com/ckeditor/ckeditor5/assets/10883184/d06eaea4-a301-43c8-89d4-66d757d939f8

Please take a look if it's something that can be easily fixed. Besides that, only some small nitpicks here and there.

There were quite a few changes in the code since the last testing, so I'd re-send this PR to the QA team once it's done on our side.

**Comment by Mati365** [comment]
@Dumluregn Can you check again? I pushed fixes and rebased PR into one commit.

**Review by Dumluregn — APPROVED** [review]
LGTM, well done :+1: We'll handle the track changes followups separately.
