### PR TITLE
The Model#insertContent() method should keep inline objects in the same auto-paragraph as text nodes and other inline objects

### LINKED ISSUE #16321: When only using block level images, insertcontent-invalid-insertion-position in console on paste of HTML
## 📝 Provide detailed reproduction steps (if any)

[Reproduction repo](https://github.com/Joel-Levi/ck-editor-5-invalid-position-on-paste-block-reproduction/tree/main)

1. Have an editor with only the folowing plugins:
[
		Essentials,
		ImageBlock,
		Paragraph,
		Undo
]

2. Paste html looking like:
```<br>```
or
```CK```

Clipboard contents on moment of pasting:
```
<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="http://127.0.0.1:5501/sample/repro.png"> <br> <img src="http://127.0.0.1:5501/sample/repro.png">%
```

### ✔️ Expected result
HTML gets pasted and is rendered properly
### ❌ Actual result
nothing is pasted, insertcontent-invalid-insertion-position error in the console, coming from here :
https://github.com/ckeditor/ckeditor5/blob/04a8c63bdad639792727275a0e30832869c7067f/packages/ckeditor5-engine/src/model/utils/insertcontent.ts#L362

### ❓ Possible solution

**unfocusing the editor after this reproduction fixes the rendering somehow.**

## 📃 Other details

* Browser: Latest Chrome, Latest Firefox
* OS: Linux Ubuntu
* First affected CKEditor version: ?
* Installed CKEditor plugins: [
		Essentials,
		ImageBlock,
		Paragraph,
		Undo
]

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (engine): `insertcontent-invalid-insertion-position` exception is no longer thrown after pasting content containing `block element` + `non-paragraph` + `block element` elements. Closes #16321.

Other (engine): The `Model#insertContent()` method should keep inline objects in the same auto-paragraph as text nodes and other inline objects. See #16321.

Other (engine): The `Schema#checkMerge()` method should return `false` if one of the elements is a limit element. See #16321.

---

### Additional information

1. @Dumluregn started debugging this issue and commented his findings [here](https://github.com/ckeditor/ckeditor5/issues/16321#issuecomment-2122644795). 
2. I continued debugging, and it seems that this line https://github.com/ckeditor/ckeditor5/blob/28fb67187f83f820cf895c39c98c0773eb260ce1/packages/ckeditor5-engine/src/model/utils/insertcontent.ts#L804 sets `this.position.parent` to be different from `node` if add block element at the end.
3. It fails `if ( this.position.parent != node || !this.position.isAtEnd ) {` this assertion.
4. It seems that removal of this assertion works, nothing more crashes, and newly added test looks similar to other tests (e.g. `inserts text + object (at the end)`).
5. I'm not sure if this is a good solution. It requires more debugging, but at this moment it works and is harmless.

### CODE REVIEW

**Review by illia-stv — APPROVED** [review]

**Review by niegowski — APPROVED** [review]

**Comment by Mati365** [comment]
@niegowski From what I can see, some of them are failing reporting real problem. For example this one:

```ts  
ImageBlockEditing
    integration with the clipboard pipeline
      ✖ should not work if there are elements other than inline images in the pipeline data

      + expected - actual

      -<paragraph>f</paragraph><imageBlock src="/assets/sample.png?id=A"></imageBlock><paragraph><imageInline src="/assets/sample.png?id=B"></imageInline>[]</paragraph><paragraph>oo</paragraph>
      +<paragraph>f</paragraph><imageBlock src="/assets/sample.png?id=A"></imageBlock><paragraph><imageInline src="/assets/sample.png?id=B"></imageInline>[]oo</paragraph>
```

it wrapped `oo` in `paragraph`

**Review by niegowski — APPROVED** [review]

File: packages/ckeditor5-engine/src/model/schema.ts [hunk 1]
```diff
@@ -432,7 +436,11 @@ export default class Schema extends /* #__PURE__ */ ObservableMixin() {
 	 * @param positionOrBaseElement The position or base element to which the `elementToMerge` will be merged.
 	 * @param elementToMerge The element to merge. Required if `positionOrBaseElement` is an element.
 	 */
-	public checkMerge( positionOrBaseElement: Position | Element, elementToMerge: Element ): boolean {
+	public checkMerge( positionOrBaseElement: Position | Element, elementToMerge?: Element ): boolean {
+		if ( elementToMerge && this.isLimit( elementToMerge ) ) {
+			return false;
+		}
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/schema.ts:442]: I'd move this `if` below and merge with line 475 into:

```javascript
if ( this.isLimit( positionOrBaseElement ) || this.isLimit( elementToMerge ) ) {
```

It should work, because I think that at that point we are in a place were both arguments are available and normalized to model nodes. It will be more clear to read.

**Review by scofalik — APPROVED** [review]
