### PR TITLE
Feedback loop in color picker in tables

### LINKED ISSUE #14389: Feedback loop in color picker in table properties
## 📝 Provide detailed reproduction steps (if any)

Visually everything is fine.

Problem actually is in color format which our table property apply to model. When we type **HEX** value into input we expect **HEX** value in model, but color picker listens on input to reflect actual color and it converts into **HSL**. Table property also listen on color picker changes and apply value in model.

### ✔️ Expected result

image

image

### ❌ Actual result

image

image

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (table): From now there is no feedback loop from color picker after changes in input. Closes #14389.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-table/tests/ui/colorinputview.js [hunk 1]
```diff
@@ -205,7 +205,11 @@ describe( 'ColorInputView', () => {
 
 				colorTableView.fire( 'cancel' );
 
-				expect( view.value ).to.be.equal( '#ffaaff' );
+				/**
+				 * TODO, should be HEX format: (https://github.com/ckeditor/ckeditor5/issues/14389)
```
Comment (Dumluregn) [inline packages/ckeditor5-table/tests/ui/colorinputview.js:209]: You should reference the issue which will handle this TODO, not the one introducing it. Whoever sees this will not get any explanation why this was done.

**Review by Dumluregn — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-table/tests/ui/colorinputview.js (hunk 1 above)
Comment (Dumluregn) [reply packages/ckeditor5-table/tests/ui/colorinputview.js:209]: This applies to all the other TODOs as well.

**Review by Dumluregn — APPROVED** [review]
