### PR TITLE
Fixes bug in selection postfixer

### LINKED ISSUE #10487: Calling `editor.setData( editor.getData() )` during image upload without content makes editor unusable
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the all features manual test.
2.  Remove the whole content.
3.  Start uploading some big image. I'm using a 15Mb image ([https://effigis.com/wp-content/uploads/2015/02/DigitalGlobe_WorldView1_50cm_8bit_BW_DRA_Bangkok_Thailand_2009JAN06_8bits_sub_r_1.jpg](https://effigis.com/wp-content/uploads/2015/02/DigitalGlobe_WorldView1_50cm_8bit_BW_DRA_Bangkok_Thailand_2009JAN06_8bits_sub_r_1.jpg)).
4.  During the upload call `editor.setData( editor.getData() )`.

### Other, simpler way to reproduce:

1.  Call `editor.setData( '<figure class="image"></figure>' )`.

### ✔️ Expected result

Editor should be usable after this

### ❌ Actual result

The empty element is inserted, however, it's not possible to type anything or create a new paragraph. The image toolbar is attached to this empty element.

### ❓ Possible solution

This is a problem with a selection postfixer which cannot fix `<figure class="image">[]</figure>`;

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (engine): Fixes bug in selection postfixer (when the selection stuck in a limit element that can't contain text). Closes #10487.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by niegowski** [comment]
Some tests are failing in the `table` package. This is because the `selection-post-fixer.js` is triggered before the `table-cell-paragraph-post-fixer.js` and the selection position is fixed (moved out from a table cell) before the paragraph is inserted into a cell. Seems like a first use case for priorities for post-fixers. But for now, let's fix those failing tests (by putting paragraphs in proper places).

File: packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js [hunk 1]
```diff
@@ -128,9 +128,17 @@ function tryFixingCollapsedRange( range, schema ) {
...
 	const nearestSelectionRange = schema.getNearestSelectionRange( originalPosition );
 
-	// This might be null ie when editor data is empty.
-	// In such cases there is no need to fix the selection range.
+	// This might be null ie when editor data is empty or the selection is inside limit element
+	// that doesn't allow text inside.
+	// In the first case there is no need to fix the selection range.
+	// In the second let's go up to the outer selectable element
 	if ( !nearestSelectionRange ) {
+		const ancestorObject = originalPosition.getAncestors().reverse().find( item => schema.isObject( item ) );
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/model/utils/selection-post-fixer.js:136]: Additional test would be great to make sure that the closest ancestor object is selected (test for the `reverse()`).

**Review by niegowski — CHANGES_REQUESTED** [review]
As commented above, there are tests in the table feature failing.

**Review by niegowski — APPROVED** [review]
