### PR TITLE
IME/typing bug-fixing

### LINKED ISSUE #13693: Composition breaks when typing a Korean phonetic radical after typing `space` key on Android Chrome
## 📝 Provide detailed reproduction steps (if any)

1. Launch any CKEditor, e.g. [this demo](https://ckeditor.com/ckeditor-5/demo/mobile-support/), on Android Chrome
2. Put caret at the start of any empty line
3. Use GBoard keyboard
4. Add keyboard language: select Korean then 2-Bulsik
5. Change keyboard language to Korean
6. Type `ㄱ`
7. Type `ㅏ`
8. Type `space`
9. Type `ㄱ`
10. Type `ㅏ`

[screenrecording.webm](https://user-images.githubusercontent.com/29354589/225513821-4b0b753b-52c0-4274-be4b-133ffa9e2d03.webm)

### ✔️ Expected result

`가 가`

### ❌ Actual result

`가 ㄱㅏ`

### ❓ Possible solution

Not updating Text node when composing, i.e. after `compositionstart` event and before `compositionend` event, by adding the following code into `renderer.ts`:

https://github.com/ckeditor/ckeditor5/blob/1bbb4dfb66395f9de41d9d6353bd8e69293621e0/packages/ckeditor5-engine/src/view/renderer.ts#L714-L728

```diff
else if ( action === 'replace' ) {
+ if (!this.isComposing) {
    updateTextNode( actualDomChildren[ i ] as DomText, ( expectedDomChildren[ i ] as DomText ).data );
+ }
  i++;
```

On Android Chrome, when a character is typed and the typing triggers a `compositionstart` event, IME seems to put the character into the Text node sometime after `compositionupdate` event. Meanwhile CKEditor also effectively puts the character into the node by invoking `updateTextNode`. So there would be two same characters. `MutationObserver` detects the DOM mutation and invokes another `updateTextNode`. Because of that invocation one of the two characters is removed. This can be confirmed by uncommenting `CK_DEBUG_TYPING` `console.log`s. I suspect that which character is removed affects whether the current composition should break, i.e. IME seems to be keeping track of which character instance is involved in the current composition.

The suggested solution will prevent the character duplication. IME will put the character while CKEditor won't. Thus there would be no removal of the duplicated character. Neither be composition-breaking.

## 📃 Other details

* Browser: Chrome 91.0
* OS: Android 12
* First affected CKEditor version: 36.0.1
* Installed CKEditor plugins: Essentials, Paragraph

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #13850: Deleting words on mobile
I'm using Gboard, but i think that doesn't matter, because nearly every mobile keyboard I know, has this functionality:

When writing words, and pressing the "remove" key, usually the whole word gets removed. However, this doesn't work in CKEditor (5). It works for the very first word, but on every other word, it just removes the last letter instead, which is kind of annoying.

-----

Edited on April 20th by @mabryl with reproduction steps and expected/actual results:

## 📝 Provide detailed reproduction steps (if any)

1. Type several words in CKE5 using the "swiping" method, i.e. by continuously dragging your finger across the keyboard
2. Press the backspace key

### ✔️ Expected result

The last word that was typed should be deleted in its entirety upon pressing backspace once

### ❌ Actual result

The word isn't removed, instead, individual letters are removed. To remove the word you have to continue pressing backspace

### LINKED ISSUE #13994: [Android-Samsung keyboard] Enter two or three spaces quickly, then the editor writes backwards
## 📝 Provide detailed reproduction steps (if any)

1. Open any CKEditor demo, e.g.https://ckeditor.com/ckeditor-5/demo/mobile-support/
2. Type a word and then either two or three spaces. Depending on the Android device, you may need two or three spaces for the problem to occur.
3. Keep typing, the editor will insert the text backwards.

### ✔️ Expected result

The editor inserts the text in the correct order.

### ❌ Actual result

The editor insert the text backwards. Subsequently, deleting the text also does not work properly and skips some letters.

## 📃 Other details

* Browser: Chrome
* OS: Android 10 + 12
* First affected CKEditor version: 36.0.1 (34.0.0 was fine)
* Installed CKEditor plugins: 
		Alignment,
		AutoImage,
		Autoformat,
		AutoLink,
		BlockQuote,
		Bold,
		Code,
		CodeBlock,
		Essentials,
		FontBackgroundColor,
		FontColor,
		FontFamily,
		FontSize,
		Heading,
		HorizontalLine,
		Image,
		ImageCaption,
		ImageInsert,
		ImageResize,
		ImageStyle,
		ImageToolbar,
		ImageUpload,
		Indent,
		IndentBlock,
		Italic,
		Link,
		LinkImage,
		List,
		ListProperties,
		MediaEmbed,
		Mention,
		Paragraph,
		PasteFromOffice,
		RemoveFormat,
		Strikethrough,
		Subscript,
		Superscript,
		Table,
		TableCellProperties,
		TableProperties,
		TableToolbar,
		TableCaption,
		TableColumnResize,
		Title,
		TextTransformation,
		TodoList,
		Underline

https://user-images.githubusercontent.com/6545286/234880218-ac675051-4219-4e54-a387-9fb7225b4fb5.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #14567: The first character of a word is duplicated to the right of the caret using Samsung keyboard using Firefox Mobile on Android
## 📝 Provide detailed reproduction steps (if any)

A user has reported that sometimes the first character of a word is duplicated and appears to the right of the caret. Any keypress is inserted to the left of the caret as expected.

The user has provided a screen recording of the issue and has explicitly confirmed that this is reproducible in the online demo of CKEditor. It was confirmed that the issue does not occur with Gboard or SwiftKey.

https://github.com/ckeditor/ckeditor5/assets/208610/d110e63a-126a-464d-ae87-f4218a54b9eb

### ✔️ Expected result

Typing just works as expected.

### ❌ Actual result

The first character of a new word is duplicated and inserted to the right of the caret.

## 📃 Other details

* Browser: Firefox Mobile 114
* OS: Android 13
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Not relevant

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #14702: [Safari] Reverse typing effect after focus change, e.g., outdent button causing text to insert backwards.
## 📝 Instructions

1. Open Safari
2. Navigate to: https://ckeditor.com/ckeditor-5/demo/feature-rich/
3. Remove all text from CKEditor input
4. Click into the CKEditor input
5. Click the Outdent button
6. Start typing

### ✔️ Expected result
_Text should input normally_

### ❌ Actual result
_The text is input in reverse_

## 📃 Other details
* Browser: Safari
* OS: macOS
* First affected CKEditor version: Latest

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #14707: Backspacing on Android with Samsung keyboard misplaces the caret
## 📝 Provide detailed reproduction steps (if any)

1. Open the online demo using Android with the Samsung keyboard.
2. Type some text into the editor ending with the word `test`
3. Try to backspace the last letter of `test` by hitting the backspace key once.

https://github.com/ckeditor/ckeditor5/assets/208610/dbe5cd2c-d08d-4e2f-bc3b-e81ad0cc3075

### ✔️ Expected result

The trailing `t` should be removed with the caret being placed behind `tes`.

### ❌ Actual result

The trailing `t` is removed, but the caret advanced by another character and is now between `te` and `s`. The editor will now look like this: `te|s` where the `|` denotes the caret position.

### ❓ Possible solution

This sounds an awful lot like #14567 which is similar but no the same.

## 📃 Other details

* Browser: Chrome 114
* OS: Android 13
* First affected CKEditor version: Unknown
* Installed CKEditor plugins: Not relevant

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #16106: [Safari 190 + Sonoma] Predictive text "double typing" effect
I'm now experiencing this (or an extremely similar) issue in the latest Safari Technology Preview (Release 190), also related to predictive text. 

Here is a demo of it happening on the CKEditor5 demo page:

https://github.com/ckeditor/ckeditor5/assets/127062/645b816a-4d27-4194-b7cf-49ba90d6afb4

I thought perhaps it's a bug in the tech preview, but I tried to reproduce it with the Quill demo editor, and it works fine there (and every other field I've tried this in on this version of Safari, outside of CKEditor):

https://github.com/ckeditor/ckeditor5/assets/127062/8fe9715d-84d9-4fcb-9717-02a533c817a5

_Originally posted by @winzig in https://github.com/ckeditor/ckeditor5/issues/14567#issuecomment-2021568844_

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (typing, engine): Predictive text should not get doubled while typing. Closes #16106.

Fix (engine): The reverse typing effect should not happen after the focus change. Closes #14702. Thanks, @urbanspr1nter!

Fix (engine, typing): Typing on Android should avoid modifying DOM while composing. Closes #13994. Closes #14707. Closes #13850. Closes #13693. Closes #14567. Closes: #11569.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-engine/src/view/observer/focusobserver.ts [hunk 1]
```diff
@@ -48,35 +49,14 @@ export default class FocusObserver extends DomEventObserver<'focus' | 'blur'> {
...
-				document.isFocused = false;
-				this._isFocusChanging = false;
-
-				// Re-render the document to update view elements
-				// (changing document.isFocused already marked view as changed since last rendering).
-				view.change( () => {} );
+		document.on<ViewDocumentFocusEvent>( 'focus', () => this._handleFocus() );
+		document.on<ViewDocumentBlurEvent>( 'blur', ( evt, data ) => this._handleBlur( data ) );
+
+		document.on<ViewDocumentInputEvent>( 'beforeinput', () => {
```
Comment (Reinmar) [inline packages/ckeditor5-engine/src/view/observer/focusobserver.ts:55]: Comments needed. Why we need to handle focus on every beforeinput? It was confusing initially that this actually SHOULD happen only once. Because it relies on the assumption that beforeinput is fired only for focused editors. Or not? If not, what happens then?

Comment (Reinmar) [reply packages/ckeditor5-engine/src/view/observer/focusobserver.ts:55]: Q: What happens when beforeinput is fired for a blurred editable?

File: packages/ckeditor5-engine/src/view/renderer.ts [hunk 2]
```diff
@@ -698,28 +711,30 @@ export default class Renderer extends /* #__PURE__ */ ObservableMixin() {
...
+				// @if CK_DEBUG_TYPING //			'color: green; font-weight: bold', 'font-weight: normal',
+				// @if CK_DEBUG_TYPING //			node
+				// @if CK_DEBUG_TYPING //		);
+				// @if CK_DEBUG_TYPING //	}
 				// @if CK_DEBUG_TYPING // }
 
 				insertAt( domElement as DomElement, i, expectedDomChildren[ i ] );
 				i++;
 			}
-			// Update the existing text node data. Note that replace action is generated only for Android for now.
```
Comment (Reinmar) [inline packages/ckeditor5-engine/src/view/renderer.ts:709]: This comment was outdated. That's why we removed the 2nd sentence.

File: packages/ckeditor5-engine/src/view/renderer.ts [hunk 3]
```diff
@@ -816,6 +831,67 @@ export default class Renderer extends /* #__PURE__ */ ObservableMixin() {
...
+			// @if CK_DEBUG_TYPING // 	console.info( '%c[Renderer]%c Text node does not need update:%c ' +
+			// @if CK_DEBUG_TYPING // 		`${ _escapeTextNodeData( actualText ) }%c (${ actualText.length })`,
+			// @if CK_DEBUG_TYPING // 		'color: green; font-weight: bold', 'font-style: italic', 'color: blue', ''
+			// @if CK_DEBUG_TYPING // 	);
+			// @if CK_DEBUG_TYPING // }
+
+			return;
+		}
+
+		if ( env.isAndroid && this.isComposing && actualText.replace( /\u00A0/g, ' ' ) == expectedText.replace( /\u00A0/g, ' ' ) ) {
```
Comment (Reinmar) [inline packages/ckeditor5-engine/src/view/renderer.ts:855]: Requires explanation.

File: packages/ckeditor5-typing/src/input.ts [hunk 4]
```diff
@@ -138,18 +195,276 @@ export default class Input extends Plugin {
...
+			// After composition end we need to verify if there are no left-overs.
+			// Listening at the lowest priority so after the InsertTextObserver added above.
+			this.listenTo<ViewDocumentCompositionEndEvent>( view.document, 'compositionend', () => {
+				// @if CK_DEBUG_TYPING // if ( ( window as any ).logCKETyping ) {
+				// @if CK_DEBUG_TYPING // 	console.group( '%c[Input]%c Force render after composition end.',
+				// @if CK_DEBUG_TYPING // 		'font-weight: bold; color: green', 'font-weight: bold', ''
+				// @if CK_DEBUG_TYPING // 	);
+				// @if CK_DEBUG_TYPING // }
+
+				view.document.fire<ViewDocumentMutationsEvent>( 'mutations', { mutations: [] } );
```
Comment (Reinmar) [inline packages/ckeditor5-typing/src/input.ts:279]: Explain that this will trigger the renderer to check all the nodes previously marked but ignored because the document was in the composition state (which blocks the renderer).  
  
Also explain an example case when this is needed.

File: packages/ckeditor5-engine/src/view/observer/focusobserver.ts (hunk 1 above)
Comment (niegowski) [reply packages/ckeditor5-engine/src/view/observer/focusobserver.ts:55]: What happens when `beforeinput` is fired for a blurred editable is described in this issue: https://github.com/ckeditor/ckeditor5/issues/14702.

File: packages/ckeditor5-typing/src/input.ts (hunk 4 above)
Comment (niegowski) [reply packages/ckeditor5-typing/src/input.ts:292]: Added in ce023f1.

File: packages/ckeditor5-typing/src/input.ts [hunk 5]
```diff
@@ -138,18 +195,276 @@ export default class Input extends Plugin {
...
+				// @if CK_DEBUG_TYPING // 	);
+				// @if CK_DEBUG_TYPING // }
+			} );
+
+			// Make sure that all changes are applied to the model before the end of composition.
+			this.listenTo<ViewDocumentCompositionEndEvent>( view.document, 'compositionend', () => {
+				this._compositionQueue.flush( 'composition end' );
+			} );
+
+			// Trigger mutations check after the composition completes to fix all DOM changes that got ignored during composition.
```
[the remark this answers is not in the document]
Comment (niegowski) [reply packages/ckeditor5-typing/src/input.ts:241]: Added in ce023f1.

File: packages/ckeditor5-engine/src/view/renderer.ts (hunk 3 above)
Comment (niegowski) [reply packages/ckeditor5-engine/src/view/renderer.ts:859]: Added in ce023f1.

File: packages/ckeditor5-engine/src/view/observer/focusobserver.ts (hunk 1 above)
Comment (niegowski) [reply packages/ckeditor5-engine/src/view/observer/focusobserver.ts:59]: Added in ce023f1.

**Review by Reinmar — APPROVED** [review]

**Comment by winzig** [comment]
@niegowski What's the ETA on when this will be released, what version of CKEditor would it be in?

**Comment by Witoso** [comment]
We are starting preparation for the release that is scheduled for the next week. Most likely it will be 43.0.0.
