### PR TITLE
Fixed emoji filtering and improved the filtering performance.

### LINKED ISSUE #17834: [Mac+Chrome] Missing emoji visible
## 📝 Provide detailed reproduction steps (if any)

1. Enter Emoji on the docs.
2. Open the picker

### ✔️ Expected result

No missing emoji.

### ❌ Actual result

Missing emoji on the list

Image

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome 132
* OS: MacOS Sequioa
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by martnpaneq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Fixed emoji filtering and improved the filtering performance. Closes #17834.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by psmyrek** [comment]
Please change target branch to `release`.

File: packages/ckeditor5-emoji/src/utils/isemojisupported.ts [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+	// Draw in blue on right.
+	ctx.fillStyle = '#0000FF';
+	ctx.fillText( unicode, CANVAS_WIDTH, 22 );
+
+	const a = ctx.getImageData( 0, 0, CANVAS_WIDTH, CANVAS_HEIGHT ).data;
+	const count = a.length;
+	let i = 0;
+
+	// Search the first visible pixel.
+	for ( ; i < count && !a[ i + 3 ]; i += 4 ) ;
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/utils/isemojisupported.ts:42]:
```suggestion
	for ( ; i < count && !a[ i + 3 ]; i += 4 );
```

File: packages/ckeditor5-emoji/src/utils/isemojisupported.ts [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+	// the result show be the same.
+	const x = CANVAS_WIDTH + ( ( i / 4 ) % CANVAS_WIDTH );
+	const y = Math.floor( i / 4 / CANVAS_WIDTH );
+	const b = ctx.getImageData( x, y, 1, 1 ).data;
+
+	if ( a[ i ] !== b[ 0 ] || a[ i + 2 ] !== b[ 2 ]) {
+		return false;
+	}
+
+	// Some emojis are a contraction of different ones, so if it's not supported, it will show multiple characters.
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/utils/isemojisupported.ts:60]:
```suggestion
	// Some emojis consist of different ones, so they will show multiple characters if they are not supported.
```

If I understood this correctly, here is my proposal to update the comment.

File: packages/ckeditor5-emoji/src/emojirepository.ts [hunk 3]
```diff
@@ -29,6 +30,16 @@ const SKIN_TONE_MAP: Record<number, SkinToneId> = {
 
 const BASELINE_EMOJI_WIDTH = 24;
 
+/**
+ * Object storing emoji support level by the operating system.
+ * Some emojis that are perceived as supported, are compound-emoji from previous version. For those emojis
+ * there has to be performed an additional width check to verify system support.
+ */
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/emojirepository.ts:37]:
```suggestion
/**
 * A map representing an emoji and its release version.
 * It's used to identify a user's minimal supported emoji level. 
 */
```

File: packages/ckeditor5-emoji/src/emojirepository.ts [hunk 4]
```diff
@@ -264,6 +291,26 @@ async function loadEmojiDatabase( emojiDatabaseUrl: string ): Promise<Array<Emoj
...
+ * Checks the supported emoji version by the OS, by sampling some representatives from different emoji releases.
+ */
+function getEmojiSupportedVersionByOs() {
+	return Object.entries( EMOJI_SUPPORT_LEVEL ).reduce( ( supportedVersion, [ emoji, version ] ) => {
+		if ( isEmojiSupported( emoji ) && version > supportedVersion ) {
+			supportedVersion = version;
+		}
+
+		return supportedVersion;
+	}, 0 );
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/emojirepository.ts:304]:
```suggestion
	return Object.entries( EMOJI_SUPPORT_LEVEL )
		.reduce( ( currentVersion, [ emoji, newVersion ] ) => {
			if ( isEmojiSupported( emoji ) && newVersion > currentVersion ) {
				return newVersion;
			}
	
			return currentVersion;
		}, 0 );
```

However, this condition could be much simpler if `EMOJI_SUPPORT_LEVEL` were sorted from the lowest to highest values.

File: packages/ckeditor5-emoji/src/emojirepository.ts [hunk 5]
```diff
@@ -226,11 +239,25 @@ export default class EmojiRepository extends Plugin {
...
+	 */
+	private static _getEmojiSupportedVersionByOs = getEmojiSupportedVersionByOs;
+
+	/**
+	 * A function used to determine if emoji has a zero width joiner.
 	 *
 	 * Referenced for unit testing purposes.
 	 */
-	private static _isEmojiSupported = isEmojiSupported;
+	private static _hasZwj = hasZwj;
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/emojirepository.ts:260]: I would think a bit if we could create an `EmojiUtils` plugin to move internals to a dedicated object that could be checked (via tests) but also gives the option to create some mocks in `EmojiRepository`.

File: packages/ckeditor5-emoji/tests/emojirepository.js [hunk 6]
```diff
@@ -140,29 +142,61 @@ describe( 'EmojiRepository', () => {
...
+			] );
+
+			fetchStubResolve( new Response( response ) );
+
+			editor = await editorPromise;
+
+			const emojiRepositoryPlugin = editor.plugins.get( EmojiRepository );
+			const hasNeutralFaceEmoji = emojiRepositoryPlugin._database.find( item => item.annotation === 'neutral face' );
+			const hasMicroscopeEmoji = emojiRepositoryPlugin._database.find( item => item.annotation === 'microscope' );
+			const hasUnamusedEmoji = emojiRepositoryPlugin._database.find( item => item.annotation === 'unamused face' );
```
Comment (pomek) [inline packages/ckeditor5-emoji/tests/emojirepository.js:165]: I know that data in mock are faked, but could we use a real example of a ZWJ emoji, as well as for a non-supported emoji in v16?

File: LICENSE.md [hunk 7]
```diff
@@ -23,6 +23,7 @@ The following libraries are included in CKEditor under the [MIT license](https:/
 * color-parse - Copyright (c) 2015 Dmitry Ivanov.
 * emoji-picker-element-data - Copyright (c) 2020 Nolan Lawson.
 * Fuse.js - Copyright (c) 2017 Kirollos Risk.
+* is-emoji-supported - Copyright (c) 2023, Koala Interactive SAS
```
Comment (psmyrek) [inline LICENSE.md:26]: The copyright from their `LICENSE.md` is:

```
Copyright (c) 2016-2020 Koala Interactive, Inc.
```

File: packages/ckeditor5-emoji/src/emojirepository.ts [hunk 8]
```diff
@@ -108,7 +120,8 @@ export default class EmojiRepository extends Plugin {
 		// Store the emoji database after normalizing the raw data.
 		this._database = emojiDatabase
 			.filter( item => isEmojiCategoryAllowed( item ) )
-			.filter( item => EmojiRepository._isEmojiSupported( item, container ) )
+			.filter( item => item.version <= emojiSupportedVersionByOs )
+			.filter( item => !EmojiRepository._hasZwj( item.emoji ) ? true : EmojiRepository._isEmojiZwjSupported( item, container ) )
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/src/emojirepository.ts:124]: These two `.filter()` calls do the same thing from a business perspective: filtering out unsupported emojis. Is it possible to merge this logic from both `.filter()` into one and hide the technical details in this place? Something like it was before:

```
.filter( item => EmojiRepository._isEmojiSupported( item, container ) )
```

IMHO it would be more readable.

File: packages/ckeditor5-emoji/src/emojirepository.ts [hunk 9]
```diff
@@ -29,6 +30,16 @@ const SKIN_TONE_MAP: Record<number, SkinToneId> = {
...
 const BASELINE_EMOJI_WIDTH = 24;
 
+/**
+ * Object storing emoji support level by the operating system.
+ * Some emojis that are perceived as supported, are compound-emoji from previous version. For those emojis
+ * there has to be performed an additional width check to verify system support.
+ */
+const EMOJI_SUPPORT_LEVEL = {
+	'🫩': 16, // face with bags under eyes
+	'🫨': 15 // shaking head
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/emojirepository.ts:40]: According to my comment about `adult-*` emoji. Perhaps we should store the latest supported `major.minor` combination. 

An alternative could be using only the `major` version when comparing versions when figuring out the latest supported version.

**Review by psmyrek — COMMENTED** [review]
It filters out too much now 🤔 

Before, I found at least two emojis that were correctly rendered in my OS:

before

On this branch, at least these two emojis are unnecessarily filtered out:

after

File: packages/ckeditor5-emoji/src/emojirepository.ts (hunk 5 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/emojirepository.ts:260]: I found two direct ways of creating utils files in CKEditor 5 codebase:
1. Exporting each util as a separate function.
2. Creating a util class that holds all required functions.

What solution would you think is best. I guess 2. is easier to mock, but requires more code, and effort to write.

**Comment by pomek** [comment]
cac496e2587e78ce4dafb7634dbc5d5845c3c078 resolves the issue that too many items were filtered out:

image

File: packages/ckeditor5-emoji/src/emojirepository.ts (hunk 5 above)
Comment (pomek) [reply packages/ckeditor5-emoji/src/emojirepository.ts:260]: `EmojiUtils` as a plugin, so (2).

File: packages/ckeditor5-emoji/src/utils/isemojisupported.ts (hunk 1 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/utils/isemojisupported.ts]: Fixed in [7343da3](https://github.com/ckeditor/ckeditor5/pull/17864/commits/7343da3b2734aaf3d93b6e1e8e455c9a2bf881df)

File: packages/ckeditor5-emoji/src/utils/isemojisupported.ts (hunk 2 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/utils/isemojisupported.ts]: Fixed in [7343da3](https://github.com/ckeditor/ckeditor5/pull/17864/commits/7343da3b2734aaf3d93b6e1e8e455c9a2bf881df)

File: packages/ckeditor5-emoji/src/emojirepository.ts (hunk 3 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/emojirepository.ts]: Fixed in [7343da3](https://github.com/ckeditor/ckeditor5/pull/17864/commits/7343da3b2734aaf3d93b6e1e8e455c9a2bf881df)

File: packages/ckeditor5-emoji/src/emojirepository.ts (hunk 4 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/emojirepository.ts]: Fixed in [7343da3](https://github.com/ckeditor/ckeditor5/pull/17864/commits/7343da3b2734aaf3d93b6e1e8e455c9a2bf881df)

File: packages/ckeditor5-emoji/src/emojirepository.ts (hunk 5 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/emojirepository.ts]: Introduced `EmojiUtils` in Fixed in [7343da3](https://github.com/ckeditor/ckeditor5/pull/17864/commits/7343da3b2734aaf3d93b6e1e8e455c9a2bf881df).

Unfortunately our tests do not support mocking a plugin that requires other plugins. `EmojiPlugin` mocks `EmojiRepository` that requires `EmojiUtils`. Maybe there is a way of solving this, that I'm not aware of, so I'm leaving this till tomorrow.

File: packages/ckeditor5-emoji/tests/emojirepository.js (hunk 6 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/tests/emojirepository.js]: Unfortunately we cannot perform fully unmocked tests for ZWJ icons, because we always install latest emoji on CI, and all ZWJ icons are going to be supported.

More detailed tests regarding emoji support are now extracted to `EmojiUtils` test.

File: packages/ckeditor5-emoji/src/emojirepository.ts (hunk 9 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/emojirepository.ts]: Checking the `major.minor` versions as You suggested.

File: LICENSE.md (hunk 7 above)
Comment (pomek) [reply LICENSE.md]: @martnpaneq, this entry repeats twice in the PR. 7343da3b2734aaf3d93b6e1e8e455c9a2bf881df includes a single fix only.

**Review by psmyrek — APPROVED** [review]
LGTM 🎉

**Review by pomek — APPROVED** [review]
