### PR TITLE
Color picker conversion

### LINKED ISSUE #2979: Pasting incorrect list is not fixed.
Originally posted by @Reinmar in ckeditor/ckeditor5#2972.

I found the following case. I copied:

image

And got:

image

It's not OT related, but I'm not sure if you want to work on all possible scenarios at once or you predict that we'll be tackling them down one by one.

### PR DESCRIPTION
**Pull request by Dumluregn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal( color-picker): Add color conversion for color picker.

---

### Additional information

A note for the reviewer - some conversion unit tests are failing. The results are off by 1%, 1 degree etc. That's probably because in the `color-convert` package the conversion between some formats is indirect, e.g. from LAB to Hex it's actually `LAB -> XYZ -> RGB -> Hex`. I think we should adjust unit tests for it instead of dropping the support, but I wanted to leave the decision about it open.

### CODE REVIEW

**Comment by mlewand** [comment]
@Dumluregn Make sense to add tolerance for the result. That was a first thing I noticed. I suppose best idea will be to make a reusable assertion.

Adding the output for reference:

```
SUMMARY:
√ 287 tests completed
× 17 tests failed

FAILED TESTS:
  utils
    convertColor
      should correctly convert the color
        from hex
          × to lab
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'lab( 55% 59 34 )' to equal 'lab( 55% 59 33 )'

      + expected - actual

      -lab( 55% 59 34 )
      +lab( 55% 59 33 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


        from rgb
          × to lab
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'lab( 55% 59 34 )' to equal 'lab( 55% 59 33 )'

      + expected - actual

      -lab( 55% 59 34 )
      +lab( 55% 59 33 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


        from hwb
          × to hex
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected '#E64D4D' to equal '#E64C4C'

      + expected - actual

      -#E64D4D
      +#E64C4C

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to rgb
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'rgb( 230, 77, 77 )' to equal 'rgb( 230, 76, 76 )'

      + expected - actual

      -rgb( 230, 77, 77 )
      +rgb( 230, 76, 76 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


        from lab
          × to hex
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected '#E74E4E' to equal '#E64C4C'

      + expected - actual

      -#E74E4E
      +#E64C4C

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to hsl
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'hsl( 360, 76%, 61% )' to equal 'hsl( 0, 75%, 60% )'

      + expected - actual

      -hsl( 360, 76%, 61% )
      +hsl( 0, 75%, 60% )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to rgb
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'rgb( 231, 78, 78 )' to equal 'rgb( 230, 76, 76 )'

      + expected - actual

      -rgb( 231, 78, 78 )
      +rgb( 230, 76, 76 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to hwb
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'hwb( 360, 31, 9 )' to equal 'hwb( 0, 30, 10 )'

      + expected - actual

      -hwb( 360, 31, 9 )
      +hwb( 0, 30, 10 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to lch
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'lch( 55% 68 29 )' to equal 'lch( 55% 68 30 )'

      + expected - actual

      -lch( 55% 68 29 )
      +lch( 55% 68 30 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


        from lch
          × to hex
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected '#E74E4C' to equal '#E64C4C'

      + expected - actual

      -#E74E4C
      +#E64C4C

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to hsl
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'hsl( 1, 76%, 60% )' to equal 'hsl( 0, 75%, 60% )'

      + expected - actual

      -hsl( 1, 76%, 60% )
      +hsl( 0, 75%, 60% )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to rgb
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'rgb( 231, 78, 76 )' to equal 'rgb( 230, 76, 76 )'

      + expected - actual

      -rgb( 231, 78, 76 )
      +rgb( 230, 76, 76 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to hwb
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'hwb( 1, 30, 9 )' to equal 'hwb( 0, 30, 10 )'

      + expected - actual

      -hwb( 1, 30, 9 )
      +hwb( 0, 30, 10 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


          × to lab
            Chrome 111.0.0.0 (Windows 10)
          AssertionError: expected 'lab( 55% 59 34 )' to equal 'lab( 55% 59 33 )'

      + expected - actual

      -lab( 55% 59 34 )
      +lab( 55% 59 33 )

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:117:109)


    convertToHex
      should correctly convert color from
        × hwb
          Chrome 111.0.0.0 (Windows 10)
        AssertionError: expected '#E64D4D' to equal '#E64C4C'

      + expected - actual

      -#E64D4D
      +#E64C4C

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:145:99)


        × lab
          Chrome 111.0.0.0 (Windows 10)
        AssertionError: expected '#E74E4E' to equal '#E64C4C'

      + expected - actual

      -#E74E4E
      +#E64C4C

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:145:99)


        × lch
          Chrome 111.0.0.0 (Windows 10)
        AssertionError: expected '#E74E4C' to equal '#E64C4C'

      + expected - actual

      -#E74E4C
      +#E64C4C

    at Context.eval (./packages/ckeditor5-font/tests/utils.js:145:99)



=============================== Coverage summary ===============================
Statements   : 100% ( 440/440 )
Branches     : 100% ( 111/111 )
Functions    : 100% ( 126/126 )
Lines        : 100% ( 433/433 )
================================================================================
```

**Comment by mlewand** [comment]
I wonder why CI is failing with coverage?

[https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/599497439](https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/599497439)

On my local setup when running `yarn test -f font --production` I have a full coverage :thinking:

File: packages/ckeditor5-font/src/utils.ts [hunk 1]
```diff
@@ -140,3 +147,79 @@ function normalizeColorCode( value: string ): string {
...
+ * @param color
+ * @returns A color string.
+ */
+export function convertColor( color: string, outputFormat: ColorPickerOutputFormat ): string {
+	if ( !color ) {
+		return '';
+	}
+
+	// Parser library treats `hex` format as belonging to `rgb` space, which messes up further conversion.
+	// Let's parse such strings on our own.
```
Comment (mlewand) [inline packages/ckeditor5-font/src/utils.ts:164]: Good comment 👍

Weird decision on their side to do that.

File: packages/ckeditor5-font/src/utils.ts [hunk 2]
```diff
@@ -140,3 +147,79 @@ function normalizeColorCode( value: string ): string {
...
+	// @ts-ignore
+	const convertedColorChannels: Array<number> = convert[ colorObject.space ][ outputFormat ]( colorObject.values );
+
+	return formatColorOutput( convertedColorChannels, outputFormat );
+}
+
+/**
+ * Color formats handled by color converter.
+ */
+export type ColorPickerOutputFormat = 'hex' | 'rgb' | 'hsl' | 'hwb' | 'lab' | 'lch';
```
Comment (mlewand) [inline packages/ckeditor5-font/src/utils.ts:184]: There's `color` format missing, but we can skip it for now to simplify implementation.

**Review by mlewand — COMMENTED** [review]
The unit tests are leaking DOM elements (CI caught that and I'm seeing this also on my local host).

I'll push this partial review for now, the rest will follow later

**Comment by Dumluregn** [comment]
> I wonder why CI is failing with coverage?
> 
> [https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/599497439](https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/599497439)
> 
> On my local setup when running `yarn test -f font --production` I have a full coverage :thinking:

[https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/599497439#L1800-L1807](https://app.travis-ci.com/github/ckeditor/ckeditor5/jobs/599497439#L1800-L1807) - looks like there was an error and some tests were not executed :thinking:

File: packages/ckeditor5-font/src/utils.ts (hunk 2 above)
Comment (Dumluregn) [reply packages/ckeditor5-font/src/utils.ts:184]: I'm not sure if you mean [the color notation](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color) (e.g. `color(display-p3 1 0.5 0);`) here or using keywords (like `blue`). The first one is not supported neither by `color-convert` nor `color-parse` libs, so it doesn't seem likely to include it in the list. Keywords, on the other hand, could be a valid inclusion, but in picker -> output conversion they would only be rounded to the closest keyword, so I'm not sure how useful it would be. Anyway, I extracted the follow-up here: cksource/ckeditor5-internal#3046.

File: packages/ckeditor5-font/src/fontconfig.ts [hunk 3]
```diff
@@ -155,14 +156,26 @@ export interface FontColorConfig {
...
 
 	/**
-	 * Color picker gives ability to choose custom color.
-	 *
-	 * By default color picker is set on `true`.
-	 *
+	 * Configuration of the color picker feature.
 	 */
-	colorPicker?: boolean;
+	colorPicker?: ColorPickerConfig;
```
[the remark this answers is not in the document]
Comment (Dumluregn) [reply packages/ckeditor5-font/src/fontconfig.ts]: The resulting type of `colorPicker?: false | ColorPickerConfig;` looks awkward to me TBH. Also, in the code where we have `const hasColorPicker = componentConfig.colorPicker !== false;` and then inside of `if ( hasColorPicker ) {` block TS doesn't correctly identify that `componentConfig.colorPicker` can't be `false`. That forced me to write a rather ugly helper: [https://github.com/ckeditor/ckeditor5/pull/13820/files#diff-5f1599483e20b0f11b1793b254cebd0eeb7582b0e61fa2207bd815a15e3cafa0R189-R195.](https://github.com/ckeditor/ckeditor5/pull/13820/files#diff-5f1599483e20b0f11b1793b254cebd0eeb7582b0e61fa2207bd815a15e3cafa0R189-R195.)

**Comment by Dumluregn** [comment]
CI is green and all notes are taken care of.

File: packages/ckeditor5-font/src/utils.ts (hunk 2 above)
Comment (mlewand) [reply packages/ckeditor5-font/src/utils.ts]: That's about later. Let's keep it in a MVP1234 follow-up.

**Review by mlewand — APPROVED** [review]

**Comment by mlewand** [comment]
Pushed changes to the branch.

**Comment by mlewand** [comment]
This PR misses one line test coverage. It will be covered once [(currently skipped) unit test for text input integration](https://github.com/ckeditor/ckeditor5/blob/3efbea82164a77f387fd614486a01eed24a70a18/packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js#L66) gets restored.

It requires #13819 to be merged to do that.
