### PR TITLE
Find and replace: Source mode integration added, manual test updated

### LINKED ISSUE #10001: Integrate find and replace plugin with source mode
## 📝 Provide detailed reproduction steps (if any)

Based on https://github.com/ckeditor/ckeditor5/issues/9964#issuecomment-869651757

> 1. Switch to source mode
> 
> **Expected:** find & replace toolbar dropdown is inactive.
> 
> **Actual:** find & replace toolbar dropdown is active, you can open it and type some text, but nothing happens anyway.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mateuszzagorski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (find-and-replace): The dropdown button should now be disabled when the source mode is active. Closes #10001.

### CODE REVIEW

File: packages/ckeditor5-find-and-replace/src/findandreplaceui.js [hunk 1]
```diff
@@ -122,6 +122,9 @@ export default class FindAndReplaceUI extends Plugin {
 				cancelEvent();
 			} );
 
+			// Dropdown won't be enabled when find command is disabled.
```
Comment (mlewand) [inline packages/ckeditor5-find-and-replace/src/findandreplaceui.js:125]: This comment describes obvious thing - it basically reads the code one line below which makes it redundant. If anything we should say **why** we are doing this binding. You could do one sentence explanation and add a reference number to issue #10001 - this will give the most insights.

**Review by mlewand — CHANGES_REQUESTED** [review]
Unit tests are missing. Other than that looks ok.

**Review by mlewand — COMMENTED** [review]
Looking good 👍
