### PR TITLE
[GHS] Table feature integration

### LINKED ISSUE #9914: [GHS] Applying attributes to existing features - table
## 📝 Provide detailed reproduction steps (if any)

Due to the complex model structure of the [Table](https://ckeditor.com/docs/ckeditor5/latest/features/table.html) feature, it's not possible to easily extend it with additional attributes. We will need to create separate integration for it.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by jacekbogdanski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (html-support): Added General HTML Support integration for Tables feature. Closes #9914.

---

### Additional information

No support for `tfooter` as it's not supported by Table feature itself. `caption`/`figcaption` elements are supported by default GHS itself and don't require any additional integration.

The class name for integration (`TableElementSupport`) doesn't follow the same naming pattern as `CodeBlockHtmlSupport` because it's something we are currently changing in https://github.com/ckeditor/ckeditor5/pull/9891 - although I have some small doubts if actually `*HtmlSupport` is not a better name as we are not providing simple element support (which is already done by GHS) but existing feature integration.

### CODE REVIEW

File: packages/ckeditor5-html-support/src/integrations/table.js [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+				if ( childNode.is( 'element', 'thead' ) ) {
+					preserveElementAttributes( childNode, 'htmlTheadAttributes' );
+				}
+
+				if ( childNode.is( 'element', 'tbody' ) ) {
+					preserveElementAttributes( childNode, 'htmlTbodyAttributes' );
+				}
+			}
+
+			function preserveElementAttributes( viewElement, attributeName ) {
```
Comment (maxbarnas) [inline packages/ckeditor5-html-support/src/integrations/table.js:92]: Maybe we can move this function directly to the body of `viewToModelTableAttributeConverter()`? Otherwise it'll be created every time the converter for `element:table` is called.

File: packages/ckeditor5-html-support/src/integrations/table.js [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+// @private
+// @returns {Function} Returns a conversion callback.
+function modelToViewTableAttributeConverter() {
+	return dispatcher => {
+		addAttributeConversionDispatcherHandler( 'table', 'htmlAttributes' );
+		addAttributeConversionDispatcherHandler( 'figure', 'htmlFigureAttributes' );
+		addAttributeConversionDispatcherHandler( 'thead', 'htmlTheadAttributes' );
+		addAttributeConversionDispatcherHandler( 'tbody', 'htmlTbodyAttributes' );
+
+		function addAttributeConversionDispatcherHandler( elementName, attributeName ) {
```
Comment (maxbarnas) [inline packages/ckeditor5-html-support/src/integrations/table.js:115]: Same thing as in line 92.

**Review by maxbarnas — CHANGES_REQUESTED** [review]
Two minor things to change, otherwise LGTM.

File: packages/ckeditor5-html-support/src/integrations/table.js (hunk 1 above)
Comment (jacekbogdanski) [reply packages/ckeditor5-html-support/src/integrations/table.js:92]: Extracting these functions outside the scope of the dispatcher function will require passing multiple (~5) parameters which looks ugly. We are looking into micro pre-optimization here, so I would prefer to keep it more readable instead.

File: packages/ckeditor5-html-support/src/integrations/table.js (hunk 2 above)
Comment (jacekbogdanski) [reply packages/ckeditor5-html-support/src/integrations/table.js:115]: https://github.com/ckeditor/ckeditor5/pull/10104#discussion_r669675048
