### PR TITLE
Remove the aria-checked attribute from the buttons.

### LINKED ISSUE #14823: Our buttons use aria-checked instead of aria-pressed attribute
## 📝 Provide detailed reproduction steps (if any)

1.  Open [latest feature-rich example (permalink)](https://ckeditor.com/docs/ckeditor5/39.0.1/examples/builds-custom/full-featured-editor.html).
2.  Turn on show blocks mode using the show blocks button.
3.  Inspect the show block button's markup.

### ✔️ Expected result

Per [WAI-ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#button) a proper attribute for a button role is `aria-pressed` attribute.

### ❌ Actual result

It has a following markup:

```
<button role="button" class="ck ck-button ck-on" type="button" tabindex="-1"
	aria-labelledby="ck-editor__aria-label_eaf76021d0235078ca4f127438479200d" data-cke-tooltip-text="Show blocks"
	data-cke-tooltip-position="s" aria-checked="true"><svg
		class="ck ck-icon ck-reset_all-excluded ck-icon_inherit-color ck-button__icon" viewBox="0 0 20 20">
		<path
			d="m6.395 9.196 2.545-.007V6.498a.598.598 0 0 1 .598-.598h.299a.598.598 0 0 1 .598.598v6.877a.598.598 0 0 1-.598.598h-.299a.598.598 0 0 1-.598-.598v-2.691l-2.545.007v2.691a.598.598 0 0 1-.598.598h-.299a.598.598 0 0 1-.598-.598V6.505a.598.598 0 0 1 .598-.598h.299a.598.598 0 0 1 .598.598v2.691Z">
		</path>
		<path
			d="M15.094 13.417V6.462a.562.562 0 0 0-.562-.562h-.782a1 1 0 0 0-.39.08l-1.017.43a.562.562 0 0 0-.343.517v.197c0 .4.406.67.775.519l.819-.337v6.111c0 .31.251.562.561.562h.377c.31 0 .562-.251.562-.562Z">
		</path>
		<path d="M0 15.417v1.5h1.5v-1.5H0Z"></path>
		<path d="M18.5 15.417v1.5H20v-1.5h-1.5Z"></path>
		<path d="M18.5 12.333v1.5H20v-1.5h-1.5Z"></path>
		<path d="M18.5 9.25v1.5H20v-1.5h-1.5Z"></path>
		<path d="M18.5 6.167v1.5H20v-1.5h-1.5Z"></path>
		<path d="M0 18.5v.5a1 1 0 0 0 1 1h.5v-1.5H0Z"></path>
		<path d="M3.083 18.5V20h1.5v-1.5h-1.5Z"></path>
		<path d="M6.167 18.5V20h1.5v-1.5h-1.5Z"></path>
		<path d="M9.25 18.5V20h1.5v-1.5h-1.5Z"></path>
		<path d="M12.333 18.5V20h1.5v-1.5h-1.5Z"></path>
		<path d="M15.417 18.5V20h1.5v-1.5h-1.5Z"></path>
		<path d="M18.5 18.5V20h.5a1 1 0 0 0 1-1v-.5h-1.5Z"></path>
		<path clip-rule="evenodd" d="M0 1a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v3.583h-1.5V1.5h-17v12.333H0V1Z"></path>
	</svg><span class="ck ck-button__label" id="ck-editor__aria-label_eaf76021d0235078ca4f127438479200d">Show
		blocks</span></button>
```

We're using `aria-checked` which is invalid attribute for this role.

It's not limited to show blocks, other "simple" buttons have this issue too, just enable other features of editor (like bold, undetline, lists etc) for your current selection and run following code in devtools:

### ❓ Possible solution

Just change it to `aria-pressed` and all should be good.

## 📃 Other details

I noticed this during live accessibility workshop session on 17th of August. If needed more info could be found there, It should be around 60-70 minute mark.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by gorzelinski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (ui): Remove the aria-checked attribute from the buttons. Closes #14823.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by mmotyczynska** [comment]
This change will probably introduce a regression for [screen readers](https://github.com/ckeditor/ckeditor5/issues/13250). I'd suggest changing the scope because we need `aria-checked` in the drop-downs with role `menu` for buttons with role `menuitemradio`.

More on why we implemented it like this can be found in the description of [this PR](https://github.com/ckeditor/ckeditor5/pull/13893).

**Comment by gorzelinski** [comment]
Thanks for the additional context. I didn't know we used that role. In such a case, you're right. I'll modify this PR.

File: packages/ckeditor5-ui/tests/button/buttonview.js [hunk 1]
```diff
@@ -298,14 +298,6 @@ describe( 'ButtonView', () => {
 				expect( view.element.hasAttribute( 'aria-pressed' ) ).to.be.false;
 			} );
 
-			it( '-checked reacts on #isOn', () => {
```
Comment (arkflpc) [inline packages/ckeditor5-ui/tests/button/buttonview.js:301]: Removing the test doesn't cover the change (against regression). I.e. if `aria-checked` is reintroduced by mistake on button, no test would fail. Please add one that checks if there is no such attribute on button.

**Review by arkflpc — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-ui/tests/button/buttonview.js (hunk 1 above)
Comment (gorzelinski) [reply packages/ckeditor5-ui/tests/button/buttonview.js:301]: Added.

File: packages/ckeditor5-ui/tests/button/buttonview.js [hunk 2]
```diff
@@ -298,21 +298,17 @@ describe( 'ButtonView', () => {
...
 			it( '-label reacts on #ariaLabel', () => {
 				view.ariaLabel = undefined;
 				expect( view.element.hasAttribute( 'aria-label' ) ).to.be.false;
 
 				view.ariaLabel = 'Foo';
 				expect( view.element.attributes[ 'aria-label' ].value ).to.equal( 'Foo' );
 			} );
+
+			it( '-checked is not present', () => {
+				expect( view.element.hasAttribute( 'aria-checked' ) ).to.be.false;
```
Comment (arkflpc) [inline packages/ckeditor5-ui/tests/button/buttonview.js:310]: This test doesn't check against regression. The reason is: it was already `false` when `view.isOn` was `false`. And it is by default. Probably there is missing `view.isOn = true`.

**Review by arkflpc — CHANGES_REQUESTED** [review]

**Review by mmotyczynska — CHANGES_REQUESTED** [review]
I think the buttons you've added `aria-checked ` to are incorrect. The buttons that should have this attribute are the buttons on the dropdown list items. Not the buttons that open the dropdown.

Check in the docs for example how it should look like (and a screenshot below). Open the font family dropdown and inspect the **selected** item from the dropdown list. It should have 3 `aria` attributes: `role`, `aria-labelledby`, and `aria-checked`. On your branch `aria-checked` Is missing in this case. And when `aria-checked` is missing, a screen reader will not announce which item from the list is selected.

It should look like this:
Screenshot 2023-09-26 at 11 59 57

**Review by arkflpc — APPROVED** [review]
