### PR TITLE
Fixes IndexSizeError when the background color is applied on Safari.

### LINKED ISSUE #12294: [Safari] Applying text format on 3 separately formatted fragments causes breaking error
## 📝 Provide detailed reproduction steps (if any)

1.  Apply text formatting to 3 parts of text (separately)
2.  Select the 3 parts and attempt to apply another format

### ✔️ Expected result

Selected part of text will format accordingly, editor will work as it should afterwards

### ❌ Actual result

The formatting goes through, but the editor crashes in process

https://user-images.githubusercontent.com/66953380/185591677-cde73daa-1579-4279-8fc2-82c0a64ce818.mov

## 📃 Other details

Safari only.

Console errors:

```javascript
CKEditorError: The index is not in the allowed range.
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-The index is not in the allowed range.

CKEditorError: cannot-change-view-tree
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-cannot-change-view-tree
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #12375: Not possible to undo and IndexSizeError when the background colour is applied on Safari in the all-feature manual test
## 📝 Provide detailed reproduction steps (if any)

1. Open on master http://localhost:8125/ckeditor5/tests/manual/all-features.html
2. Select this text:
Zrzut ekranu 2022-08-31 o 12 34 09

3. Try to apply background colour

### ✔️ Expected result

Background colour applied, no errors in the console, possibility to undo. 

### ❌ Actual result

Background colour applied, errors in the console, undo not possible. 
background colour issue

```
[Error] IndexSizeError: The index is not in the allowed range.
	fire (all-features.js:1936)
	domListener (all-features.js:29602)
[Error] CKEditorError: cannot-change-view-tree
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree
	fire (all-features.js:1936)
	set (all-features.js:871)
	(anonimowa funkcja) (all-features.js:33708)
```

## 📃 Other details

* Browser: Safari
* OS: Mac OS Monterey
Checked that it is reproducing from at least version `31.0.0`
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (engine). Fixes \`IndexSizeError\` when the background color is applied on Safari. Closes #12375. Closes #12294.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by niegowski — COMMENTED** [review]
I'm not sure if this solution would work correctly with selection anchored or focused in some container element, for example `<p><b>fo[o</b>]</p>`

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 1]
```diff
@@ -1168,8 +1168,12 @@ export default class DomConverter {
 		// we will use the fact that range will collapse if it's end is before it's start.
 		const range = this._domDocument.createRange();
 
-		range.setStart( selection.anchorNode!, selection.anchorOffset );
-		range.setEnd( selection.focusNode!, selection.focusOffset );
+		try {
+			range.setStart( selection.anchorNode!, selection.anchorOffset );
+			range.setEnd( selection.focusNode!, selection.focusOffset );
+		} catch {
+			return false;
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:1175]: Probably you should call `range.detach();` before.

Comment (niegowski) [reply packages/ckeditor5-engine/src/view/domconverter.ts:1175]: Ok, ignore me, it does nothing https://developer.mozilla.org/en-US/docs/Web/API/Range/detach

File: packages/ckeditor5-engine/src/view/domconverter.ts [hunk 2]
```diff
@@ -1168,8 +1168,12 @@ export default class DomConverter {
 		// we will use the fact that range will collapse if it's end is before it's start.
 		const range = this._domDocument.createRange();
 
-		range.setStart( selection.anchorNode!, selection.anchorOffset );
-		range.setEnd( selection.focusNode!, selection.focusOffset );
+		try {
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/view/domconverter.ts:1171]: Please add a comment about the reason and a link to the GH issue.
