### PR TITLE
Emoji mention will take into account the selected skin tone

### LINKED ISSUE #17656: Apply the active skin tone from a balloon when using the autocomplete feature
## 📝 Provide a description of the improvement

Using the balloon, a user can update the skin tone:

Image

While the balloon respects the option after reopening:

Image

The autocomplete feature ignores it.

Image

This issue aims to make the autocomplete feature compatible with the emoji displayed in the balloon.

### LINKED ISSUE #17660: Balloon does not show an active skin tone
## 📝 Provide detailed reproduction steps (if any)

1. Visit http://localhost:8125/ckeditor5-emoji/tests/manual/emoji.html
2. Open the emoji balloon.
3. Change the skin tone.
4. Open the skin tone again.

### ✔️ Expected result

An example from the _heading_ demo:

Image

### ❌ Actual result

Image

### PR DESCRIPTION
**Pull request by przemyslaw-zan**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Emoji mention will take into account the selected skin tone. Closes #17656.

Internal: Active skin tone in the emoji picker will have checkmark and be selected upon opening the skin tone dropdown. Closes #17660.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-emoji/src/emojipicker.ts [hunk 1]
```diff
@@ -42,16 +42,16 @@ export default class EmojiPicker extends Plugin {
 	/**
 	 * Registered emojis. A pair of an emoji name and all its available skin tone variants.
 	 */
-	private _emojis: Map<string, Array<string>>;
+	public emojis: Map<string, Array<string>>;
+
+	public selectedSkinTone: SkinToneId;
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/emojipicker.ts:47]: I would keep it private/protected. Create a getter (fn or just a property) that returns this value.

File: packages/ckeditor5-emoji/src/ui/emojitoneview.ts [hunk 2]
```diff
@@ -89,21 +91,25 @@ export default class EmojiToneView extends View {
...
 			label: example,
 			withText: true,
 			tooltip,
-			tooltipPosition: 'e'
+			tooltipPosition: 'e',
+			hasCheckSpace: true,
+			isToggleable: true
 		} );
 
+		buttonView.bind( 'isOn' ).to( this, 'selectedSkinTone', newSkinToneId => newSkinToneId === buttonSkinToneId );
```
Comment (pomek) [inline packages/ckeditor5-emoji/src/ui/emojitoneview.ts:106]: I think this needs to be verified via unit tests. Is it possible?

**Review by pomek — APPROVED** [review]
LGTM.
