### PR TITLE
Link UI should not show up on Ctrl+K when LinkCommand is disabled

### LINKED ISSUE #7919: Link UI should not show up on Ctrl+K when LinkCommand is disabled
## 📝 Provide detailed reproduction steps (if any)

1.  Open any sample.
2.  Select some content that makes the `LinkCommand` disabled (e.g. a table, a media, or multiple table cells)
3.  Check out the link button (it should be disabled)
4.  Hit `Ctrl+K`

### ✔️ Expected result

Nothing should happen. The `LinkCommand` is disabled.

### ❌ Actual result

The link insertion UI pops up but you cannot save it. It does not make any sense.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   CKEditor version: Looks like a regression in 16.0.0.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pkwasnik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix: Do not show up Link UI on Ctrl+K when LinkCommand is disabled. Closes #7919.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-link/tests/linkui.js [hunk 1]
```diff
@@ -795,6 +795,20 @@ describe( 'LinkUI', () => {
...
+			const command = editor.commands.get( 'link' );
+			command.isEnabled = false;
+
+			editor.keystrokes.press( {
+				keyCode: keyCodes.k,
+				ctrlKey: true,
+				preventDefault: sinon.spy(),
+				stopPropagation: sinon.spy()
+			} );
+			sinon.assert.notCalled( spy );
```
Comment (jodator) [inline packages/ckeditor5-link/tests/linkui.js:809]:
```suggestion
			} );

			sinon.assert.notCalled( spy );
```

Minor formatting - separate visually test action from the assertion block.

**Review by jodator — APPROVED** [review]
LGTM :+1: Only PR related things to close:

*   missing commit message proposal
*   CLA signing
