### PR TITLE
Reject unwanted hidden bookmark links from imported word content in paste from office.

### LINKED ISSUE #18846: Pasting content from Word inserts unwanted visible bookmarks into the editor
## 📝 Provide detailed reproduction steps (if any)

1. Copy the content of the problematic docx file - [bookmarks.docx](https://github.com/user-attachments/files/21213345/bookmarks.docx)
2. Paste it into the editor - [full-featured-editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)

### ✔️ Expected result

Only meaningful bookmarks from the original Word document should be preserved after pasting.

### ❌ Actual result

Extra empty bookmarks are added during paste, including visible icons in the content that were not present in the original Word file.

Image

Clipboard - [text:html.zip](https://github.com/user-attachments/files/21213568/text.html.zip)

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Mati365**
### 🚀 Summary

Reject unwanted hidden bookmark links from imported word content in paste from office.

### 📌 Related issues

* Closes https://github.com/ckeditor/ckeditor5/issues/18846

---

### 🧾 Checklists

Use the following checklists to ensure important areas were not overlooked.
This does not apply to feature-branch merges.
If an item is **not relevant** to this type of change, simply leave it unchecked.

#### Author checklist

- [ ] Is the changelog entry intentionally omitted?
- [x] Is the change backward-compatible?
- [x] Have you considered the impact on different editor setups and core interactions? _(e.g., classic/inline/multi-root/many editors, typing, selection, paste, tables, lists, images, collaboration, pagination)_
- [x] Has the change been manually verified in the relevant setups?
- [x] Does this change affect any of the above?
- [ ] Is performance impacted?
- [ ] Is accessibility affected?
- [x] Have tests been added that fail without this change (against regression)?
- [ ] Have the API documentation, guides, feature digest, and related feature sections been updated where needed?
- [ ] Have metadata files (ckeditor5-metadata.json) been updated if needed?
- [ ] Are there any changes the team should be informed about (e.g. architectural, difficult to revert in future versions or having impact on other features)?
- [ ] Were these changes documented (in Logbook)?

#### Reviewer checklist

- [ ] PR description explains the changes and the chosen approach (especially when  performance, API, or UX is affected).
- [ ] The changelog entry is clear, user‑ or integrator-facing, and it describes any breaking changes.
- [ ] All new external dependencies have been approved and mentioned in LICENSE.md (if any).
- [ ] All human-readable, translateable strings in this PR been introduced using `t()` (if any).
- [ ] I manually verified the change (e.g., in manual tests or documentation).
- [ ] The target branch is correct.

### CODE REVIEW

File: packages/ckeditor5-paste-from-office/src/filters/bookmark.ts [hunk 1]
```diff
@@ -40,5 +41,15 @@ export function transformBookmarks(
...
+		if ( isHiddenBookmarkAnchor( element ) ) {
+			writer.remove( element );
+		}
 	}
 }
+
+function isHiddenBookmarkAnchor( element: ViewElement ) {
+	const name = element.getAttribute( 'name' );
+
+	return !!name && name.startsWith( '_' );
```
Comment (pszczesniak) [inline packages/ckeditor5-paste-from-office/src/filters/bookmark.ts:65]: I would add a comment here that we filter all when it starts with `_` because MS Word does not allow to create a bookmark that starts with `_`.

```
MS Word reserves `_`-prefixed bookmark names for auto-generated TOC/hyperlink anchors.
```

File: packages/ckeditor5-paste-from-office/src/filters/bookmark.ts [hunk 2]
```diff
@@ -40,5 +41,15 @@ export function transformBookmarks(
...
 		writer.insertChild( index, children, element.parent! );
+
+		if ( isHiddenBookmarkAnchor( element ) ) {
+			writer.remove( element );
+		}
 	}
 }
+
+function isHiddenBookmarkAnchor( element: ViewElement ) {
+	const name = element.getAttribute( 'name' );
```
Comment (pszczesniak) [inline packages/ckeditor5-paste-from-office/src/filters/bookmark.ts:63]: We could add a comment here that MS Word do not use `id` just `name`.

File: packages/ckeditor5-paste-from-office/src/filters/bookmark.ts [hunk 3]
```diff
@@ -40,5 +41,15 @@ export function transformBookmarks(
...
 
 		writer.insertChild( index, children, element.parent! );
+
+		if ( isHiddenBookmarkAnchor( element ) ) {
+			writer.remove( element );
+		}
 	}
 }
+
+function isHiddenBookmarkAnchor( element: ViewElement ) {
```
Comment (pszczesniak) [inline packages/ckeditor5-paste-from-office/src/filters/bookmark.ts:62]: Maybe would be good to point that it's about MS bookmarks?? WDYT? 🤔 


```suggestion
function isHiddenMsBookmarkAnchor( element: ViewElement ) {
```

**Review by pszczesniak — CHANGES_REQUESTED** [review]
Overall it looks good :+1:

I would add two tests to `ckeditor5-paste-from-office/tests/filters/bookmark.js`:
 - removes anchor when name starts with `_`
 - preserves anchor when name does not start with `_`

File: packages/ckeditor5-paste-from-office/src/filters/bookmark.ts (hunk 3 above)
Comment (Mati365) [reply packages/ckeditor5-paste-from-office/src/filters/bookmark.ts:62]: I'd keep it more generic. Google Docs tends to create hidden bookmarks the same way (at least in ToC headings).

**Review by pszczesniak — APPROVED** [review]
