### PR TITLE
Tests should not depend on debug mode.

### LINKED ISSUE #13593: Change automated tests so that they do not rely on CK_DEBUG flags.
## Provide a description of the task

Code coverage on CI is failing from time to time, and removing `ck-debug-loader` seems to solve the problems. However, that makes some automated tests fail. Besides, automated tests should test production code anyway.

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Tests: Tests changed so that they do not depend on debug mode. Closes #13593.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Review by niegowski — APPROVED** [review]

**Comment by niegowski** [comment]
CI fails:

```
WARN: 'Detected `console.warn()`:', 'Cannot determine a proper selection range after insertion.'
```

**Review by niegowski — CHANGES_REQUESTED** [review]
```
WARN: 'Detected `console.warn()`:', 'Cannot determine a proper selection range after insertion.'
```

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 1]
```diff
@@ -2634,6 +2637,7 @@ describe( 'DataController utils', () => {
 				// <paragraph>{Ba}r</paragraph>
 				//
 				// <paragraph>{Ba}rfoo</paragraph>
+				testUtils.sinon.stub( console, 'warn' );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2640]: Please make sure that this is not permanent.
```js
testUtils.createSinonSandbox();
```
