### PR TITLE
Fix inconsistent marker boundary order v2

### LINKED ISSUE #19975: Incorrect order of adjacent marker boundary elements in editing downcast
Load content with adjacent markers in the model, e.g.:

```html
<p>
    Some content
    <custom-start name="type:1"></custom-start>
    more content
    <custom-end name="type:1"></custom-end>
    <custom-start name="type:2"></custom-start>
    followed by more content
    <custom-end name="type:2"></custom-end>
</p>
```

Register markers using markerToElement() in editingDowncast:

```ts
editor.conversion.for( 'editingDowncast' ).markerToElement( {
    model: 'custom',
    view: ( markerData, { writer } ) => {
        const parts = markerData.markerName.split( ':' );
        const [ , type, id ] = parts;
        const customId = `${ type }:${ id }`;

        const className = markerData.isOpening
            ? 'custom-label custom-label--start'
            : 'custom-label custom-label--end';

        return writer.createUIElement( 'div', {
            class: className,
            'data-custom-id': customId,
            'data-start': markerData.isOpening
        } );
    }
} );
```

Ensure two markers are adjacent in the model (end of one immediately followed by start of another).

Inspect the editing view (e.g. using CKEditor Inspector).

✔️ Expected result

Boundary elements are rendered in the same order as in the model:

[marker1-end][marker2-start]
❌ Actual result

Boundary elements are swapped in the editing view:

`[marker2-start][marker1-end]`

The model structure and editor.getData() output remain correct.

### PR DESCRIPTION
**Pull request by niegowski**
### 🚀 Summary

Fixes incorrect order of adjacent marker boundary elements in editing downcast.

---

### 📌 Related issues

* Closes #19975

---

### 💡 Additional information

Code from this PR was [previously merged](https://github.com/ckeditor/ckeditor5/pull/19995) and reverted because of invalid sorts of markers. In this PR, the sort was fixed.

---

### 🧾 Checklists

Use the following checklists to ensure important areas were not overlooked.
This does not apply to feature-branch merges.
If an item is **not relevant** to this type of change, simply leave it unchecked.

#### Author checklist

- [ ] Is the changelog entry intentionally omitted?
- [ ] Is the change backward-compatible?
- [ ] Have you considered the impact on different editor setups and core interactions? _(e.g., classic/inline/multi-root/many editors, typing, selection, paste, tables, lists, images, collaboration, pagination)_
- [ ] Has the change been manually verified in the relevant setups?
- [ ] Does this change affect any of the above?
- [ ] Is performance impacted?
- [ ] Is accessibility affected?
- [ ] Have tests been added that fail without this change (against regression)?
- [ ] Have the API documentation, guides, feature digest, and related feature sections been updated where needed?
- [ ] Have metadata files (ckeditor5-metadata.json) been updated if needed?
- [ ] Are there any changes the team should be informed about (e.g. architectural, difficult to revert in future versions or having impact on other features)?
- [ ] Were these changes documented (in Logbook)?

#### Reviewer checklist

- [ ] PR description explains the changes and the chosen approach (especially when  performance, API, or UX is affected).
- [ ] The changelog entry is clear, user‑ or integrator-facing, and it describes any breaking changes.
- [ ] All new external dependencies have been approved and mentioned in LICENSE.md (if any).
- [ ] All human-readable, translateable strings in this PR been introduced using `t()` (if any).
- [ ] I manually verified the change (e.g., in manual tests or documentation).
- [ ] The target branch is correct.

### CODE REVIEW

**Comment by pomek** [comment]
@niegowski, could you confirm that tests from Commercial are green, too? At least, AI and TC.

**Comment by niegowski** [comment]
> @niegowski, could you confirm that tests from Commercial are green, too? At least, AI and TC.

It reqired a slight change in TC test: https://github.com/ckeditor/ckeditor5-commercial/pull/9773

**Comment by pomek** [comment]
Thanks @niegowski. It's good to see that now we are prepared :D

File: packages/ckeditor5-engine/src/conversion/comparemarkers.ts [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+ */
+
+import type { ModelRange } from '../model/range.js';
+
+/**
+ * Sorts markers in a stable fashion so their addition order does not affect downcast output.
+ *
+ * Markers are ordered in reverse DOM order for non-intersecting ranges. For intersecting ranges,
+ * the start position is the primary sort key and the end position is the secondary sort key.
+ *
```
Comment (f1ames) [inline packages/ckeditor5-engine/src/conversion/comparemarkers.ts]: Do you think a few "visual" examples could benefit the docs so it's easier to see what the outcomes are for different cases?

File: packages/ckeditor5-engine/src/conversion/downcastdispatcher.ts [hunk 2]
```diff
@@ -200,8 +201,23 @@ export class DowncastDispatcher extends /* #__PURE__ */ EmitterMixin() {
...
+		//
+		// Example: replacing "old" with "new" creates two adjacent markers (delete + insert).
+		// With `markerToElement`, each boundary is a self-closing tag, so the processing
+		// order directly controls where they land at the shared boundary point:
+		//
+		//   Stable (reverse DOM order):   <DEL-START/>old<DEL-END/><INS-START/>new<INS-END/>
+		//   Unstable (insertion order):    <DEL-START/>old<INS-START/><DEL-END/>new<INS-END/>
+		//
+		// Non-intersecting ranges  → strict reverse DOM order.
+		// Intersecting ranges      → best-effort reverse DOM order (ambiguous by nature).
```
Comment (f1ames) [inline packages/ckeditor5-engine/src/conversion/downcastdispatcher.ts]: I have some slight doubts about the wording:
1. `Unstable` sorting usually means that the order of some pieces is random (could be different after each sort). Was it the case here? Or just the order was different than expected (so stable but invalid)?
2. ~What does "reverse DOM order" exactly mean? We use it in multiple places here, and I'm not fully sure how to understand it 🤔~ Ok, after looking into unit tests it's clear 😄 At least for non-intersecting markers, it's easy to understand without looking into the sorting algorithm.

**Review by f1ames — CHANGES_REQUESTED** [review]
Looking good 👍

Just some minor docs-related suggestions.

**Review by f1ames — APPROVED** [review]
👍
