### PR TITLE
Fixed compatibility issues with Paste from Office by skipping all comments

### LINKED ISSUE #10155: HTML comments: tests from `ckeditor5-paste-from-office` are failing
## Provide a description of the task

On HTML comment feature branch `ck/8822-html-comment` run `yarn test -f paste-from-office`.

There are multiple errors related to new view element `<$comment></$comment>`.

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (html-support): Fixed compatibility issues with Paste from Office by skipping all comments. Closes #10155.

### CODE REVIEW

File: packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js [hunk 1]
```diff
@@ -45,8 +45,11 @@ export default class GoogleDocsNormalizer {
 	 */
 	execute( data ) {
 		const writer = new UpcastWriter( this.document );
+		const { body } = data._parsedData;
```
Comment (ma2ciek) [inline packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js:48]: Maybe we could rename the `body` variable to `documentFragment` inside this method? All these names here are quite hard to distinguish like `data`, `data._parsedData`, `body`, `data.content` :smile:

File: packages/ckeditor5-paste-from-office/tests/pastefromoffice.js [hunk 2]
```diff
@@ -62,7 +62,12 @@ describe( 'PasteFromOffice', () => {
 
 				clipboard.fire( 'inputTransformation', data );
 
-				expect( data.isTransformedWithPasteFromOffice ).to.be.true;
+				expect( data._isTransformedWithPasteFromOffice ).to.be.true;
+				expect( data._parsedData ).to.have.property( 'body' );
+				expect( data._parsedData ).to.have.property( 'bodyString' );
+				expect( data._parsedData ).to.have.property( 'styles' );
+				expect( data._parsedData ).to.have.property( 'stylesString' );
```
Comment (ma2ciek) [inline packages/ckeditor5-paste-from-office/tests/pastefromoffice.js:69]: I'd replace it with a check that `data._parsedData` is an instance of view document fragment.

File: packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js (hunk 1 above)
Comment (psmyrek) [reply packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js]: Good point. I've renamed `body` to `documentFragment` and `bodyString` to `documentFragmentString` to be consistent.

File: packages/ckeditor5-paste-from-office/tests/pastefromoffice.js (hunk 2 above)
Comment (psmyrek) [reply packages/ckeditor5-paste-from-office/tests/pastefromoffice.js]: But `data._parsedData` is not an instance of the document fragment. It is just an object with 4 properties.

I've added an additional check for `data._parsedData.documentFragment` to assert that it is an instance of view document fragment.

File: packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js (hunk 1 above)
Comment (psmyrek) [reply packages/ckeditor5-paste-from-office/src/normalizers/googledocsnormalizer.js]: It turned out that I got it wrong and I shouldn't change all these properties as it will create a breaking change.

Now, I just used the `documentFragment` variable name inside `execute()` method in both normalizers.
