### PR TITLE
Fixed saving in HTML embed after it lost selection

### LINKED ISSUE #8328: Can't save an HTML embed after pasting a text from the editor
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a new HTML embed/edit the existing one.
2.  Select some text in the editor.
3.  Copy it.
4.  Paste it to the HTML embed.
5.  Save changes.

### ✔️ Expected result

Changes are saved.

### ❌ Actual result

Nothing happens.

## 📃 Other details

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (html-embed): Fixed saving in HTML embed after it lost selection. Closes #8328.

### CODE REVIEW

File: packages/ckeditor5-html-embed/src/htmlembedediting.js [hunk 1]
```diff
@@ -165,6 +166,14 @@ export default class HtmlEmbedEditing extends Plugin {
 						// If the value didn't change, we just cancel. If it changed,
 						// it's enough to update the model – the entire widget will be reconverted.
 						if ( newValue !== state.getRawHtmlValue() ) {
+							const selectedElement = model.document.selection.getSelectedElement();
+							const modelContainer = editor.editing.mapper.toModelElement( viewContainer );
+
+							// The HTML embed widget must be selected to be able to save new value.
+							if ( selectedElement !== modelContainer ) {
+								model.change( writer => writer.setSelection( modelContainer, 'on' ) );
+							}
```
Comment (niegowski) [inline packages/ckeditor5-html-embed/src/htmlembedediting.js:175]: I'm not sure if this is the right place for this. This widget focus behaves quite inconsistent (because of the `data-cke-ignore-events` feature, but it's needed in editing mode).

Have a look at this screencast:

While not in editing mode - click on the widget is handled by the [`mousedown` handler in the widget plugin](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-widget/src/widget.js#L187), but in the editing mode those events are blocked by `data-cke-ignore-events`. Maybe this should be handled in a similar way in this feature - the selection might be moved onto the widget before a button click was handled or a textarea focused?

**Review by niegowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-html-embed/src/htmlembedediting.js (hunk 1 above)
Comment (jodator) [reply packages/ckeditor5-html-embed/src/htmlembedediting.js:175]: That would solve other issues as well. I'm thinking about handling this in other PR (#8421).

Similar case: #8328.

File: packages/ckeditor5-html-embed/src/htmlembedediting.js [hunk 2]
```diff
@@ -165,6 +166,14 @@ export default class HtmlEmbedEditing extends Plugin {
 						// If the value didn't change, we just cancel. If it changed,
 						// it's enough to update the model – the entire widget will be reconverted.
 						if ( newValue !== state.getRawHtmlValue() ) {
+							const selectedElement = model.document.selection.getSelectedElement();
+							const modelContainer = editor.editing.mapper.toModelElement( viewContainer );
```
[the remark this answers is not in the document]
Comment (psmyrek) [reply packages/ckeditor5-html-embed/src/htmlembedediting.js]: You are right, I missed that.

File: packages/ckeditor5-html-embed/src/htmlembedediting.js (hunk 1 above)
Comment (psmyrek) [reply packages/ckeditor5-html-embed/src/htmlembedediting.js]: I've changed my solution basing on your comment (I hope I understood you correctly 😅), and I've added a `click` event listener on the `capture` phase to the wrapper to be able to move the selection onto the whole widget in the editing mode.

File: packages/ckeditor5-html-embed/src/htmlembedediting.js [hunk 3]
```diff
@@ -143,6 +143,21 @@ export default class HtmlEmbedEditing extends Plugin {
 					domContentWrapper = domElement;
 
 					renderContent( { domElement, editor, state, props } );
+
+					// Since there is a `data-cke-ignore-events` attribute set on the wrapper element in the editable mode,
+					// the explicit `click` handler on the `capture` phase is needed to move the selection onto the whole
+					// HTML embed widget.
+					domContentWrapper.addEventListener( 'click', () => {
```
Comment (pomek) [inline packages/ckeditor5-html-embed/src/htmlembedediting.js:150]: Wondering why couldn't we attach the listener on`textarea#focus`? Shouldn't it be easier?

Comment (niegowski) [reply packages/ckeditor5-html-embed/src/htmlembedediting.js:150]: In widgets, it's handled on `mousedown` so maybe we should do the same here? The click event is triggered on a `mouseup` so there is a visible difference in behavior.

Comment (psmyrek) [reply packages/ckeditor5-html-embed/src/htmlembedediting.js]: Done - the `click` event listener has been replaced with `mousedown` event listener.
