### PR TITLE
#9524: Selected inline widgets wrapped in an attribute in the view should create a fake selection

### LINKED ISSUE #9521: Linked image resize handlers do not refresh when converting block image to inline
## 📝 Provide detailed reproduction steps (if any)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #9524: Selected inline widgets wrapped in an attribute in the view should create fake selection
A generalization of https://github.com/ckeditor/ckeditor5/issues/9521.

ATM when a linked inline image gets selected, the selection is `[<a><span class="ck-widget"></span></a>]`. This is how engine works, selecting a linked text also results in `[<a>text</a>]`. 

This causes numerous issues with the logic depending on view selection `getSelectedElement()` (where `<a>` is returned instead of the widget). The main issue is that the selection is not fake, which affects accessibility and who-know-what-else – the widget plugin does not recognize as `[<a><span class="ck-widget"></span></a>]` a selected widget.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (widget): Selected inline widgets wrapped in an attribute in the view should create a fake selection. Closes #9524. Closes #9521.

### CODE REVIEW

File: packages/ckeditor5-widget/tests/widget.js [hunk 1]
```diff
@@ -228,6 +236,51 @@ describe( 'Widget', () => {
 		expect( viewDocument.selection.isFake ).to.be.true;
 	} );
 
+	it( 'should apply fake view selection when an inline widget is surrounded by an attribute element', () => {
```
Comment (niegowski) [inline packages/ckeditor5-widget/tests/widget.js:239]: Please add test for deeper nested `AttributeElements`.

Comment (oleq) [reply packages/ckeditor5-widget/tests/widget.js:242]: There you go 6fe4964.

**Review by niegowski — APPROVED** [review]
👍  LGTM
