### PR TITLE
Table multi-cell selection should not be possible with the keystrokes when the TableSelection plugin is disabled

### LINKED ISSUE #7483: Shift + Arrow key selects multiple cells while TableSelection is disabled
## 📝 Provide detailed reproduction steps (if any)

1.  Insert a table and put the caret in a table cell.
2.  Disable the Table Selection plugin - `editor.plugins.get('TableSelection').forceDisabled()`
3.  Select multiple cells using Shift + Arrow key.

### ✔️ Expected result

It's impossible to select multiple cells.

### ❌ Actual result

Cells are selected.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Table multi-cell selection should not be possible with the keystrokes when the TableSelection plugin is disabled. Closes #7483.

---

### Additional information

### CODE REVIEW

File: packages/ckeditor5-table/tests/tablekeyboard.js [hunk 1]
```diff
@@ -1277,6 +1277,30 @@ describe( 'TableKeyboard', () => {
 						downArrowDomEvtDataStub.shiftKey = true;
 					} );
 
+					it( 'should not expand the selection if TableSelection plugin is disabled', () => {
```
Comment (jodator) [inline packages/ckeditor5-table/tests/tablekeyboard.js:1280]:
```suggestion
					it( 'should move to the cell below if TableSelection plugin is disabled', () => {
```
