### PR TITLE
Fix native undo/redo functionality in source editing mode

### LINKED ISSUE #13700: Do it can undo or redo in source editing mode?
## Provide a description of the task
is it possible do undo /redo in source editing?
it look like only can do it after close souce code mode,

_What steps should be taken to fulfill the task?_

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

### PR DESCRIPTION
**Pull request by jacek-cke**
### 🚀 Summary

When source editing mode is active, the editor's keystroke handler intercepts Ctrl/Cmd+Z/Y and blocks native undo/redo in the textarea. This PR adds a keydown listener that stops propagation of these keystrokes before they reach the editor, restoring native browser undo/redo.

---

### 📌 Related issues

* Closes #13700

---

### 🧾 Checklists

Use the following checklists to ensure important areas were not overlooked.
This does not apply to feature-branch merges.
If an item is **not relevant** to this type of change, simply leave it unchecked.

#### Author checklist

- [ ] Is the changelog entry intentionally omitted?
- [x] Is the change backward-compatible?
- [ ] Have you considered the impact on different editor setups and core interactions? _(e.g., classic/inline/multi-root/many editors, typing, selection, paste, tables, lists, images, collaboration, pagination)_
- [ ] Has the change been manually verified in the relevant setups?
- [ ] Does this change affect any of the above?
- [ ] Is performance impacted?
- [ ] Is accessibility affected?
- [x] Have tests been added that fail without this change (against regression)?
- [ ] Have the API documentation, guides, feature digest, and related feature sections been updated where needed?
- [ ] Have metadata files (ckeditor5-metadata.json) been updated if needed?
- [ ] Are there any changes the team should be informed about (e.g. architectural, difficult to revert in future versions or having impact on other features)?
- [ ] Were these changes documented (in Logbook)?

#### Reviewer checklist

- [ ] PR description explains the changes and the chosen approach (especially when  performance, API, or UX is affected).
- [ ] The changelog entry is clear, user‑ or integrator-facing, and it describes any breaking changes.
- [ ] All new external dependencies have been approved and mentioned in LICENSE.md (if any).
- [ ] All human-readable, translateable strings in this PR been introduced using `t()` (if any).
- [ ] I manually verified the change (e.g., in manual tests or documentation).
- [ ] The target branch is correct.

### CODE REVIEW

**Comment by Reinmar** [comment]
Two findings:
* Cmd+Y does not redo (on macOS). CKEditor does that (we support both keystrokes:  Cmd+Y and Cmd+Shift+Z) so it may be slightly confusing that the former does not work in source area. We could try to plug a listener that tries to do `execCommand( 'redo' )` but only for macOS (because Ctrl+Y works already fine on Linux and Windows).
* When doing Cmd+Z on an empty undo stack, at least in Arc, this triggers a native Arc action (opens a previously closed tab). This might not be safely fixable because we'd need to do `preventDefault()` and that would stop native undo 🤷  And I'd avoid trying to use `execCommand()` here too (too unsafe).

**Review by Reinmar — CHANGES_REQUESTED** [review]
Let's try to fix the Cmd+Y scenario.

File: packages/ckeditor5-source-editing/src/sourceediting.ts [hunk 1]
```diff
@@ -266,6 +266,18 @@ export class SourceEditing extends Plugin {
 				editor.ui.update();
 			} );
 
+			// Allow native undo/redo in the textarea. The editor's keystroke handler (attached via
+			// setEditableElement()) intercepts Ctrl+Z/Y and calls preventDefault(), blocking browser
+			// undo/redo while editor commands are force-disabled in source editing mode.
+			// See: https://github.com/ckeditor/ckeditor5/issues/13700
+			domSourceEditingElementTextarea.addEventListener( 'keydown', evt => {
+				const key = evt.key.toLowerCase();
```
Comment (Reinmar) [inline packages/ckeditor5-source-editing/src/sourceediting.ts:277]: Missing a comment why it's needed here.

Comment (jacek-cke) [reply packages/ckeditor5-source-editing/src/sourceediting.ts:277]: Makes sense, added.

**Comment by jacek-cke** [comment]
> Let's try to fix the Cmd+Y scenario.

Fixed. Wondering if we should also cover the iOS/iPadOS case where a user might have a keyboard connected?

**Review by Reinmar — APPROVED** [review]

**Comment by Reinmar** [comment]
> > Let's try to fix the Cmd+Y scenario.
> 
> Fixed. Wondering if we should also cover the iOS/iPadOS case where a user might have a keyboard connected?

I think it's ok to keep the scope under control. There are dragons in adding more to it :D
