### PR TITLE
Ck/12467 insert content does not insert markers

### LINKED ISSUE #12467: model.insertContent() does not insert markers (added in a document fragment)
## 📝 Provide a description of the improvement

When `model.DocumentFragment` is inserted to the model using `model.insertContent()`, its children are inserted but markers saved in `model.DocumentFragment#markers` are skipped. They should be inserted as well.

Most probably here: https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/model/utils/insertcontent.ts#L90

The difficulty in this task is that we need to re-calculate the markers ranges. Additional difficulty is introduced by the fact that `model.insertContent()` may heavily affect the model, so re-calculation would be different depending on how some elements are split, merged, etc. I don't think that just "using math" will be enough.

One idea to simplify this calculations that I have is to add temporary, fake elements to the document fragment at the positions were marker boundaries are. Then, those elements would be inserted to the model together with regular children. After this is done, fake elements positions would be saved, the elements would be removed and markers would be added instead. I am not sure this method would be 100% accurate in all cases (e.g. when markers are at the beginning/end of the document fragment, or when the insertion causes massive splitting and merging in the document model).

The other idea is to handle markers in `insertion.handleNodes()` (maybe change the method name). Markers could be passed as second parameter and then processed in `Insertion` class as the nodes are inserted to the model. This way we could very precisely calculate new positions for markers boundaries.

I think the second idea would be more precise but it is probably tougher to implement. We can do it in two steps, first use fake nodes and then implement better solution if needed.

Another thing is that I wonder whether we should put it behind some kind of a flag for backward compatibility but I am leaning towards "no". At the moment, the markers are "silently dropped", so, yeah, we will introduce backward incompatibility. But will it be problematic?

1. In most cases you don't have any markers in the document fragment (or you don't even insert a document fragment). We noticed this problem only now, after long time and it was probably never raised by our users.
2. In cut/copy+paste, markers are removed earlier (probably during copy) and they are not available inside `insertContent()`. So this won't be a problem.
3. Internally, we use `insertContent()` in a couple of places. We can check if there's a possibility that in those places document fragment with marker might be inserted.
4. If the user has problems, the fix is very easy (just remove markers from document fragment before inserting it).
5. The fact that markers are skipped can be treated as a bug, actually. We can treat this as fixing incorrect behavior of `insertContent()`. If your document fragment has markers and you don't want them, remove them.

So, I propose no flag and marking this as minor breaking change + adding simple migration guide.

### PR DESCRIPTION
**Pull request by DawidKossowski**
### **Suggested merge commit message (**[**convention**](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html)**)**

Other (engine): `Model#insertContent()` will now insert markers added to `DocumentFragment#markers`. Closes #12467.

---

### **Additional information**

This improvement has been implemented to allow Import from Word plugin to work correctly.

### CODE REVIEW

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 1]
```diff
@@ -306,7 +358,7 @@ class Insertion {
 			return Range._createOn( this._nodeToSelect );
 		}
 
-		return this.model.schema.getNearestSelectionRange( this.position );
+		return this.model.schema.getNearestSelectionRange( this._affectedEnd ? this._affectedEnd.toPosition() : this.position );
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:361]: I wouldn't make the change here.

First, although it seems logical in most cases, I am not 100% sure that `this._affectedEnd` is always "same enough" as `this.position`. It seems it should be but it is not apparent from the code. Actually, the logic behind setting `this._affectedEnd` seems complicated. When `this._affectedEnd` is set, it is always set to `this.position` but then, `this.position` may change differently than `this._affectedEnd`.

Second, `getSelectionRange()` makes sense only straight after handling nodes insertion. Most probably it would even make more sense to return the selection range in `handleNodes()` rather than have a separate method. What happens in your code is this: you insert nodes, then you tinker with the inserted content outside of `Insertion` class and then you expect `Insertion` class to return correct results. It kind-of worked for you, because `this._affectedEnd` is a `LiveRange`, so it got updated after you removed the nodes.

But it is not a good design, as you make change in `Insertion` class that is triggered by a new functionality added in a different place. Unless it is a trivial change, an unavoidable change, or a bug we should solve it in a different place. It seems that results returned by `getSelectionRange()` make sense and there were no bugs related strictly to how `Insertion` class works.

Instead, you should reorganize the code, so that the new functionality (handling markers) solves the problem that it introduces. After all, the selection is wrong because we inserted and removed the fake elements:

1.  `handleNodes()`
2.  `let newRange = getSelectionRange()`
3.  if there are fake markers elements to handle:
    1.  create a new live range, same as the range returned by `getSelectionRange()`
    2.  remove fake elements, create markers
    3.  overwrite `newRange` with the live range (that will be updated in step 3.ii)

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 2]
```diff
@@ -1299,6 +1299,358 @@ describe( 'DataController utils', () => {
...
+
+				expect( getData( model ) )
+					.to.equal( '<paragraph>Bar[]foo</paragraph>' );
+
+				expect( expectedMarker ).to.exist;
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0, 0 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 0, 2 ] );
+			} );
+
+			it( 'should create collapsed marker after inserting paragraph at the beginning', () => {
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1365]: I am also missing a test where the collapsed marker is before/after paragraph, not only inside it.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 3]
```diff
@@ -1299,6 +1299,358 @@ describe( 'DataController utils', () => {
...
+				const expectedMarker = model.markers.get( 'comment-thread-1' );
+
+				expect( getData( model ) )
+					.to.equal( '<paragraph>foo</paragraph><paragraph>test<imageInline></imageInline>[]</paragraph>' );
+
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 1, 4 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 1, 5 ] );
+			} );
+
+			it( 'should create marker on imageInline after inserting when content is empty', () => {
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1494]: And block image into empty content.

**Review by scofalik — CHANGES_REQUESTED** [review]
Requested changes as in comments.

Regarding `getSelectionRange()` - similar problem may happen with `affectedRange` which is returned by `insertContent()`. In the test, you do not test this value (it is returned by `insertHelper()`). I am almost positive that `affectedRange` will be correct though, since it is made of live positions. But it would be nice to test it and be sure.

Regarding the unit tests. I am almost happy with the amount of test you prepared _for this category._ You prepared a lot of unit tests. I'd like to see a few more, as commented, because such core functionality must be heavily tested. But, in general, you considered a lot of different cases.

But, those tests are only from one category. All these tests are inserting inline content (text, inline image) into block-non-object element (paragraph). I don't feel like there are a lot of tests where marker is on whole `<paragraph>`, there are only few. I am also missing a simple test where we insert `[<paragraph>Bar</paragraph>]`. Other than that we need full suite of tests that will have markers on/around block-object element (block image). Then we need tests that insert paragraphs/text/inline images/block images:

*   insert next to paragraph
*   insert next to block image
*   insert next to/into paragraph which is in a block quote
*   insert into a limit element
*   insert at a place where insertion is forbidden (see "filtering out" suite)

We probably don't need to duplicate all the different scenarios that you already came up with for these configurations. But for each configuration we need at least a few tests. Finally, we need a test that inserts empty document fragment with a (collapsed) marker.

So, I see a potential for at least 30-40 more unit tests. I know it is a chore and writing tests requires a lot of creativity. But this is a core functionality. Please, try to look at the tests that are already existing for different configurations of pasted content / receiving content.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 4]
```diff
@@ -1299,6 +1299,358 @@ describe( 'DataController utils', () => {
...
+				const expectedNeastedMarker = model.markers.get( 'comment-thread-2' );
+
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0, 3 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 0, 5 ] );
+
+				expect( expectedNeastedMarker.getRange().start.path ).to.deep.equal( [ 0, 4 ] );
+				expect( expectedNeastedMarker.getRange().end.path ).to.deep.equal( [ 0, 6 ] );
+			} );
+
+			it( 'should create inline marker after inserting paragraph', () => {
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1442]: The same probably will happen if you test pasting `[<blockImage></blockImage>]` next to, or into `<paragraph>`.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 5]
```diff
@@ -1299,6 +1299,358 @@ describe( 'DataController utils', () => {
...
+
+				expect( getData( model ) )
+					.to.equal( '<paragraph>Foo<imageInline></imageInline></paragraph><paragraph>>bar[]</paragraph>' );
+
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0, 3 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 1, 2 ] );
+			} );
+
+			it( 'should create 500 markers', () => {
+				setData( model, '<paragraph>foo[]</paragraph>' );
```
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1640]: I wanted to check if nothing crashed when the number of markers is large

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 6]
```diff
@@ -1299,6 +1299,358 @@ describe( 'DataController utils', () => {
...
+			} );
+
+			it( 'should create marker which starts in paragraph and ends inside the beginning of next paragraph', () => {
+				setData( model, '<paragraph>Foo[]</paragraph>' );
+
+				insertHelper( '<paragraph>>bar</paragraph><paragraph></paragraph>', {
+					'comment-thread-1': { start: [ 0, 1 ], end: [ 1, 0 ] }
+				} );
+
+				const expectedMarker = model.markers.get( 'comment-thread-1' );
```
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1617]: My intention wasn't to check getData output and only check markers positions, because I created similar tests where I checked getData. Anyways, I will update it.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1473]: That's true. I also added test case with `blockImage`

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js]: I created multiple combinations with collapsed markers

**Comment by DawidKossowski** [comment]
@scofalik all done (I hope so...). You can review it again.

**Comment by DawidKossowski** [comment]
I forgot to mention that the issue with merging `$marker` element is still existing. We need to figure out how to fix it.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 7]
```diff
@@ -1299,6 +1299,1251 @@ describe( 'DataController utils', () => {
...
+				insertHelper( '<imageBlock></imageBlock>', {
+					'marker-a': { start: [ 0 ], end: [ 1 ] }
+				} );
+
+				const expectedMarker = model.markers.get( 'marker-a' );
+
+				// <paragraph><imageInline></imageInline></paragraph>[<imageBlock></imageBlock>]
+				expect( getData( model ) ).to.equal( '<paragraph><imageInline></imageInline></paragraph>[<imageBlock></imageBlock>]' );
+
+				// <paragraph><imageInline></imageInline>{</paragraph><imageBlock></imageBlock>}
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2032]: Test cases are good but most/all expects will need to be changed anyway after the solution is fixed.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 8]
```diff
@@ -1299,6 +1299,1251 @@ describe( 'DataController utils', () => {
...
+
+					// <paragraph>{}<imageInline></imageInline>()</paragraph><imageBlock></imageBlock>
+					expect( expectedMarkerA.getRange().start.path ).to.deep.equal( [ 0, 0 ] );
+					expect( expectedMarkerA.getRange().end.path ).to.deep.equal( [ 0, 0 ] );
+					expect( expectedMarkerB.getRange().start.path ).to.deep.equal( [ 0, 1 ] );
+					expect( expectedMarkerB.getRange().end.path ).to.deep.equal( [ 0, 1 ] );
+				} );
+			} );
+
+			it( 'should does not create marker when insertion is forbidden', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2424]:
```suggestion
			it( 'should not create marker when insertion is forbidden', () => {
```

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 9]
```diff
@@ -1299,6 +1299,1251 @@ describe( 'DataController utils', () => {
...
+				setData( model, '<wrapper><limit><paragraph>[]</paragraph></limit></wrapper>', {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2425]: Umm wait wait wait. Markers declaring should be in `insertHelper` not here :).

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 10]
```diff
@@ -1299,6 +1299,1251 @@ describe( 'DataController utils', () => {
...
+				}
+
+				insertHelper( '<paragraph>Bar</paragraph>', mockMarkers );
+
+				for ( let i = 0; i < 500; i++ ) {
+					expect( model.markers.get( `comment-thread-${ i }` ) ).to.exist;
+				}
+			} );
+
+			describe( 'affected range', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2455]: I thought you forgot about testing `affectedRange` :). I thought you will add these checks in current tests.

**Review by scofalik — CHANGES_REQUESTED** [review]
The testing suite is much better now.

Four things:

1.  Make sure that in tests like `setData( '[]<paragraph>Foo</paragraph>' )` the content is actually inserted at `[ 0 ]`, not `[ 0, 0 ]`.
2.  Fix expects.
3.  We need to fix problems when `$marker` is at the beginning or end of the document fragment. We already discussed that on Slack.
4.  I am missing a couple tests more:
    1.  Test for inserting `<image></image>[]<image></image>` - I expect that `$marker` elements in such inserted content may behave interestingly. Similar case for `<paragraph>`s.
    2.  I am not sure, maybe I missed it, do we have a test where we insert empty document fragment, just with marker(s)?
    3.  A few tests where marker is wholly or partially on filtered-out element, e.g. `{<limit><p>Foo</p></limit><p>B}ar</p>` added into another limit (I think this should be filtered).

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 11]
```diff
@@ -1299,6 +1299,1251 @@ describe( 'DataController utils', () => {
...
+			it( 'should create marker after inserting paragraph', () => {
+				setData( model, '<paragraph>foo[]</paragraph>' );
+
+				insertHelper( '<paragraph>Bar</paragraph>', {
+					'marker-a': { start: [ 0, 0 ], end: [ 0, 3 ] }
+				} );
+
+				const expectedMarker = model.markers.get( 'marker-a' );
+
+				// <paragraph>fooBar[]</paragraph>
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:1351]: Or maybe for better readability:

```
// <paragraph>foo[]</paragraph>
// <paragraph>{Bar}</paragraph>
//
// <paragraph>foo{Bar}</paragraph>
```

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 12]
```diff
@@ -88,7 +116,35 @@ export default function insertContent(
...
+
+			for ( const [ name, [ start, end ] ] of Object.entries( markersData ) ) {
+				writer.addMarker( name, {
+					usingOperation: true,
+					affectsData: true,
+					range: new Range( start, end )
+				} );
+			}
+
+			newRange = markerRange && markerRange.toRange();
```
[the remark this answers is not in the document]
Comment (scofalik) [reply packages/ckeditor5-engine/src/model/utils/insertcontent.ts:146]: Also `markerRange` doesn't seem like a correct name. `selectionLiveRange` is better. It also has `liveRange` in it, so when you see it you instantly know that you need to detach live range :D.

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 13]
```diff
@@ -88,7 +116,35 @@ export default function insertContent(
 
 		insertion.handleNodes( nodesToInsert );
 
-		const newRange = insertion.getSelectionRange();
+		let newRange = insertion.getSelectionRange();
+
+		if ( fakeMarkerElements.length ) {
+			const markerRange = newRange && LiveRange.fromRange( newRange );
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:122]: For readability reasons, I'd prefer `= newRange ? LiveRange.fromRange( newRange ) : null`.

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 14]
```diff
@@ -85,21 +85,28 @@ export default function insertContent(
...
 				} );
 			}
 
 			markersPosition.sort( ( { position: posA }, { position: posB } ) => posA.isBefore( posB ) ? 1 : -1 );
 
 			for ( const { position, name } of markersPosition ) {
-				const fakeElement = writer.createElement( '$marker', { 'data-name': name } );
+				let fakeElement = null;
+				const isBeginning = position.path.length === 1 && position.path[ 0 ] === 0;
+				const isEnding = position.path.length === 1 && position.path[ 0 ] === content.childCount;
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:104]: `content.maxOffset`. But you should also be able to use `Position#isAtEnd()` 🤔.

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 15]
```diff
@@ -449,6 +490,8 @@ class Insertion {
 
 		const livePosition = LivePosition.fromPosition( this.position, 'toNext' );
 
+		this._positionBeforeFirstInsert = livePosition.toPosition();
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:493]: This has to be set only if it hasn't been set before.

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts (hunk 14 above)
Comment (scofalik) [reply packages/ckeditor5-engine/src/model/utils/insertcontent.ts:104]: I think I'd go with `position.parent === content && position.isAtStart` and `position.isAtEnd`. Will be more clear what is going on here.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 9 above)
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2425]: What do you mean? Markers are sent in the second parameter

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 10 above)
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2614]: Can we stay with these tests?

**Comment by DawidKossowski** [comment]
@scofalik it's ready to review. However, there are still issues that we discussed and will be fixed in the following tasks:
1. We use `affectedRange` to calculate starting and ending markers' positions. It causes that sometimes markers are created in the wrong place (like inserting imageBlock inside paragraph):
```
// <paragraph>Fo[]o</paragraph>
// {<imageBlock></imageBlock>}
//
// <paragraph>Fo{</paragraph><imageBlock></imageBlock><paragraph>}o</paragraph>
```

2. Sometimes, when we set the custom selection the resulting insertion is wrong (it's not connected to markers):
```
setData( model, '<imageBlock></imageBlock>[]<imageBlock></imageBlock>' );

insertHelper( '<imageBlock></imageBlock>', null, [ 1 ] );

expect( getData( model ) ).to.equal( '[<imageBlock></imageBlock>]<imageBlock></imageBlock><imageBlock></imageBlock>' );
```

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 16]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 1 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 2 ] );
+			} );
+
+			it( 'should create marker on imageBlock and imageInline after inserting', () => {
+				// <paragraph>[]</paragraph>
+				// {<imageBlock></imageBlock><imageInline></imageInline>}
+				//
+				// {<imageBlock></imageBlock><paragraph><imageInline></imageInline></paragraph>}
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2133]: This is an interesting, although rather not probable case. Interesting as it is one big marker and the inline image will need to be paragraphed, so the marker has to be on `<paragraph>` but it does not have to be on `</paragraph>`.

I think this will get also fixed when we will change from basing on `affectedRange` to some more precise solution.

Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2133]: For the moment, I don't care much about this scenario as I think it will change. You can leave it like this (and it should start failing after we improve our solution).

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 17]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 2 ] );
+			} );
+
+			it( 'should create marker on imageBlock after inserting in block quoted paragraph', () => {
+				// <blockQuote><paragraph>f[]oo</paragraph></blockQuote>
+				// {<imageBlock></imageBlock>}
+				//
+				// <blockQuote><paragraph>f{</paragraph><imageBlock></imageBlock>}<paragraph>oo</paragraph></blockQuote>
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2152]: Change expect + off.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 18]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+
+					expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0, 3 ] );
+					expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 0, 3 ] );
+				} );
+
+				it( 'should create collapsed marker after inserting imageInline next to paragraph', () => {
+					// <paragraph>foo</paragraph>[]
+					// {}<imageInline></imageInline>
+					//
+					// <paragraph>foo[]</paragraph>{<paragraph><imageInline></imageInline></paragraph>}
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2426]: It should either be before `<paragraph>` or before `<imageInline>` but not like this. AFAICS, the expect is correct but the comment is wrong.

Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2426]: The question here is what behavior we see as correct regarding the positioning of the collapsed marker, i.e., should it be at the beginning of inserted content, or should it stay next to element that it was in the original content.

In other words, what is correct: `{}<paragraph><imageInline>` or `<paragraph>{}<imageInline>`. I believe the second one and we can see what will happen to this test after we improve the solution.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 19]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+
+					expect( getData( model ) ).to.equal( '<paragraph>f</paragraph>[<imageBlock></imageBlock>]<paragraph>oo</paragraph>' );
+
+					expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0, 1 ] );
+					expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 0, 1 ] );
+				} );
+
+				it( 'should create collapsed marker after inserting imageBlock at the end of paragraph', () => {
+					// <paragraph>foo[]</paragraph>
+					// {}<imageBlock></imageBlock>
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2500]: Interesting that in this case it was moved out of the paragraph, but in previous case it stayed in the paragraph.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 20]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+
+					const expectedMarker = model.markers.get( 'marker-a' );
+
+					expect( getData( model ) ).to.equal( '<paragraph>foo[]</paragraph><imageBlock></imageBlock>' );
+
+					expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 1 ] );
+					expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 1 ] );
+				} );
+
+				it( 'should create collapsed marker after inserting imageBlock before paragraph', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2536]: In general, I miss some tests where `{}` is at the end of pasted content. Like this test, but `{}` after `</imageBlock>`.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 21]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+					expect( getData( model ) ).to.equal( '<paragraph><imageInline></imageInline></paragraph>[<imageBlock></imageBlock>]' );
+
+					expect( expectedMarkerA.getRange().start.path ).to.deep.equal( [ 0, 0 ] );
+					expect( expectedMarkerA.getRange().end.path ).to.deep.equal( [ 0, 0 ] );
+					expect( expectedMarkerB.getRange().start.path ).to.deep.equal( [ 0, 1 ] );
+					expect( expectedMarkerB.getRange().end.path ).to.deep.equal( [ 0, 1 ] );
+				} );
+			} );
+
+			it( 'should not create marker after inserting empty document fragment', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2579]: Why not? IMO it should.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 22]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+				const expectedMarker = model.markers.get( 'marker-a' );
+
+				expect( getData( model ) ).to.equal( '<paragraph>fo[]o</paragraph>' );
+
+				expect( expectedMarker ).to.be.null;
+			} );
+
+			it( 'should not create marker when insertion is forbidden', () => {
+				// <wrapper><limit><paragraph>[]</paragraph></limit></wrapper>
+				// {<wrapper><limit><paragraph>foo</paragraph></limit></wrapper>}
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2599]: Here is a more interesting example but, in the end, similar to the one before. In this case it is more discussable whether the marker should be added or not.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 23]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+
+				const expectedMarker = model.markers.get( 'marker-a' );
+
+				expect( getData( model ) ).to.equal( '<wrapper><limit><paragraph>Bar[]</paragraph></limit></wrapper>' );
+
+				expect( expectedMarker.getRange().start.path ).to.deep.equal( [ 0, 0, 0 ] );
+				expect( expectedMarker.getRange().end.path ).to.deep.equal( [ 0, 0, 0, 2 ] );
+			} );
+
+			it( 'should not create marker that is next to forbidden content', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2635]: Test name looks incorrect given that the marker is added.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 10 above)
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2694]: My problem is that these test cover much less scenarios than the rest of the test you added. And it will be easier to add `affectedRange` checks to the tests you wrote above, than to recreated those scenarios here.

Our current solution looks like it should not change `affectedRange`. I would be fine with adding tests for `affectedRange` in a followup issue. In this case, we can leave this tests suite, add an issue and when solving that new issue, we will remove this suite and make `affectedRange` checks in other markers-related tests.

BTW. It may be easier for you to check `affectedRange` if you use `stringify()` (from the same file as `getData()`). You can pass there a range that should be printed. It would be also easier for checking markers. I should have pointed this out earlier :(.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 24]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+					} );
+
+					expect( affectedRange.start.path ).to.deep.equal( [ 0 ] );
+					expect( affectedRange.end.path ).to.deep.equal( [ 1 ] );
+				} );
+			} );
+		} );
+	} );
+
+	describe( 'integration with limit elements', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2788]: Just to confirm: you didn't change anything here but the GH diff got it incorrectly?

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js [hunk 25]
```diff
@@ -1299,128 +1302,1629 @@ describe( 'DataController utils', () => {
...
+			doc.selection;
+
+		const markersMap = new Map();
+
+		if ( typeof content == 'string' ) {
+			content = parse( content, model.schema, {
+				context: [ '$clipboardHolder' ]
+			} );
+
+			if ( markers && !content.markers ) {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2913]:
```suggestion
			if ( markers && !content.is( 'documentFragment' ) ) {
```

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 26]
```diff
@@ -77,9 +78,50 @@ export default function insertContent(
 		}
 
 		const insertion = new Insertion( model, writer, selection.anchor! );
+		const markersPosition = [];
+		const fakeMarkerElements = [];
 
 		let nodesToInsert: any;
 
+		if ( content.is( 'documentFragment' ) && content.markers ) {
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:86]: We could merge this `if` with the one below:

```javascript
if ( content.is( 'documentFragment' ) ) {
	nodesToInsert = content.getChildren();
	
	if ( content.markers ) {
		...
	}
}
```

**Review by scofalik — CHANGES_REQUESTED** [review]

**Comment by scofalik** [comment]
Regarding your previous post:

1.  Please create an issue to improve current solution. Title: "`insertContent()` should not depend on affected range when inserting markers".
2.  I think this happens because in `setData()` (or rather: just after) the selection is autofixed to `[<imageBlock></imageBlock>]<imageBlock></imageBlock>`. After you insert between the paragraphs, it does not affect document selection in any way. Since you passed the selection by hand to `insertContent()`, `insertContent()` does not change the document selection either. So, everything looks good here, after all.

**Comment by scofalik** [comment]
What about a case where marker starts in filtered content but ends in non-filtered content (and vice versa)?

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 27]
```diff
@@ -88,7 +130,52 @@ export default function insertContent(
...
+					if ( markersData[ name ] ) {
+						markersData[ name ].push( elementPosition );
+					} else {
+						markersData[ name ] = [ elementPosition ];
+					}
+
+					writer.remove( element );
+				} else {
+					if ( markersData[ name ] ) {
+						markersData[ name ].push( collapsed ? rangeBetweenInsertion[ collapsed ] : rangeBetweenInsertion.end );
```
[the remark this answers is not in the document]
Comment (DawidKossowski) [reply packages/ckeditor5-engine/src/model/utils/insertcontent.ts:159]: `collapsed` variable can have 3 possible values:  `false`, `'start'`, `'end'`. Based on those values I determine the position of collapsed markers

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 24 above)
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2788]: That's true. I didn't change those tests. Screenshot:

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 19 above)
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2500]: It's since in the previous example the insertion of `imageBlock` split the original paragraph into two and `affectedRange` starts from the beginning of the first split paragraph.  
  
In that case the `imageBlock` element is inserted just after the paragraph even if the selection is inside.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 18 above)
Comment (DawidKossowski) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js:2426]: I updated this test and the answer is the first one: `{}<paragraph><imageInline>`

**Comment by DawidKossowski** [comment]
@scofalik you can take a look at it again.

File: packages/ckeditor5-engine/tests/model/utils/insertcontent.js (hunk 18 above)
Comment (scofalik) [reply packages/ckeditor5-engine/tests/model/utils/insertcontent.js]: :+1:, I expected this to end up as `{}<paragraph>`, what I meant by "correct" is what we want to achieve / what is the user's expected behavior.

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 28]
```diff
@@ -77,18 +78,111 @@ export default function insertContent(
...
+				markersPosition.sort( ( { position: posA }, { position: posB } ) => posA.isBefore( posB ) ? 1 : -1 );
+
+				for ( const { position, name, isCollapsed } of markersPosition ) {
+					let fakeElement = null;
+					let collapsed = null;
+					const isBeginning = position.parent === content && position.isAtStart;
+					const isEnding = position.parent === content && position.isAtEnd;
+
+					if ( !isBeginning && !isEnding ) {
+						fakeElement = writer.createElement( '$marker', { 'data-name': name } );
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:112]: Since this is not an HTML element, you can simply use "name" as the attribute ... name. Nothing bad should happen.

Comment (scofalik) [reply packages/ckeditor5-engine/src/model/utils/insertcontent.ts:112]: BTW. it seems that you don't even read the name stored in this attribute :D.

**Review by scofalik — CHANGES_REQUESTED** [review]
I added one more comment and I have one more request.

This new code in `insertContent()` handles some complicated logic. There are some tricky cases that we cover. I would expect that this new code has several comments with explanations why we are doing this or that, what will happen next, what is the whole idea of handling the markers.

Other than that, LGTM.

We have two issues that we need to create tickets for: using `affectedRange` and markers on filtered content.

**Comment by scofalik** [comment]
@arkflpc Could you look at it from TS perspective?

File: packages/ckeditor5-engine/src/model/utils/insertcontent.ts [hunk 29]
```diff
@@ -77,18 +78,111 @@ export default function insertContent(
...
 		}
 
 		insertion.handleNodes( nodesToInsert );
 
-		const newRange = insertion.getSelectionRange();
+		let newRange = insertion.getSelectionRange();
+
+		if ( content.is( 'documentFragment' ) && fakeMarkerElements.length ) {
+			const selectionLiveRange = newRange ? LiveRange.fromRange( newRange ) : null;
+			const markersData: Record<string, Array<Position>> = {};
```
Comment (arkflpc) [inline packages/ckeditor5-engine/src/model/utils/insertcontent.ts:137]: I'd rather use `Position[]` instead of `Array<Position>`. It would be consistent with the rest of `engine`. We decided not to force any convention (see [comment](https://github.com/ckeditor/ckeditor5/issues/11719#issuecomment-1148731592)), so it is up to you.
