### PR TITLE
Internal (image): Add `loading=lazy` to images with `sources` attribute.

### LINKED ISSUE #17865: Add `loading=lazy` to all images with `width` and `height` attribute
We recently made a change to add the `loading="lazy"` attribute to images with `width` and `height` attributes.

Unfortunately, it doesn't work for some images because of the early exit in code: https://github.com/ckeditor/ckeditor5/blob/5d01baf4f54b1e85cba3aed9d46d7e856f227ade/packages/ckeditor5-image/src/imagesizeattributes.ts#L155-L158

An example is image added using CKBox.

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal (image): Add `loading=lazy` to images with `sources` attribute. Closes #17865.

---

### Additional information

:warning: This PR targets the `release` branch :warning:

### CODE REVIEW

**Review by mmotyczynska — APPROVED** [review]
Your change does not affect the case for aspect-ratio, so there is a 🟢 from me.

File: packages/ckeditor5-image/src/imagesizeattributes.ts [hunk 1]
```diff
@@ -164,17 +172,8 @@ export default class ImageSizeAttributes extends Plugin {
...
-
-				if ( !width || !height ) {
-					return;
-				}
-
-				viewWriter.setStyle( 'aspect-ratio', `${ width }/${ height }`, img );
-
-				if ( isEditingDowncast ) {
-					viewWriter.setAttribute( 'loading', 'lazy', img );
+				if ( hasSizes ) {
```
Comment (niegowski) [inline packages/ckeditor5-image/src/imagesizeattributes.ts:175]:
```suggestion
				if ( hasSizes && isEditingDowncast ) {
```

**Review by pszczesniak — APPROVED** [review]
All works as expected :+1:
