### PR TITLE
Fixed emoji config marker already used warning in Revision History.

### LINKED ISSUE #6980: Consider making eslint-config-ckeditor5 a scoped package
Right after I published eslint-config-ckeditor5 I found in an issue (https://github.com/eslint/eslint/issues/3123) that configs can be scoped packages too.

I don't think it's worth to make our config a scoped `@ckeditor/eslint-config` (because most configs are not scoped), but I'll be wondering in the future why I chose to make it unscoped, so the answer is – I didn't know it can be scoped ;).

### PR DESCRIPTION
**Pull request by martnpaneq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Fixed emoji config marker already used warning in Revision History. Closes cksource/ckeditor5-commercial#6980.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-emoji/src/emojimention.ts [hunk 1]
```diff
@@ -81,9 +81,21 @@ export default class EmojiMention extends Plugin {
...
+		this._setupMentionConfiguration( editor );
+	}
+
+	/**
+	 * Initializes the configuration for emojis in the mention feature.
+	 * If the marker used by emoji mention is already registered, it displays a warning.
+	 * If emoji mention configuration is detected, it does not register it for a second time.
+	 */
+	private _setupMentionConfiguration( editor: Editor ) {
+		const mentionFeedsConfigs = editor.config.get( 'mention.feeds' )! as Array<EmojiMentionFeed>;
```
Comment (martnpaneq) [inline packages/ckeditor5-emoji/src/emojimention.ts:93]: I'm not sure if I'm supposed to use `editor.config.get( 'mention.feeds' )` and `editor.config.get( 'mergeFields.prefix' )!` outside of a constructor method. I'm doing it, because it's hard to meet the coverage without it, and also I have seen some examples in the ckeditor5 code that do the same.

Comment (filipsobol) [reply packages/ckeditor5-emoji/src/emojimention.ts:93]: It's fine :+1:

File: packages/ckeditor5-emoji/src/emojimention.ts [hunk 2]
```diff
@@ -81,9 +81,21 @@ export default class EmojiMention extends Plugin {
...
 		const mergeFieldsPrefix = editor.config.get( 'mergeFields.prefix' )! as string;
-		const markerAlreadyUsed = mentionFeedsConfigs.some( config => config.marker === EMOJI_MENTION_MARKER );
+		const isEmojiMarkerAlreadyAdded = mentionFeedsConfigs.find( config => config._isEmojiMarker );
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/src/emojimention.ts:95]: `mentionFeedsConfigs.some()` fits better, as we want `boolean` here.

File: packages/ckeditor5-emoji/src/emojimention.ts [hunk 3]
```diff
@@ -81,9 +81,21 @@ export default class EmojiMention extends Plugin {
...
+		const markerAlreadyUsed = mentionFeedsConfigs
+			.filter( config => !config._isEmojiMarker )
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/src/emojimention.ts:97]: Commenting out this line `.filter( config => !config._isEmojiMarker )` causes that all tests still pass correctly, so probably one more unit test is needed.

File: packages/ckeditor5-emoji/tests/emojimention.js [hunk 4]
```diff
@@ -133,6 +134,24 @@ describe( 'EmojiMention', () => {
 			editorElement.remove();
 		} );
 
+		it( 'should not modify mention feed when emoji plugin is already in mention feeds', async () => {
+			const editorElement = document.createElement( 'div' );
+			document.body.appendChild( editorElement );
+
+			const editor = await ClassicTestEditor.create( editorElement, {
+				plugins: [ EmojiMention, Mention ]
+			} );
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/tests/emojimention.js:143]: Creating a test editor in this way causes that real `EmojiDatabase` is loaded, so real `fetch()` call to CDN is performed.

File: packages/ckeditor5-emoji/tests/emojimention.js [hunk 5]
```diff
@@ -133,6 +134,24 @@ describe( 'EmojiMention', () => {
 			editorElement.remove();
 		} );
 
+		it( 'should not modify mention feed when emoji plugin is already in mention feeds', async () => {
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/tests/emojimention.js:137]:
```suggestion
		it( 'should not update the mention configuration when emoji configuration is already added', async () => {
```

**Review by psmyrek — COMMENTED** [review]
It works 🎉 

---

I noticed a few things that made it difficult for me to quickly understand the fix, so I would like to propose my version of the `_setupMentionConfiguration()` function, where:

- The names of boolean variables that check similar things, have the same beginning of the name: `isEmojiMarkerUsedByMergeFields`, `isEmojiMarkerUsedByMention`.

- A few blank lines help grouping similar things together mentally.

- Variables are created only when they are needed: `isEmojiConfigDefined` after logging a potential warning.

<details>

<summary> See the proposed _setupMentionConfiguration() function</summary>

```js
private _setupMentionConfiguration( editor: Editor ) {
    const mergeFieldsPrefix = editor.config.get( 'mergeFields.prefix' )! as string;
    const mentionFeedsConfigs = editor.config.get( 'mention.feeds' )! as Array<EmojiMentionFeed>;

    const isEmojiMarkerUsedByMergeFields = mergeFieldsPrefix ? mergeFieldsPrefix[ 0 ] === EMOJI_MENTION_MARKER : false;
    const isEmojiMarkerUsedByMention = mentionFeedsConfigs
        .filter( config => !config._isEmojiMarker )
        .some( config => config.marker === EMOJI_MENTION_MARKER );

    if ( isEmojiMarkerUsedByMention || isEmojiMarkerUsedByMergeFields ) {
        /**
         * The `marker` in the `emoji` config is already used by other plugin configuration.
         *
         * @error emoji-config-marker-already-used
         * @param {string} marker Used marker.
         */
        logWarning( 'emoji-config-marker-already-used', { marker: EMOJI_MENTION_MARKER } );

        return;
    }

    const isEmojiConfigDefined = mentionFeedsConfigs.some( config => config._isEmojiMarker );

    if ( isEmojiConfigDefined ) {
        return;
    }

    const emojiMentionFeedConfig = {
        _isEmojiMarker: true,
        marker: EMOJI_MENTION_MARKER,
        dropdownLimit: this._emojiDropdownLimit,
        itemRenderer: this._customItemRendererFactory( this.editor.t ),
        feed: this._queryEmojiCallbackFactory()
    };

    this.editor.config.set( 'mention.feeds', [ ...mentionFeedsConfigs, emojiMentionFeedConfig ] );
}
```

</details>

This is just my personal feeling after doing the review in the morning 😄

**Comment by pomek** [comment]
Note: We will be merging this change to the `#release` branch as I am preparing TP now.

File: packages/ckeditor5-emoji/src/emojimention.ts (hunk 3 above)
Comment (pomek) [reply packages/ckeditor5-emoji/src/emojimention.ts:97]: Let's create two editors, but the second one uses a configuration ('mention.feeds') from the first one. Both must load the `EmojiMention` plugin. This way it should verify the fix and confirm that we fix the issue.

Comment (martnpaneq) [reply packages/ckeditor5-emoji/src/emojimention.ts:98]: Added in [61774d6](https://github.com/ckeditor/ckeditor5/pull/17826/commits/61774d6abb6decd570dea22415700995f91c5266)

File: packages/ckeditor5-emoji/tests/emojimention.js [hunk 6]
```diff
@@ -195,6 +196,162 @@ describe( 'EmojiMention', () => {
...
+		const editorElement = document.createElement( 'div' );
+		const editor1Element = document.createElement( 'div' );
+		document.body.appendChild( editorElement );
+
+		const editor = await ClassicTestEditor.create( editorElement, {
+			plugins: [ EmojiMention, Mention ],
+			substitutePlugins: [ EmojiDatabaseMock ]
+		} );
+
+		const editor1 = await ClassicTestEditor.create( editorElement, {
```
Comment (pomek) [inline packages/ckeditor5-emoji/tests/emojimention.js:209]:
```suggestion
		const editor1 = await ClassicTestEditor.create( editor1Element, {
```

Comment (martnpaneq) [reply packages/ckeditor5-emoji/tests/emojimention.js]: Fixed in [0e071f6](https://github.com/ckeditor/ckeditor5/pull/17826/commits/0e071f61f260d4c85e2311852622560bae43f695)

File: packages/ckeditor5-emoji/tests/emojimention.js [hunk 7]
```diff
@@ -195,6 +196,163 @@ describe( 'EmojiMention', () => {
...
+
+			// Should not call console warn when there are no mention or merge fields configs defined.
+			expect( consoleWarnStub.callCount ).to.equal( 0 );
+			expect( editor.config.get( 'mention.feeds' ).length ).to.equal( 1 );
+
+			await editor.destroy();
+			editorElement.remove();
+		} );
+
+		it( 'should call console warn when merge fields config uses `:` prefix', async () => {
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/tests/emojimention.js:259]: These 3 tests (starting from line 259) to check warning in the console are already covered earlier, see:
- "should not update the mention configuration when the : character is already used",
- "should not update the mention configuration when the Merge fields feature use the : character".

File: packages/ckeditor5-emoji/tests/emojimention.js [hunk 8]
```diff
@@ -195,6 +196,163 @@ describe( 'EmojiMention', () => {
...
+				substitutePlugins: [ EmojiDatabaseMock ],
+				mergeFields: {
+					prefix: ':'
+				}
+			} );
+
+			expect( editor.config.get( 'mention.feeds' ).length ).to.equal( 0 );
+			expect( consoleWarnStub.callCount ).to.equal( 1 );
+
+			editor.plugins.get( 'EmojiMention' )._setupMentionConfiguration( editor );
```
Comment (psmyrek) [inline packages/ckeditor5-emoji/tests/emojimention.js:274]: Calling `_setupMentionConfiguration()` to check if emoji config is not added again is already checked in test "should not call console warn when no additional mention or merge fields config is defined".

This `_setupMentionConfiguration()` is unnecessarily executed in these 3 new tests.

File: packages/ckeditor5-emoji/tests/emojimention.js (hunk 7 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/tests/emojimention.js]: Removed redundant tests in [3a50d9a](https://github.com/ckeditor/ckeditor5/pull/17826/commits/3a50d9af558b4047a3f132e651e37698a49e74e3)

File: packages/ckeditor5-emoji/tests/emojimention.js (hunk 8 above)
Comment (martnpaneq) [reply packages/ckeditor5-emoji/tests/emojimention.js]: Removed redundant tests in [3a50d9a](https://github.com/ckeditor/ckeditor5/pull/17826/commits/3a50d9af558b4047a3f132e651e37698a49e74e3)

**Review by psmyrek — APPROVED** [review]
LGTM 🎉
