### PR TITLE
Focus issue

### LINKED ISSUE #12967: Focus issue on Chromium
## 📝 Provide detailed reproduction steps (if any)

Chromium sends the \`focus\` event before the \`selectionchange\` event, which leads to rendering with the old selection state.

## 📃 Other details

*   Browser: Edge and Chrome (Chromium)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by DawidKossowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (engine): Introducing a new flag to prevent rendering on Chrome before changing the selection. Closes #12967.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-engine/src/view/document.ts [hunk 1]
```diff
@@ -96,6 +97,19 @@ export default class Document extends BubblingEmitterMixin( ObservableMixin() )
...
+		 *
+		 * This property has been introduced due to the different behaviors on browsers.
+		 * Chromium sends the focus event before the changeselection which causes the renders with the old selection.
+		 * This flag is used to prevent rerenders when the focus is in progress and we are still waiting for new value.
+		 *
+		 * @readonly
+		 * @observable
+		 * @member {Boolean} module:engine/view/document~Document#isFocusChanging
+		 */
+		this.set( 'isFocusChanging', false );
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/view/document.ts:111]:
```suggestion
		/**
		 * Set to `true` if the document is in the process of setting the focus.
		 *
		 * To be precise, there are two browser events that we care about: `focus` and `selectionchange`. 
		 *
		 * Different browsers handle them differently. Chromium sends the `focus` event before the
		 * `selectionchange` event, which leads to rendering with the old selection state.
		 *
		 * The flag is used to prevent rendering when setting the focus is in progress
		 * and we are waiting for the new value.
		 *
		 * @readonly
		 * @observable
		 * @member {Boolean} module:engine/view/document~Document#isFocusChanging
		 */
		this.set( 'isFocusChanging', false );
```

File: packages/ckeditor5-engine/src/view/renderer.ts [hunk 2]
```diff
@@ -901,6 +910,13 @@ export default class Renderer extends ObservableMixin() {
 			return;
 		}
 
+		// The focus is still in progress and we are waiting for new values from changeselection event.
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/view/renderer.ts:913]:
```suggestion
		// The focus is still in progress and we are waiting for new values from selectionchange event.
```

File: packages/ckeditor5-engine/src/view/renderer.ts [hunk 3]
```diff
@@ -901,6 +910,13 @@ export default class Renderer extends ObservableMixin() {
...
+		// In that case, we need to prevent update selection since it would be updated using old values.
+		// It's related to: https://github.com/cksource/collaboration-features/issues/4722
+		if ( this.isFocusChanging ) {
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/view/renderer.ts:916]:
```suggestion
		if ( this.isFocusChanging ) {
```

File: packages/ckeditor5-engine/src/view/renderer.ts [hunk 4]
```diff
@@ -134,6 +135,14 @@ export default class Renderer extends ObservableMixin() {
 		 */
 		this.set( 'isFocused', false );
 
+		/**
+		 * Indicates if the view document is changing the focus and selection can be rendered.
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/view/renderer.ts:139]:
```suggestion
		 * Indicates if the view document is changing the focus (`true`) and selection rendering should be prevented.
```

**Review by scofalik — CHANGES_REQUESTED** [review]
Please make the flag internal (pre-TS `protected`).

**Comment by scofalik** [comment]
Also, please update files in `_src` with JSDoc.

**Comment by DawidKossowski** [comment]
@scofalik - done

**Review by scofalik — APPROVED** [review]

**Comment by scofalik** [comment]
LGTM. @niegowski could you review this test? https://github.com/ckeditor/ckeditor5/pull/12898/files#diff-27194246929928fe0b02d2cb3b079333c579de2c607abc61561dc271bf02f766R5409-R5460

File: packages/ckeditor5-engine/tests/view/renderer.js [hunk 5]
```diff
@@ -5395,6 +5405,59 @@ describe( 'Renderer', () => {
 				expect( domSelection.getRangeAt( 0 ).startOffset ).to.equal( 2 );
 				expect( domSelection.getRangeAt( 0 ).endOffset ).to.equal( 3 );
 			} );
+
+			it( 'should not update when document#isFocusChaning is set to true', () => {
```
Comment (scofalik) [inline packages/ckeditor5-engine/tests/view/renderer.js:5409]:
```suggestion
			it( 'should not update when document#_isFocusChaning is set to true', () => {
```

**Review by niegowski — APPROVED** [review]
