### PR TITLE
#6667: Table heading rows should be properly updated after removing rows as a side effect of merging cells

### LINKED ISSUE #6667: Merging cells in header do not update heading rows properly
## 📝 Provide detailed reproduction steps (if any)

1.  Open "coffee table" sample.
2.  Merge cells "milk" and two below.

### ✔️ Expected result

The table features works properly (merging cells in body, setting heading rows, etc).

### ❌ Actual result

Table has one heading row (visually) but model have heading rows = 2.

## 📃 Other details

I don't know which command should take care of this (\`TableUtils.removeRow()\`, commands or a post-fixer).

Similar thing happen on `v18.0.0` using merge table cell left/right/up/down buttons:

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Table heading rows should be properly updated after removing rows as a side effect of merging cells. Closes #6667.

---

### Additional information

### CODE REVIEW

**Comment by jodator** [comment]
I've almost merged it with some changes but I had to revert it by force push (sorry for that).

Unfortunatelly it doesn't play well with undo (current master works):



the broken structure is a bug but the other thing is that number of heading rows isn't restored properly or isn't well handled. I had similar case but i can't reproduce it without that broken structure.

Could you check why this happens in this PR? Maybe a merge with master will be enough. The other hint is to check it how remove rows command handle this.

File: packages/ckeditor5-table/src/commands/mergecellcommand.js [hunk 1]
```diff
@@ -108,7 +107,9 @@ export default class MergeCellCommand extends Command {
 
 			// Remove empty row after merging.
 			if ( !removedTableCellRow.childCount ) {
-				removeEmptyRow( removedTableCellRow, writer );
+				const tableUtils = this.editor.plugins.get( 'TableUtils' );
+
+				tableUtils.removeRows( table, { at: table.getChildIndex( removedTableCellRow ), batch: writer.batch } );
```
Comment (jodator) [inline packages/ckeditor5-table/src/commands/mergecellcommand.js:112]:
```suggestion
				tableUtils.removeRows( table, { at: removedTableCellRow.index, batch: writer.batch } );
```

A bit shorter. Basically the same and

File: packages/ckeditor5-table/src/commands/mergecellcommand.js [hunk 2]
```diff
@@ -83,6 +80,8 @@ export default class MergeCellCommand extends Command {
 		const model = this.editor.model;
 		const doc = model.document;
 		const tableCell = getTableCellsContainingSelection( doc.selection )[ 0 ];
+		const table = findAncestor( 'table', tableCell );
```
Comment (jodator) [inline packages/ckeditor5-table/src/commands/mergecellcommand.js:83]: Can be moved to `if` below - AFAICS it will not be needed in other cases.

File: packages/ckeditor5-table/src/commands/mergecellscommand.js [hunk 3]
```diff
@@ -57,40 +57,25 @@ export default class MergeCellsCommand extends Command {
 			updateNumericAttribute( 'colspan', mergeWidth, firstTableCell, writer );
 			updateNumericAttribute( 'rowspan', mergeHeight, firstTableCell, writer );
 
+			const emptyRows = [];
```
Comment (jodator) [inline packages/ckeditor5-table/src/commands/mergecellscommand.js:60]: Maybe `emptyRowsIndexes` - just to be ultra precise.

File: packages/ckeditor5-table/src/commands/mergecellscommand.js [hunk 4]
```diff
@@ -57,40 +57,25 @@ export default class MergeCellsCommand extends Command {
...
+
 			for ( const tableCell of selectedTableCells ) {
 				const tableRow = tableCell.parent;
+
 				mergeTableCells( tableCell, firstTableCell, writer );
-				removeRowIfEmpty( tableRow, writer );
+
+				if ( !tableRow.childCount ) {
+					emptyRows.push( table.getChildIndex( tableRow ) );
```
Comment (jodator) [inline packages/ckeditor5-table/src/commands/mergecellscommand.js:68]:
```suggestion
					emptyRows.push( tableRow.index );
```

File: packages/ckeditor5-table/src/commands/mergecellscommand.js [hunk 5]
```diff
@@ -57,40 +57,25 @@ export default class MergeCellsCommand extends Command {
...
+				}
 			}
 
+			emptyRows.reverse().forEach( row => tableUtils.removeRows( table, { at: row, batch: writer.batch } ) );
```
Comment (jodator) [inline packages/ckeditor5-table/src/commands/mergecellscommand.js:72]: And since a `table` is only needed here maybe a wrap in `if( emptyRows.length )` ? But IDK for sure - this can be left as is.

File: packages/ckeditor5-table/src/tableutils.js [hunk 6]
```diff
@@ -289,17 +289,21 @@ export default class TableUtils extends Plugin {
 		const last = first + rowsToRemove - 1;
 		const batch = options.batch || 'default';
 
-		// Removing rows from table requires most calculations to be done prior to changing table structure.
+		model.enqueueChange( batch, writer => {
+			// Removing rows from table requires most calculations to be done prior to changing table structure.
+			// Preparations must be done in enqueueChange callback to use the current table structure.
```
Comment (jodator) [inline packages/ckeditor5-table/src/tableutils.js:294]:
```suggestion
			// Removing rows from the table require that most calculations to be done prior to changing table structure.
			// Preparations must be done in the same enqueueChange callback to use the current table structure.
```

Minor wording change.

File: packages/ckeditor5-table/src/tableutils.js [hunk 7]
```diff
@@ -753,17 +757,19 @@ function adjustHeadingColumns( table, removedColumnIndexes, writer ) {
 
 // Calculates a new heading rows value for removing rows from heading section.
 function updateHeadingRows( table, first, last, model, batch ) {
-	const headingRows = table.getAttribute( 'headingRows' ) || 0;
+	// Must be done after the changes in table structure (removing rows).
+	// Otherwise the downcast converter for headingRows attribute will fail. ckeditor/ckeditor5#6391.
+	//
```
Comment (jodator) [inline packages/ckeditor5-table/src/tableutils.js:762]:
```suggestion
	// Otherwise the downcast converter for headingRows attribute will fail.
	// See https://github.com/ckeditor/ckeditor5/issues/6391.
	//
```
