### PR TITLE
Fixed `pnpm release:clean` script to match all TS packages.

### LINKED ISSUE #19273: The `release:clean` script does not remove build artifacts from `ckeditor5` package
## 📝 Provide detailed reproduction steps (if any)

In `packages/ckeditor5` run `pnpm run build` and then try to clean up the artifacts:

```
cd packages/ckeditor5
pnpm run build
cd ../..
pnpm run release:clean
```

### ✔️ Expected result

Build artifacts from all packages are removed.

### ❌ Actual result

Build artifacts from `packages/ckeditor5` are not removed.

### ❓ Possible solution

See `isTypeScriptPackage()` in `scripts/release/utils/istypescriptpackage.mjs`. This function returns `false` for `packages/ckeditor5` package.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by martnpaneq**
### 🚀 Summary

Fixed `pnpm release:clean` script to match all TS packages.

The `packages/ckeditor5/package.json` file has a different value in the main field than the rest of the packages ( 'dist/ckediotr5.js` vs `src/index.ts` ), so it was recognised by the clean script as a JS package.

The `isTypeScriptPackage` function was modified to make to detect if any `.ts` files are present in `src` directory.

---

### 📌 Related issues

* Closes #19273

---

### 💡 Additional information

*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*

### CODE REVIEW

File: scripts/release/utils/istypescriptpackage.mjs [hunk 1]
```diff
@@ -16,12 +17,19 @@ export default async function isTypeScriptPackage( packagePath ) {
...
-	return checkFileExists( path.join( packagePath, 'tsconfig.json' ) );
+	// In step two, Let's check if the package contains a `tsconfig.json` file.
+	if ( await checkFileExists( path.join( packagePath, 'tsconfig.json' ) ) ) {
+		return true;
+	}
+
+	// In the last step check if any typescript files are present in the src directory.
+	const tsFiles = await glob( 'src/**/*.ts', { cwd: packagePath } );
+
+	return tsFiles.length > 0;
```
Comment (pomek) [inline scripts/release/utils/istypescriptpackage.mjs]: Wouldn't it be enough? I mean, I think, we could skip all of the checks and determine whether to process a TypeScript package based on its source.

Comment (martnpaneq) [reply scripts/release/utils/istypescriptpackage.mjs]: Yeah, it should be enough.

Comment (martnpaneq) [reply scripts/release/utils/istypescriptpackage.mjs]: Updated in [279b997](https://github.com/ckeditor/ckeditor5/pull/19289/commits/279b99700eeafbf6600a35a322021ab0b83b74d0).

File: scripts/release/utils/istypescriptpackage.mjs [hunk 2]
```diff
@@ -3,29 +3,14 @@
...
+import { glob } from 'glob';
 
 /**
  * @param {String} packagePath
  * @returns {Promise.<Boolean>}
  */
 export default async function isTypeScriptPackage( packagePath ) {
-	const packageJsonPath = path.join( packagePath, 'package.json' );
-	const packageJson = await fs.readJson( packageJsonPath );
+	const tsFiles = await glob( 'src/**/*.ts', { cwd: packagePath } );
```
Comment (pomek) [inline scripts/release/utils/istypescriptpackage.mjs:13]:
```suggestion
	const tsFiles = await glob( 'src/*.ts', { cwd: packagePath } );
```

I am unsure, but it would be enough. There must be at least one file, always, in the `src` directory. I do not force this change.

Comment (martnpaneq) [reply scripts/release/utils/istypescriptpackage.mjs:13]: We agreed to not make this change for now.
