### PR TITLE
Fix (html-support): Redefine most GHS-elements as not blocks in schema.

### LINKED ISSUE #12430: Multiple GHS-elements are incorrectly defined as blocks in schema
## 📝 Provide detailed reproduction steps (if any)

GHS feature introduces multiple model elements that represent related HTML tags. Most of those elements/tags are for creating document structure, like `<article>` (`htmlArticle`) or `<section>` (`htmlSection`). We call such elements "containers". Considering CKE5 features, there is just one container defined and it is `blockQuote` element.

Those GHS-related elements are incorrectly marked as blocks in model schema. I didn't make full list but I guess that most these elements are incorrect. However, `htmlDivParagraph` should stay a block.

Due to this incorrect setting, [we have problems with styles feature](https://github.com/ckeditor/ckeditor5/issues/12417) and also with other features (e.g. heading feature will change section into a heading...).

Additional context:

Block elements are:

*   paragraph, heading, list item, etc. (non-objects),
*   table, image, media, etc. (objects).

Block elements are "low level" when it comes to document structure, they are either content-holders (like paragraph) or they "are content" themselves (like image). Non-object block elements are expected to allow inline elements in them. It is also possible to split them (using enter key) and merge them together (delete). Finally, non-object block elements cannot contain other block elements.

_(Side note, I dislike, that images are blocks and paragraphs are blocks as well, as they are totally different: #12432_.)

On the other hand, containers keep other containers and blocks to provide more complex document structure. [Containers are those elements that are not any other type of element, like block quote](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html#defining-additional-semantics). Block quote works totally different than paragraphs. We intuitively feel that paragraph and block quote are in different groups of elements.

Finally, we use `selection.getSelectedBlocks()` in many places in our features and we expect that it returns paragraph-like elements.

### PR DESCRIPTION
**Pull request by kbinieda**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (html-support): Redefine most GHS-elements as not blocks in schema. Closes #12430.

### CODE REVIEW

**Comment by scofalik** [comment]
I think that `htmlCaption` and `htmlFigCaption` should not be blocks. They are not splittable and merge'able (using enter and backspace). In general, they aren't like paragraphs. They can include text, though. I'd say that's an exception, as I earlier thought that `$text` can be only in `$block`s.

As we discussed with @kbinieda, we don't have a strict definitions for schema items and this is causing confusion.

Other than that, I think that, `htmlFigure` should be block (and object). This is another confusing part, where block+object is something completely different than block+non-object. I wrote about it here: #12432. However, I'd test how this behaves.

**Comment by scofalik** [comment]
Actually, I'd check how `htmlCaption` and `htmlFigCaption` behaves when it is `isBlock: false` and `isLimit: true`. That is how our own caption is defined is schema but we have special handling for our own caption (as it is our own feature). I am not sure if the editor will have good UX for a "generic" block-non-object-limit.

File: packages/ckeditor5-html-support/src/schemadefinitions.js [hunk 1]
```diff
@@ -211,7 +212,7 @@ export default {
 			view: 'figure',
 			modelSchema: {
 				inheritAllFrom: '$container',
-				isBlock: true
+				isBlock: false
```
Comment (scofalik) [inline packages/ckeditor5-html-support/src/schemadefinitions.js:215]:
```suggestion
				isBlock: true
```

**Comment by scofalik** [comment]
I proposed some additional changes for some elements however I am not 100% sure about them.

I changed `tr`, `td` and `th` to better reflect schema that we have for them in the actual feature. Previously, you were able to do such silly things like removing `<td>` if you clicked backspace too much and removed whole content.

I also reverted changes for `figcaption` and `caption`. When changed to `isLimit` it was difficult to remove them and, as a result, it was difficult to remove `figure` that contained them. It was possible, but you had to make a selection that contained the whole figure. I believe that enter should not split `figcaption` and unfortunately, after revert, it does split it. But I think this is a smaller evil. I'd rather be able to easily remove the `figcaption`.
