### PR TITLE
Fix for skipping building `ckeditor5-premium-features` when set up as standalone repository.

### LINKED ISSUE #19110: Unable to build the docs in a standalone `ckeditor5` repository
## 📝 Provide detailed reproduction steps (if any)

1. Clone `ckeditor5`.
2. Install dependencies: `pnpm install`.
3. Build the docs: `pnpm run docs`.

### ✔️ Expected result

Docs are built without errors.

### ❌ Actual result

```
$ pnpm run docs

> ckeditor5-root@46.1.0 docs D:\Projects\tmp\ckeditor5
> node scripts/docs/build-docs.mjs


> ckeditor5-root@46.1.0 docs:api D:\Projects\tmp\ckeditor5
> node scripts/docs/build-api-docs.mjs

Started building API.
Typedoc started...
[warning] element has multiple declarations with a comment. An arbitrary comment will be used
[warning] element has multiple declarations with a comment. An arbitrary comment will be used
[warning] element has multiple declarations with a comment. An arbitrary comment will be used
[warning] element has multiple declarations with a comment. An arbitrary comment will be used
[warning] element has multiple declarations with a comment. An arbitrary comment will be used
[warning] element has multiple declarations with a comment. An arbitrary comment will be used
Documented 986 files!
Finished building API.

> ckeditor5-root@46.1.0 docs:ckeditor5 D:\Projects\tmp\ckeditor5
> node scripts/docs/build-ckeditor-packages.mjs

Started building `ckeditor5`.
Finished building `ckeditor5`.
Started building `ckeditor5-premium-features`.
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Projects\scripts\docs\generate-ckeditor5-premium-features-docs-build.mjs' imported from D:\Projects\tmp\ckeditor5\scripts\docs\build-ckeditor-packages.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
    at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:643:36)
    at TracingChannel.tracePromise (node:diagnostics_channel:344:14)
    at ModuleLoader.import (node:internal/modules/esm/loader:642:21) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///D:/Projects/scripts/docs/generate-ckeditor5-premium-features-docs-build.mjs'
}

 ELIFECYCLE  Command failed with exit code 1.

Error: Process exited with code 1
    at ChildProcess.<anonymous> (file:///D:/Projects/tmp/ckeditor5/scripts/docs/build-docs.mjs:109:13)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

### ❓ Possible solution

The condition that checks if commercial repository is present is invalid:

https://github.com/ckeditor/ckeditor5/blob/7d866210677db6408ab37183dcebfa81990c50b4/scripts/docs/build-ckeditor-packages.mjs#L51

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by martnpaneq**
### 🚀 Summary

Fix for skipping building `ckeditor5-premium-features` when set up as standalone repository.

---

### 📌 Related issues

* Closes #19110

---

### 💡 Additional information

*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*

### CODE REVIEW

**Comment by martnpaneq** [comment]
Here is the new warning that will be shown in the standalone mode:

image

**Comment by martnpaneq** [comment]
The `pnpm run docs` script returns code `1`, but the documentation is built correctly.

There are some expected link errors.

image

File: scripts/docs/parse-arguments.mjs [hunk 1]
```diff
@@ -126,6 +131,19 @@ function warnAboutUsingDevEnvironment() {
...
+ */
+function warnAboutDocsValidationInStandaloneMode() {
+	const warning = styleText(
+		'yellow',
+		'Docs validation is disabled in standalone mode, because it is expected to fail without premium ' +
+		'features repository context.\nUse "--skip-validation=false" to validate the docs anyway.'
+	);
+
+	console.log( warning );
+}
```
Comment (pomek) [inline scripts/docs/parse-arguments.mjs]:
```suggestion
function warnAboutDocsValidationInStandaloneMode() {
	const warning = styleText(
		'yellow',
		'This repository is normally used together with a private companion project.\n' +
		'Because that project is not present here, some documentation links will not resolve - ' +
		'this is expected and does not indicate a problem.\n\n' +
		'The purpose of this task is to build the API reference and contributor-facing ' +
		'guides for this repository on its own.\n' +
		'If you still want to run full documentation validation, use "--skip-validation=false".'
	);

	console.log( warning );
}
```

File: scripts/constants.mjs [hunk 2]
```diff
@@ -10,6 +10,7 @@ export const CKEDITOR5_ROOT_PATH = upath.join( import.meta.dirname, '..' );
 export const CKEDITOR5_PACKAGES_PATH = upath.join( CKEDITOR5_ROOT_PATH, PACKAGES_DIRECTORY );
 export const CKEDITOR5_COMMERCIAL_PATH = upath.join( CKEDITOR5_ROOT_PATH, '..', '..' );
 export const CKEDITOR5_COMMERCIAL_PACKAGES_PATH = upath.join( CKEDITOR5_COMMERCIAL_PATH, PACKAGES_DIRECTORY );
+export const IS_STANDALONE_REPOSITORY = upath.basename( upath.join( CKEDITOR5_ROOT_PATH, '..' ) ) !== 'external';
```
Comment (pomek) [inline scripts/constants.mjs]:
```suggestion
export const IS_ISOLATED_REPOSITORY = upath.basename( upath.join( CKEDITOR5_ROOT_PATH, '..' ) ) !== 'external';
```

File: scripts/docs/parse-arguments.mjs [hunk 3]
```diff
@@ -70,6 +71,10 @@ export default function parseArguments( args ) {
 		}
 	} );
 
+	if ( IS_STANDALONE_REPOSITORY ) {
+		warnAboutDocsValidationInStandaloneMode();
+	}
```
Comment (pomek) [inline scripts/docs/parse-arguments.mjs]: This warning must be produced once the documentation is built. Otherwise, this is not visible.

Comment (martnpaneq) [reply scripts/docs/parse-arguments.mjs]: Moved the warning to be displayed after the docs are built in [a5355f9](https://github.com/ckeditor/ckeditor5/pull/19173/commits/a5355f94d7c7d5805986a4bda94648403ecce07d).

File: scripts/constants.mjs (hunk 2 above)
Comment (martnpaneq) [reply scripts/constants.mjs]: Renamed in [a5355f9](https://github.com/ckeditor/ckeditor5/pull/19173/commits/a5355f94d7c7d5805986a4bda94648403ecce07d).

File: scripts/docs/parse-arguments.mjs (hunk 1 above)
Comment (martnpaneq) [reply scripts/docs/parse-arguments.mjs]: Added your suggestion in [a5355f9](https://github.com/ckeditor/ckeditor5/pull/19173/commits/a5355f94d7c7d5805986a4bda94648403ecce07d).

File: scripts/docs/build-docs.mjs [hunk 4]
```diff
@@ -80,6 +81,24 @@ async function buildDocs() {
 			await fs.copy( asset, upath.join( destinationPath, directoryName ) );
 		}
 	}
+
+	if ( IS_ISOLATED_REPOSITORY ) {
+		warnAboutDocsValidationInStandaloneMode();
+	}
+}
+
+function warnAboutDocsValidationInStandaloneMode() {
```
Comment (pomek) [inline scripts/docs/build-docs.mjs]:
```suggestion
function printWarningIsolatedRepository() {
```
I hope you align the fn name according the constant change.

Comment (martnpaneq) [reply scripts/docs/build-docs.mjs]: Aligned in [220d1a4](https://github.com/ckeditor/ckeditor5/pull/19173/commits/220d1a40b036b1bde02c549bf3e1dde2fd7105b0).

File: scripts/docs/build-docs.mjs [hunk 5]
```diff
@@ -80,6 +81,24 @@ async function buildDocs() {
...
+function printWarningIsolatedRepository() {
+	const warning = styleText(
+		'yellow',
+		'\nThis repository is normally used together with a private companion project.\n' +
+		'Because that project is not present here, some documentation links will not resolve - ' +
+		'this is expected and does not indicate a problem.\n\n' +
+		'The purpose of this task is to build the API reference and contributor-facing ' +
+		'guides for this repository on its own.\n' +
+		'If you still want to run full documentation validation, use "--skip-validation=false".'
+	);
```
Comment (pomek) [inline scripts/docs/build-docs.mjs:99]:
```suggestion
	const warning = styleText(
		'yellow',
		'\nThis repository is typically used in conjunction with a private project.\n\n' +
		'Since the project is not present here, some documentation links may not resolve - ' +
		'this is expected and does not indicate a problem.\n\n' +
		'The purpose of this task is to create the API reference and contributor-facing ' +
		'guides for this repository independently.\n\n' +
		'If you still want to run full documentation validation, use "--skip-validation=false".'
	);
```

I reread it and propose a few tweaks.

Comment (martnpaneq) [reply scripts/docs/build-docs.mjs:99]: Addressed in [282dd9c](https://github.com/ckeditor/ckeditor5/pull/19173/commits/282dd9c9a9014db89bdc74bcbdbd089922a7b355).
