### PR TITLE
Pressing the tab key in restricted editing mode enters a table thats non editable

### LINKED ISSUE #15506: Pressing the `Tab` key in restricted editing mode enters a table that's non-editable
## 📝 Provide detailed reproduction steps (if any)

1. Create a document that has some editable areas and a non-editable table
2. Place the caret in the first editable area
3. Keep pressing the `Tab` key

### ✔️ Expected result

The non-editable table should not be focusable when pressing `Tab`. At the very least, it should be possible to exit the table when pressing `Tab` again or when pressing `Shift + Tab`

### ❌ Actual result

Eventually, the caret will enter the table and get stuck there:

https://github.com/ckeditor/ckeditor5/assets/72079603/e0bed056-93ce-4fb5-992d-f34ad0dff70d

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (widget): Pressing tab should not focus widget editable. Closes #15506.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-restricted-editing/src/restrictededitingmodeediting.ts [hunk 1]
```diff
@@ -13,14 +13,15 @@ import {
...
-import type {
-	DocumentSelection,
-	Marker,
-	ModelDeleteContentEvent,
-	ModelPostFixer,
-	Range,
-	SchemaAttributeCheckCallback,
-	SchemaChildCheckCallback
+import {
+	UpcastWriter,
```
Comment (arkflpc) [inline packages/ckeditor5-restricted-editing/src/restrictededitingmodeediting.ts:17]: This is unused in this file.

File: packages/ckeditor5-widget/src/utils.ts [hunk 2]
```diff
@@ -287,6 +287,7 @@ export function toWidgetEditable(
 	writer.addClass( [ 'ck-editor__editable', 'ck-editor__nested-editable' ], editable );
 
 	writer.setAttribute( 'role', 'textbox', editable );
+	writer.setAttribute( 'tabindex', '-1', editable );
```
Comment (arkflpc) [inline packages/ckeditor5-widget/src/utils.ts:290]: How would it behave if the whole editor has other `tabindex` set by integrators? For instance `tablindex=-2`. Was it tested (in manual test or otherwise)?

**Review by arkflpc — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-widget/src/utils.ts (hunk 2 above)
Comment (niegowski) [reply packages/ckeditor5-widget/src/utils.ts:290]: From MDN: 

> A negative value (the exact negative value doesn't actually matter, usually tabindex="-1") means that the element is not reachable via sequential keyboard navigation.
> Note: tabindex="-1" may be useful for elements that should not be navigated to directly using the Tab key, but need to have keyboard focus set to them. Examples include an off-screen modal window that should be focused when it comes into view, or a form submission error message that should be immediately focused when an errant form is submitted.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Review by niegowski — APPROVED** [review]
