### PR TITLE
#9502: The image should not save the caption in the model attribute

### LINKED ISSUE #9502: The image should not save the caption in the model attribute to prevent issues in collaboration
## 📝 Provide detailed reproduction steps (if any)

Extracted the `ckeditort-image` part from #9368.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (image): The image should not save the caption in the model attribute to prevent issues in collaboration. Closes #9502.

### CODE REVIEW

File: packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js [hunk 1]
```diff
@@ -116,6 +132,104 @@ export default class ImageCaptionEditing extends Plugin {
...
+
+			const { oldElement, newElement } = evt.return;
+
+			if ( imageUtils.isBlockImage( oldElement ) ) {
+				const oldCaptionElement = getCaptionFromImageModelElement( oldElement );
+
+				// If the old element was a captioned block image (the caption was visible),
+				// simply save it so it can be restored.
+				if ( oldCaptionElement ) {
+					return this._saveCaption( newElement, oldCaptionElement.toJSON() );
```
Comment (niegowski) [inline packages/ckeditor5-image/src/imagecaption/imagecaptionediting.js]:
```suggestion
					this._saveCaption( newElement, oldCaptionElement.toJSON() );

					return;
```

**Review by niegowski — APPROVED** [review]
