### PR TITLE
Reset insert table view in menu bar

### LINKED ISSUE #16156: Selection of the table cells does not reset after leaving the menu bar
## 📝 Provide detailed reproduction steps (if any)

1. Open a manual test that includes the `Table` plugin.
2. Open the Table from the menu bar (under the `Insert` category).
3. Close the menu bar and open again Insert -> Table from the menu bar.

### ✔️ Expected result

The selected cells are reset.

### ❌ Actual result

The selected cells are not reset.

https://github.com/ckeditor/ckeditor5/assets/20561161/d76e27a5-ca37-445e-b718-3a45f68455f6

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mremiszewski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (table) Table insert in menu bar always start at 1x1 on menu open. Closes #16156.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-table/src/ui/inserttableview.ts [hunk 1]
```diff
@@ -159,6 +159,16 @@ export default class InsertTableView extends View {
 		this.keystrokes.listenTo( this.element! );
 	}
 
+	/**
+	 * Resets the rows and columns selection.
+	 */
+	public reset(): void {
```
Comment (DawidKossowski) [inline packages/ckeditor5-table/src/ui/inserttableview.ts:165]: I would add a unit test for this method.

**Review by DawidKossowski — CHANGES_REQUESTED** [review]

**Review by DawidKossowski — APPROVED** [review]
