### PR TITLE
Fix column resizing in table with only heading rows

### LINKED ISSUE #11878: Table column resize produces errors for the table with all the header rows
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/table.html#table-column-resize
2. Select all the rows
3. Change them to header rows
4. Try to resize any column

### ✔️ Expected result

Resize works normally.

### ❌ Actual result

There are errors in the console:
```
snippet.js:4 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at wk (snippet.js:4:729485)
    at bk (snippet.js:4:729722)
    at Rk._getResizingData (snippet.js:4:738645)
    at Rk._onMouseDownHandler (snippet.js:4:736448)
    at Object.fire (snippet.js:4:2958)
    at Us (snippet.js:4:70810)
    at Gs.fire (snippet.js:4:70316)
    at bu.fire (snippet.js:4:122423)
    at bu.onDomEvent (snippet.js:4:394164)
    at listenTo.useCapture (snippet.js:4:122332)
rethrowUnexpectedError @ snippet.js:4
fire @ snippet.js:4
Us @ snippet.js:4
fire @ snippet.js:4
fire @ snippet.js:4
onDomEvent @ snippet.js:4
listenTo.useCapture @ snippet.js:4
fire @ snippet.js:4
t @ snippet.js:4
snippet.js:4 Uncaught TypeError: Cannot destructure property 'columnPosition' of 'this._resizingData' as it is null.
    at Rk._onMouseMoveHandler (snippet.js:4:737512)
    at m (snippet.js:4:123458)
    at g (snippet.js:4:123514)
    at ur.b (snippet.js:4:123836)
    at ur.fire (snippet.js:4:2958)
    at HTMLDocument.t (snippet.js:4:115818)
```

## 📃 Other details

* Browser: all
* OS: macOS
* First affected CKEditor version: `34.1.0` (the first one with column resize feature)
* Installed CKEditor plugins: `table`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Dumluregn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Fixed column resize for tables containing only table headers. Closes #11878.

---

### Additional information

Tested also with a table pasted from CKE4 containing only `<thead>` element - see https://github.com/ckeditor/ckeditor5/issues/11975#issue-1285829256 for details.

### CODE REVIEW

File: packages/ckeditor5-table/src/tablecolumnresize/utils.js [hunk 1]
```diff
@@ -92,25 +92,39 @@ export function getElementWidthInPixels( domElement ) {
  * @returns {Number}
  */
 export function getTableWidthInPixels( table, editor ) {
-	const viewTbody = getTbodyViewElement( table, editor );
-	const domTbody = editor.editing.view.domConverter.mapViewToDom( viewTbody );
+	// It is possible for table to not have a <tbody> element - see #11878.
```
Comment (mlewand) [inline packages/ckeditor5-table/src/tablecolumnresize/utils.js:95]:
```suggestion
	// It is possible for a table to not have a <tbody> element - see #11878.
```

File: packages/ckeditor5-table/tests/manual/tablecolumnresize.html [hunk 2]
```diff
@@ -59,6 +59,29 @@ <h3>Table with a single cell and a table width style</h3>
 			</tbody>
 		</table>
 	</figure>
+
+	<h3>Table without &lt;tbody&gt;</h3>
```
Comment (mlewand) [inline packages/ckeditor5-table/tests/manual/tablecolumnresize.html:63]:
```suggestion
	<h3>Table with headers only</h3>
```

File: packages/ckeditor5-table/tests/manual/tablecolumnresize.html [hunk 3]
```diff
@@ -150,6 +173,29 @@ <h3>Table with a single cell and a table width style</h3>
...
```
Comment (mlewand) [inline packages/ckeditor5-table/tests/manual/tablecolumnresize.html:177]:
```suggestion
	<h3>Table with headers only</h3>
```

**Review by mlewand — COMMENTED** [review]
Just minor wording other than that fix and test works fine.

There are three almost identical functions now:

https://github.com/ckeditor/ckeditor5/blob/abf9cda92ff0225a71d0b49d9166e9e7c0969a57/packages/ckeditor5-table/src/tablecolumnresize/utils.js#L185-L190

https://github.com/ckeditor/ckeditor5/blob/abf9cda92ff0225a71d0b49d9166e9e7c0969a57/packages/ckeditor5-table/src/tablecolumnresize/utils.js#L108-L113

https://github.com/ckeditor/ckeditor5/blob/abf9cda92ff0225a71d0b49d9166e9e7c0969a57/packages/ckeditor5-table/src/tablecolumnresize/utils.js#L121-L126

Let's combine them into one reusable function.

I'll do that as a part of the review.

**Review by mlewand — APPROVED** [review]
LGTM
