### PR TITLE
Source editing should not add white spaces to pre-formatted code lines

### LINKED ISSUE #15084: Source code view causes <pre><code> to gain leading whitespace if inside <li>
## 📝 Provide detailed reproduction steps (if any)

1. Create `<li><pre><code>` markup, for example:
```
<h2>
    Good:
</h2>
<pre><code class="language-plaintext"># From any path:
something --flag</code></pre>
<h2>
    <strong>Bad:</strong>
</h2>
<ol>
    <li>
        <p>
            preformatted code block in list gains leading whitespace 😬
        </p>
        <pre><code class="language-plaintext"># From any path:
something --flag</code></pre>
    </li>
</ol>
```
2. Enable source view
3. Change *anything at all*, e.g. change "Good:" to "Good!"
4. Disable source view

### ✔️ Expected result

The only change is the one you made.

### ❌ Actual result

The `something --flag` has been indented with additional spaces:
li pre code

## 📃 Other details

* Browser: Chrome
* OS: macOS
* First affected CKEditor version: Unknown.
* Installed CKEditor plugins: Reproduced at https://ckeditor.com/ckeditor-5/demo/html-support/

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #15810: Source editing mode adds leading whitespaces to code block
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/41.1.0/features/source-editing.html
2. In source editing mode paste
```
<h2>
    Good:
</h2>
<pre><code class="language-plaintext"># From any path:
something --wflag</code></pre>
<h2>
    <strong>Bada:</strong>
</h2>
<ol>
    <li>
        <p>
            preformatted code block in list gains leading whitespace
        </p>
        <pre><code class="language-plaintext"># From any path:
something --flag</code></pre>
    </li>
</ol>
```
3. Close source editing mode and open it again
4. Change something outside the code blocks and close source editing mode

### ✔️ Expected result

Code block shouldn't change

### ❌ Actual result

Code in list got some additional whitespace beside the first line

### ❓ Possible solution

Ignore extra whitespaces on code block upcast or do not add them in code block downcast.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (source-editing): Source editing should not add white spaces to pre-formatted code lines. Closes #15084.

---

### Additional information

I don't like our approach in this helper. Using RegExp to manipulate HTML was not the best idea in the first place and there's always a risk of the whole thing breaking up. A parser would be a better choice but that would mean a re-write of the helper. I briefly researched how `DOMParser` could help us and this only confirmed my suspicion that a lot of work is necessary. We could also use an external library to prettify the source output.

### CODE REVIEW

File: packages/ckeditor5-source-editing/src/utils/formathtml.ts [hunk 1]
```diff
@@ -79,10 +79,13 @@ export function formatHtml( input: string ): string {
 		.split( '\n' );
 
 	let indentCount = 0;
+	let isPreformattedLine: ReturnType<typeof isPreformattedBlockLine> = false;
```
Comment (Dumluregn) [inline packages/ckeditor5-source-editing/src/utils/formathtml.ts:82]: Nice typing :+1:

**Review by Dumluregn — APPROVED** [review]
Agree that regexp is not great but for now it does the work. I think we could switch to the external lib (like [https://www.npmjs.com/package/js-beautify](https://www.npmjs.com/package/js-beautify) ) if at some point we decide to have syntax highlight (as that would probably also use some existing tooling). Or maybe we'll just use some more complex thing like Monako :thinking: anyway, for now LGTM and it also resolves #15084.
