### PR TITLE
#7542: Widget type around UI should not be selectable by triple-click.

### LINKED ISSUE #6021: [Safari] Triple click on links or mentions in image caption and table results in crash
## 📝 Provide detailed reproduction steps (if any)

This happens only in Safari with links or mentions, and there are a few cases:

First example:
1. Open localhost:8125/ckeditor5-mention/tests/manual/mention-asynchronous.html
2. Select image caption text and type '@'
3. Select one of the mentions
4. Triple click on the mention
5. Try to type after the mention

### ✔️ Expected result
Whole mention should be selected with no crashes

### ❌ Actual result
App crashes

mentions_err

Errors:
```
[Error] CKEditorError: model-selection-setTo-not-selectable: Cannot set the selection to the given place. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-selection-setTo-not-selectable

	fire (mention-asynchronous.js:117806)
	domListener (mention-asynchronous.js:115536)
```
```
[Error] CKEditorError: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
 {"offset":17,"nodeList":[{"attributes":{"mention":{"_uid":"e4ddfb9107d48ba6631360bb77c68b875","_text":"@angryrabbit821","id":"@angryrabbit821","username":"angryrabbit821","fullName":"Jackson Graves","thumbnail":"https://randomuser.me/api/portraits/thumb/men/61.jpg"}},"data":"@angryrabbit821"},{"data":" "}]}
	fire (mention-asynchronous.js:117806)
	domListener (mention-asynchronous.js:115536)
```

Second example:
1. Open ckeditor5 with table plugin
2. Create a table and create a link in some cell
3. Triple click on the link

### ✔️ Expected result
Link should be selected

### ❌ Actual result

App crashes

Error:
```
[Error] CKEditorError: model-selection-setTo-not-selectable: Cannot set the selection to the given place. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-selection-setTo-not-selectable

	rethrowUnexpectedError (snippet.js:4:1482)
	fire (snippet.js:4:22271)
	n (snippet.js:4:120568)
```

## 📃 Other details

* Browser: Safari
* OS: macOS
* CKEditor version: 5
* Installed CKEditor plugins: Mention, Table

It also happens the other way round - when you triple click on link in a caption and a mention in a table.

I found some issues related to triple clicking in safari here:
https://github.com/ckeditor/ckeditor5/issues/1677

and here:
https://github.com/ckeditor/ckeditor5/issues/1463

but I guess this is a bit different behaviour.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #7542: Triple-click inside image caption causes error in Firefox
## 📝 Provide detailed reproduction steps (if any)

1. Launch Firefox browser. (Do not use Chrome browser).
2. Go to [CKEditor Images documentation page](https://ckeditor.com/docs/ckeditor5/latest/features/image.html) 
3. Scroll down to the Image Captions section ( [direct link](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-captions) )
4. Look at the image with a caption "_Autumn fields by Aleksander Nowodziński_". 
5. Triple-click inside the caption anywhere on the caption text (click 3 times very fast). Normally doing a triple-click should select all the text. 
6. Instead you will see an error in the console. Also you will now be unable to select that image (meaning you can hover over it and see a yellow outline, but if you click it you will not get a blue outline). In fact you will not be able to select the other image in the editor either (the one without a caption), so it appears that the selection tool stops working after the error happens. 
7. Try again, this time using Chrome browser. No error in Chrome; caption text gets selected correctly.

### ✔️ Expected result

Clicking 3 times in a row should select all the caption text.
If you use Chrome that is what will happen. 
But if you use Firefox you will get an error in the console.

### ❌ Actual result

You get an error in the console:
```
CKEditorError: model-selection-range-intersects: Trying to add a range that intersects with another range in the selection. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…port/error-codes.html#error-model-selection-range-intersects
 {"addedRange":{"start":{"root":"main","path":[1],"stickiness":"toNext"},"end":{"root":"main","path":[2],"stickiness":"toPrevious"}},"intersectingRange":{"start":{"root":"main","path":[1,0,0],"stickiness":"toNone"},"end":{"root":"main","path":[1,0,0],"stickiness":"toNone"}}}
```
Also, after this error happens it is not possible to select the image. It is also not possible to select the image that is after it (the one without a caption). In other words the selection tool stops working.

## 📃 Other details

* Browser: Firefox
* OS: Win 10
* CKEditor version: 20
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (widget): Triple-click inside image caption should not crash editor in Firefox. Closes #7542.

Fix (widget): Triple-click on link inside image caption should not crash editor in Safari. Closes #6021.

---

### Additional information

### CODE REVIEW

**Comment by niegowski** [comment]
DOM Selection Ranges after triple-click:



View Ranges converted by `DomConverter`:



Model Ranges converted by `Mapper` that are triggering `model-selection-range-intersects` exception:

**Comment by niegowski** [comment]
Also I noticed that `<figcaption>` has `display: table-caption;` style, but it's replaced with `display: block;` if image was resized. This problem doesn't occur if `<figcaption>` has `display: block;` style.

File: packages/ckeditor5-widget/src/widget.js [hunk 1]
```diff
@@ -146,12 +146,15 @@ export default class Widget extends Plugin {
 			// But at least triple click inside nested editable causes broken selection in Safari.
 			// For such event, we select the entire nested editable element.
 			// See: https://github.com/ckeditor/ckeditor5/issues/1463.
-			if ( env.isSafari && domEventData.domEvent.detail >= 3 ) {
+			if ( ( env.isSafari || env.isGecko ) && domEventData.domEvent.detail >= 3 ) {
 				const mapper = editor.editing.mapper;
-				const modelElement = mapper.toModelElement( element );
+				const viewElement = element.is( 'attributeElement' ) ?
+					element.findAncestor( element => !element.is( 'attributeElement' ) ) : element;
```
Comment (oleq) [inline packages/ckeditor5-widget/src/widget.js:152]: What if there's a `widget > nested editable > block-quote > link` structure? Feels like `viewElement` will be the blockquote and the entire nested editable will not be selected. I think `isInsideNestedEditable()` could become `getClosestNestedEditable()` and you could re-use its output here.

Comment (niegowski) [reply packages/ckeditor5-widget/src/widget.js:152]: But in that situation entire content of that content editable would be selected instead of single paragraph.

Comment (niegowski) [reply packages/ckeditor5-widget/src/widget.js:152]: Note that table cells are also nested editables and triple-click action is expected to select current block only, not entire content editable.

Comment (oleq) [reply packages/ckeditor5-widget/src/widget.js:152]: You're right, my bad.

Comment (oleq) [reply packages/ckeditor5-widget/src/widget.js:152]: Can we have another test then that checks only the closest non-attribute is selected and not the entire nested editable?

Comment (niegowski) [reply packages/ckeditor5-widget/src/widget.js:152]: ok
