### PR TITLE
Decorator downcasting should ignore elements without links.

### LINKED ISSUE #8401: Crash when unlinking a linked image
## 📝 Provide detailed reproduction steps (if any)

1.  Click a linked image.
2.  Press Cmd+K.
3.  Press Esc or click "Cancel".
4.  Click "Unlink".

### ✔️ Expected result

All works fine.

### ❌ Actual result

```
downcastwriter.js:323 Uncaught TypeError: Cannot read property '_setAttribute' of undefined
    at DowncastWriter.setAttribute (downcastwriter.js:323)
    at DowncastDispatcher.<anonymous> (linkimageediting.js:218)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:560)
    at DowncastDispatcher.convertAttribute (downcastdispatcher.js:249)
    at DowncastDispatcher.convertChanges (downcastdispatcher.js:161)
    at editingcontroller.js:94
    at View.change (view.js:477)
    at Document.EditingController.listenTo.priority (editingcontroller.js:93)
    at Document.fire (emittermixin.js:209)
setAttribute @ downcastwriter.js:323
(anonymous) @ linkimageediting.js:218
fire @ emittermixin.js:209
_testAndFire @ downcastdispatcher.js:560
convertAttribute @ downcastdispatcher.js:249
convertChanges @ downcastdispatcher.js:161
(anonymous) @ editingcontroller.js:94
change @ view.js:477
EditingController.listenTo.priority @ editingcontroller.js:93
fire @ emittermixin.js:209
_handleChangeBlock @ document.js:309
_runPendingChanges @ model.js:833
change @ model.js:175
execute @ unlinkcommand.js:58
(anonymous) @ observablemixin.js:255
fire @ emittermixin.js:209
<computed> @ observablemixin.js:259
execute @ commandcollection.js:69
execute @ editor.js:291
(anonymous) @ linkui.js:136
fire @ emittermixin.js:209
fireDelegatedEvents @ emittermixin.js:625
fire @ emittermixin.js:232
(anonymous) @ buttonview.js:162
callback @ template.js:956
fire @ emittermixin.js:209
domListener @ emittermixin.js:247
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by maxbarnas**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (link): Removing the link from the image no longer throws an error. Closes #8401.

### CODE REVIEW

File: packages/ckeditor5-link/src/linkimageediting.js [hunk 1]
```diff
@@ -214,6 +214,11 @@ function downcastImageLinkManualDecorator( manualDecorators, decorator ) {
 			const viewFigure = conversionApi.mapper.toViewElement( data.item );
 			const linkInImage = Array.from( viewFigure.getChildren() ).find( child => child.name === 'a' );
 
+			// The unlink command is removing the link by the time this dispatcher is ran.
```
Comment (Reinmar) [inline packages/ckeditor5-link/src/linkimageediting.js:217]:
```suggestion
			// The <a> element was removed by the time this converter is executed.
			// It may happen when the base `linkHref` and decorator attributes are removed
			// at the same time (see #8401).
```

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 2]
```diff
@@ -826,6 +826,34 @@ describe( 'LinkImageEditing', () => {
 					'</p>'
 				);
 			} );
+
+			it( 'should downcast without error if the image already has no link', () => {
```
Comment (Reinmar) [inline packages/ckeditor5-link/tests/linkimageediting.js:830]: I'd add two more tests. In the one you adde you check whether what the command does works. But what if someone operates on the attributes themselves? Then they can do things in a different order and also they can mix those operations with other, potentially conflicting operations (e.g. set decorator attr, remove linkHref). I actually don't know what will happen in this case in the model as I don't know if there's some postfixer that cleans up decorator attrs.

Comment (maxbarnas) [reply packages/ckeditor5-link/tests/linkimageediting.js:831]: Just added another test for reversed order of downcasters. Will the first test be enough to cover the "regular" order, or should I explicitly add it?

Comment (maxbarnas) [reply packages/ckeditor5-link/tests/linkimageediting.js:831]: Actually, it makes sense to add another test with an explicit, "default" order of operations. Just in case the default behavior changes.
