### PR TITLE
[Document lists] Improve pasting plain-text lists and lists of different type into document list

### LINKED ISSUE #13826: List breaks when you paste content as plain text
## 📝 Provide detailed reproduction steps (if any)

1. Go to [demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html).
2. Create a list with two nested list items
3. Copy two list items from some other list
4. Put the cursor at the beginning of the first nested list item
5. Paste as plain text (`cmd+shift+v`)

### ✔️ Expected result

Content gets pasted as new list items or at least inside the list item. Example from Google Docs.
  
First paste is normal, second is pasted as plain tex:

https://user-images.githubusercontent.com/34380544/230026525-f03b6eb8-9078-4a90-b8aa-2c8c00baf8eb.mov

### ❌ Actual result

List breaks (happens for both normal and document lists).
  
First paste is normal, second is pasted as plain text:

https://user-images.githubusercontent.com/34380544/230026602-5f2d86b5-a00c-46b7-81d9-5e9e1272754d.mov

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by filipsobol**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (list): Pasting plain text content should not break the lists. Closes #13826.

Fix (list): Pasting one list into another should preserve the target list type. See #13826. 

---

#### Disclaimer

The issue reported in #13826 affects both Lists and DocumentLists. However, since we will soon be deprecating Lists, this PR only fixes DocumentLists.

When discussing this internally, we came to the conclusion that when pasting content into a list, we should do our best to **not** break it, even if the pasted content is not itself a list.

#### Pasting plain text

Copying and pasting plain text lists no longer breaks them.

[plain_text_paste.webm](https://github.com/ckeditor/ckeditor5/assets/4145208/e9825f97-8569-40a2-9a02-d318b4c26496)

#### Pasting paragraphs

Since plain text list items are just paragraphs, we can now also paste regular paragraphs without breaking the list too.

[pasting_paragraphs.webm](https://github.com/ckeditor/ckeditor5/assets/4145208/638b779c-95fc-48e9-8c69-0ca70ba733ec)

This also works when pasting lists separated by paragraphs.

[pasting_paragraph_mixed_with_lists.webm](https://github.com/ckeditor/ckeditor5/assets/4145208/f6c513ff-7c9c-41a6-ba29-dccd041de1ba)

This partially fixes issue reported in #11656, as pasting paragraphs no longer breaks the list. However, paragraphs pasted into a multi-line list item should place the content within it, not convert the paragraphs into new list items.

#### Preserving list style

When pasting both plain text and regular lists into another list, the original list type is preserved.

[preserving_list_style.webm](https://github.com/ckeditor/ckeditor5/assets/4145208/1c4286d6-ba0f-4c82-aa01-2f1498759d65)

### CODE REVIEW

**Comment by arkflpc** [comment]
> Don't break the list when pasting plain text content into it.
Please rephrase it, so it doesn't sound like an imperative to the changelog reader. Like "Fixes pastsing plaing text..." or "Pasting plaing text content should not break the list..."

**Review by arkflpc — APPROVED** [review]

File: packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts [hunk 1]
```diff
@@ -21,41 +21,61 @@ const smallPaddingElements = [ 'figcaption', 'li' ];
...
+function newLinePadding(
+	element: ViewElement,
+	previous: ViewElement | null
+): string {
+	if ( !previous ) {
+		// Don't add padding to first elements in a level.
+		return '';
+	}
+
+	if ( element.is( 'element', 'li' ) && !element.getChild( 0 )!.is( '$text' ) ) {
```
Comment (niegowski) [inline packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts:64]: I'm not sure if this is safe. We should check if there is any child before accessing it.

File: packages/ckeditor5-list/src/documentlist/documentlistediting.ts [hunk 2]
```diff
@@ -767,72 +768,68 @@ function modelChangePostFixer(
...
+
+				for ( const child of content.getChildren() ) {
+					const isListItem = isListItemBlock( child );
+
+					writer.setAttributes( {
+						listIndent: ( isListItem ? child.getAttribute( 'listIndent' ) : 0 ) + indentDiff,
+						listItemId: isListItem ? child.getAttribute( 'listItemId' ) : ListItemUid.next(),
+						listType: refType
+					}, child );
+				}
```
Comment (niegowski) [inline packages/ckeditor5-list/src/documentlist/documentlistediting.ts:832]: This part looks strange. You should not rely on the `content` type. It's just a different way of passing parameters to this function. The logic that alters the content should be unified.

**Review by niegowski — CHANGES_REQUESTED** [review]
Also, CI is failing on some tests.

File: packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts (hunk 1 above)
Comment (filipsobol) [reply packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts]: I added check to ensure that `element` is not empty

File: packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts [hunk 3]
```diff
@@ -21,41 +21,61 @@ const smallPaddingElements = [ 'figcaption', 'li' ];
...
+): string {
+	if ( !previous ) {
+		// Don't add padding to first elements in a level.
+		return '';
+	}
+
+	if ( element.is( 'element', 'li' ) && !element.isEmpty && !element.getChild( 0 )!.is( '$text' ) ) {
+		// Separate document list items with empty lines.
+		return '\n\n';
+	}
```
Comment (niegowski) [inline packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts:67]: If I understand this correctly, it's supposed to detect list items with blocks inside. This would fail on such a structure:

```html
<ul>
  <li>UL List item 1</li>
  <li><strong>UL List item 2</strong></li>
</ul>
```
The second LI would be detected as DocumentList but it's not in legacy lists.

Also, the code above would not detect properly simple lists in document lists.

Comment (filipsobol) [reply packages/ckeditor5-clipboard/src/utils/viewtoplaintext.ts]: I pushed fixes to:

* properly detect if element is a document list (https://github.com/ckeditor/ckeditor5/pull/15042/commits/8c16e9eecef64094a869060ae27c8a9472bac3b6),
* avoid breaking simple lists when pasting paragraphs or plain text lists (https://github.com/ckeditor/ckeditor5/pull/15042/commits/906ee8060383c1a3723a4043de78d9ab1df1fa39).

File: packages/ckeditor5-list/src/documentlist/documentlistediting.ts [hunk 4]
```diff
@@ -790,72 +788,73 @@ function modelChangePostFixer(
...
+
+			for ( const item of items ) {
+				const isListItem = isListItemBlock( item );
+
+				if ( refItem.is( 'element', 'listItem' ) && item.is( 'element', 'paragraph' ) ) {
+					/**
+					 * When paragraphs or a plain text list is pasted into a simple list, convert
+					 * the `<paragraphs>' to `<listItem>' to avoid breaking the target list.
+					 *
+					 * See https://github.com/ckeditor/ckeditor5/issues/13826
```
Comment (niegowski) [inline packages/ckeditor5-list/src/documentlist/documentlistediting.ts:848]:
```suggestion
					 * See https://github.com/ckeditor/ckeditor5/issues/13826.
```

**Review by niegowski — CHANGES_REQUESTED** [review]
Just a small bug while copying mixed lists:
