### PR TITLE
Fixed a crash when pasting lists from Word to the editor

### LINKED ISSUE #9055: Paste from word / List - List not pasting
Hey,

## 📝 Provide detailed reproduction steps (if any)

Here is a very basic list in a word document. Pasting it in the editor is impossible. 
The file : [List issue.docx](https://github.com/ckeditor/ckeditor5/files/6012340/List.issue.docx)

Screenshot of its content : 
Screenshot 2021-02-19 at 19 53 47

### ❌ Actual result

It's not pasting in my app, but it looks like it's not pasting in the demo editor in the "Paste from Word" documentation either. Same error I believe.

Screenshot from the Paste from word documention : 
Screenshot 2021-02-19 at 20 02 51

Screenshot from my app : 
Screenshot 2021-02-19 at 20 07 02

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #9954: Editor crashes after pasting double-commented text in a bulleted list from MS Word
## 📝 Provide detailed reproduction steps (if any)

1.  In MS Word create a new bulleted list with one item.
2.  Type something.
3.  Select the text, right-click on it and add a comment.
4.  Repeat step 3.
5.  Select all and copy.
6.  Paste it to https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo.

### ✔️ Expected result

The content pastes.

### ❌ Actual result

The editor crashes.

## 📃 Other details

It's a regression introduced in v24.0.0.

**Error**

```javascript
list.js:235 Uncaught TypeError: Cannot read property 'is' of undefined
    at findListMarkerNode (list.js:235)
    at findBulletedListStyle (list.js:202)
    at detectListStyle (list.js:183)
    at list.js:49
    at Array.forEach (<anonymous>)
    at transformListItemLikeElementsIntoLists (list.js:38)
    at MSWordNormalizer.execute (mswordnormalizer.js:49)
    at ClipboardPipeline.editor.plugins.get.on.priority (pastefromoffice.js:68)
    at ClipboardPipeline.fire (emittermixin.js:199)
    at Object.listenTo.priority (clipboardpipeline.js:179)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (paste-from-office): Fixed a crash when pasting lists from Word to the editor. Closes #9055. Closes #9954.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

**Comment by pomek** [comment]
Dear @ckeditor/qa-team, could you verify this solution?

**Comment by LukaszGudel** [comment]
It fixes all 3 scenarios/example files from linked tickets. I've played a bit with various content with lists, while mixing it with some inline styles and everything looks correctly or at least the same as in CKEditor 5 v23.1.0 (as this issue was a regression since v24.0.0). LGTM :+1:

File: packages/ckeditor5-paste-from-office/src/filters/list.js [hunk 1]
```diff
@@ -225,17 +225,23 @@ function findBulletedListStyle( element ) {
...
+	// If the first child is a text node, it is the data for the element.
+	// The list-style marker is not present here.
 	if ( element.getChild( 0 ).is( '$text' ) ) {
 		return null;
 	}
 
-	const textNodeOrElement = element.getChild( 0 ).getChild( 0 );
+	// The list-style marker will be inside the `<span>` element. Let's ignore all non-span elements.
+	// It may happen that the `<a>` element is added as the first child. Most probably, it's an anchor element.
+	let textNodeOrElement = [ ...element.getChildren() ].filter( element => element.is( 'element', 'span' ) );
```
Comment (jacekbogdanski) [inline packages/ckeditor5-paste-from-office/src/filters/list.js]: We are doing a lot of unnecessary operations here:

* converting iterable to an array which removes benefits from having a generator
* iterating through all elements with filter method

to only get the first span child. Parsing Office content has good overload already, so maybe we could improve this code a bit performance-wise?

I've added a commit message with the proposed change as I can't use GH suggestions on deleted content. Please take a look if you agree to these changes @pomek

**Review by jacekbogdanski — CHANGES_REQUESTED** [review]
Looks good! I really like that you added additional explanation comments to the code. It made the review much easier. Just a small suggestion to improve the code a bit.

File: packages/ckeditor5-paste-from-office/src/filters/list.js (hunk 1 above)
Comment (pomek) [reply packages/ckeditor5-paste-from-office/src/filters/list.js]: Thanks for the proposed change. It makes sense. Let's wait for a response for CI, and if it still is green, let's merge the PR.

Comment (pomek) [reply packages/ckeditor5-paste-from-office/src/filters/list.js]: As I can see, we're restarting one of the jobs because something fails, but it is not related to our work. I will verify the PR locally then we can merge it without waiting for CI results.

**Comment by pomek** [comment]
image
