### PR TITLE
#5866: To-do lists down-casting refactored

### LINKED ISSUE #5779: Adding a link to a to-do list item produces incorrect HTML
## 📝 Provide detailed reproduction steps (if any)

1. Open the to-do list manual test.
2. Create a new to-do list with 1 list item and a few words.
3. Select the first word.
4. Add a link.

### ✔️ Expected result

In the preview, the link is added only to the first word.

### ❌ Actual result

In the preview, the link is added to the whole list item.

## 📃 Other details

bug_cke5

Related - https://github.com/ckeditor/ckeditor5/issues/5775

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #5866: Pressing enter in the todolist created from code block crashes the editor
## 📝 Provide detailed reproduction steps (if any)

1. Create a code block that contains a few lines
1. Change it to todo-list 
1. Press enter after the first line

### ✔️ Expected result

No crash

### ❌ Actual result

Crash

## 📃 Other details

* Browser: All 
* OS: macOS
* CKEditor version: latest 15.0.0 (before the release)
* Installed CKEditor plugins: CodeBlock, TodoList

todolist

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #6585: Editor crashes after pressing Enter in a to-do list item with soft-break
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-5/demo/
2. Put the caret at the end of the paragraph
3. Press <kbd>Shift</kbd> + <kbd>Enter</kbd>
4. Transform the block into the to-do list
5. Move the selection to the end of the previous line
6. Press <kbd>Enter</kbd>

### ❌ Actual result

The editor crashes.

## 📃 Other details
**Error**

```js
Uncaught CKEditorError: view-writer-cannot-break-empty-element
    at Cn._breakAttributes (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:221317)
    at Cn.breakAttributes (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:213368)
    at Cs.Ks.downcastDispatcher.on.priority (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:321063)
    at Cs.fire (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:159513)
    at Cs.convertSelection (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:293257)
    at https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:319424
    at hs.change (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:262600)
    at Za.Ks.listenTo.priority (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:319336)
    at Za.fire (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:159513)
    at Za._handleChangeBlock (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:381807)
```

It seems to not be a regression, as I can reproduce it in v15.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (list): Editor should not crash on the enter key press inside a to-do list item containing soft-breaks. Closes #5866. Closes #6585.

Fix (list): Links inside a to-do list item should be properly converted to HTML. Closes #5779.

Feature (engine): Changed visibility scope of `Mapper#findPositionIn()` from `private` to `public`.

---

### Additional information

### CODE REVIEW

File: packages/ckeditor5-list/src/todolistediting.js [hunk 1]
```diff
@@ -106,10 +105,19 @@ export default class TodoListEditing extends Plugin {
...
-		editor.keystrokes.set( localizedJumpOverCheckmarkKey, ( evt, stop ) => jumpOverCheckmarkOnSideArrowKeyPress( stop, model ) );
+			if ( direction != 'left' ) {
+				return;
+			}
+
+			if ( jumpOverCheckmarkOnSideArrowKeyPress( model ) ) {
+				domEventData.preventDefault();
+				domEventData.stopPropagation();
+				eventInfo.stop();
+			}
```
Comment (jodator) [inline packages/ckeditor5-list/src/todolistediting.js:119]: Why not keep that in `jumpOverCheckmarkOnSideArrowKeyPress()` together:

```javascript
this.listenTo( editing.view.document, 'keydown', getJumpOverCheckmarkOnSideArrowKeyPress( editor ) );
// or just editor.locale.contentLanguageDirection + editor.model
```

so, no returning Boolean and stopping event propagation outside.

Comment (jodator) [reply packages/ckeditor5-list/src/todolistediting.js:119]: Yeah. Especially since now the method returns:

1.  `undefined`
2.  `true`
3.  `false`

There's something strange and at least should be double checked.
