### PR TITLE
#8871: Integrate inline images with the link feature

### LINKED ISSUE #8871: Integrate inline images with the link feature

### LINKED ISSUE #9017: Update inline image to use AttributeElement for links
## Provide a description of the task

Links should not break while spanning over text and inline images. This depends on #8998 - there will be an option to mark a `ContainerElement` as an inline so it will accept wrapping with an `AttributeElement` `<a>`.

### LINKED ISSUE #9167: The linked image indicator does not work well with small (inline) images
ATM we use the anchor icon as the only indicator for linked image. This works OK (also debatable) for large images but there's simply not enough space to do the same for a 32x32px inline image, which will be common in certain cases.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (link): Integrated the link feature with inline images. Closes #8871. Closes #9017. Closes #9167.

Other (image): Turned the image utils module into an editor plugin to allow sharing utils outside the package. Code refactoring (see #8871).

---

### Additional information

BREAKING CHANGE (image): The image utils module (`@ckeditor/ckeditor5-image/src/image/utils.js`) has turned into the [`ImageUtils` plugin](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils-ImageUtils.html). The helpers are still accessible via `editor.plugins.get( 'ImageUtils' )` namespace, for instance, `editor.plugins.get( 'ImageUtils' ).isImage( ... )`.

BREAKING CHANGE (image): The linked image indicator (icon) rendered as a `<span>` with the `.ck-link-image_icon` CSS class has been removed. To alter the look of the indicator (including the icon), please use `figure.image > a::after` (for linked block images) and `a span.image-inline::after` (for linked inline images) CSS selectors instead.

BREAKING CHANGE (image): The API of the [`insertImage()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils-ImageUtils.html#function-insertImage) helper has changed, please make sure to update your integrations.

BREAKING CHANGE (image): The `isImageWidget()` helper is no longer exposed by the [`Image`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image-Image.html) plugin. Use the [`ImageUtils`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils-ImageUtils.html#function-isImageWidget) plugin to access this helper instead.

BREAKING CHANGE (image): The API of common [image converters](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_converters.html) has changed. Please refer to the documentation to learn more.

BREAKING CHANGE (image): The API of various [image caption utils](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagecaption_utils.html) has changed. Please refer to the documentation to learn more.

### CODE REVIEW

File: packages/ckeditor5-link/src/linkimageediting.js [hunk 1]
```diff
@@ -115,6 +117,19 @@ function upcastLink() {
 				return;
 			}
 
+			const blockImageView = imageInLink.findAncestor( linkUtils.isBlockImageView.bind( linkUtils ) );
```
Comment (niegowski) [inline packages/ckeditor5-link/src/linkimageediting.js:120]:
```suggestion
			const blockImageView = imageInLink.findAncestor( element => linkUtils.isBlockImageView( element ) );
```

**Review by niegowski — CHANGES_REQUESTED** [review]
The image linking looks good but I really do not like that we put all the helpers into `ImageUtils`. I'd expect it to expose only the helpers used in the other package.

**Review by niegowski — CHANGES_REQUESTED** [review]
Some comments as below. Tests not reviewed yet.

**Comment by oleq** [comment]
There are plenty of conflicts now since #9459 was merged and I'm addressing them.

File: packages/ckeditor5-image/src/imageutils.js [hunk 2]
```diff
@@ -0,0 +1,345 @@
...
+// @param {module:engine/model/selection~Selectable} selection
+// @returns {Boolean}
+function isNotInsideImage( selection ) {
+	return [ ...selection.focus.getAncestors() ].every( ancestor => !ancestor.is( 'element', 'image' ) );
+}
+
+// Returns a node that will be used to insert image with `model.insertContent`.
+//
+// @private
+// @param {module:engine/model/selection~Selectable} selection
```
Comment (niegowski) [inline packages/ckeditor5-image/src/imageutils.js:293]:
```suggestion
// @param {module:engine/model/selection~Selection} selection
```

This could be also `DocumentSelection` but since this is internal helper we don't need to focus on that (same applies to other functions - I just skipped comments there)
