### PR TITLE
Link doesn't show a change in the link

### LINKED ISSUE #12588: When adding hyperlink without link text, editing the link doesn’t show a change in the link.
## 📝 Provide detailed reproduction steps (if any)

1. Click 'link' from the toolbar and type https://www.google.co.in and enter
2. Then click on link to reedit and enter https://about.google/
3. Editing the link doesn’t show a change in the link.

### ✔️ Expected result

On editing the link it should be changed.

### ❌ Actual result

but on editing the link doesn’t show a change in the link.
Screenshot 2022-10-06 at 12 32 36 PM

Browser: Google Chrome latest.
OS: macOS Monterey v12.3.1 

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix: Link doesn't show a change in the link. Closes #12588.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 1]
```diff
@@ -277,4 +288,37 @@ export default class LinkCommand extends Command {
 
 		return true;
 	}
+
+	private _updateLinkContent( model: Model, writer: Writer, range: Range, href: string ): Range {
+		const attributes = toMap( {} );
+
+		attributes.set( 'linkHref', href );
+
+		const text = writer.createText( href, attributes );
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:297]: How about just `writer.createText( href, { linkHref: href } )`?

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 2]
```diff
@@ -277,4 +288,37 @@ export default class LinkCommand extends Command {
 
 		return true;
 	}
+
+	private _updateLinkContent( model: Model, writer: Writer, range: Range, href: string ): Range {
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:292]: Missing API docs.

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 3]
```diff
@@ -277,4 +288,37 @@ export default class LinkCommand extends Command {
...
+		attributes.set( 'linkHref', href );
+
+		const text = writer.createText( href, attributes );
+
+		return model.insertContent( text, range );
+	}
+}
+
+function getTextFromRange( range: Range | null ): string {
+	if ( !range || range && !Array.from( range.getItems() ).length ) {
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:304]: You could simplify this one

```
const firstNode = first( range.getItems() );

if( !range || range && !firstNode ) { 
	... 
}
```

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 4]
```diff
@@ -277,4 +288,37 @@ export default class LinkCommand extends Command {
...
+
+		attributes.set( 'linkHref', href );
+
+		const text = writer.createText( href, attributes );
+
+		return model.insertContent( text, range );
+	}
+}
+
+function getTextFromRange( range: Range | null ): string {
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:303]: Missing API docs.

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 5]
```diff
@@ -277,4 +288,37 @@ export default class LinkCommand extends Command {
...
+		return '';
+	}
+
+	const firstNode = Array.from( range.getItems() )[ 0 ];
+
+	if ( firstNode.is( '$text' ) || firstNode.is( '$textProxy' ) ) {
+		return firstNode.data;
+	}
+
+	return '';
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:314]: I'd return `null` in this case. If there's no range or the range is empty or it has no text nodes, there's no text inside (semantics).

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 6]
```diff
@@ -142,6 +141,7 @@ export default class LinkCommand extends Command {
 	public override execute( href: string, manualDecoratorIds: Record<string, boolean> = {} ): void {
 		const model = this.editor.model;
 		const selection = model.document.selection;
+		const linkText = extractTextFromSelection( selection );
```
[the remark this answers is not in the document]
Comment (oleq) [reply packages/ckeditor5-link/src/linkcommand.ts:144]: This should also simplify the internal logic of the helper. For instance, you can assume there's always some range in the selection.

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 7]
```diff
@@ -227,14 +231,21 @@ export default class LinkCommand extends Command {
 				}
 
 				for ( const range of rangesToUpdate ) {
-					writer.setAttribute( 'linkHref', href, range );
+					let linkRange = range;
+
+					if ( selection.getAttribute( 'linkHref' ) === linkText ) {
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:236]: In the text extraction helper you're checking the text under the first position of the first range in the selection. 
Here, the code is iterating over multiple possible ranges that can accept the link. 
And on top of that, you're obtaining `linkHref`'s value from selection's attribute (which is the attribute value under the selection's first position only).

Check out this use-case:

```js
editor.setData( '<p><a href="foo">foo</a></p><p>bar</p><p>baz</p>' )

editor.model.change( writer => writer.setSelection( editor.model.document.getRoot(), 'in' ) );

editor.execute( 'link', 'foo' );

console.log( editor.getData() );
```

You'd expect the 2nd and 3rd paragraphs to keep their text after linking but their text gets replaced by "foo".

**Review by oleq — CHANGES_REQUESTED** [review]
Some bits of code can be simplified. Applying links to the non-collapsed selection needs work.

File: packages/ckeditor5-link/src/linkcommand.ts (hunk 3 above)
Comment (illia-stv) [reply packages/ckeditor5-link/src/linkcommand.ts:304]: but how we could get items from range until we didn't check is range null or not?
image

**Comment by illia-stv** [comment]
> * In the text extraction helper you're checking the text under the first position of the first range in the selection.
> * Here, the code is iterating over multiple possible ranges that can accept the link.
> * And on top of that, you're obtaining `linkHref`'s value from selection's attribute (which is the attribute value under the selection's first position only).
> * Result: there will be bugs :P
> 
> Check out this use-case:
> 
> ```js
> editor.setData( '<p><a href="foo">foo</a></p><p>bar</p><p>baz</p>' )
> 
> editor.model.change( writer => writer.setSelection( editor.model.document.getRoot(), 'in' ) );
> 
> editor.execute( 'link', 'foo' );
> 
> console.log( editor.getData() );
> ```
> 
> You'd expect the 2nd and 3rd paragraphs to keep their text after linking but their text gets replaced by "foo".



Regarding this comment, I suggest the next solution. We could just not modify the link even if it is equal to href when the selection is on more than one element. After applying the link's command selection should be the same, but if we would replace the link it brokes the selection and selection.**focus** will be set at the end of inserted content. so we also should handle this case. Then I propose simplifying everything and updating the link's content only in collapsed selection and if the range is only on one text element.

File: packages/ckeditor5-link/src/linkcommand.ts (hunk 3 above)
Comment (oleq) [reply packages/ckeditor5-link/src/linkcommand.ts:316]: TS is meant to help us but it's not all-knowing. We know that the model document selection in the editor has always at least one range and one position. There's no scenario when document selection has no ranges. We can use this to `!` certain things and simplify code.

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 8]
```diff
@@ -277,4 +291,46 @@ export default class LinkCommand extends Command {
...
+	return null;
+}
+
+function extractTextFromSelection( selection: DocumentSelection ): string | null {
+	const range = selection.getFirstRange( );
+	const firstPosition = selection.getFirstPosition();
+	const textFromPosition = firstPosition !== null && firstPosition.textNode && firstPosition.textNode.data || null;
+	const textFromRange = getTextFromRange( range );
+
+	return selection.isCollapsed ? textFromPosition : textFromRange;
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:335]: If `selection.isCollapsed === true`, you don't have to calculate `textFromRange`. If `false`, you don't have to calculate `textFromPosition`. It's a waste of time and degrades performance.

File: packages/ckeditor5-link/src/linkcommand.ts [hunk 9]
```diff
@@ -277,4 +291,46 @@ export default class LinkCommand extends Command {
...
+		return firstNode.data;
+	}
+
+	return null;
+}
+
+function extractTextFromSelection( selection: DocumentSelection ): string | null {
+	const range = selection.getFirstRange( );
+	const firstPosition = selection.getFirstPosition();
+	const textFromPosition = firstPosition !== null && firstPosition.textNode && firstPosition.textNode.data || null;
```
Comment (oleq) [inline packages/ckeditor5-link/src/linkcommand.ts:332]: You can safely assume `firstPosition`[ always exists](https://github.com/ckeditor/ckeditor5/pull/13702/files#r1143111217) and use `const textFromPosition = firstPosition!.textNode && firstPosition!.textNode.data`.

File: packages/ckeditor5-link/src/linkcommand.ts (hunk 3 above)
Comment (oleq) [reply packages/ckeditor5-link/src/linkcommand.ts:316]: This code could be simplified to

```js
function getTextFromRange( range: Range ): string | null {
	if ( range.isCollapsed ) {
        return null;
    }

	const firstNode = first( range.getItems() );

	if ( firstNode.is( '$text' ) || firstNode.is( '$textProxy' ) ) {
		return firstNode.data;
	}

	return null;
}
```

because:
1. you can safely assume there always will be a range, 
2. you don't have to engage `TreeWalker` to know there are no items in the range. A collapsed range has no items.

**Review by oleq — APPROVED** [review]
Waiting for the CI.
