### PR TITLE
I/8798 disable commands embed html

### LINKED ISSUE #8798: Some toolbar items are active when editing html embed
## 📝 Provide detailed reproduction steps (if any)

1. Add html embed, click `Edit source`
2. Add table / add media embed

### ✔️ Expected result

Table / media embed icons should be deactivated

### ❌ Actual result

Table / media embed is added after the html embed:  
  
0_embed1

- similar: https://github.com/ckeditor/ckeditor5/issues/8796
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by magda-chrzescian**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): The `insertTable` command should be disabled if any object is selected. Closes #8798.  

Fix (media-embed): The `insertMediaEmbed` command should be disabled if any non-media object is selected. See #8798.

Other (widget): The `checkSelectionOnObject` function should be exported by the `@ckeditor/ckeditor5-widget/src/utils package`. See #8798.

Tests (html-embed): The manual test should show the insert table and insert media buttons and describe their correct state. See #8798.

### CODE REVIEW

File: packages/ckeditor5-widget/src/utils.js [hunk 1]
```diff
@@ -304,6 +304,19 @@ export function findOptimalInsertionPosition( selection, model ) {
 	return selection.focus;
 }
 
+/**
+ * Checks if the selection is on object.
```
Comment (oleq) [inline packages/ckeditor5-widget/src/utils.js:308]:
```suggestion
 * Checks if the selection is on an object.
```

File: packages/ckeditor5-widget/tests/utils.js [hunk 2]
```diff
@@ -502,6 +503,58 @@ describe( 'widget utils', () => {
...
+
+		it( 'should return true if the selection is on the object', () => {
+			setData( model, '<paragraph></paragraph>[<image></image>]' );
+
+			const selection = model.document.selection;
+			const isSelectionOnObject = checkSelectionOnObject( selection, model.schema );
+
+			expect( isSelectionOnObject ).to.be.true;
+		} );
+	} );
```
Comment (oleq) [inline packages/ckeditor5-widget/tests/utils.js:556]: I think we're missing two cases here

*   `<paragraph>fo[o</paragraph><image></image><paragraph>ba]r</paragraph>` 
*   `<image>[foo]</image>` (this will require allowing `$text` in `image`)

File: packages/ckeditor5-media-embed/src/mediaembedcommand.js [hunk 3]
```diff
@@ -69,3 +64,29 @@ export default class MediaEmbedCommand extends Command {
...
+	return model.schema.checkChild( parent, 'media' );
+}
+
+// Checks if the media object is selected.
+//
+// @param {module:engine/model/selection~Selection|module:engine/model/documentselection~DocumentSelection} selection
+// @returns {Boolean}
+function isMediaSelected( selection ) {
+	const element = selection.getSelectedElement();
+	return element && element.name === 'media' || false;
```
Comment (oleq) [inline packages/ckeditor5-media-embed/src/mediaembedcommand.js:91]:
```suggestion
	return !!element && element.name === 'media';
```

is more natural and does not raise confusion regarding the order of operators.

File: packages/ckeditor5-widget/src/utils.js [hunk 4]
```diff
@@ -304,6 +304,19 @@ export function findOptimalInsertionPosition( selection, model ) {
...
+ *
+ * @param {module:engine/model/selection~Selection|module:engine/model/documentselection~DocumentSelection} selection
+ * @param {module:engine/model/schema~Schema} schema
+ * @returns {Boolean}
+*/
+export function checkSelectionOnObject( selection, schema ) {
+	const selectedElement = selection.getSelectedElement();
+
+	return selectedElement && schema.isObject( selectedElement ) || false;
```
Comment (oleq) [inline packages/ckeditor5-widget/src/utils.js:317]:
```suggestion
	return !!selectedElement && schema.isObject( selectedElement );
```

is simpler and does not make you think about the order of operators.

**Review by oleq — CHANGES_REQUESTED** [review]
LGTM! 

One small note, make sure you use Markdown in `Suggested merge commit message`. This saves time when merging the pull request :)

**Comment by pomek** [comment]
What about the horizontal line and page break features? They are also marked as an object in the schema and rendered as a widget in the editing data.

**Comment by oleq** [comment]
They're fine :)
