### PR TITLE
Fix MoveOperation x SplitOperation OT for some undo edge cases

### LINKED ISSUE #18415: Removing two or more selected paragraphs seem to not place on of paragraph to graveyard causing undo issue
## 📝 Provide detailed reproduction steps (if any)

1. Paste 3 or more paragraph into ckeditor
2. Select two paragraph from the end
3. Cut or remove
4. Click undo - paragraph will reappear
5. Click undo again - the last paragraph will be presented instead of all paragraph to be removed

I could reproduce it on demo projects in ckeditor repo

### ✔️ Expected result
Undo the paste operation should remove all pasted paragraphs.

_What is the expected result of the above steps?_

### ❌ Actual result

The last paragraph presented when paste operation should be undone.

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #18740: Elements are not correctly re-wrapped into blockquote after using undo
## 📝 Provide detailed reproduction steps (if any)

Scenario 1:

1. Create document content: `<p>A</p><blockquote><p>B</p><p>C</p></blockquote>`.
2. Unwrap all elements from blockquote.
3. Merge paragraph B to A.
4. Undo, undo.

Scenario 2:

1. Create document content: `<p>A</p><blockquote><p>B</p><p>C</p></blockquote>`.
2. Unwrap all elements from blockquote.
3. Merge paragraph C to B.
4. Undo, undo.

### ✔️ Expected result

In both scenarios, expected result is the editor content from step 1., i.e. `<p>A</p><blockquote><p>B</p><p>C</p></blockquote>`

### ❌ Actual result

Scenario 1:

`<p>A</p><blockquote><p>C</p></blockquote><p>B</p>`

Scenario 2:

`<p>A</p><blockquote><p>B</p></blockquote><p>C</p>`

### ❓ Possible solution

This happens due to incorrect `MoveOperation` x `SplitOperation` in OT during undo. The move operation range is first shrunk when first or last element in moved range is merged. But if the merge is undone, then on split, the move operation range is not expanded:

```
     <p>A</p>[<p>B</p><p>C</p>]
merge: <p>A</p>[<p>BC</p>]
split: <p>A</p>[<p>B</p>]<p>C</p>
```

```
     <p>A</p>[<p>B</p><p>C</p>]
merge: <p>AB</p>[<p>C</p>]
split: <p>A</p><p>B</p>[<p>C</p>]
```

This is why in these cases only one of the paragraphs ended up in the blockquote after undo.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (undo): Undo incorrectly restored content in scenario when a block quote (or other similar container) was unwrapped, then its former first or last element were merged, and then undo was used to restore block quote. Closes #18740. Closes #18415.

Internal (engine): Fixed `MoveOperation` x `SplitOperation` transformation for cases when first or last element to move was first merge and then split. See #18740.

Internal (engine): Changed `MoveOperation#type` to be `"move"` instead of `"remove"`, if the nodes where moved from graveyard root to graveyard root. Earlier behavior triggered special OT case when it shouldn't.

### CODE REVIEW

File: packages/ckeditor5-engine/src/model/operation/transform.ts [hunk 1]
```diff
@@ -1911,6 +1915,18 @@ setTransformation( MoveOperation, SplitOperation, ( a, b, context ) => {
 
 	// Case 1:
 	//
+	// Split operation brings back an element that wos earlier a part of the move operation (first element of the original move operation).
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/model/operation/transform.ts]:
```suggestion
	// Split operation brings back an element that was earlier a part of the move operation (first element of the original move operation).
```

**Review by niegowski — APPROVED** [review]

**Comment by charlttsie** [comment]
I've taken a look at issues mentioned in https://github.com/ckeditor/ckeditor5/pull/18741#pullrequestreview-2971101889:
- [#18415](https://github.com/ckeditor/ckeditor5/issues/18415) looks fixed also on my side
- [#17856](https://github.com/ckeditor/ckeditor5/issues/17856) still reproduces
- [#17856](https://github.com/ckeditor/ckeditor5/issues/17178) also reproduces for me
