### PR TITLE
#7285: Using full list of font-family values as a model attribute value.

### LINKED ISSUE #7285: Font Family is not applied correctly inside the editor when used with supportAllValues
## 📝 Provide detailed reproduction steps (if any)

1. Use the following configuration for your editor
```
fontFamily: {
            options: [
				'default',
				'Arial,Helvetica,sans-serif',
				'Courier New, Courier, monospace',
				'Georgia, serif',
				'Lucida Sans Unicode, Lucida Grande, sans-serif',
				'Tahoma, Geneva, sans-serif',
				'Times New Roman, serif',
				'Trebuchet MS, Helvetica, sans-serif',
				'Verdana, Geneva, sans-serif',
				'Ubuntu,Arial,sans-serif',
				'Ubuntu Mono, Courier New, Courier,monospace', 
				'Comic Sans MS,Comic Sans MS,cursive'
            ]
	   ,supportAllValues: true
},
```
2. Try to apply `Ubuntu` or `Ubuntu Moono` font.

### ✔️ Expected result

Whole font should be applied `'Ubuntu Mono, Courier New, Courier,monospace` just like when the above configuration is used without  `,supportAllValues: true` property.
without

### ❌ Actual result

Only the first part of font-family is applied, so in case of  `'Ubuntu Mono, Courier New, Courier,monospace'` this will be only `Ubuntu Mono` **and will have no effect**. 
supportAllValues

## 📃 Other details

* Browser: Any
* OS: Any
* CKEditor version: 19.0.0
* Installed CKEditor plugins: Font

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (font): Font Family should be applied correctly (all values of font families) inside the editor when used with `supportAllValues`. Closes #7285.

---

### Additional information

### CODE REVIEW

File: packages/ckeditor5-font/tests/fontfamily/fontfamilyui.js [hunk 1]
```diff
@@ -97,47 +99,67 @@ describe( 'FontFamilyUI', () => {
...
+				dropdown = editor.ui.componentFactory.create( 'fontFamily' );
+			} );
+
+			afterEach( async () => {
+				await editor.destroy();
+				element.remove();
+			} );
 
-					const listView = dropdown.listView;
+			it( 'should activate current option in dropdown for full font family definitions', () => {
```
Comment (oleq) [inline packages/ckeditor5-font/tests/fontfamily/fontfamilyui.js:133]:
```suggestion
			it( 'should activate the current option in the dropdown for full font family definitions', () => {
```

File: packages/ckeditor5-font/tests/fontfamily/fontfamilyui.js [hunk 2]
```diff
@@ -97,47 +99,67 @@ describe( 'FontFamilyUI', () => {
...
+
+				command.value = '\'Courier New\', Courier, monospace';
 
-					command.value = undefined;
+				// The third item is 'Courier New' font family.
+				expect( listView.items.map( item => item.children.first.isOn ) )
+					.to.deep.equal( [ false, false, true, false, false, false, false, false, false ] );
+			} );
+
+			it( 'should apply complete font-family value (list of font-families)', () => {
```
Comment (oleq) [inline packages/ckeditor5-font/tests/fontfamily/fontfamilyui.js:149]:
```suggestion
			it( 'should apply the complete font-family value (list of font-families)', () => {
```
