### PR TITLE
No longer keep todo list items placed on start of the editable when press backspace.

### LINKED ISSUE #18356: Removing the first checkbox from the to-do list is not possible / Removal of first list item or element
## 📝 Provide detailed reproduction steps (if any)

1. Open [feature-rich editor demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html)
2. Enter the to-do list and try to remove the first checkbox

### ✔️ Expected result

The checkbox is removed

### ❌ Actual result

There is no option to remove the first checkbox

https://github.com/user-attachments/assets/7dd99482-9cb3-4cdc-9756-a674814648f6

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: 44.3.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (typing): The list items and headings at the beginning of the editable area can be changed to a plain paragraph on backspace keypress. Closes #18356.

---

### Additional information

Caused by https://github.com/ckeditor/ckeditor5/issues/17383 and https://github.com/ckeditor/ckeditor5/pull/17809

### CODE REVIEW

**Review by gorzelinski — DISMISSED** [review]
I tested it on different browsers with key combinations - and it seems to work fine.

**Comment by Witoso** [comment]
Please check it with all list items, not just todo.

**Comment by Mati365** [comment]
@Witoso Been that, did that.

File: packages/ckeditor5-typing/src/delete.ts [hunk 1]
```diff
@@ -95,11 +95,29 @@ export default class Delete extends Plugin {
...
+			// See: https://github.com/ckeditor/ckeditor5/issues/18356
+			if (
+				selectionPosition.parent !== ancestorLimit &&
+				selectionPosition.parent.is( 'element' ) &&
+				[ ...selectionPosition.parent.getAttributeKeys() ].length
+			) {
+				return;
 			}
+
+			data.preventDefault();
```
Comment (niegowski) [inline packages/ckeditor5-typing/src/delete.ts:120]: Maybe a less synthetic solution would be to prevent-default the keydown event (as we do here). This would stop the invalid `beforeinput` event. Still, instead of detecting whether a parent has attributes, we could fire a `ViewDocumentDeleteEvent` (as listened above) that would replace the one generated with invalid target ranges. As we fire the `delete` event from the `DeleteObserver`, I'd suggest moving this keydown listener to `DeleteObserver`.

**Review by niegowski — CHANGES_REQUESTED** [review]
As commented above.

**Review by arkflpc — APPROVED** [review]
