### PR TITLE
Fix inline editor withArrow property.

### LINKED ISSUE #10529: There's a black rectangle rendered under inline editor's toolbar
## 📝 Provide detailed reproduction steps (if any)

Looks like the aftermath of recent `viewportTopOffset` changes. The panel gets obsolete `.ck-balloon-panel_with-arrow` without any specific arrow class.

### ❓ Possible solution

[This line used to do the trick](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js#L74) but now it's probably obsolete and things are handled on the fly as new positions are chosen for the panel. This worked for me

```diff
diff --git a/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js b/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
index c97ed66273..4b98ea591c 100644
--- a/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
+++ b/packages/ckeditor5-editor-inline/src/inlineeditoruiview.js
@@ -71,8 +71,6 @@ export default class InlineEditorUIView extends EditorUIView {
                    */
                   this.panel = new BalloonPanelView( locale );
 
-                  this.panel.withArrow = false;
-
                   /**
                    * A set of positioning functions used by the {@link #panel} to float around
                    * {@link #element editableElement}.
@@ -217,14 +215,20 @@ export default class InlineEditorUIView extends EditorUIView {
                                     return {
                                              top: this._getPanelPositionTop( editableRect, panelRect ),
                                              left: editableRect.left,
-                                             name: 'toolbar_west'
+                                             name: 'toolbar_west',
+                                             config: {
+                                                      withArrow: false
+                                             }
                                     };
                            },
                            ( editableRect, panelRect ) => {
                                     return {
                                              top: this._getPanelPositionTop( editableRect, panelRect ),
                                              left: editableRect.left + editableRect.width - panelRect.width,
-                                             name: 'toolbar_east'
+                                             name: 'toolbar_east',
+                                             config: {
+                                                      withArrow: false
+                                             }
                                     };
                            }
                   ];
```

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by dawidurbanski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (editor-inline): Set `withArrow` to `false` in inline editor toolbar balloon. Closes #10529.

### CODE REVIEW

File: packages/ckeditor5-editor-inline/src/inlineeditoruiview.js [hunk 1]
```diff
@@ -217,14 +215,20 @@ export default class InlineEditorUIView extends EditorUIView {
...
 			},
 			( editableRect, panelRect ) => {
 				return {
 					top: this._getPanelPositionTop( editableRect, panelRect ),
 					left: editableRect.left + editableRect.width - panelRect.width,
-					name: 'toolbar_east'
+					name: 'toolbar_east',
+					config: {
+						withArrow: false
+					}
```
Comment (oleq) [inline packages/ckeditor5-editor-inline/src/inlineeditoruiview.js:231]: Missing tests for these changes. They should land in this section https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-editor-inline/tests/inlineeditoruiview.js#L205.

**Review by oleq — CHANGES_REQUESTED** [review]
