### PR TITLE
Fixed list properties input behaviour when invalid values typed

### LINKED ISSUE #14939: Typing "e" in the numeric field causes overlap input content with its label
## 📝 Provide detailed reproduction steps (if any)

1. Go to numeric field in List Properties (Numbered List)
2. Type "e"
3. Leave the field
4. Go back
5. The entered content and label will overlap in the input

https://github.com/ckeditor/ckeditor5/assets/135701960/fe94d08d-5bf6-4c19-aa55-658f1ebaf957

### ✔️ Expected result

The content of a numeric field should not overlap with its label

### ❌ Actual result

The entered content and label overlap in the input

### ❓ Possible solution

The user probably shouldn't be able to write "e" in numeric fields because it's not needed for numbered lists

## 📃 Other details

* Browser: Chrome
* OS: Ventura 13.4
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #15848: Updating isEmpty state on InputBase is getting called multiple times
## 📝 Provide detailed reproduction steps (if any)

1. Have a log or debugger to check the `InputBase._updateIsEmpty` (from ui package) (fn that updates isEmpty state of the input view)
2. Make a numbered list
3. open the List properties plugin dropdown while on that list
4. Click on the start index input and type in any character

### ✔️ Expected result

The mentioned function should only get called once per valid input value change

### ❌ Actual result

Unnecessary calls of the function, `_updateIsEmpty` is called two or three times, which adds only a very tiny load to the  editor's performance, but a big disaster is a sum of many small ones isn't it.

### ❓ Possible solution

Seen that the double calls emerge from two-way kind of binding between `value` in the view and the DOM value of input, and the other way around happens probably after the DOM value propagates its event up.
Adding same value checks in one of the "secondary" events that trigger updateIsEmpty might be an option.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by map-r**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (list): Added new error message in case of an invalid value format in the input. Closes #14939 .
Other (theme-lark): Disabled scaling up of the label onto an empty input if there is an error (`LabeledFieldView`).

---

### Findings
During working on a fix, some side potential issues have been discovered, some of them are already documented under issue tickets:
- https://github.com/ckeditor/ckeditor5/issues/15849
- https://github.com/ckeditor/ckeditor5/issues/15850

### The error text:
The error was still required to both inform about a pasted value being a NaN (like `e`).
This error text can be merged with the original error message instead of having two messages, but in this situation all translations also have to adjust to the change, so either way we require some translation updates.

### CODE REVIEW

File: packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts [hunk 1]
```diff
@@ -366,6 +369,7 @@ export default class ListPropertiesView extends View {
 			const startIndex = inputElement.valueAsNumber;
 
 			if ( Number.isNaN( startIndex ) ) {
+				startIndexFieldView.errorText = t( 'Invalid start index value.' );
```
Comment (map-r) [inline packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts:372]: second-thought question: do we have any core translation for just 'invalid format' or something like this? we could avoid the new key.

File: packages/ckeditor5-list/lang/contexts.json [hunk 2]
```diff
@@ -24,6 +24,7 @@
 	"Upper-latin": "The tooltip text of the button that toggles the \"upper–latin\" list style.",
 	"List properties": "The label of the button that toggles the visibility of additional numbered list property UI fields.",
 	"Start at": "The label of the input allowing to change the start index of a numbered list.",
+	"Invalid start index value.": "The error message displayed when the numbered list is not a valid number",
```
Comment (DawidKossowski) [inline packages/ckeditor5-list/lang/contexts.json:27]: There is no `.` at the end of the message.

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js [hunk 3]
```diff
@@ -567,6 +567,76 @@ describe( 'ListPropertiesView', () => {
...
+				it( 'should not prevent from typing digits in the start index field', () => {
+					const keyEvent = {
+						key: '0',
+						keyCode: 48,
+						shiftCode: false
+					};
+					view.startIndexFieldView.fieldView.element.dispatchEvent( new KeyboardEvent( 'keydown', keyEvent ) );
+					const args = preventSpecialNumericValuesSpy.args[ 0 ];
+
+					expect( args[ 0 ].isTrusted ).to.equal( false );
```
Comment (DawidKossowski) [inline packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:587]: This check is useless in our case.

File: packages/ckeditor5-ui/src/input/inputbase.ts [hunk 4]
```diff
@@ -149,8 +149,10 @@ export default abstract class InputBase<TElement extends HTMLInputElement | HTML
 		// Bind `this.value` to the DOM element's value.
 		// We cannot use `value` DOM attribute because removing it on Edge does not clear the DOM element's value property.
 		this.on<ObservableChangeEvent>( 'change:value', ( evt, name, value ) => {
-			this._setDomElementValue( value );
-			this._updateIsEmpty();
+			if ( value?.toString() !== this.element!.value ) {
```
Comment (DawidKossowski) [inline packages/ckeditor5-ui/src/input/inputbase.ts:152]: We do not use `?.` operator since it could generate additional branches in unit tests.
I will send you ADR later.

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js [hunk 5]
```diff
@@ -567,6 +567,76 @@ describe( 'ListPropertiesView', () => {
 				view.keystrokes.press( keyEvtData );
 				sinon.assert.callCount( keyEvtData.stopPropagation, 4 );
 			} );
+
+			describe( 'special keys keydown event', () => {
```
Comment (DawidKossowski) [inline packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:571]: The tests do not accurately assess the true impact of  the `_preventSpecialNumericValues` function. Even if I remove the `event.preventDefault();` logic from this function, all tests still pass.

**Review by DawidKossowski — CHANGES_REQUESTED** [review]
After reviewing the entire code, the issue, and how this solution works, I think we need to adjust our approach slightly. Currently, there's still a possibility of pasting incorrect content into the number input, resulting in an error display. We would need to add further checks for such cases (on the `input` event) and handle them accordingly, which would again complicate our code.

Therefore, I believe the best approach is to withdraw the code responsible for blocking not allowed keys (`keydown` event) and leave only the error messages you've added. I've discussed this approach with Tomek, and it aligns with WCAG (error notification when user input contains incorrect value). Remember to write several unit tests.

I understand that we're changing concepts and approaches now, which is why it's crucial to consult on issues and work effects continuously.

File: packages/ckeditor5-ui/src/input/inputbase.ts (hunk 4 above)
Comment (DawidKossowski) [reply packages/ckeditor5-ui/src/input/inputbase.ts:152]: ADR: https://github.com/cksource/ckeditor5-commercial/blob/master/adr/0018-avoid-using-certain-operators.md

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js (hunk 3 above)
Comment (map-r) [reply packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:587]: yes, it was intentionally left for reviewer with a comment of mine (above) to explain context.

File: packages/ckeditor5-ui/src/input/inputbase.ts (hunk 4 above)
Comment (map-r) [reply packages/ckeditor5-ui/src/input/inputbase.ts:152]: thanks.

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js (hunk 5 above)
Comment (map-r) [reply packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:571]: Did you get to my comment about tests? If so, feel free to comment on that as at this point I'm not sure which approach would be better in terms of code quality.
https://github.com/ckeditor/ckeditor5/pull/15851#discussion_r1487968936

File: packages/ckeditor5-list/lang/contexts.json (hunk 2 above)
Comment (map-r) [reply packages/ckeditor5-list/lang/contexts.json:27]: I don't get it, I did the same as the other existing example below:
image

Comment (map-r) [reply packages/ckeditor5-list/lang/contexts.json:27]: Please explain what do you expect here

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js (hunk 5 above)
Comment (map-r) [reply packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:571]: actually I see now another approach to this, simply extracting only the regexp check, thus making this way simpler in tests. But , given general comment to shift approach, I should rather revert all tests and the logic addition.

**Comment by map-r** [comment]
> Therefore, I believe the best approach is to withdraw the code responsible for blocking not allowed keys (keydown event) and leave only the error messages you've added.
Just FYI, going with this change.

File: packages/ckeditor5-list/lang/contexts.json (hunk 2 above)
Comment (map-r) [reply packages/ckeditor5-list/lang/contexts.json:27]: okay, not the id but the message, now I get you I think:)

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js (hunk 5 above)
Comment (map-r) [reply packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js]: closing as outdated (removed)

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js [hunk 6]
```diff
@@ -708,6 +708,17 @@ describe( 'ListPropertiesView', () => {
 				sinon.assert.notCalled( spy );
 				expect( view.startIndexFieldView.errorText ).to.equal( 'Start index must be greater than 0.' );
 			} );
+
+			it( 'should not fire #listStart upon #input but display an error if the numeric value is NaN', () => {
```
Comment (DawidKossowski) [inline packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:712]: There are still no tests or assertions to verify the disappearance of error messages after typing the correct value.

File: packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts [hunk 7]
```diff
@@ -366,6 +366,7 @@ export default class ListPropertiesView extends View {
...
```
Comment (DawidKossowski) [inline packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.ts:369]: I would add a comment explaining the cases/values that could result in this error.

**Review by DawidKossowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js (hunk 6 above)
Comment (map-r) [reply packages/ckeditor5-list/tests/listproperties/ui/listpropertiesview.js:712]: okay, but I don't see them in all other tests, anyway good idea
