### PR TITLE
Fire `addMarker` event in data pipeline if marker is at element boundary

### LINKED ISSUE #8485: addMarker event is not called in data pipeline when range is at start of the root element
## 📝 Provide detailed reproduction steps (if any)

1. Open https://codepen.io/jacekbogdanski/pen/XWKwRjB?editors=1010
2. Open developer tools console.
3. Refresh the page.

### ✔️ Expected result

Debugger statement for `addMarker` event should stop script execution.

### ❌ Actual result

Nothing happens.

The issue seems to be caused by the https://github.com/ckeditor/ckeditor5/blob/eee94cef569a159ba1e59482d571e2413dde575c/packages/ckeditor5-engine/src/controller/datacontroller.js#L491-L510 function executed in https://github.com/ckeditor/ckeditor5/blob/eee94cef569a159ba1e59482d571e2413dde575c/packages/ckeditor5-engine/src/controller/datacontroller.js#L240-L248

It looks like when the marker range is at the start or end of the root it won't be contained in the root element range and the following code will fail to process markers.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (engine): Fire `addMarker` event in data pipeline if collapsed marker is at element boundary. Closes #8485.

### CODE REVIEW

File: packages/ckeditor5-engine/src/controller/datacontroller.js [hunk 1]
```diff
@@ -250,7 +250,7 @@ export default class DataController {
 		// Convert markers.
 		// For document fragment, simply take the markers assigned to this document fragment.
 		// For model root, all markers in that root will be taken.
-		// For model element, we need to check which markers are intersecting with this element and relatively modify the markers' ranges.
+		// For model element, we need to check which markers are contained in this element and relatively modify the markers' ranges.
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/controller/datacontroller.js:253]: This comment change is not entirely true - markers that are partly in that element are also included.

File: packages/ckeditor5-engine/src/controller/datacontroller.js [hunk 2]
```diff
@@ -541,10 +542,16 @@ function _getMarkersRelativeToElement( element ) {
 	const elementRange = ModelRange._createIn( element );
 
 	for ( const marker of doc.model.markers ) {
-		const intersection = elementRange.getIntersection( marker.getRange() );
+		const markerRange = marker.getRange();
 
-		if ( intersection ) {
-			result.push( [ marker.name, intersection ] );
+		const isMarkerCollapsedAtElementBoundary = markerRange.isCollapsed && ( markerRange.start.isAtStart || markerRange.start.isAtEnd );
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/controller/datacontroller.js:547]:
```suggestion
		const isMarkerCollapsedAtElementBoundary = markerRange.isCollapsed && ( markerRange.start.isEqual( elementRange.start) || markerRange.start.isEqual( elemenetRange.end ) );
```

File: packages/ckeditor5-engine/tests/controller/datacontroller.js [hunk 3]
```diff
@@ -671,6 +671,78 @@ describe( 'DataController', () => {
...
+				writer.addMarker( 'fooMarkerAtElementEnd', {
+					range: writer.createRange(
+						writer.createPositionFromPath( root, [ 1 ] ),
+						writer.createPositionFromPath( root, [ 1 ] )
+					),
+					usingOperation: true
+				} );
+			} );
+
+			data.toView( root );
```
Comment (niegowski) [inline packages/ckeditor5-engine/tests/controller/datacontroller.js:702]: Let's check how this looks in the view as in other tests it's done.

File: packages/ckeditor5-engine/src/controller/datacontroller.js (hunk 2 above)
Comment (niegowski) [reply packages/ckeditor5-engine/src/controller/datacontroller.js:547]: It's worth adding tests for the previous implementation - with a collapsed marker that is at the start or end of some other element (not included in the checked element) and for a collapsed marker at the start or end inside some deeper nested element.

**Review by niegowski — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-engine/src/controller/datacontroller.js (hunk 2 above)
Comment (psmyrek) [reply packages/ckeditor5-engine/src/controller/datacontroller.js]: Added.

File: packages/ckeditor5-engine/tests/controller/datacontroller.js (hunk 3 above)
Comment (psmyrek) [reply packages/ckeditor5-engine/tests/controller/datacontroller.js]: I rewrote the tests to make them look similar to others. I didn't use the `markerToHighlight` conversion, because it seems that it does not allow creating a collapsed marker. Instead, I'm using now `markerToData` helper.

**Review by niegowski — APPROVED** [review]
