### PR TITLE
Ck/10131 Whole word search with spaces

### LINKED ISSUE #10131: "Whole words only" checkbox does not work correctly when searching for query with 'space'
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/find-and-replace.html) page.
2.  Search for, for example: ` rather` in `foo rather bar`
3.  Check the "Whole words only" checkbox, and search again.

### ✔️ Expected result

One result remains highlighted.

NOTE: It's a valid use case to search for a term with a trailing space.

### ❌ Actual result

No results were shown.

## 📃 Other details

*   Browser: Chrome
*   OS: macOS BigSur 11.3
*   The same behavior can be replicated in manual tests.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (find-and-replace): Allows search term to contain trailing/leading space when searching 'whole word only'. Closes #10131.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-find-and-replace/src/utils.js [hunk 1]
```diff
@@ -138,7 +133,15 @@ export function findByTextCallback( searchTerm, options ) {
 	if ( options.wholeWords ) {
 		const nonLetterGroup = '[^a-zA-Z\u00C0-\u024F\u1E00-\u1EFF]';
 
-		regExpQuery = `(^|${ nonLetterGroup }|_)` + regExpQuery + `(?:_|${ nonLetterGroup }|$)`;
+		if ( !new RegExp( '^' + nonLetterGroup ).test( searchTerm ) )
+		{
+			regExpQuery = `(?<=^|${ nonLetterGroup }|_)${ regExpQuery }`;
```
Comment (niegowski) [inline packages/ckeditor5-find-and-replace/src/utils.js:138]: This option is unfortunately not supported by Safari so we need to find a better way.

Comment (arkflpc) [reply packages/ckeditor5-find-and-replace/src/utils.js]: Reverted to the previous mechanism.

File: packages/ckeditor5-find-and-replace/src/utils.js [hunk 2]
```diff
@@ -138,7 +139,15 @@ export function findByTextCallback( searchTerm, options ) {
...
-		regExpQuery = `(^|${ nonLetterGroup }|_)` + regExpQuery + `(?:_|${ nonLetterGroup }|$)`;
+		if ( !new RegExp( '^' + nonLetterGroup ).test( searchTerm ) )
+		{
+			regExpQuery = `(^|${ nonLetterGroup }|_)${ regExpQuery }`;
+		}
+
+		if ( !new RegExp( nonLetterGroup + '$' ).test( searchTerm ) )
+		{
+			regExpQuery = `${ regExpQuery }(?:_|${ nonLetterGroup }|$)`;
+		}
```
Comment (niegowski) [inline packages/ckeditor5-find-and-replace/src/utils.js:150]:
```suggestion
		if ( !new RegExp( '^' + nonLetterGroup ).test( searchTerm ) ) {
			regExpQuery = `(^|${ nonLetterGroup }|_)${ regExpQuery }`;
		}

		if ( !new RegExp( nonLetterGroup + '$' ).test( searchTerm ) ) {
			regExpQuery = `${ regExpQuery }(?:_|${ nonLetterGroup }|$)`;
		}
```
