### PR TITLE
AutoMediaEmbed should detach LiveRange

### LINKED ISSUE #6806: Media embed does not clear its LiveRange
Found by @FilipTokarski in table paste scenario.

### Steps to reproduce:

1. Go to table test
2. Copy `Table with 2 tbody` or `Table with no tbody`
3. Paste it into the big table
4. Select the big table and press `delete`

Expected: big table is deleted

Actual:
```js
Uncaught CKEditorError: model-createPositionAt-offset-required: Model#createPositionAt() requires the offset when the first parameter is a model item. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-createPositionAt-offset-required

    at Function._createAt (http://localhost:8125/ckeditor5-table/tests/manual/table.js:61264:11)
    at new Range (http://localhost:8125/ckeditor5-table/tests/manual/table.js:61560:66)
    at LiveRange._getTransformedByMove (http://localhost:8125/ckeditor5-table/tests/manual/table.js:62314:17)
    at LiveRange._getTransformedByMoveOperation (http://localhost:8125/ckeditor5-table/tests/manual/table.js:62096:15)
    at LiveRange.getTransformedByOperation (http://localhost:8125/ckeditor5-table/tests/manual/table.js:61968:17)
    at LiveRange.transform (http://localhost:8125/ckeditor5-table/tests/manual/table.js:53137:22)
    at Model.listenTo.priority (http://localhost:8125/ckeditor5-table/tests/manual/table.js:53125:14)
    at Model.fire (http://localhost:8125/ckeditor5-table/tests/manual/table.js:128091:30)
    at Model.<computed> [as applyOperation] (http://localhost:8125/ckeditor5-table/tests/manual/table.js:130254:16)
    at applyRemoveOperation (http://localhost:8125/ckeditor5-table/tests/manual/table.js:69302:8)
```

12_table_4

_Originally posted by @FilipTokarski in https://github.com/ckeditor/ckeditor5/pull/6786#issuecomment-627230047_

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (media-embed): AutoMediaEmbed should detach LiveRange. Closes #6806.

---

### Additional information

### CODE REVIEW

File: packages/ckeditor5-media-embed/tests/automediaembed.js [hunk 1]
```diff
@@ -573,6 +574,39 @@ describe( 'AutoMediaEmbed - integration', () => {
...
+					'<tableCell><paragraph>two</paragraph></tableCell>' +
+				'</tableRow>' +
+			'</table>'
+		);
+
+		expect( () => {
+			editor.setData( '' );
+		} ).not.to.throw();
+
+		editor.destroy();
```
Comment (jodator) [inline packages/ckeditor5-media-embed/tests/automediaembed.js:607]:
```suggestion
		await editor.destroy();
```
