### PR TITLE
Fix tableCell content inconsistency after executing editor.data.set

### LINKED ISSUE #13053: Markers change positions in tableCell after calling editor.data.set
Markers change positions in tableCells after multiple `editor.data.set( editor.data.get() )` commands.

More information: https://github.com/cksource/collaboration-features/issues/4061

### PR DESCRIPTION
**Pull request by kbinieda**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Fix tableCell content inconsistency after executing editor.data.set. Closes #13053.

### Additional information

Connected to: https://github.com/cksource/collaboration-features/issues/4061

### CODE REVIEW

**Review by scofalik — CHANGES_REQUESTED** [review]
This is a fine base solution but there are some things I dislike, so let's try to come up with something better.

What I don't like is that:

1.  This solution is not efficient.
2.  We leave some mess in the generated HTML.

---

In this solution, for every cell, we check every marker. This is highly inefficient in some CKE5 use cases, where you edit mostly huge tables and you use track changes (users have different roles and permissions).

We've already seen CKE5 being used with tables with hundreds of rows and, at the same time, with hundreds of suggestions. 500 rows x 5 columns x 200 suggestions gives you 500000 checks, and these are not exaggerated numbers.

To fix the efficiency but stick with this solution, we should rather look through all markers and then see whether particular marker is on a table cell. This will be faster, as it will only depend on number of markers. The question is - where and when to do it?

I have two candidates: evaluate the list of "affected cells" on every marker update (listen to `editor.markers`), or add a callback to `DataController#get` in which we will perform the check for every marker (affected cells can be passed in `options`). cc @niegowski.

---

The second problem: it would be best not to leave any mess in HTML. But, if we add extra markup, It looks like a simple `<span>` does it job, so we could skip the CSS class (not in the case of `asWidget`, of course).

However, there was already a similar problem in revision history and it was solved by forcing `<p>` rather than `<span>`. Whatever we do here, we will need to check whether a new approach works well with revision history.

---

As a next step, I'd go with the fixes I proposed so that we have a nice base solution. But it doesn't feel right that we need to hack it this way. This should "just work" ™.

I found an old ticket where I discuss the same problem (the new ticket is actually a DUP of that one: #11533). There is another ticket linked. After we have a nice base solution, we can try to solve it even better.

**Comment by scofalik** [comment]
The new solution is interesting as it does not change current solution heavily but it does not work well for images, for which it is correct to have a marker starting directly in a table cell (the editor throws an error because it tries to fix the marker but the `oldRange` is `null`).

We should not disallow such markers, such markers are okay. And we (CKS) are not only ones using markers. It should be allowed to create markers wherever people want.

So, I'd go back to the original solution and solve this in following way:

1.  Define a `Map` that will hold model table cell -> integer binding, where the integer is the number of markers in the cell. Or a similar structure.
2.  On markers `update` event, update the structure (remove table cell if there are no markers in that cell).
3.  Pass this structure to the converter.
4.  In the converter check if given table cell has markers, if so, return.

**Review by scofalik — CHANGES_REQUESTED** [review]
As described.

File: packages/ckeditor5-engine/src/conversion/upcasthelpers.ts [hunk 1]
```diff
@@ -523,7 +523,18 @@ export function convertText() {
...
+				const markerNode = position.nodeBefore;
+				position = wrapInParagraph( position, writer );
+
+				// Move $marker to paragraph
+				writer.move( writer.createRangeOn( markerNode ), position );
+
+				position = writer.createPositionAfter( markerNode );
+			} else {
+				position = wrapInParagraph( position, writer );
+			}
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/conversion/upcasthelpers.ts:537]:
```suggestion
			// Wrap `$text` in a paragraph and include any marker that is directly before `$text`. See #13053.
			const nodeBefore = position.nodeBefore;
			
			position = wrapInParagraph( position, writer );
			
			if ( nodeBefore && nodeBefore.is( 'element', '$marker' ) ) {
				// Move `$marker` to the paragraph.
				writer.move( writer.createRangeOn( nodeBefore ), position );

				position = writer.createPositionAfter( nodeBefore );
			}
```

Would this work?

**Review by scofalik — CHANGES_REQUESTED** [review]
I proposed code simplification. Other than that, a nice idea.

I am afraid that there are other places in the engine where we autoparagh text. Could you try to to find them and research whether they need fixing too?

I think we autoparagraph empty roots, although I don't know whether a root with just one paragraph and marker inside is downcasted to `<p><marker /></p>` or `<marker />` probably the first one, so this doesn't count.

We also autoparagraph in `insertContent()` but this has it's own markers handling, so I'd leave it for now.

I don't know about other places.

File: packages/ckeditor5-engine/src/conversion/upcasthelpers.ts [hunk 2]
```diff
@@ -523,7 +523,16 @@ export function convertText() {
 				return;
 			}
 
+			// Wrap $text in paragraph and include any marker that is directly before $text. #13053
```
Comment (scofalik) [inline packages/ckeditor5-engine/src/conversion/upcasthelpers.ts:526]:
```suggestion
			// Wrap `$text` in paragraph and include any marker that is directly before `$text`. See #13053.
```
