### PR TITLE
Fix incorrect upcast scan table heuristics responsible for creating heading rows.

### LINKED ISSUE #17556: editor.getData() returns invalid table in specific case
## 📝 Provide detailed reproduction steps (if any)

1. Open for example https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html
2. Create a 4x3 table
3. Merge cells from the second row and second column to the third row of the third column
4. Set the first column as the header
5. Use `editor.getData()` to extract HTML
6. Use `editor.setData()` to implement the table into the editor

### ✔️ Expected result

_`editor.getData()` returns a valid table without additional columns and rows_

### ❌ Actual result

_`editor.getData()` returns a table with additional columns and rows_

https://github.com/user-attachments/assets/d91a57a1-f78f-4127-8b14-3704fd17d2bc

## 📃 Other details

* Browser: Any
* OS: Any
* First affected CKEditor version: 37.0.0-alpha.1
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Mati365**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (table): Prevent table corruption when setting editor data with `th` cells following `colspan` rows. Closes #17556, #17404

---

### Additional information

Our table upcasting does not recognize colspans correctly during calculation of the header rows. This PR ensures that rows that follow the rows with colspans are not longer used as table headings.

<details>
   <summary>Check this HTML</summary>
   
   ```html
   	<figure class="table">
		<table>
			<tbody>
				<tr>
					<th>&nbsp;</th>
					<td colspan="2" rowspan="2">&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</figure>
	<figure class="table">
		<table>
			<tbody>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td colspan="2" rowspan="2">&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</figure>
	<figure class="table">
		<table>
			<tbody>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td colspan="2" rowspan="2">&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<th>&nbsp;</th>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</figure>
   ```
</details> 

#### Before

obraz

#### After

obraz

### CODE REVIEW

**Review by pszczesniak — DISMISSED** [review]
The fix is working as expected, didn't found any side effects :+1:

File: packages/ckeditor5-table/src/converters/upcasttable.ts [hunk 1]
```diff
@@ -263,6 +275,11 @@ function scanTable( viewTable: ViewElement ) {
 					headingColumns = headingCols;
 				}
 			}
+
+			// We use the maximum number of columns to avoid false positives when detecting
+			// multiple rows with single column within `rowspan`. Without it the last row of `rowspan=3`
+			// would be detected as a heading row because it has only one column (identical to the previous row).
+			maxPrevColumns = Math.max( maxPrevColumns || -Infinity, trColumns.length );
```
Comment (niegowski) [inline packages/ckeditor5-table/src/converters/upcasttable.ts:282]: Can we make it simpler like this?

```suggestion
			maxPrevColumns = Math.max( maxPrevColumns || 0, trColumns.length );
```

**Review by niegowski — APPROVED** [review]

**Review by pszczesniak — APPROVED** [review]

**Comment by Proudloaf** [comment]
Great news that this one has been fixed, nice work! Any rough idea on when it might get released?

**Comment by Witoso** [comment]
Mid-Jan or early February.

**Comment by Proudloaf** [comment]
Excellent, thanks!

**Comment by Mati365** [comment]
@Proudloaf While we'll release it in the stable next year, there is a way to check it on our nightly builds. Keep in mind, that it's unstable and should not be used on production.

**Comment by Proudloaf** [comment]
Fair enough, we're planning on updating to 44.1.0 very soon anyway, so once we have that stable we'll give it a go on your nightly. Thanks
