### PR TITLE
#7275: Paste from Office should use the same instance of StylesProcessor as editor

### LINKED ISSUE #7275: Copy Word table and pasting into CKE5 loses table cell background color
## 📝 Provide detailed reproduction steps (if any)

1. Visit demo page [Pasting content from Microsoft Word](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo)
2. Download [sample Word document](https://ckeditor.com/docs/ckeditor5/latest/assets/CKEditor5.PFO.Sample.Recognition_of_Achievement.docx)
3. Copy table from sample Word document and paste it into the demo editor

Screen Shot 2020-05-22 at 12 18 09 PM

Screen Shot 2020-05-22 at 12 18 49 PM

### ✔️ Expected result

Copied table cell background colors from Word document are properly transferred to Ckeditor5 as described at [Table styles compatibility with CKEditor 4 and office suites (Word, Excel, Google Docs) #5652](https://github.com/ckeditor/ckeditor5/issues/5652). 

### ❌ Actual result

Table loses cell background color data after it is pasted into CKE. This appears to be happening in upcasting (?); some table cell inline styles are transferred to attributes, while others are not.

## 📃 Other details

* Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
* OS: macOS Catalina Version 10.15.4 (19E287)
* CKEditor version: @ckeditor/ckeditor5-editor-classic@18.0.0
* Installed CKEditor plugins: A bunch, but this issue exists in the demo editor at [Pasting content from Microsoft Word](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-from-word.html#demo)
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (paste-from-office): Paste from Office should use the same instance of StylesProcessor as editor. Closes #7275.

---

### Additional information

### CODE REVIEW

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team

File: packages/ckeditor5-paste-from-office/src/normalizers/mswordnormalizer.js [hunk 1]
```diff
@@ -20,6 +20,14 @@ const msWordMatch2 = /xmlns:o="urn:schemas-microsoft-com/i;
  * @implements module:paste-from-office/normalizer~Normalizer
  */
 export default class MSWordNormalizer {
+	constructor( document ) {
```
Comment (jodator) [inline packages/ckeditor5-paste-from-office/src/normalizers/mswordnormalizer.js:23]: Missing annotation.

**Comment by FilipTokarski** [comment]
I checked it and pasted content looks pretty good now. It solves the latest issues with highlight and background colors in tables pasted from Word 👍
