### PR TITLE
Keyboard navigation in insert table dropdown should not be reversed in rtl editor

### LINKED ISSUE #12871: Keyboard navigation in grid dropdowns should not be reversed in RTL editor
## 📝 Provide detailed reproduction steps (if any)

1.  Open [demo with RTL editor](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#demo-2).
2.  Open the insert table dropdown.
3.  Press arrow left.

### ❓ Possible solution

The right/left arrow navigation is reversed. It should work naturally instead.

The same thing happens for all grids in the editor UI:
- color picker
- styles
- special characters
- list styles

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by illia-stv**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (Table): Keyboard navigation in insert table dropdown should not be reversed in RTL editor. Closes #12871.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-ui/tests/bindings/addkeyboardhandlingforgrid.js [hunk 1]
```diff
@@ -275,6 +275,72 @@ describe( 'addKeyboardHandlingForGrid()', () => {
 		} );
 	} );
 
+	describe( 'arrows moves in rtl', () => {
+		let view, keystrokes, focusTracker, gridElementsCollection, numberOfColumnsStub, uiLanguageDirection;
```
Comment (Dumluregn) [inline packages/ckeditor5-ui/tests/bindings/addkeyboardhandlingforgrid.js:279]: You don't really need any of those variables:

*   `view, keystrokes, focusTracker, gridElementsCollection` are all already in the scope so you can reassign them.
*   `numberOfColumnsStub, uiLanguageDirection` have always the same values in your tests, so these values can be used directly.

**Review by Dumluregn — CHANGES_REQUESTED** [review]
Besides the inline comments - there are still two more grids awaiting the handling: list styles:



and styles dropdown:

File: packages/ckeditor5-special-characters/src/ui/charactergridview.js [hunk 2]
```diff
@@ -82,7 +82,8 @@ export default class CharacterGridView extends View {
 				.getComputedStyle( this.element.firstChild ) // Responsive .ck-character-grid__tiles
 				.getPropertyValue( 'grid-template-columns' )
 				.split( ' ' )
-				.length
+				.length,
+			uiLanguageDirection: this.locale && this.locale.uiLanguageDirection
```
[the remark this answers is not in the document]
Comment (illia-stv) [reply packages/ckeditor5-special-characters/src/ui/charactergridview.js:86]: Screenshot 2022-11-24 at 12 34 01

File: packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts [hunk 3]
```diff
@@ -84,4 +82,52 @@ export default function addKeyboardHandlingForGrid(
 			evt.preventDefault();
 		};
 	}
+
+	// Function returning a right index relatively current index.
```
Comment (Dumluregn) [inline packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts:86]: The function actually doesn't know, how many elements there are in the grid row. It sees the collection linearly - only knows where it starts and ends. So the more correct description is that it returns a next index, and if the last element is being checked, returns the first index (0).

File: packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts [hunk 4]
```diff
@@ -84,4 +82,52 @@ export default function addKeyboardHandlingForGrid(
...
+	// If current index is at the left conner, function return last index of previous row.
+	//
+	// before: [ ][ ][ ]	after: [ ][ ][x]
+	//         [x][ ][ ]	       [ ][ ][ ]
+	//         [ ]      	       [ ]
+	// index = 2            index = 0
+	//
+	// @param {number} [elementIndex] Number of current index.
+	// @param {module:ui/viewcollection~ViewCollection} [gridItems] A collection of grid items.
+	function getLeftElementIndex( elementIndex: number, gridItems: ViewCollection ) {
```
Comment (Dumluregn) [inline packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts:126]: Same comments as for the previous function, only with a change in the docs - if the first index is passed, it returns the last one.

File: packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts [hunk 5]
```diff
@@ -84,4 +82,52 @@ export default function addKeyboardHandlingForGrid(
...
+	//
+	// @param {number} [elementIndex] Number of current index.
+	// @param {module:ui/viewcollection~ViewCollection} [gridItems] A collection of grid items.
+	function getRightElementIndex( elementIndex: number, gridItems: ViewCollection ) {
+		if ( elementIndex === gridItems.length - 1 ) {
+			return 0;
+		} else {
+			return elementIndex + 1;
+		}
+	}
```
Comment (Dumluregn) [inline packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts:108]: It's usually a good practise to only pass what is necessary to the function - it makes it easier to understand, refactor etc. Here, if you look carefully, we're passing `gridItems` object, but the function actually only uses its length - so it makes sense to pass just that - the length of the collection, and name it e.g. `collectionLength`. It will show that we don't do any operations on the collection inside the function.

File: packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js [hunk 6]
```diff
@@ -203,7 +203,8 @@ export default class ListPropertiesView extends View {
 					.getComputedStyle( this.stylesView.element )
 					.getPropertyValue( 'grid-template-columns' )
 					.split( ' ' )
-					.length
+					.length,
+				uiLanguageDirection: this.locale.uiLanguageDirection
```
Comment (Dumluregn) [inline packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js:207]: I did some digging and I see that `locale` is optional in all the packages that are already rewritten to TS, so we can safely assume it will happen also for this one - let's add the check you've provided elsewhere: `this.locale && this.locale.uiLanguageDirection`.

File: packages/ckeditor5-style/src/ui/stylegridview.js [hunk 7]
```diff
@@ -130,7 +130,8 @@ export default class StyleGridView extends View {
 			keystrokeHandler: this.keystrokes,
 			focusTracker: this.focusTracker,
 			gridItems: this.children,
-			numberOfColumns: 3
+			numberOfColumns: 3,
+			uiLanguageDirection: this.locale.uiLanguageDirection
```
Comment (Dumluregn) [inline packages/ckeditor5-style/src/ui/stylegridview.js:134]: I did some digging and I see that `locale` is optional in all the packages that are already rewritten to TS, so we can safely assume it will happen also for this one - let's add the check you've provided elsewhere: `this.locale && this.locale.uiLanguageDirection`.

File: packages/ckeditor5-table/src/ui/inserttableview.js [hunk 8]
```diff
@@ -158,7 +158,8 @@ export default class InsertTableView extends View {
 			keystrokeHandler: this.keystrokes,
 			focusTracker: this.focusTracker,
 			gridItems: this.items,
-			numberOfColumns: 10
+			numberOfColumns: 10,
+			uiLanguageDirection: this.locale.uiLanguageDirection
```
Comment (Dumluregn) [inline packages/ckeditor5-table/src/ui/inserttableview.js:162]: I did some digging and I see that `locale` is optional in all the packages that are already rewritten to TS, so we can safely assume it will happen also for this one - let's add the check you've provided elsewhere: `this.locale && this.locale.uiLanguageDirection`.

File: packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts [hunk 9]
```diff
@@ -21,31 +21,29 @@ import type ViewCollection from '../viewcollection';
  * @param {module:ui/viewcollection~ViewCollection} options.gridItems A collection of grid items.
  * @param {Number|Function} options.numberOfColumns Number of columns in the grid. Can be specified as a function that returns
  * the number (e.g. for responsive grids).
+ * @param {String|Undefined} options.uiLanguageDirection String of ui language direction.
```
Comment (Dumluregn) [inline packages/ckeditor5-ui/src/bindings/addkeyboardhandlingforgrid.ts:24]: We use lowercase `undefined` for types (same with `null`).

**Review by Dumluregn — CHANGES_REQUESTED** [review]

**Review by Dumluregn — APPROVED** [review]
LGTM, well done :clap:
