### PR TITLE
Inheriting the `listStyle` attribute for elements inserted next to the existing list

### LINKED ISSUE #7932: Creating a numbered list above an unordered list results with a unordered
## 📝 Provide detailed reproduction steps (if any)

1.  Open [lists feature demo](https://ckeditor.com/docs/ckeditor5/latest/features/link.html) for the upcoming v21 release (not not published yet, so production link won't work).
2.  Focus the editor under the "List styles" section.
3.  Put the selection in the "Ingredients required for making a coffee:" paragraph.
4.  Press "Numbered list" button.

### ✔️ Expected result

Should create a numbered list.

### ❌ Actual result

It makes unordered list instead.

## 📃 Other details

It doesn't happen if there's no list styles demo.

*   Browser: Chrome (didn't check others, but my assumption is that it's a cross-browser thing)
*   OS: Windows
*   CKEditor version: v21.0.0
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (list): The `listStyle` attribute should be inherited when inserting or replacing a `listItem` with the same kind of the list (the `listType` attribute for the inserted/modified item is equal to next/previous sibling list). Closes #7932.

### CODE REVIEW

File: packages/ckeditor5-list/src/liststyleediting.js [hunk 1]
```diff
@@ -573,3 +556,34 @@ function restoreDefaultListStyle( editor ) {
...
+		if ( change.type === 'attribute' ) {
+			return change.range.start.nodeAfter;
+		}
+
+		if ( change.type === 'insert' ) {
+			return change.position.nodeAfter;
+		}
+
+		return null;
+	}
```
Comment (jodator) [inline packages/ckeditor5-list/src/liststyleediting.js]: I'd move this out of the parent function. It is re-created on every `getChangedListItems()` call (taking whole scope, etc) and as it is pure it can be placed outside.

No special docs are needed for it as it is small an pretty self-explanatory.

File: packages/ckeditor5-list/src/liststyleediting.js [hunk 2]
```diff
@@ -509,6 +506,10 @@ function fixListStyleAttributeOnListItemElements( editor ) {
 			return false;
 		}
 
+		if ( baseItem.getAttribute( 'listType' ) !== itemToChange.getAttribute( 'listType' ) ) {
+			return false;
+		}
+
```
Comment (jodator) [inline packages/ckeditor5-list/src/liststyleediting.js:507]: I'm thinking aloud here:

*   I like that it has the same pattern as above check.
*   I don't like the fact that the last check _could_ be a return.

```javascript
return baseItem.getAttribute( 'listType' ) === itemToChange.getAttribute( 'listType' );
```

However, in this scenario both are OK so it's just a matter of a preference here I think.

For now, this function makes all the checks as I could think of and maybe keeping a same pattern has more benefits here rather than going with preferred `if-else` return form.

**Review by jodator — APPROVED** [review]
LGTM :+1: I had some minor comments - one dissertation about ifs and second one which I've applied already. 

ps.: Please check them as I'm going to close this PR as generally it was OK and the change was minor.

**Comment by pomek** [comment]
@jodator, LGTM.
