### PR TITLE
Fix export ColorPaletteIcon from ckeditor5-ui.

### LINKED ISSUE #14205: error TS2307: Cannot find module
## 📝 Provide a description of requested docs changes

image

image

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (ui): Fixes export of `ColorPaletteIcon` from `ckeditor5-ui`. Closes #14205.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-ui/src/index.ts [hunk 1]
```diff
@@ -75,6 +75,8 @@ export { default as BlockToolbar } from './toolbar/block/blocktoolbar';
 export { default as View, type UIViewRenderEvent } from './view';
 export { default as ViewCollection } from './viewcollection';
 
-export { default as ColorPaletteIcon } from '../theme/icons/color-palette.svg';
+import { default as colorPalette } from '../theme/icons/color-palette.svg';
+
+export const ColorPaletteIcon = colorPalette;
```
Comment (Reinmar) [inline packages/ckeditor5-ui/src/index.ts:80]: Is it consistent with other icons that this one is UpperCased?

Comment (Reinmar) [reply packages/ckeditor5-ui/src/index.ts:80]: Actually, I can't see any other icon exported this way:

Comment (mlewand) [reply packages/ckeditor5-ui/src/index.ts]: Other icons (coming from our premium features) are exported lowercased so that's what we do here as well.
