### PR TITLE
Fix (engine). Fixes calling writer.setSelection() so that it does not break the editor.

### LINKED ISSUE #11925: Calling writer.setSelection on an invalid selection breaks the editor
## 📝 Provide detailed reproduction steps (if any)

1. Make a selection in the CKE5 editor and run `let s = editor.model.document.selection.getFirstRange()`
2. Remove text or lines such that the selection location is no longer valid (this bug won't happen if you delete the line with selected text only to have another equally long line take its place)
3. Run `editor.model.change((writer) => {writer.setSelection(s)})`
4. CKE will throw error `Uncaught CKEditorError: model-nodelist-offset-out-of-bounds` and remain broken until reloaded

### ✔️ Expected result

The `writer.setSelection` call should just throw an error and abort

### ❌ Actual result

The editor becomes buggy until reloaded - any time you try clicking or selecting the cursor snaps back to the failed selection location.

https://www.screencast.com/t/bUHzZVnvQ2Q

```
ckeditorerror.js:104 Uncaught CKEditorError: model-nodelist-offset-out-of-bounds {"offset":7,"nodeList":[{"data":"sfaafs"}]}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
    at NodeList.offsetToIndex (nodelist.js:161:1)
    at Element.offsetToIndex (element.js:186:1)
    at getTextNodeAtPosition (position.js:1100:1)
    at get textNode [as textNode] (position.js:218:1)
    at validateTextNodePosition (document.js:473:1)
    at Document._validateSelectionRange (document.js:382:1)
    at LiveSelection.<anonymous> (documentselection.js:666:1)
    at LiveSelection.fire (emittermixin.js:199:1)
    at LiveSelection._setRanges (selection.js:471:1)
    at LiveSelection.setTo (selection.js:376:1)
```

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (engine). Fixes calling `writer.setSelection()` so that it does not break the editor. Closes #11925.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-engine/src/model/documentselection.ts [hunk 1]
```diff
@@ -897,6 +888,25 @@ class LiveSelection extends Selection {
 		}
 	}
 
+	private _validateSelectionRanges( ranges: Iterable<Range> ) {
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/model/documentselection.ts:891]: Missing JSDoc.
