### PR TITLE
Fixed an edge case where mention is sometimes still displayed in a code block.

### LINKED ISSUE #19992: Further improvements for disabling mentions in code blocks.
## 📝 Provide a description of the improvement

While the fix works correctly for the primary scenario (typing a marker character inside a code block) here: https://github.com/ckeditor/ckeditor5/pull/19984, there is still an edge case worth being aware of: if a marker pattern (e.g. /head or :) is already present inside a code block and you click to position the cursor right after it, the autocomplete panel appears.

https://github.com/user-attachments/assets/bddf65a8-f891-4dc5-be13-20121c94a0cd

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by martnpaneq**
### 🚀 Summary

Fixed an edge case where the mention panel could still appear if an async feed response arrived after the cursor had moved into a code block.

https://github.com/user-attachments/assets/96637f2a-a6f7-431e-bbee-85433df7dba2

---

### 📌 Related issues

* Closes #19992

---

### 💡 Additional information

*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*

---

### 🧾 Checklists

Use the following checklists to ensure important areas were not overlooked.
This does not apply to feature-branch merges.
If an item is **not relevant** to this type of change, simply leave it unchecked.

#### Author checklist

- [x] Is the changelog entry intentionally omitted?
- [x] Is the change backward-compatible?
- [x] Have you considered the impact on different editor setups and core interactions? _(e.g., classic/inline/multi-root/many editors, typing, selection, paste, tables, lists, images, collaboration, pagination)_
- [x] Has the change been manually verified in the relevant setups?
- [x] Does this change affect any of the above?
- [x] Is performance impacted?
- [x] Is accessibility affected?
- [x] Have tests been added that fail without this change (against regression)?
- [x] Have the API documentation, guides, feature digest, and related feature sections been updated where needed?
- [x] Have metadata files (ckeditor5-metadata.json) been updated if needed?
- [x] Are there any changes the team should be informed about (e.g. architectural, difficult to revert in future versions or having impact on other features)?
- [x] Were these changes documented (in Logbook)?

#### Reviewer checklist

- [ ] PR description explains the changes and the chosen approach (especially when  performance, API, or UX is affected).
- [ ] The changelog entry is clear, user‑ or integrator-facing, and it describes any breaking changes.
- [ ] All new external dependencies have been approved and mentioned in LICENSE.md (if any).
- [ ] All human-readable, translateable strings in this PR been introduced using `t()` (if any).
- [x] I manually verified the change (e.g., in manual tests or documentation).
- [x] The target branch is correct.

### CODE REVIEW

File: packages/ckeditor5-mention/tests/mentionui.js [hunk 1]
```diff
@@ -727,6 +727,105 @@ describe( 'MentionUI', () => {
 				codeBlockEditorElement.remove();
 			} );
 
+			it( 'should not show panel when feed response arrives after cursor moved into a code block', async () => {
```
Comment (mmotyczynska) [inline packages/ckeditor5-mention/tests/mentionui.js]: I noticed this test passes even without the fix - do you think it's still needed?

If so, maybe we could make it a bit more specific to cover the intended behavior? And if not, perhaps we could consider removing it, especially since there's already another test covering the new code. WDYT?

File: packages/ckeditor5-mention/tests/mentionui.js [hunk 2]
```diff
@@ -727,6 +727,105 @@ describe( 'MentionUI', () => {
...
+				expect( codeBlockPanelView.isVisible ).to.be.false;
+
+				await codeBlockEditor.destroy();
+				codeBlockEditorElement.remove();
+			} );
+
+			it( 'should not show panel when feed response arrives after mention command was disabled', async () => {
+				let feedResolve;
+
+				const codeBlockEditorElement = document.createElement( 'div' );
```
Comment (mmotyczynska) [inline packages/ckeditor5-mention/tests/mentionui.js]: Small suggestion: we usually refer to this as `editorElement` or `element` in the codebase, so it might be good to keep it consistent here as well 🙂

File: packages/ckeditor5-mention/tests/mentionui.js [hunk 3]
```diff
@@ -727,6 +727,105 @@ describe( 'MentionUI', () => {
...
+				document.body.appendChild( codeBlockEditorElement );
+
+				const codeBlockEditor = await ClassicTestEditor.create( codeBlockEditorElement, {
```
Comment (mmotyczynska) [inline packages/ckeditor5-mention/tests/mentionui.js]: As above: we usually refer to this as `editor` in the codebase.

File: packages/ckeditor5-mention/tests/mentionui.js [hunk 4]
```diff
@@ -727,6 +727,105 @@ describe( 'MentionUI', () => {
...
+						feeds: [ {
+							marker: '@',
+							feed: () => new Promise( resolve => {
+								feedResolve = resolve;
+							} )
+						} ]
+					}
+				} );
+
+				const codeBlockModel = codeBlockEditor.model;
```
Comment (mmotyczynska) [inline packages/ckeditor5-mention/tests/mentionui.js]: As above: we usually refer to this as `model` in the codebase.

File: packages/ckeditor5-mention/tests/mentionui.js [hunk 5]
```diff
@@ -727,6 +727,105 @@ describe( 'MentionUI', () => {
...
+				const codeBlockPanelView = codeBlockEditor.plugins.get( ContextualBalloon ).view;
```
Comment (mmotyczynska) [inline packages/ckeditor5-mention/tests/mentionui.js]: Maybe `panelView` would be a clearer name here, since this panel doesn't seem to be specific to the code block.

File: packages/ckeditor5-mention/tests/mentionui.js (hunk 1 above)
Comment (martnpaneq) [reply packages/ckeditor5-mention/tests/mentionui.js]: It was redundant. Removed in [aa170a5](https://github.com/ckeditor/ckeditor5/pull/19993/commits/aa170a5a8e2a42529a7d33d47a69de037e089e06).

File: packages/ckeditor5-mention/tests/mentionui.js (hunk 2 above)
Comment (martnpaneq) [reply packages/ckeditor5-mention/tests/mentionui.js]: Renamed in [f027731](https://github.com/ckeditor/ckeditor5/pull/19993/commits/f0277311bd969a89847f7c197b7bd58372e2d711).

File: packages/ckeditor5-mention/tests/mentionui.js (hunk 4 above)
Comment (martnpaneq) [reply packages/ckeditor5-mention/tests/mentionui.js]: Renamed in [f027731](https://github.com/ckeditor/ckeditor5/pull/19993/commits/f0277311bd969a89847f7c197b7bd58372e2d711).

File: packages/ckeditor5-mention/tests/mentionui.js (hunk 3 above)
Comment (martnpaneq) [reply packages/ckeditor5-mention/tests/mentionui.js]: Renamed in [f027731](https://github.com/ckeditor/ckeditor5/pull/19993/commits/f0277311bd969a89847f7c197b7bd58372e2d711).

File: packages/ckeditor5-mention/tests/mentionui.js (hunk 5 above)
Comment (martnpaneq) [reply packages/ckeditor5-mention/tests/mentionui.js]: Renamed in [f027731](https://github.com/ckeditor/ckeditor5/pull/19993/commits/f0277311bd969a89847f7c197b7bd58372e2d711).
