### PR TITLE
Hide resizers when resizing commands are disabled (e.g. in comments-only mode)

### LINKED ISSUE #11886: Column resize doesn't work with comments-only (or any other feature that disables commands)
## 📝 Provide detailed reproduction steps (if any)

Currently the comments-only feature doesn't disable the column resize feature as it disables all the commands.

Since currently column resize doesn't expose any command it doesn't work.

We're planning to add commands so that it also works well with the Track Changes feature.

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: 34.0.0
*   Installed CKEditor plugins: Table column resize

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Dumluregn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Table column resizers should be hidden when resizing commands are disabled. Closes #11886.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js [hunk 1]
```diff
@@ -581,12 +598,18 @@ export default class TableColumnResizeEditing extends Plugin {
 				}
 			} else {
 				// In read-only mode revert all changes in the editing view. The model is not touched so it does not need to be restored.
+				// This case can occur if the read-only mode kicks in during the resizing process.
 				editingView.change( writer => {
 					if ( isColumnWidthsAttributeChanged ) {
-						const columnWidths = columnWidthsAttributeOld.split( ',' );
+						if ( columnWidthsAttributeOld ) {
```
Comment (mlewand) [inline packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js:604]: Let's add a short comment what is it needed for.

**Review by mlewand — COMMENTED** [review]
Couple of minor things.

Please, don't forget to provide the commit message for the fix. This PR has just a placeholder "Type: Message.".

File: packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js (hunk 1 above)
Comment (Dumluregn) [reply packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js:604]: I added a comment - this `if` is necessary to avoid running the `split()` method if there is no previous value (so it would result in an error). I see that I didn't add a test for this case here, but in a CC fixing PR - https://github.com/ckeditor/ckeditor5/pull/12049/files#diff-d08d4a33389c9c57bdda1abc834750454c8f1d7f135bee1dd9fa4ff5a13eb883R888-R907. I'd rather not copy this one test to avoid issues during branch merging - do you think we can do it like that?

Comment (Dumluregn) [reply packages/ckeditor5-table/src/tablecolumnresize/tablecolumnresizeediting.js:607]: Ok, #12049 was just merged, so we have this test here already :see\_no\_evil:

**Comment by Dumluregn** [comment]
To test how the feature behaves with the `comments-only` mode best to use `editor-modes` manual test from CF repo.

**Comment by Dumluregn** [comment]
I also modified the CSS selector hiding the resizers according to https://github.com/ckeditor/ckeditor5/issues/11922.

**Review by mlewand — APPROVED** [review]
LGTM
