### PR TITLE
No longer allow to drag & drop content into disabled roots.

### LINKED ISSUE #19028: It's possible to drag content into a disabled root
## 📝 Provide detailed reproduction steps (if any)

1. Use multi-root editor
2. Disable one root
3. Drag content from another root to the disabled one

### ✔️ Expected result

Not possible to drag content into a disabled root.

### ❌ Actual result

https://github.com/user-attachments/assets/a7d604b5-cd17-4335-83ea-a3d2859bdc10

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Mati365**
### 🚀 Summary

No longer allow drag & drop content into disabled roots. 

**Before:**

https://github.com/user-attachments/assets/36431014-a6c9-48b2-8b2b-c42737826e3d

**After:**

https://github.com/user-attachments/assets/728a843f-df24-48cc-bc1a-c45a07a93a2f

---

### 📌 Related issues

* Closes #19028 

---

### 💡 Additional information

Initial implementation: https://github.com/ckeditor/ckeditor5/pull/13726
Regression introduced in: https://github.com/ckeditor/ckeditor5/pull/15016

### CODE REVIEW

File: packages/ckeditor5-clipboard/src/dragdrop.ts [hunk 1]
```diff
@@ -363,6 +365,12 @@ export class DragDrop extends Plugin {
 				this._draggedRange
 			);
 
+			// Do not allow dropping if there is no valid target range (e.g., dropping on non-editable place).
+			if ( !targetRange ) {
+				data.dataTransfer.dropEffect = 'none';
+				return;
```
Comment (niegowski) [inline packages/ckeditor5-clipboard/src/dragdrop.ts:372]:
```suggestion
				data.dataTransfer.dropEffect = 'none';

				return;
```

File: packages/ckeditor5-clipboard/src/dragdroptarget.ts [hunk 2]
```diff
@@ -148,15 +149,23 @@ export class DragDropTarget extends Plugin {
...
 		if ( !targetRange ) {
-			return;
+			return null;
 		}
 
 		if ( draggedRange && draggedRange.containsRange( targetRange ) ) {
 			// Target range is inside the dragged range.
-			return this.removeDropMarker();
+			this.removeDropMarker();
+			return null;
```
Comment (niegowski) [inline packages/ckeditor5-clipboard/src/dragdroptarget.ts:159]:
```suggestion
			this.removeDropMarker();

			return null;
```

File: packages/ckeditor5-clipboard/src/dragdroptarget.ts [hunk 3]
```diff
@@ -148,15 +149,23 @@ export class DragDropTarget extends Plugin {
...
+		}
+
+		if ( targetRange && !this.editor.model.canEditAt( targetRange ) ) {
+			// Do not show drop marker if target place is not editable.
+			this.removeDropMarker();
+			return null;
 		}
 
 		this._updateDropMarkerThrottled( targetRange );
+		return targetRange;
```
Comment (niegowski) [inline packages/ckeditor5-clipboard/src/dragdroptarget.ts:171]:
```suggestion

		return targetRange;
```

File: packages/ckeditor5-clipboard/src/dragdroptarget.ts [hunk 4]
```diff
@@ -148,15 +149,23 @@ export class DragDropTarget extends Plugin {
...
 			// Target range is inside the dragged range.
-			return this.removeDropMarker();
+			this.removeDropMarker();
+			return null;
+		}
+
+		if ( targetRange && !this.editor.model.canEditAt( targetRange ) ) {
+			// Do not show drop marker if target place is not editable.
+			this.removeDropMarker();
+			return null;
```
Comment (niegowski) [inline packages/ckeditor5-clipboard/src/dragdroptarget.ts:166]:
```suggestion
			this.removeDropMarker();

			return null;
```

**Review by niegowski — CHANGES_REQUESTED** [review]

**Review by niegowski — APPROVED** [review]
