### PR TITLE
Preserve formatting when deleting content.

### LINKED ISSUE #10517: Formatting, for example font color, is lost when all content is removed / Preserve font styles / Change default font
## 📝 Provide detailed reproduction steps (if any)

1. Enter some text into the content area
2. Apply some formatting, change font size, color etc.
3. Delete all that content
4. Type new content

### ✔️ Expected result

I expect to see the newly typed content with the last selected font styles (similar to word, powerpoint, etc)

### ❌ Actual result

The font has the editors default styles applied

### ❓ Possible solution

Don't remove the last span element that is the document editor, as this has the style

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #19777: Fonts are being reset to the default on new lines and new bullet points. When we type a text and backspace to the start of the line.
## 📝 Provide detailed reproduction steps (if any)
**Fonts are being reset to the default on new lines and new bullet points. When we type a text and backspace to the start of the line.**
**For Plain text**
1. Change font and font size.
2. Type  words. 
Image
3. Press/Hit Enter.
4. On new line type few letters and remove it using backspace do not go to first line while removing.
Image
Image
5. Start typing the font and font size is changed to default one.
Image
**For Bullet points**
1. Change font and font size.
2. Create bullet list.
Image
3. Add first point and go to second one.
Image
4. On new bullet point  type few letters and remove it using backspace do not remove bullet. 
Image
5. Start typing the font and font size is changed to default one.
Image

### ✔️ Expected result
The font and font size should be the same as selected not the default one for both simple text or bullet point

### ❌ Actual result

The font and font size is changing to default for both simple text or bullet point.

## 📃 Other details

* Browser: Google Chrome
* OS: Windows
* First affected CKEditor version: CKEditor 5 version 43.2.0.

Note: This issue is also present in demo https://ckeditor.com/ckeditor-5/demo/

### PR DESCRIPTION
**Pull request by arkflpc**
### 🚀 Summary

Preserve formatting when deleting content.

---

### 📌 Related issues

* Closes #10517
* Closes #19777

---

### 💡 Additional information

*Optional: Notes on decisions, edge cases, or anything helpful for reviewers.*

---

### 🧾 Checklists

Use the following checklists to ensure important areas were not overlooked.
This does not apply to feature-branch merges.
If an item is **not relevant** to this type of change, simply leave it unchecked.

#### Author checklist

- [ ] Is the changelog entry intentionally omitted?
- [ ] Is the change backward-compatible?
- [x] Have you considered the impact on different editor setups and core interactions? _(e.g., classic/inline/multi-root/many editors, typing, selection, paste, tables, lists, images, collaboration, pagination)_
- [x] Has the change been manually verified in the relevant setups?
- [ ] Does this change affect any of the above?
- [ ] Is performance impacted?
- [ ] Is accessibility affected?
- [x] Have tests been added that fail without this change (against regression)?
- [ ] Have the API documentation, guides, feature digest, and related feature sections been updated where needed?
- [ ] Have metadata files (ckeditor5-metadata.json) been updated if needed?
- [ ] Are there any changes the team should be informed about (e.g. architectural, difficult to revert in future versions or having impact on other features)?
- [ ] Were these changes documented (in Logbook)?

#### Reviewer checklist

- [ ] PR description explains the changes and the chosen approach (especially when  performance, API, or UX is affected).
- [ ] The changelog entry is clear, user‑ or integrator-facing, and it describes any breaking changes.
- [ ] All new external dependencies have been approved and mentioned in LICENSE.md (if any).
- [ ] All human-readable, translateable strings in this PR been introduced using `t()` (if any).
- [ ] I manually verified the change (e.g., in manual tests or documentation).
- [x] The target branch is correct.

---

> [!NOTE]
> **Medium Risk**
> Touches core `deleteContent()` behavior and selection attribute handling, which can affect typing/formatting outcomes across many editor scenarios. The change is narrowly scoped and covered by new regression tests, but it alters a widely used editing primitive.
> 
> **Overview**
> `deleteContent()` now **preserves document selection attributes (e.g. bold/italic)** when a deletion leaves the *live* selection in a newly-emptied parent block, so subsequent typing keeps the pre-delete formatting.
> 
> It avoids restoring attributes when the parent was already empty (e.g. when deleting via a synthetic selection elsewhere) and keeps the existing behavior of **clearing attributes** when the entire content is replaced with a fresh paragraph. Tests were updated/added to cover these formatting preservation and non-restoration cases.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit b7ceeaf5755b64d0060c85afec3380c2b78a576c. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by Witoso** [comment]
Could we describe in the PR description the behavior that was introduced with some before/after videos? The ticket that this closes is very complex, and I wonder what feature this touches. Also, I wonder if this would close #19777.

**Comment by Reinmar** [comment]
I tested it a bit manually to get a feeling where it gets us:

### Scenario 1

```html
<p><i>foo</i></p>
<p><i>[bar]</i></p>
<p><i>bom</i></p>
```

And do either:

* type "x"
* or backspace + type "x"

On this branch: `<i>x</i>`  (style preserved) in both cases

On master:

* type "x" -> style was preserved
* backspace + type "x" -> style was not preserved

### Scenario 2 (all content selected)

```html
<p><i>[foo</i></p>
<p><i>bar</i></p>
<p><i>bom]</i></p>
```

And do either:

* type "x"
* or backspace + type "x"

No changes to the behavior. Both master and this branch:

* type "x" -> style preserved
* backspace + type "x" -> style not preserved

That's something I wanted to maintain. You can easily clean content by ctrl+a and backspace.

### Scenario 3 (all content selected but only one paragraph present)

This is an edge case of scenario 2. What if you have just one paragraph and you styled it.

It works like Scenario 1 after changes. I think it's ok and even reasonable because in such case the user would most likely be much more focused on this single paragraph. So, less likely to want to "clear all content".

---

### Summing up 

So, from my brief tests, I like the change.

It fixes the second scenario from https://github.com/ckeditor/ckeditor5/issues/10517#issuecomment-4066299620.

**Comment by Witoso** [comment]
For reviewer/QA, please check if it solves https://github.com/ckeditor/ckeditor5/issues/19777. I created the Closes link in the description.

File: packages/ckeditor5-engine/src/model/utils/deletecontent.ts [hunk 1]
```diff
@@ -98,6 +98,9 @@ export function deleteContent(
 	}
 
 	const schema = model.schema;
+	const documentSelection = model.document.selection;
+	const selectionAttributes = Array.from( model.document.selection.getAttributes() );
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/model/utils/deletecontent.ts]: Why is this code not using the provided selection? It could be a completely different selection from the current document selection. I'd verify if the provided selection (in params) is the same as the document selection, as there might be some mapping along the way. What I mean is verify if they have equal ranges, not whether those are the same instance.

File: packages/ckeditor5-engine/src/model/utils/deletecontent.ts [hunk 2]
```diff
@@ -627,3 +632,36 @@ function collapseSelectionAt(
 		selection.setTo( positionOrRange );
 	}
 }
+
+function restoreSelectionAttributesOnEmptyParent(
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/model/utils/deletecontent.ts:650]: There should be a comment on what this helper does.

**Review by pszczesniak — DISMISSED** [review]
:+1: from my side.

**Review by Mati365 — DISMISSED** [review]

File: packages/ckeditor5-engine/src/model/utils/deletecontent.ts [hunk 3]
```diff
@@ -627,3 +641,47 @@ function collapseSelectionAt(
...
+		return;
+	}
+
+	// Setting document selection attributes here also persists them as `selection:*`
+	// on the empty parent, so future typing keeps the pre-delete formatting.
+	for ( const [ key, value ] of selectionAttributes ) {
+		if ( writer.model.schema.getAttributeProperties( key ).isFormatting &&
+			writer.model.schema.checkAttributeInSelection( documentSelection, key ) ) {
+			writer.setSelectionAttribute( key, value );
+		}
```
Comment (niegowski) [inline packages/ckeditor5-engine/src/model/utils/deletecontent.ts]:
```suggestion
		if ( 
			writer.model.schema.getAttributeProperties( key ).isFormatting &&
			writer.model.schema.checkAttributeInSelection( documentSelection, key ) 
		) {
			writer.setSelectionAttribute( key, value );
		}
```

**Review by niegowski — DISMISSED** [review]

**Review by Mati365 — DISMISSED** [review]

**Comment by pszczesniak** [comment]
QA tests passed 🎉 .

```
No regressions found; everything works as expected.
```
