### PR TITLE
Autoformat only the text after the last code element.

### LINKED ISSUE #1239: Autoformatting styles trigger within inline code
🐞 Bug report

## 💻 Version of CKEditor

v11.0.1

Classic editor with at least enabled plugins:

* Code (Basic styles)
* Italic (Basic styles)
* Autoformatting

## 📋 Steps to reproduce

1. Create an inline code element
2. Type something like `text with _underscores_`.

## ✅ Expected result

Autoformatting is not expanded within code element

## ❎ Actual result

Autoformatting rules expand within code element

Example

## 📃 Other details that might be useful

This happens with all styles within autoformatting since there's no construct of where this will be disallowed. I wonder if maybe the autoformatting plugin could export an attribute that we can set to elements that will result in skipping extraction?

(It will also happen in the block code plugin elements, for example)

---

Add 👍 reaction to this post if you'd like to see this issue fixed.

### PR DESCRIPTION
**Pull request by tomalec**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (autoformat): Autoformatting no longer changes the content of a code element. Closes #1239.

---

### Additional information

I changed the logic of ~~`I`~~`inlineAutoformatEditing` to format only the text after the last `code`, instead of the entire line, and do not format at all if the plugin is disabled.

I also did some cleanup:
- removed `pluginName` from `*AutoformatEditing` as they are not plugins,
- changed trivial classes, with constructors only, creating an object which was not used, to simple functions,
- make `*AutoformatEditing` listen to `change:data` instead of `change` to reduce the notice and avoid pointless runs,
- simplified `attributeOrCallback` to `formatCallback`, as the attribute was used only in tests, and was having some buggy behavior.

There are still some code smells I'd clean here (like untangling `callbackOrCommand` flow) , but decided to finish here, not to block nor postpone actual bug fix. 

Note, that I changed the `*inline*AutoformatEditing` API if we care to keep it stable.

### CODE REVIEW

File: packages/ckeditor5-autoformat/tests/autoformat.js [hunk 1]
```diff
@@ -410,6 +410,146 @@ describe( 'Autoformat', () => {
...
+			model.change( writer => {
+				writer.insertText( '*', doc.selection.getFirstPosition() );
+			} );
+
+			expect( getData( model ) ).to.equal( '<paragraph>**foobar**[]</paragraph>' );
+		} );
+
+		describe( 'with code element', () => {
+			it( 'should not format inside', () => {
+				// Test *.
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/autoformat.js:427]: These are OK to read when you browse tests. But when one of them fails, they are useless because there are many (similar) assertions within a single failing `it()` and you don't know which one it is. You can pass an [optional message to `expect()`](https://www.chaijs.com/api/bdd/#method_equal) so when an assertion fails, it is clear which one. [Check out how I did this in some tests](https://github.com/ckeditor/ckeditor5/commit/33e9b37c3808e53cf1e6025fb7ed250b393d9f4b#diff-e725861539867051799a155cdf02b85bR26-R49).

Alternatively, you could create multiple `it()` and boost our test stats :P

File: packages/ckeditor5-autoformat/tests/blockautoformatediting.js [hunk 2]
```diff
@@ -104,9 +101,23 @@ describe( 'BlockAutoformatEditing', () => {
 			sinon.assert.calledOnce( spy );
 		} );
 
+		it( 'should not call callback when the pattern is matched and plugin is disabled', () => {
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/blockautoformatediting.js:104]:
```suggestion
        it( 'should not call the callback when the pattern is matched but the plugin is disabled', () => {
```

File: packages/ckeditor5-autoformat/tests/autoformat.js [hunk 3]
```diff
@@ -410,6 +410,146 @@ describe( 'Autoformat', () => {
 			expect( getData( model ) ).to.equal( '<paragraph>**foobar**[]</paragraph>' );
 		} );
 
+		it( 'should not format if the plugin is not enabled', () => {
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/autoformat.js:413]:
```suggestion
		it( 'should not format if the plugin is disabled', () => {
```

File: packages/ckeditor5-autoformat/tests/inlineautoformatediting.js [hunk 4]
```diff
@@ -25,59 +27,55 @@ describe( 'InlineAutoformatEditing', () => {
...
 
-	it( 'should have pluginName', () => {
-		expect( InlineAutoformatEditing.pluginName ).to.equal( 'InlineAutoformatEditing' );
-	} );
-
-	describe( 'attribute', () => {
-		it( 'should stop early if there are less than 3 capture groups', () => {
-			new InlineAutoformatEditing( editor, /(\*)(.+?)\*/g, 'testAttribute' ); // eslint-disable-line no-new
+	describe( 'regExp', () => {
+		it( 'should not call formatCallback if there are less than 3 capture groups', () => {
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/inlineautoformatediting.js:37]:
```suggestion
		it( 'should not call the formatCallback if there are less than 3 capture groups', () => {
```

File: packages/ckeditor5-autoformat/tests/inlineautoformatediting.js [hunk 5]
```diff
@@ -25,59 +27,55 @@ describe( 'InlineAutoformatEditing', () => {
...
 				writer.insertText( '*', doc.selection.getFirstPosition() );
 			} );
 
-			expect( getData( model ) ).to.equal( '<paragraph>*foobar*[]</paragraph>' );
+			sinon.assert.notCalled( formatSpy );
 		} );
 
-		it( 'should apply an attribute when the pattern is matched', () => {
-			new InlineAutoformatEditing( editor, /(\*)(.+?)(\*)/g, 'testAttribute' ); // eslint-disable-line no-new
+		it( 'should call formatCallback when the pattern is matched', () => {
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/inlineautoformatediting.js:48]:
```suggestion
		it( 'should call the formatCallback when the pattern is matched', () => {
```

File: packages/ckeditor5-autoformat/tests/inlineautoformatediting.js [hunk 6]
```diff
@@ -25,59 +27,55 @@ describe( 'InlineAutoformatEditing', () => {
...
 				writer.insertText( '*', doc.selection.getFirstPosition() );
 			} );
 
-			expect( getData( model ) ).to.equal( '<paragraph><$text testAttribute="true">foobar</$text>[]</paragraph>' );
+			sinon.assert.calledOnce( formatSpy );
 		} );
 
-		it( 'should stop early if selection is not collapsed', () => {
-			new InlineAutoformatEditing( editor, /(\*)(.+?)\*/g, 'testAttribute' ); // eslint-disable-line no-new
+		it( 'should not call formatCallback if selection is not collapsed', () => {
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/inlineautoformatediting.js:59]:
```suggestion
		it( 'should not call the formatCallback if the selection is not collapsed', () => {
```

File: packages/ckeditor5-autoformat/tests/inlineautoformatediting.js [hunk 7]
```diff
@@ -121,6 +117,19 @@ describe( 'InlineAutoformatEditing', () => {
 			sinon.assert.notCalled( formatSpy );
 		} );
 
+		it( 'should not run formatCallback when the pattern is matched and plugin is disabled', () => {
```
Comment (oleq) [inline packages/ckeditor5-autoformat/tests/inlineautoformatediting.js:120]:
```suggestion
		it( 'should not run the formatCallback when the pattern is matched but the plugin is disabled', () => {
```

**Comment by tomalec** [comment]
All issues addressed. Ready for another round of review.

**Comment by oliverguenther** [comment]
Awesome to see this being addressed. Thanks! :tada:
