### PR TITLE
#6190: Balloons attached to widgets should always be visible even if the widget is longer than a visible viewport

### LINKED ISSUE #6190: There's no way to access table properties when table longer than the viewport
## 📝 Provide detailed reproduction steps (if any)

A follow-up of https://github.com/ckeditor/ckeditor5/issues/6049 and https://github.com/ckeditor/ckeditor5/issues/6112.

1. Create a table longer than the viewport.
2. Try to open the table (not cell) properties form.

### ✔️ Expected result

It should be visible somewhere and accessible.

### ❌ Actual result

It is pinned either to the top or to the bottom, way beyond the visible viewport and user's reach.

## 📃 Other details

image

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (widget): The widget toolbar should always be visible even if the widget is longer than a visible viewport (see #6190).

Fix (table): The table properties balloon should always be visible if the table is longer than a visible viewport. Closes #6190.

---

### Additional information

*   I'm not sure about the name of `centeredBalloonPositionForLongWidgets()` but there's so much going on in there I'm not sure there's an easy way to express that in simple words.
*   At first I wanted `centeredBalloonPositionForLongWidgets()` to be a part of `BalloonPanelView#defaultPositions` but I figured (so far) this is a widget-specific behavior so maybe let's keep it in `ckeditor5-widget` for a while.

### CODE REVIEW

**Comment by oleq** [comment]
@ckeditor/qa-team Can you take a look at this? You can test both scenarios in http://fake.ckeditor.com:8125/ckeditor5-table/tests/manual/tableproperties.html using a very long table (or a very small viewport).

**Comment by FilipTokarski** [comment]
Desktop browsers work fine, but on Android the balloon appears halfway when scrolling up:
14_android_1

File: packages/ckeditor5-widget/src/utils.js [hunk 1]
```diff
@@ -339,6 +342,75 @@ export function viewToModelPositionOutsideModelElement( model, viewElementMatche
...
+		};
+	}
+	// Cases (A) and (B).
+	else {
+		return {
+			top: Math.max( widgetRect.top, 0 ) + BalloonPanelView.arrowVerticalOffset,
+			left,
+			name: 'arrow_n'
+		};
+	}
```
Comment (niegowski) [inline packages/ckeditor5-widget/src/utils.js:411]: I would simplify this function only to cases A and B. C seems to appear only in very "short" scenario and makes balloon jump on the bottom of the widget.
```suggestion
	return {
		top: Math.max( widgetRect.top, 0 ) + BalloonPanelView.arrowVerticalOffset,
		left,
		name: 'arrow_n'
	};
```

File: packages/ckeditor5-widget/tests/utils.js [hunk 2]
```diff
@@ -489,4 +493,123 @@ describe( 'widget utils', () => {
...
+			width: 10,
+			height: 10
+		} );
+
+		beforeEach( () => {
+			testUtils.sinon.stub( global.window, 'innerWidth' ).value( 100 );
+			testUtils.sinon.stub( global.window, 'innerHeight' ).value( 100 );
+		} );
+
+		it( 'should position the balloon inside a widget – at the top + in the middla', () => {
```
Comment (niegowski) [inline packages/ckeditor5-widget/tests/utils.js:515]:
```suggestion
		it( 'should position the balloon inside a widget – at the top + in the middle', () => {
```

File: packages/ckeditor5-widget/src/utils.js (hunk 1 above)
Comment (oleq) [reply packages/ckeditor5-widget/src/utils.js:411]: I also had some doubts about it but I figured it feels sort of OK when the balloon is attached to the bottom and there's not enough space to keep it there. This way we avoid a rapid change and provide this one extra step `[ underneath, inside at the bottom, inside at the top]` instead of `[underneath, inside at the top]`. 

Anyway, a funny idea popped into my head when I was thinking about it. What if... the position detects which direction the window is scrolling? Like as long as scrolling down (the upper edge of widget disappears) we would attach it to the top of the viewport and to the bottom of the viewport if scrolling in to opposite direction. 

WDYT?

Comment (niegowski) [reply packages/ckeditor5-widget/src/utils.js:411]: As we talked F2F, for this edge scenario there is no point in complicating it.

**Comment by oleq** [comment]
> Desktop browsers & iOS work fine, but on Android the balloon appears halfway when scrolling up:

I guess I'm ready to live with that.

**Comment by niegowski** [comment]
I'm wondering about the scenario where editor is limited in height with `overflow: scroll`. If editor would be in the middle of window, then this balloons would be displayed on the edge of the window (could be far away from editor), maybe we should try to stick it to closest scrollable instead of window?

**Comment by oleq** [comment]
> I'm wondering about the scenario where editor is limited in height with `overflow: scroll`. If editor would be in the middle of window, then this balloons would be displayed on the edge of the window (could be far away from editor), maybe we should try to stick it to closest scrollable instead of window?

That's a bigger topic because it touches all balloons, not only widget balloons. See #5328.
