### PR TITLE
Fixed dragging text in read-only mode. Fixed dragging nested editable.

### LINKED ISSUE #9370: Entire table cell can be dragged
## 📝 Provide detailed reproduction steps (if any)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #9372: Selection is stuck in read only mode
## 📝 Provide detailed reproduction steps (if any)

1.  Turn the editor into read only mode.
2.  Make non-collapsed selection.
3.  Try to change the selection in the editable.

### ✔️ Expected result

Selection is changed.

### ❌ Actual result

The selection flickers and cannot be changed. If you focus something outside the editor, you can't focus anything in the editor again.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (clipboard): Fixed changing selection in read-only mode. Closes #9372.

Fix (clipboard): Nested editable should not be dragged. Closes #9370.

---

### Additional information

### CODE REVIEW

File: packages/ckeditor5-clipboard/src/dragdrop.js [hunk 1]
```diff
@@ -470,7 +470,7 @@ export default class DragDrop extends Plugin {
 			// If this was not a widget then we should check if we need to drag some text content.
 			// In Chrome set a 'draggable' attribute on closest editable to allow immediate dragging of the selected text range.
 			// In Firefox this is not needed. In Safari it makes the whole editable draggable (not just textual content).
-			if ( env.isBlink && !draggableElement && !viewDocument.selection.isCollapsed ) {
+			if ( env.isBlink && !editor.isReadOnly && !draggableElement && !viewDocument.selection.isCollapsed ) {
```
Comment (scofalik) [inline packages/ckeditor5-clipboard/src/dragdrop.js:473]:
```suggestion
			// Disabled in read-only mode because draggable="true" + contenteditable="false" results
			// in not firing selectionchange event ever, which makes the selection stuck in read-only mode.
			if ( env.isBlink && !editor.isReadOnly && !draggableElement && !viewDocument.selection.isCollapsed ) {
```
