### PR TITLE
Ck/10146 find in multiroot

### LINKED ISSUE #10146: Find and replace multiroot support
## 📝 Provide detailed reproduction steps (if any)

The find and replace feature should support editor with multiple document roots.

Surely we'd have to ignore special roots (that starting with the $ sign).

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by magda-chrzescian**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (find-and-replace): Find and replace feature should work in the multi-root editor. Closes #10146.

Fix (find-and-replace): The `Ctrl+F` shortcut should open the find and replace drop-down.

Tests (find-and-replace): Added automatic and manual tests for the find and replace feature in the multi-root editor. See #10146.

Docs: Added the find and replace feature to the multi-root editor example.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-find-and-replace/src/findandreplaceui.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default class FindAndReplaceUI extends Plugin {
 			this.formView = formView;
 
 			editor.keystrokes.set( 'Ctrl+F', ( data, cancelEvent ) => {
-				dropdown.buttonView.actionView.fire( 'execute' );
```
Comment (mlewand) [inline packages/ckeditor5-find-and-replace/src/findandreplaceui.js:91]: This has been fixed couple of days ago #10189 I'll merge the latest master branch.

**Review by mlewand — APPROVED** [review]
LGTM 👍 Not sure about adding find and replace to the multiroot example though so please verify this with CCX squad if that's something we want to have.
