### PR TITLE
Fixed insert table row/column commands when a widget is selected inside the table cell

### LINKED ISSUE #6607: Editor crashes when pressing tab in a table cell with selection on an image
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor5/latest/features/table.html.
2. Upload an image in a table cell (as the last child).
3. Select the image.
4. Tab.

### ✔️ Expected result

Probably the new table row should be created (or some sort of navigation).

### ❌ Actual result

The editor crashes.

```
downcast.js:491 Uncaught TypeError: Cannot read property 'getChildren' of undefined
    at getExistingTableSectionElement (downcast.js:491)
    at getOrCreateTableSection (downcast.js:480)
    at DowncastDispatcher.<anonymous> (downcast.js:114)
    at DowncastDispatcher.fire (emittermixin.js:209)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:474)
    at DowncastDispatcher.convertInsert (downcastdispatcher.js:185)
    at DowncastDispatcher.convertChanges (downcastdispatcher.js:137)
    at editingcontroller.js:93
    at View.change (view.js:479)
    at Document.EditingController.listenTo.priority (editingcontroller.js:92)
```

## 📃 Other details

It exists prior to it31.

Have you seen this before @jodator, @ckeditor/qa-team?

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (table): Fixed insert table row/column commands when a widget is selected inside the table cell. Closes #6607.

---

### Additional information

### CODE REVIEW

File: packages/ckeditor5-table/src/commands/insertcolumncommand.js [hunk 1]
```diff
@@ -75,8 +75,11 @@ export default class InsertColumnCommand extends Command {
...
 
-		const tableCell = referenceRange.getContainedElement() || findAncestor( 'tableCell', referencePosition );
-		const table = tableCell.parent.parent;
+		const containedElement = referenceRange.getContainedElement();
+		const isTableCell = containedElement && containedElement.is( 'tableCell' );
+
+		const tableCell = isTableCell ? containedElement : findAncestor( 'tableCell', referencePosition );
+		const table = findAncestor( 'table', tableCell );
 
 		const { column } = tableUtils.getCellLocation( tableCell );
```
Comment (jodator) [inline packages/ckeditor5-table/src/commands/insertcolumncommand.js:84]: I would change the whole thing to:
```js

		const affectedTableCells = getSelectionAffectedTableCells( selection );
		const columnIndexes = getColumnIndexes( affectedTableCells );

		const column = insertBefore ? columnIndexes.first : columnIndexes.last;
		const table = findAncestor( 'table', affectedTableCells[ 0 ] );
```

if the tests aren't too simplistic it works :man_shrugging:.

AFAICS the same thing can be done with inserting rows.

Comment (jodator) [reply packages/ckeditor5-table/src/commands/insertcolumncommand.js:84]: The reason I would see that change is that it looks like this code tried to copy utility methods behavior that we already have. Using utility method for extracting this data makes me safe that we do it properly.
