### PR TITLE
Fix feedback loop in the color picker

### LINKED ISSUE #14415: Selected color is not propagated to the color table and color picker
## 📝 Provide detailed reproduction steps (if any)

Only present at [ck/epic/2978-integrate-color-picker-with-tables](https://github.com/ckeditor/ckeditor5/tree/ck/epic/2978-integrate-color-picker-with-tables).

1.  Put selection in a table cell with cell background color set.
2.  Open color picker in the table cell properties.

### ✔️ Expected result

Currently selected color is marked.

### ❌ Actual result

No color is marked, the "Remove color" button is focues.

## 📃 Other details

*   Browser: …
*   OS: …
*   First affected CKEditor version: …
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #14432: Feedback loop while color dropdown is open in table properties
## 📝 Provide detailed reproduction steps (if any)

You could reproduce this behaviour on this `epic`: https://github.com/ckeditor/ckeditor5/tree/ck/epic/2978-integrate-color-picker-with-tables

1. Go to http://localhost:8125/ckeditor5-table/tests/manual/tableproperties.html
2. Choose any cell in table
3. Click on `cell properties button` ( image )
4. Type in background color input any **HEX** value e.g. `#ffaaff`
5. Next to input will be button with color panel  (image ), click on it
6. Click on `color picker button` ( image )
7. Start choosing any color
8. Click on `cancel button` ( image )

### ✔️ Expected result

In model on this cell should be applied **HEX** value as it was

image

### ❌ Actual result

image

----------------------------

The same problem with `remove color button`, so when we set default color, e.g. ( `rgb(255,0,0)` ) and after color changes and removing color it will apply in model color in **HSL** format or that format which was defined in color picker as output.

This problem is directly related with **feedback loop** which was partially resolved by this PR: https://github.com/ckeditor/ckeditor5/pull/14416
But it was temporarily fix, we need something more generic and bulletproof solution which cover all cases.  

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Dumluregn**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal (ui): Fix feedback loop in the color picker. Closes #14432.  
Internal (ui): Propagate the selected color to the color table in table properties. Closes #14415.

---

### Additional information

I requested the QA team assistance, so let's wait with merge until they accept the PR.

### CODE REVIEW

File: packages/ckeditor5-table/tests/ui/colorinputview.js [hunk 1]
```diff
@@ -195,21 +195,16 @@ describe( 'ColorInputView', () => {
...
+				colorTableView.colorPickerPageView.colorPickerView.fire( 'colorSelected', { color: 'hsl( 250, 100%, 83% )' } );
 
 				colorTableView.fire( 'cancel' );
 
-				/**
-				 * TODO, should be HEX format: (https://github.com/ckeditor/ckeditor5/issues/14432)
-				 */
-				expect( view.value ).to.be.equal( 'hsl( 300, 100%, 83% )' );
-				// expect( view.value ).to.be.equal( '#ffaaff' );
+				expect( view.value ).to.be.equal( '#ffaaff' );
```
Comment (illia-stv) [inline packages/ckeditor5-table/tests/ui/colorinputview.js:207]: Maybe good idea could be creating similar test with `Remove Color`
Screenshot 2023-06-26 at 13 21 45

File: packages/ckeditor5-table/tests/ui/colorinputview.js [hunk 2]
```diff
@@ -302,12 +293,11 @@ describe( 'ColorInputView', () => {
 				sinon.assert.calledWithExactly( spy.lastCall, 'input' );
 			} );
 
-			it.skip( 'should have #selectedColor bound to the #value', () => {
+			it( 'should set #selectedColor to the #value upon dropdown opening', () => {
```
Comment (illia-stv) [inline packages/ckeditor5-table/tests/ui/colorinputview.js:296]: Maybe we could also create test which tests the logic of `#selectedColor` when dropdown is closed, then it should not be bound.

**Review by illia-stv — CHANGES_REQUESTED** [review]
I like this solution it works well, I suggested adding only a few additional tests.

File: packages/ckeditor5-ui/tests/colortable/colortableview.js [hunk 3]
```diff
@@ -343,6 +343,13 @@ describe( 'ColorTableView', () => {
 			expect( colorTableView.colorPickerPageView.items.length ).to.equal( 2 );
 		} );
 
+		it( 'should set selected color after changes in color picker', () => {
+			colorTableView._appendColorPicker();
+			colorTableView.colorPickerPageView.colorPickerView._debounceColorPickerEvent( '#113322' );
```
Comment (oleq) [inline packages/ckeditor5-ui/tests/colortable/colortableview.js:348]: Please don't use private properties in tests unless there's absolutely no other choice. This leads to multitude of tests failing in random places if the internal implementation of a class/component changes in the future. 

You can fire an event that belongs to the public API of the `ColorPickerView`

```
colorPickerView.fire( 'colorSelected', { color: '#113322' } );
```

to test this since all we want to know here is that the data propagation between components exists and works fine

```
this.colorPickerView!.on<ColorPickerColorSelectedEvent>( 'colorSelected', ( evt, data ) => {
	// ... 

	this.set( 'selectedColor', data.color );
} );
```

File: packages/ckeditor5-font/tests/ui/colorui.js [hunk 4]
```diff
@@ -181,7 +181,8 @@ describe( 'ColorUI', () => {
 		describe( 'color picker', () => {
 			it( 'should execute command if the color gets changed when dropdown is open', () => {
 				const spy = sinon.spy( editor, 'execute' );
-				dropdown.colorTableView.colorPickerPageView.colorPickerView.color = '#a37474';
+
+				dropdown.colorTableView.colorPickerPageView.colorPickerView._debounceColorPickerEvent( '#a37474' );
```
Comment (oleq) [inline packages/ckeditor5-font/tests/ui/colorui.js:185]: Same here: let's fire a proper event here. All we want to know is that there's a proper response to the public event being fired. 

At this stage, we don't care about the internal state of the `ColorPickerView`. I know that `_debounceColorPickerEvent()` sets both `#color` and fires the event but the latter does not matter here.

**Review by oleq — CHANGES_REQUESTED** [review]
It looks like we finally got it right. Commented on the usage of private properties in tests.
