### PR TITLE
The old view element should be properly unbound after reconversion is done

### LINKED ISSUE #8358: Old view element should be unbound after reconversion is done
## 📝 Provide detailed reproduction steps (if any)

When reconversion happens, the old view element is removed but it is not unbound, because we want to use it to get its children (without reconverting those children).

However, this element is never unbound which is incorrect. This causes an error, because markers that were created on that view element will still be bound to the old view element.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (engine): The old view element should be properly unbound after reconversion is done. Closes #8358.

### CODE REVIEW

File: packages/ckeditor5-engine/tests/conversion/downcasthelpers.js [hunk 1]
```diff
@@ -192,6 +194,53 @@ describe( 'DowncastHelpers', () => {
 					expectResult( '<div class="is-classy"></div>' );
 				} );
 
+				it( 'should properly re-bind mapper', () => {
```
Comment (jodator) [inline packages/ckeditor5-engine/tests/conversion/downcasthelpers.js:197]:
```suggestion
				it( 'should properly re-bind mapper mappings and retain markers', () => {
```

**Review by jodator — APPROVED** [review]
LGTM :+1: I'll just update the test case name.

**Comment by jodator** [comment]
ps.: I've also changed to `Internal` as this is a fix for the feature from the current release.
