### PR TITLE
Ck/11904

### LINKED ISSUE #11904: [Chrome] Can't remove the whole content when the widget is at the beginning/end of the document
Branch `ck/11438-beforeinput-ime-research-vol1.2-android`

## 📝 Provide detailed reproduction steps (if any)

Steps updated 13.09.2022 as explained here: https://github.com/ckeditor/ckeditor5/issues/11904#issuecomment-1245109027

1.  Open http://localhost:8125/ckeditor5/tests/manual/all-features.html in Chrome.
2.  Create a new paragraph at the beginning of the document.
3.  Put an image at the document's beginning (inside a previously created paragraph).
4.  Select all.
5.  Press Delete.

### ✔️ Expected result

The content is removed.

### ❌ Actual result

Nothing happens.

## 📃 Other details

Can't reproduce it on `master`.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by arkflpc**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (typing). Fixes deleting all content in Chrome. Closes #11904.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

### CODE REVIEW

File: packages/ckeditor5-typing/src/deleteobserver.js [hunk 1]
```diff
@@ -211,3 +215,73 @@ export default class DeleteObserver extends Observer {
...
+			const eventInfo = new BubblingEventInfo( document, 'delete', targetRange );
+			const deleteData = {
+				unit: DELETE_SELECTION,
+				direction: getDeleteDirection( keyCode ),
+				selectionToRemove: selection
+			};
+
+			document.fire( eventInfo, new DomEventData( document, domEvent, deleteData ) );
+
+			if ( eventInfo.stop.called ) {
```
Comment (niegowski) [inline packages/ckeditor5-typing/src/deleteobserver.js:253]: Why is this needed? We use that event just to detect missing event so maybe we should not allow to stop the original `keyup` event?

**Review by niegowski — COMMENTED** [review]
Apart from the other comment, this PR should be based on `ck/epic/11438-migrate-to-beforeinput` branch.

**Review by niegowski — APPROVED** [review]
