### PR TITLE
Pressing Shift+Enter in Safari should fire soft enter event

### LINKED ISSUE #13321: Shift enter not inserting <br>'s in Safari
## 📝 Provide detailed reproduction steps (if any)

1. Goto the feature rich editor example in Safari & another browser
2. Remove all content
3. Type something
4. Press shift and enter a few times:

### ✔️ Expected result

In Chrome you get the expected `<br>`s

```
<p data-placeholder="Type or paste your content here!">Something<br><br><br><br><br><br><br><br data-cke-filler="true"></p>
```

### ❌ Actual result

In Safari you get multiple `<p>`s

```
<p data-placeholder="Type or paste your content here!">Something</p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p><p><br data-cke-filler="true"></p>
```

## 📃 Other details

* Browser: Safari 15.6.1 (OSX), Chrome 109.0.5414.87 (OSX)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by niegowski**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (enter): Pressing <kbd>Shift</kbd>+<kbd>Enter</kbd> in Safari should insert `<br>` instead of splitting block. Closes #13321.

---

### CODE REVIEW

File: packages/ckeditor5-enter/tests/enterobserver.js [hunk 1]
```diff
@@ -9,7 +9,9 @@ import View from '@ckeditor/ckeditor5-engine/src/view/view';
 import EnterObserver from '../src/enterobserver';
 import createViewRoot from '@ckeditor/ckeditor5-engine/tests/view/_utils/createroot';
 import testUtils from '@ckeditor/ckeditor5-core/tests/_utils/utils';
+import env from '@ckeditor/ckeditor5-utils/src/env';
```
Comment (arkflpc) [inline packages/ckeditor5-enter/tests/enterobserver.js:12]: Let's merge that with `import { getCode } ...`.

File: packages/ckeditor5-enter/src/enterobserver.ts [hunk 2]
```diff
@@ -32,14 +35,26 @@ export default class EnterObserver extends Observer {
 		super( view );
 
 		const doc = this.document;
+		let shiftPressed = false;
+
+		doc.on<ViewDocumentKeyDownEvent>( 'keydown', ( evt, data ) => {
```
Comment (arkflpc) [inline packages/ckeditor5-enter/src/enterobserver.ts:40]: What about `'keyup'`? What if the user had released `shift` before she pressed `enter`?

File: packages/ckeditor5-enter/tests/enterobserver.js [hunk 3]
```diff
@@ -84,6 +86,32 @@ describe( 'EnterObserver', () => {
 		sinon.assert.notCalled( enterSpy );
 	} );
 
+	// See https://github.com/ckeditor/ckeditor5/issues/13321.
+	it( 'should handle the insertParagraph input type and fire the soft enter event if shift key is pressed in Safari', () => {
```
Comment (arkflpc) [inline packages/ckeditor5-enter/tests/enterobserver.js:90]: I'd also test the following scenario:

1.  A user presses `shift`.
2.  A user releases `shift`.
3.  A user presses `enter`.

**Review by arkflpc — CHANGES_REQUESTED** [review]

File: packages/ckeditor5-enter/src/enterobserver.ts (hunk 2 above)
Comment (niegowski) [reply packages/ckeditor5-enter/src/enterobserver.ts:40]: This listener does not care what key was pressed, just the `shiftKey` flag that is provided in every key event. So the shift key state will be from the last `keydown` event and it would be `enter` key that triggered `beforeinput`.

File: packages/ckeditor5-enter/tests/enterobserver.js (hunk 3 above)
Comment (niegowski) [reply packages/ckeditor5-enter/tests/enterobserver.js:89]: Added test.

**Review by arkflpc — APPROVED** [review]
