### PR TITLE
Keyboard handling for grid components discovery PoC

### LINKED ISSUE #11041: Cannot change list style with keyboard
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/lists/lists.html#demo-2
2. Focus the editor and press `Alt+F10`.
3. Use keyboard arrows to navigate to list styles dropdown.
4. Open dropdown with `space` or `enter` key.
5. Try to select a different list style with arrows.

### ✔️ Expected result

You are able to use arrows to choose a different style.

### ❌ Actual result

After opening the dropdown you are unable to change the style with arrows.

### Notes:
- this scenario works on https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#demo-2 demo
- regression on current `master` branch, possibly related to recent changes to list styles

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #11841: Color button focusing order doesn’t follow any logic
## 📝 Provide detailed reproduction steps (if any)

1. Open [full-featured editor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html).
2. Navigate to Font color button using keyboard.
3. Try to navigate between: "remove color" button, color pallette and document colors section.

### ✔️ Expected result

1. Navigation between "remove color" button, color pallette and document colors section is intuitive.

### ❌ Actual result

1. You can switch between "remove color" button and color pallette by using arrow down key, but to access document colors below, you have to press arrow up key.

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### LINKED ISSUE #11851: Discovery: research keyboard handling for grid components
## Provide a description of the task

Research best practices on how to handle grid navigation using the keyboard.

We have multiple grid-like UI components:

*   [Colors in the font color dropdown.](https://github.com/ckeditor/ckeditor5/issues/11841)
*   [List styles (in a dropdown)](https://github.com/ckeditor/ckeditor5/issues/11041).
*   [Table dimension grid in insert table button dropdown.](https://github.com/ckeditor/ckeditor5/issues/3176)
*   [Special characters](https://github.com/ckeditor/ckeditor5/issues/9037).

To make it clear: this issue is just discovery. It's meant just to figure out best way to implement it and see why we have it implemented the way we did. We also can make some PoC to see how much effort will it require to fix it.

Once we have figured how this should be solved, we can move on to each separate issue.

### PR DESCRIPTION
**Pull request by mmotyczynska**
### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (ui): Introduced a common `addKeyboardHandlingForGrid()` helper to handle grid keyboard navigation. Closes #11851.

Fix (font): Fixed focus order for color grid in font color and background dropdowns. Closes #11841.

Fix (list): Unified focus handling and keyboard navigation in list properties dropdowns. Closes #11041.

---

### Additional information

<table>
<tr>
<th>Font color / background</th>
<th>List style</th>
</tr>
<tr>
<td>

https://user-images.githubusercontent.com/5353898/182343384-b1f5d16d-ef1c-4096-8dc2-2d8596b71b05.mp4

</td>
<td>

https://user-images.githubusercontent.com/5353898/182343600-5fad8629-5893-459a-98d9-2a384c743829.mp4

</td>
</tr>
</table>

### CODE REVIEW

File: packages/ckeditor5-table/src/ui/inserttableview.js [hunk 1]
```diff
@@ -98,6 +102,13 @@ export default class InsertTableView extends View {
 
 				click: bind.to( () => {
 					this.fire( 'execute' );
+				} ),
+
+				keydown: bind.to( ( evt ) => {
+					if ( evt.key === 'Enter') {
+						this.fire( 'execute' );
```
Comment (oleq) [inline packages/ckeditor5-table/src/ui/inserttableview.js:109]: No sure which piece of logic is responsible for this but clicking a toolbar button followed by enter creates a 2x2 table (should be 1x1, I guess)

File: packages/ckeditor5-table/src/ui/inserttableview.js [hunk 2]
```diff
@@ -119,14 +130,21 @@ export default class InsertTableView extends View {
...
+		this.keystrokes.listenTo( this.element );
 	}
 
 	/**
 	 * @inheritDoc
 	 */
 	focus() {
-		// The dropdown panel expects DropdownPanelFocusable interface on views passed to dropdown panel. See #30.
-		// The method should be implemented while working on keyboard support for this view. See #22.
+		this.items.get( 0 ).focus();
```
Comment (oleq) [inline packages/ckeditor5-table/src/ui/inserttableview.js:147]: A CSS-related comment but I'm leaving it around here: I noticed the focused grid element has a weird (bold) outline. I think we should get rid of it, the mouse and keyboard selections should look the same IMO.

image

Comment (oleq) [reply packages/ckeditor5-table/src/ui/inserttableview.js:147]: (Nothing critical, this could be a follow-up) 

Also, the `'boxover'` logic, should focus the grid item. Use case:

1.  Open the dropdown
2.  Select some geometry using a mouse
3.  Start playing with arrow keys

**Expected**: Arrow keys should take over and modify existing geometry.

**Actual**: They always start from 1x1

**Review by oleq — CHANGES_REQUESTED** [review]
The direction is right. Refactoring needed, though.

File: packages/ckeditor5-ui/src/dropdown/utils.js [hunk 3]
```diff
@@ -291,6 +291,97 @@ export function focusChildOnDropdownOpen( dropdownView, childSelectorCallback )
...
+
+		if ( isTable ) {
+			gridElements[ nextIndex ].selectTile( view );
+		}
+
+		evt.stopPropagation();
+		evt.preventDefault();
+	} );
+
+	function getFocusedElement( gridElements ) {
```
[the remark this answers is not in the document]
Comment (mmotyczynska) [reply packages/ckeditor5-ui/src/dropdown/utils.js]: I chose the first option for two reasons:

1.  Less code if we have the focus tracker only in helper (not in every grid view)
2.  In case of new grid view we won't force the developer to remember that the focus tracker has to be created

File: packages/ckeditor5-ui/src/dropdown/utils.js [hunk 4]
```diff
@@ -291,6 +291,97 @@ export function focusChildOnDropdownOpen( dropdownView, childSelectorCallback )
...
+		// TODO: for tables'd be ok, for others should not change row no
+		if ( focusedElementIndex === gridElements.length - 1 ) {
+			nextIndex = 0;
+		} else {
+			nextIndex = focusedElementIndex + 1;
+		}
+
+		gridElements[ nextIndex ].focus();
+
+		if ( isTable ) {
```
[the remark this answers is not in the document]
Comment (mmotyczynska) [reply packages/ckeditor5-ui/src/dropdown/utils.js]: Thanks for this great idea :+1:

File: packages/ckeditor5-table/src/ui/inserttableview.js (hunk 2 above)
Comment (mmotyczynska) [reply packages/ckeditor5-table/src/ui/inserttableview.js:147]: Good point :+1:

File: packages/ckeditor5-ui/src/dropdown/utils.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (mmotyczynska) [reply packages/ckeditor5-ui/src/dropdown/utils.js]: Eventually I chose the second option because some grids already have their own focusTrackers and we can use them.

File: packages/ckeditor5-ui/src/bindings/addKeyboardHandlingForGrid.js [hunk 5]
```diff
@@ -0,0 +1,82 @@
+/**
+ * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
+ * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
+ */
+
+/**
+ * @module ui/bindings/addKeyboardHandlingForGrid
+ */
+
+export default function addKeyboardHandlingForGrid( keystrokes, focusTracker, gridElementsCollection, numberOfColumns ) {
```
Comment (oleq) [inline packages/ckeditor5-ui/src/bindings/addKeyboardHandlingForGrid.js:10]: Docs are needed here 🙂

File: packages/ckeditor5-ui/src/colorgrid/colorgridview.js [hunk 6]
```diff
@@ -174,6 +154,8 @@ export default class ColorGridView extends View {
 
 		// Start listening for the keystrokes coming from #element.
 		this.keystrokes.listenTo( this.element );
+
+		addKeyboardHandlingForGrid( this.keystrokes, this.focusTracker, this.items, 5 );
```
Comment (oleq) [inline packages/ckeditor5-ui/src/colorgrid/colorgridview.js:158]: Pass `options.columns` here instead of hardoded value.

File: packages/ckeditor5-ui/tests/bindings/addKeyboardHandlingForGrid.js [hunk 7]
```diff
@@ -0,0 +1,274 @@
...
+	describe( 'basic arrow moves', () => {
+		it( 'arrowright moves focus to the next grid item', () => {
+			// before: [x][ ][ ]	after: [ ][x][ ]	key: →
+			//         [ ][ ][ ]	       [ ][ ][ ]
+			//         [ ]      	       [ ]
+			const keyEvtData = {
+				keyCode: keyCodes.arrowright,
+				preventDefault: sinon.spy(),
+				stopPropagation: sinon.spy()
+			};
```
Comment (oleq) [inline packages/ckeditor5-ui/tests/bindings/addKeyboardHandlingForGrid.js:52]: Tip: Move these together with `keystrokes.press( ... )` to helper functions at the end of the file named `pressLeftArrow()`, `pressRightArrow()`, etc.. Helps with redundancy and makes the code very easy to read in natural language.

File: packages/ckeditor5-ui/tests/bindings/addKeyboardHandlingForGrid.js [hunk 8]
```diff
@@ -0,0 +1,274 @@
...
+
+			const spy = sinon.spy( gridElementsCollection.first, 'focus' );
+
+			keystrokes.press( keyEvtData );
+			sinon.assert.calledOnce( spy );
+		} );
+	} );
+} );
+
+class TestView extends View {
```
Comment (oleq) [inline packages/ckeditor5-ui/tests/bindings/addKeyboardHandlingForGrid.js:266]: Better keep it in the top-level `describe()`. Don't remember exactly how but these could leak somehow and affect other tests in some cases.

File: packages/ckeditor5-ui/src/bindings/addKeyboardHandlingForGrid.js [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+	keystrokes.set( 'arrowright', evt => {
+		const gridElements = [ ...gridElementsCollection ];
```
Comment (oleq) [inline packages/ckeditor5-ui/src/bindings/addKeyboardHandlingForGrid.js:12]: Why do you convert collection to array here? The `Collection` class has `get( index )` and `getIndex()` and `length`. Is there anything missing? This could have an unnecessary performance implication in large collections.

File: packages/ckeditor5-font/tests/ui/colortableview.js [hunk 10]
```diff
@@ -382,8 +383,9 @@ describe( 'ColorTableView', () => {
 					removeButtonLabel: 'Remove color',
 					documentColorsCount: 0
 				} );
-				colorTableView.appendGrids();
+				// Grids rendering is deferred (#6192) therefeore render happens before appending grids.
```
Comment (oleq) [inline packages/ckeditor5-font/tests/ui/colortableview.js:386]: Typo: therefore.

File: packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js [hunk 11]
```diff
@@ -178,19 +179,23 @@ export default class ListPropertiesView extends View {
...
 				this.focusables.add( this.children.last.buttonView );
 				this.focusTracker.add( this.children.last.buttonView.element );
 			}
+
+			for ( const item of this.stylesView.children ) {
+				this.stylesView.focusTracker.add( item.element );
+			}
+
+			this.stylesView.keystrokes = new KeystrokeHandler();
+			this.stylesView.keystrokes.listenTo( this.stylesView.element );
```
Comment (oleq) [inline packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js:196]: These should be moved to `_createStylesView()` (per single responsibility principle). Let's not mix things when we have dedicated places to organize the code. These are internals of the `stylesView` and they should be initialized next to other internals.

File: packages/ckeditor5-special-characters/src/ui/charactergridview.js [hunk 12]
```diff
@@ -56,6 +58,18 @@ export default class CharacterGridView extends View {
...
+		 * Tracks information about the DOM focus in the grid.
+		 *
+		 * @readonly
+		 * @member {module:utils/focustracker~FocusTracker}
+		 */
+		this.focusTracker = new FocusTracker();
+
+		this.keystrokes = new KeystrokeHandler();
+
+		addKeyboardHandlingForGrid( this.keystrokes, this.focusTracker, this.tiles, 10 );
```
Comment (oleq) [inline packages/ckeditor5-special-characters/src/ui/charactergridview.js:71]: What about the issue related to Windows vs Mac rendering? Can we hardcode the grid geometry in CSS to make it safer?

**Review by oleq — CHANGES_REQUESTED** [review]
The direction looks good. Mostly code refactoring suggestions and some questions.

File: packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js (hunk 11 above)
Comment (mmotyczynska) [reply packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js:196]: I moved initialisation of `stylesView.keystrokes` to `_createStylesView()`, but for the listener it would be too early (`stylesView.element` would be undefined) so I left the second line in place.

File: packages/ckeditor5-special-characters/src/ui/charactergridview.js (hunk 12 above)
Comment (mmotyczynska) [reply packages/ckeditor5-special-characters/src/ui/charactergridview.js:71]: Yes, we will handle it in [#9037](https://github.com/ckeditor/ckeditor5/issues/9037).

File: packages/ckeditor5-table/src/ui/inserttableview.js (hunk 1 above)
Comment (mmotyczynska) [reply packages/ckeditor5-table/src/ui/inserttableview.js]: Will be handled in #12256.

File: packages/ckeditor5-table/src/ui/inserttableview.js (hunk 2 above)
Comment (mmotyczynska) [reply packages/ckeditor5-table/src/ui/inserttableview.js]: Outline will be handled in #12256.

File: packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js (hunk 11 above)
Comment (mmotyczynska) [reply packages/ckeditor5-list/src/listproperties/ui/listpropertiesview.js]: Thanks for the tip with `render()`. Both lines are now in `_createStylesView()` 👍

**Review by oleq — APPROVED** [review]
Just waiting for the CI.
