### PR TITLE
Preserve all content when setting data with multiple images or mixed content in a link.

### LINKED ISSUE #18961: Pasting a link with images and other content throws away everything but the first image when only ImageBlock is enabled
## 📝 Provide detailed reproduction steps (if any)

[Reproduction repo](https://github.com/Joel-Levi/ck-editor-5-reproductions-2)
Similar to but slightly different [16778](https://github.com/ckeditor/ckeditor5/issues/16778)

1. Have an editor with Essentials, ImageBlock, ImageToolbar, Link, LinkImage, Paragraph. (No ImageInline)
2. Paste something that looks like the following HTML ( See reproduction )
```html
<a href="https://example.com">
  Text before
  <img src="https://example.com/first-image" width="100" height="200">
  Text between
  <img src="https://example.com/second-image" width="100" height="200">
  Text after
</a>
```

### ✔️ Expected result
Maybe something like
```html
<p><a href="https://example.com">Text before</a></p>
<a href="https://example.com"><img src="https://example.com/first-image" width="100" height="200"></a>
<p><a href="https://example.com">Text between</a></p>
<a href="https://example.com"><img src="https://example.com/second-image" width="100" height="200"></a>
<p><a href="https://example.com">Text after</a></p>
```

### ❌ Actual result

```html
<a href="https://example.com">
  <img src="https://example.com/first-image" width="100" height="200">
</a>
```
## 📃 Other details

* Browser: All
* OS: All
* First affected CKEditor version: ?
* Installed CKEditor plugins:
Essentials,
ImageBlock,
LinkEditing,
LinkImageEditing,
Paragraph,
Undo
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by Mati365**
### 🚀 Summary

Preserve all content when setting data with multiple images or mixed content in a link.

---

### 📌 Related issues

* Closes #18961

### CODE REVIEW

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 1]
```diff
@@ -318,6 +318,40 @@ describe( 'LinkImageEditing', () => {
...
+					expect( _getModelData( model, { withoutSelection: true } ) ).to.equal(
+						'<paragraph>' +
+							'<$text linkHref="http://ckeditor.com">Foo</$text>' +
+						'</paragraph>' +
+						'<imageBlock alt="alt text" linkHref="http://ckeditor.com" src="/assets/sample.png"></imageBlock>' +
+						'<paragraph>' +
+							'<$text linkHref="http://ckeditor.com">Bar</$text>' +
+						'</paragraph>'
+					);
+				} );
```
Comment (niegowski) [inline packages/ckeditor5-link/tests/linkimageediting.js]: Please make sure automatic and manual link decorators work correctly after this change.

Comment (Mati365) [reply packages/ckeditor5-link/tests/linkimageediting.js]: I added tests and updated logic as it was not handled properly.

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 2]
```diff
@@ -318,6 +318,155 @@ describe( 'LinkImageEditing', () => {
...
+						'</a>'
+					);
+
+					expect( _getModelData( model, { withoutSelection: true } ) ).to.equal(
+						'<imageBlock alt="alt text" linkHref="http://ckeditor.com" src="/assets/sample.png"></imageBlock>' +
+						'<imageBlock alt="alt text 2" linkHref="http://ckeditor.com" src="/assets/sample2.png"></imageBlock>'
+					);
+				} );
+
+				it( 'should convert an block image and text surrounded by a link', () => {
```
Comment (niegowski) [inline packages/ckeditor5-link/tests/linkimageediting.js]:
```suggestion
				it( 'should convert a block image and text surrounded by a link', () => {
```

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 3]
```diff
@@ -318,6 +318,155 @@ describe( 'LinkImageEditing', () => {
...
+					);
+
+					expect( _getModelData( newEditor.model, { withoutSelection: true } ) ).to.equal(
+						'<imageBlock alt="alt text" linkHref="http://ckeditor.com" linkIsGallery="true" src="/assets/sample.png">' +
+						'</imageBlock>' +
+						'<imageBlock alt="alt text 2" linkHref="http://ckeditor.com" linkIsGallery="true" src="/assets/sample2.png">' +
+						'</imageBlock>'
+					);
+
+					await newEditor.destroy();
```
Comment (niegowski) [inline packages/ckeditor5-link/tests/linkimageediting.js:438]: Please verify the data pipeline downcast.

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 4]
```diff
@@ -318,6 +318,155 @@ describe( 'LinkImageEditing', () => {
...
+							}
+						}
+					} );
+
+					newEditor.setData(
+						'<a href="http://ckeditor.com" class="gallery">' +
+							'<img src="/assets/sample.png" alt="alt text" />' +
+							'<img src="/assets/sample2.png" alt="alt text 2" />' +
+						'</a>'
+					);
```
Comment (niegowski) [inline packages/ckeditor5-link/tests/linkimageediting.js:382]: Please add a test with mixed content (text+images).

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 5]
```diff
@@ -318,6 +318,155 @@ describe( 'LinkImageEditing', () => {
...
+							}
+						}
+					} );
+
+					newEditor.setData(
+						'<a href="http://ckeditor.com/example.pdf" class="gallery">' +
+							'<img src="/assets/sample.png" alt="alt text" />' +
+							'<img src="/assets/sample2.png" alt="alt text 2" />' +
+						'</a>'
+					);
```
Comment (niegowski) [inline packages/ckeditor5-link/tests/linkimageediting.js:462]: Please add a test with mixed content (text+images).

File: packages/ckeditor5-link/tests/linkimageediting.js [hunk 6]
```diff
@@ -318,6 +318,155 @@ describe( 'LinkImageEditing', () => {
...
+							addTargetToExternalLinks: true
+						}
+					} );
+
+					newEditor.setData(
+						'<a href="http://ckeditor.com">' +
+							'<img src="/assets/sample.png" alt="alt text" />' +
+							'<img src="/assets/sample2.png" alt="alt text 2" />' +
+						'</a>'
+					);
```
Comment (niegowski) [inline packages/ckeditor5-link/tests/linkimageediting.js:557]: Please add a test with mixed content (text+images).

File: packages/ckeditor5-link/src/linkimageediting.ts [hunk 7]
```diff
@@ -323,13 +322,25 @@ function upcastImageLinkManualDecorator( editor: Editor, decorator: LinkManualDe
...
+			const modelElement = data.modelCursor.parent;
 
-			conversionApi.writer.setAttribute( decorator.id, true, modelElement );
+			if ( modelElement?.is( 'element', 'imageBlock' ) ) {
+				conversionApi.writer.setAttribute( decorator.id, true, modelElement );
+				return;
+			}
+
+			if ( data.modelRange ) {
+				for ( const { item } of data.modelRange!.getWalker( { ignoreElementEnd: true } ) ) {
```
Comment (niegowski) [inline packages/ckeditor5-link/src/linkimageediting.ts]:
```suggestion
				for ( const item  of data.modelRange.getItems() ) {
```

File: packages/ckeditor5-link/src/linkimageediting.ts [hunk 8]
```diff
@@ -165,24 +165,23 @@ function upcastLink( editor: Editor ): ( dispatcher: UpcastDispatcher ) => void
...
+			if ( modelElement.is( 'element', 'imageBlock' ) ) {
 				// Set the linkHref attribute from link element on model image element.
 				conversionApi.writer.setAttribute( 'linkHref', linkHref, modelElement );
+			} else {
+				// a > img: parent of the view link is not the image (figure) element. We need to convert it manually.
+				Object.assign( data, conversionApi.convertChildren( viewLink, data.modelCursor ) );
+
+				// Iterate over all converted model elements and set the linkHref attribute on image elements.
+				if ( data.modelRange ) {
+					for ( const { item } of data.modelRange.getWalker( { ignoreElementEnd: true } ) ) {
```
Comment (niegowski) [inline packages/ckeditor5-link/src/linkimageediting.ts]:
```suggestion
					for ( const item of data.modelRange.getItems() ) {
```

File: packages/ckeditor5-link/src/linkimageediting.ts [hunk 9]
```diff
@@ -323,13 +322,25 @@ function upcastImageLinkManualDecorator( editor: Editor, decorator: LinkManualDe
...
-			conversionApi.writer.setAttribute( decorator.id, true, modelElement );
+			if ( modelElement?.is( 'element', 'imageBlock' ) ) {
+				conversionApi.writer.setAttribute( decorator.id, true, modelElement );
+				return;
+			}
+
+			if ( data.modelRange ) {
+				for ( const { item } of data.modelRange!.getWalker( { ignoreElementEnd: true } ) ) {
+					if (
+						item.is( 'element', 'imageBlock' ) &&
```
Comment (niegowski) [inline packages/ckeditor5-link/src/linkimageediting.ts]: Why only on images? What if there is a text or other inline node inside a link?

Comment (Mati365) [reply packages/ckeditor5-link/src/linkimageediting.ts]: Agh, right. `checkAttribute` should be enough.
